### ISSUE TITLE
apollo-engine doesn't work with 2.0.0-beta.1

### ISSUE THREAD

**Issue by respectTheCode** [apollographql/apollo-server#1041]
In 2.0.0-beta.0 apollo-engine works as documented in the blog post but after upgrading to 2.0.0-beta.1 it stops working. I don't know if this is because something changed or if something is broken now.

**Comment by loicplaire** [comment]
I am running into the same issue: `apollo-engine` doesn't work on `2.0.0-beta.1` but works on `2.0.0-beta.0`.

**Comment by loicplaire** [comment]
I found the problem by looking at the `apollo-server-code` latest source: [the blog post](https://dev-blog.apollodata.com/apollo-server-2-0-30c9bbb4ab5e) and [glitch example](https://glitch.com/edit/#!/dog-graphql-api?path=server.js:69:44) are based on `2.0.0-beta.0` but the API has changed. It looks like the the `engine` flag needs to be passed on the `listen()` call instead of doing it on the `ApolloServer` instantiation. 

Here is how I got it working:

```js
const server = new ApolloServer({ typeDefs, resolvers });

server
  .listen({ engine: true })
  .then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`)
  })
``` 

@jbaxleyiii @peggyrayzis  it would be great if you could update[ the blog post](https://dev-blog.apollodata.com/apollo-server-2-0-30c9bbb4ab5e) and [glitch example](https://glitch.com/edit/#!/dog-graphql-api?path=server.js:69:44) to avoid confusion. I am sure I am not the only one who relied on these sources of truth to enable `apollo-engine`.

Let me know if it's also in the new docs and I will be happy to help out with a PR.

By the way, awesome work on the new `apollo-server`! I am in ❤️ with everything you guys do!

**Comment by evans** [comment]
Thank you @loicplaire for the solution! In the newest beta, we've changed the option from `engine` to `engineProxy`. You can check it out in the same [glitch](https://glitch.com/edit/#!/dog-graphql-api?path=server.js:70:0)

@leovanhaaren How are you passing the environment variable the node process? Can you add a `console.log(process.env.ENGINE_API_KEY)`?

```
const server = new ApolloServer({ typeDefs, resolvers });

server
  .listen({ engineProxy: true })
  .then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`)
  })
```

**Comment by leovanhaaren** [comment]
@evans thanks, adding engineProxy fixed it. Thought it was something else.
