### ISSUE TITLE
Specifying endpointUrl in Apollo Server 2.0

### ISSUE THREAD

**Issue by damianthekreeeytor** [apollographql/apollo-server#1064]
Can you specify an endpointUrl to new ApolloServer constructor. This is because when deploying to AWS lambda with Apex Up, they using /staging/graphql and /production/graphql endpoints. I get HTTP 400 when trying to fetch the schema and unable to load playground.

**Comment by evans** [comment]
@damianthekreeeytor Thank you for opening the issue! Take a look at [this glitch example](https://glitch.com/edit/#!/issue-1064?path=server.js:32:53)

You're able to specify the path in `registerServer`. Since it's a more advanced use case, there is a little more work to get there. If you could add some documentation to [the integration section](https://www.apollographql.com/docs/apollo-server/v2/essentials/server.html#integrations) that would be incredible.

**Comment by tanakachitsamba** [comment]
Hi @evans, 

trying to do the same thing as @damianthekreeeytor with Lambda and Apex Up

As registerServer has been deprecated and its recommended to use server.applyMiddleware does the same logic still allows in regards to path ?
