### ISSUE TITLE
question: Throttling resolvers execution

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-server#1147]
I have a node server with apollo-server and I was wondering-is there any way to throttle the resolvers?
Like if I have a parent resolver which resolves an array of 2000 items and I want to run a resolver on each item returned it needs quite a lot of memory. Whereas if I did 20 batches per 100 items that would work out just fine with my available memory.
Is there a way to do that?

**Comment by Tyler-Churchill** [comment]
Not 100% sure if this is truly apollo-server related.

Kind of confused on what you are trying to accomplish by running a resolver on each sub field of a type and a separate resolver of the parent? May need to post some code as I can't picture why this would be necessary.

For processing large lists with low memory footprint, I myself would start looking to see if async iterators/generators may work. Not sure what data you are loading and where/how it is being queried.

Maybe you can architect and achieve what you need to in a different way?  Maybe these links could help?
https://github.com/graphql/graphql-js/issues/26 
https://github.com/facebook/dataloader

**Comment by evans** [comment]
@capaj check out the work being done on #1287. If you have thoughts around how it might help your situation, please feel free to comment. The semantics around deferring particular chunks of a list are especially hard, so your use case would be especially informative

**Comment by capaj** [comment]
@Tyler-Churchill I looked at dataloader, but that wouldn't help me, because I don't load any entities twice. I just have too much of them for my small `t2.nano` API server.

@evans defer seems veery tasty. Does it mean it has to be used with a websocket on the client? How exactly does the streaming occur?

**Comment by abernix** [comment]
I suspect that this logic would need to be implemented on a case-by-case basis due to differences in resolver execution.  If this behavior works for your application, you can absolutely wrap your resolvers in something like [`lodash`'s `throttle`](https://lodash.com/docs/4.17.11#throttle) method, if you'd like to limit the number of resolvers (of a specific type, perhaps?) which can run at a given time.  Of course, doing so will draw out the overall execution of your response, but that may be exactly what you're looking for.

I'd also say this is the perfect kind of question to raise in the _Apollo Server_ channel of [the Apollo community on Spectrum](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.
