### ISSUE TITLE
Tracing not working with applyMiddleware?

### ISSUE THREAD

**Issue by wmdmark** [apollographql/apollo-server#1229]
I'm in a perhaps unusual case where I'm creating multiple GraphQL endpoints on a single express app. To do this I'm configuring each `ApolloServer` instance like so:

```javascript
  const config: any = {
      typeDefs,
      resolvers,
      tracing: true
    }
    // this is pulling an express app from a in-memory cache
    const app = _gqlApps[account.id][base.id]
    const server = new ApolloServer(config)
    server.applyMiddleware({
      app,
      path
    })
```

The servers work great but I'm not getting any `extensions` data back. Does the `tracing` flag work with `applyMiddleware` or is something else going on that I'm missing?

Here's the full code for creating the GraphQL apps if it helps:
```javascript
const _gqlApps = {}

export const getGQLApp = (account, base) => {
  if (!_gqlApps[account.id]) {
    _gqlApps[account.id] = { watchers: {} }
  }

  if (!_gqlApps[account.id][base.id]) {
    console.log("creating cached base app: ", account.id, base.id)
    _gqlApps[account.id][base.id] = express()
    initWatcher(account.id, base.id)
  }

  try {
    const resolvers = {
      Query: createQueryResolvers(account, base),
      ...createTypeResolvers(account, base)
    }
    const path = `/${account.id}/${base.id}/graphql`
    const typeDefs = gql`
      ${base.schema}
    `
    const config: any = {
      typeDefs,
      resolvers,
      tracing: true,
      cacheControl: {
        defaultMaxAge: 30 * 1000
      },
      engine: true
    }
    const app = _gqlApps[account.id][base.id]
    const server = new ApolloServer(config)
    server.applyMiddleware({
      app,
      path
    })
  } catch (error) {
    console.error("Error creating GraphQL server: ", error.toString())
  }
  return _gqlApps[account.id][base.id]
}
```

**Comment by jdubray** [comment]
I see the same problem

**Comment by evans** [comment]
@wmdmark super odd, are you running the latest RC.2? There were some issues with RC.0

**Comment by evans** [comment]
Also since you are using AS2, you can turn off tracing, since `engine:true` already sends the performance data to the Engine Backend, so there's no need to pass the tracing extensions to the proxy. Until AS2 supports full response caching, we'll still need to enable the cacheControl though

**Comment by wmdmark** [comment]
Hmm, tried upgrading to `"apollo-server": "^2.0.0-rc.2",` but no change. Engine appears to be collecting data just fine but doesn't appear to be caching anything: https://www.dropbox.com/s/u7b4bd5c6lzn20v/Screenshot%202018-06-22%2015.14.55.png?dl=0

I'm still not seeing any `extensions` data returned by the GraphQL for tracing or cache control.

**Comment by evans** [comment]
Ah try setting up the cache control to be the following.

```
      cacheControl: {
        defaultMaxAge: 30 * 1000
        calculateHttpHeaders: false,
        stripFormattedExtensions: false,
      },
```

We have some documentation in the works now #1223. Happy to hear reporting is working for you!

**Comment by wmdmark** [comment]
Just tried that, thanks for the quick responses! Still no dice though unfortunately. 

Here's my updated config:
```javascript
const config: any = {
  typeDefs,
  resolvers,
  cacheControl: {
    defaultMaxAge: 30 * 1000,
    calculateHttpHeaders: false,
    stripFormattedExtensions: false
  },
  engine: true
}
```

Engine isn't detecting a the cache policy: https://www.dropbox.com/s/o98h87j8wr6tq2t/Screenshot%202018-06-22%2015.42.24.png?dl=0

Should I be seeing `extensions` data in the GraphQL response for this to be working correctly?
https://www.dropbox.com/s/on7jmxq9eoq9xf9/Screenshot%202018-06-22%2015.40.26.png?dl=0

**Comment by evans** [comment]
@wmdmark Do you see the extensions in your network tab? GraphQL playground seems to strip them out of the response.

**Comment by evans** [comment]
@wmdmark very odd, I've created a reproduction of your setup https://glitch.com/edit/#!/cache-control?path=server.js:33:32 and the network tab seems to display both extensions.

What version of `apollo-server-express` are you using? Is it the latest RC.2?

It may be due to having multiple graphQL endpoints, though I doubt it. That's the next thing I would check if the versions are up to date.

**Comment by wmdmark** [comment]
@evans I'm not using `apollo-server-express`... perhaps that's the issue?

Here's my main server setup code:
```typescript
require("dotenv").config()
import express from "express"
import cors from "cors"

import { loadAccount } from "./db/api"
import { getGQLApp } from "./server"

const app = express()
app.use(cors())

const gqlRouteHandler = async (req, res) => {
  const account = await loadAccount(req.params.accountId)
  if (!account) return res.status(404).send("Invalid account")
  const base = account.bases[req.params.baseId]
  if (!base) return res.status(404).send("Invalid base")
  return getGQLApp(account, base)(req, res)
}

app.get("/:accountId/:baseId/graphql", gqlRouteHandler)
app.post("/:accountId/:baseId/graphql", gqlRouteHandler)

app.listen(8000)

```

(`getGQLApp`, the code that creates the `ApolloServer` is listed above).

Appreciate your help with this!

**Comment by wmdmark** [comment]
@evans switched to using `apollo-graphql-express` rc.2 and now I am seeing extensions data in the response... so progress!

```
 "cacheControl": {
      "version": 1,
      "hints": [{ "path": ["Books"], "maxAge": 30000 }]
    }
```

Although, when I look at it in engine, it's still saying there's no cache policy: https://www.dropbox.com/s/zd5cyoci5hcmsib/Screenshot%202018-06-23%2011.54.51.png?dl=0

**Comment by evans** [comment]
@wmdmark Hmm that might be because of the hybrid reporting. I was mistaken in my suggestion to use `engine: true`. Instead keeping `tracing:true` and `engine:false` is best. That should fix up the cache policy issues in the Engine UI, since the proxy will include the caching information in all tracing reports.

**Comment by wmdmark** [comment]
@evans hmm, tried that and not getting [anything in Engine](https://www.dropbox.com/s/klyaev3kcsqevt2/Screenshot%202018-06-27%2016.47.47.png?dl=0) now. 

My server with Engine proxy setup looks like this:
```typescript
require("dotenv").config()
import express from "express"
import { ApolloEngine } from "apollo-engine"
import cors from "cors"

import { loadAccount } from "./db/api"
import { getGQLApp } from "./server"

const app = express()
app.use(cors())

const gqlRouteHandler = async (req, res) => {
  const account = await loadAccount(req.params.accountId)
  if (!account) return res.status(404).send("Invalid account")
  const base = account.bases[req.params.baseId]
  if (!base) return res.status(404).send("Invalid base")
  return getGQLApp(account, base)(req, res)
}

app.get("/:accountId/:baseId/graphql", gqlRouteHandler)
app.post("/:accountId/:baseId/graphql", gqlRouteHandler)

const engine = new ApolloEngine({
  apiKey: process.env.ENGINE_API_KEY
})

engine.listen({
  port: 8000,
  expressApp: app
})

```

Proxy seems to be running fine:
```
[nodemon] starting `./node_modules/.bin/ts-node ./src/index.ts`
INFO[0000] Started HTTP server.                          address="[::]:8000" usingNamedPipe=false                                                                             wmdmark@Marks-MacBook-Pro
INFO[0000] Engine proxy started.                         build=2018.06-20-gc0e4bb519 version=1.1.
```

Not sure if it helps, but here's a GraphQL bin link for what I'm running (this is a GraphQL wrapper around an Airtable base): https://graphqlbin.com/v2/VAQZCg

**Comment by evans** [comment]
@wmdmark I just recreated the setup and it looks like there's a configuration option in Engine Proxy to set the GraphQL path https://www.apollographql.com/docs/engine/setup-node.html#extra-setup-config. The proxy was set up this way, since most GraphQL usage should have a single endpoint where the account/baseId in you case are passed as arguments or included in the headers. While that might be an ideal solution, I'm guessing that it wouldn't work well quick enough.

```js
engine.listen({
  port: 3000,
  graphqlPaths: ['/'],
  expressApp: app,
});
```

We're working towards a world that includes all of the proxy features in native JS. In the short term, I'd recommend using AS2 with a CDN in front to provide the caching found in Engine Proxy https://www.apollographql.com/docs/apollo-server/v2/features/cdn.html. The next feature on our roadmap is including full response caching in AS2, which should be out and available in a week or so. Hopefully that makes this conversation a lot easier.

If you'd like to use the proxy, it is possible to dynamically add endpoints to the configuration with an `engine-proxy.json`, which is documented: https://www.apollographql.com/docs/engine/proxy-config.html#Frontend. This configuration file is hot reloaded, so it's possible to add another path each time an account or base id is added.

```json
{
  frontend: [{ endpoints: ['/account/baseId/graphql'] }]
}
```

**Comment by wmdmark** [comment]
@evans thanks Evans, that's helpful info. I think I'll wait till the response caching is ready and go from there. Exciting stuff!

**Comment by JacobT14** [comment]
@evans I know this is closed, but I am actually getting this same issue on rc.6.  I get the cache control extension appearing in the response, but engine doesn't report any cache usage.  I am using apollo-server.  Any ideas?
