### ISSUE TITLE
Apollo Server 2: Export makeExecutableSchema from integrations

### ISSUE THREAD

**Issue by olistic** [apollographql/apollo-server#1251]
Should `makeExecutableSchema` be re-exported from integrations, as `gql` currently is?

**Comment by evans** [comment]
@olistic Ah yeah that's a great point! We should be exporting * from `graphql-tools` and `graphql-subscriptions` inside of the integrations. Thank you for brining it up

**Comment by olistic** [comment]
@evans Hmm, this is interesting. In `apollo-server`, that's exactly what's being done [here](https://github.com/apollographql/apollo-server/blob/a4f0336ea7709e4f97e1fb88ebf6884d4e2f6715/packages/apollo-server/src/exports.ts#L1-L2). However, if you look at the [dependencies](https://github.com/apollographql/apollo-server/blob/a4f0336ea7709e4f97e1fb88ebf6884d4e2f6715/packages/apollo-server/package.json#L35-L39), only `graphql-subscriptions` is defined there. Wouldn't doing `export * from 'graphql-tools'` be a problem in that case? Doesn't `graphql-tools` need to be a dependency in order to be able to do `export * from graphql-tools`?

**Comment by evans** [comment]
@olistic Ah yes it does! Good catch! We need to go over these dependencies, since lerna hoist doesn't do the best job for us 😬. Ideally we should have a smoke test before publish

Only for the integrations that support it, we should export the subscriptions code, so lambda doesn't need to worry about it.

**Comment by olistic** [comment]
What if the integration packages just exported the specifics for the integration itself, and the user was responsible for installing `apollo-server-errors`, `graphql-tools`, `graphql-subscriptions`, and any other additional library as it is demanded by their projects? It seems to me that re-exporting all these things from `apollo-server-core`, and then from each one of the integrations, has a high mantainability impact.

**Comment by evans** [comment]
Totally hear you on the maintainability. I love that your PR #1257 exports them directly from the integrations. What we have seen is that importing from a single package rather than requiring the user to install another package each time, like in AS1 is much better for documentation and learning.

Really really appreciate the PR and Issues! The newest RC.6 should have your changes
