### ISSUE TITLE
Any examples of using a database as a datasource rather than a REST api?

### ISSUE THREAD

**Issue by JacobT14** [apollographql/apollo-server#1260]
I can't seem to find anywhere any examples(or the library to use) to accomplish the datasource concept through a database library(i.e. sequelize).  I switched over from graphqlLambda to Apollo Server 2 and now my responses are taking 6-10 times as long(300ms --> 2.2-2.8 seconds) and I'm thinking maybe it is because I'm not including a datasource?

**Comment by linonetwo** [comment]
You can try prisma-binding with apollo-server.

**Comment by JacobT14** [comment]
Is that reliant on getting prisma setup?  I would rather not have to depend on a 3rd party service when I don't need to...

**Comment by JacobT14** [comment]
Still haven't found a way around this... Even just using the in memory cache isn't working.  When I issue a query I do get the cache-control extension, but it isn't caching at all.  Also looking at apollo-engine it says that no cache control policy was found for that query... I'm at a loss as to how to get response caching from apollo server currently.

**Comment by tab00** [comment]
A MySQL Data Source class would be good.

**Comment by sbrichardson** [comment]
[This example](https://github.com/apollographql/fullstack-workshop-server/blob/datasources/src/datasources/LikesDB.js) uses Sequelize, but it doesn't include caching, it's a more basic example.

**Comment by tab00** [comment]
Can we assume that by using [Data Sources](https://www.apollographql.com/docs/apollo-server/v2/features/data-sources.html) caching is handled automatically? The introductory paragraph of that page states it has "built-in support for caching, deduplication".

If you look at the [Refactor using data sources](https://github.com/apollographql/fullstack-workshop-server/commit/1bee4a0f01569f33057c99d6c71939c14eb7845c) commit of that example you can see [dataloader](https://github.com/facebook/dataloader) (which handled caching and batching) had been removed.

**Comment by sbrichardson** [comment]
No, caching isn't handled automatically, unless you instantiate a datasource class that 
with an initialize method. The RestDataSource that Apollo provides does cache automatically, since they built the HTTPCache. 

For a db cache you probably can start with the HTTPCache as a boilerplate (from ApolloServer source), but it needs a bit of work to customize properly. 

```ts
initialize(config: DataSourceConfig<TContext>): void {
  this.context = config.context;
  this.httpCache = new HTTPCache(config.cache);
}
```

See: 
apollo-server/packages/apollo-datasource-rest/src/RESTDataSource.ts
apollo-server/packages/apollo-datasource-rest/src/HTTPCache.ts
apollo-server/packages/apollo-datasource/src/index.ts

**Comment by tab00** [comment]
Is the `cache` option in `ApolloServer` the solution?

```javascript
const { RedisCache } = require('apollo-server-cache-redis');

const server = new ApolloServer({
  typeDefs,
  resolvers,
  cache: new RedisCache({
    host: 'redis-server',
    // Options are passed through to the Redis client
  }),
  dataSources: () => ({
    moviesAPI: new MoviesAPI(),
  }),
});
```

[apollo-server-caching](https://www.npmjs.com/package/apollo-server-caching) states:
> Internally, Apollo Server uses the KeyValueCache interface to provide a caching store for the Data Sources.  An in-memory LRU cache is used by default, and we provide connectors for Memcached/Redis backends.

I noticed that the [Redis implementation](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-cache-redis/src/index.ts) uses `dataloader`. Could that be the reason `dataloader` was removed from the [LikesDB](https://github.com/apollographql/fullstack-workshop-server/blob/datasources/src/datasources/LikesDB.js) example, i.e. caching is handled elsewhere?

**Comment by tab00** [comment]
Can anyone provide more clarity about caching when using Data Sources with a database?

**Comment by cvburgess** [comment]
I left some sample code on https://github.com/tgriesser/knex/issues/2787 - its a bit hacky but it shows how to make a SQL datasource using Knex

**Comment by smeijer** [comment]
The docs mention that `dataSources` are an alternative to `dataloader`. But I cannot find anywhere how to use it, or if the cache for the `Rest` example is request scoped?

Does anyone have good examples by now? Are you using Apollo's cache methods? Or still using Facebooks dataloader?

**Comment by smeijer** [comment]
@cvburgess, I did read about the batching. And I agree that we can still use DataLoader for that part. But I'm trying to find a clean solution for the database access. (Mongo to be specific).

Due to the nesting nature of Graphql, it can happen that a single graphql request, will trigger multiple hits to the database, for the same id's. This is a caching issue that DataLoader can solve, by caching the objects based on their primary keys, on request scope. Once the request has been handled, the cache is disposed of.

I'm curious if there is a way to handle that case with an 'Apollo solution'. So not the batching perse, more the cache per request to avoid redundant db hits.

**Comment by intellix** [comment]
Am currently using both: 
- https://github.com/mickhansen/graphql-sequelize
- https://github.com/mickhansen/dataloader-sequelize

Was originally using ApolloEngine full query caching with field-based caching TTLs like so:
```gql
type User implements Node @cacheControl(maxAge: 90) {
  firstName: String
  lastName: String
  balance: Float @cacheControl(maxAge: 0)
}
```

Since ApolloEngine was deprecated the above caching has stopped working. The extensions are there but it seems it only hits the CDN.

Was looking towards migrating towards DataSources as they're the latest thing from Apollo that reference caching.

As @tab00 says, this quote from the docs is a little confusing: 
> Internally, Apollo Server uses the KeyValueCache interface to provide a caching store for the Data Sources. An in-memory LRU cache is used by default, and we provide connectors for Memcached/Redis backends.

Originally made a quick wrapper around a Sequelize resolver and noticed it always hits the DB. Then I start looking at RESTDataSource and see that the cache implementation is completely manual and has nothing to do with the `@cacheControl()` directive at all.

I guess with ApolloEngine magically handling cache based on those directives in the past it's not clear where the magic starts and ends, especially when it says it's out of the box and the example MoviesAPI DataSource doesn't handle cache at all (I assumed there was some magic).

**Comment by lorensr** [comment]
Another (small) example is https://github.com/GraphQLGuide/apollo-datasource-mongodb/ for MongoDB

**Comment by trevorblades** [comment]
There are a few great examples in this thread, and I'll add one more from our docs: https://www.apollographql.com/docs/tutorial/data-source/#connect-a-database

Closing this issue now, but please create a new one if this pattern is still unclear!
