### ISSUE TITLE
When running in production, I get an error: Cannot find module 'lru-cache'

### ISSUE THREAD

**Issue by mattwexa** [apollographql/apollo-server#1305]
I got the issue when running apollo-server@2.0.0-rc.6. The dependencies are installed with --production, and when starting the server I get the error message "Cannot find module 'lru-cache'

The issue is solved by adding `lru-cache` as a dependency.

Expected: this dependency should be a dependency of apollo-server (or one of its sub-packages).

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this. In `rc.6`, `lru-cache` was a dependency of `apollo-datasource-rest`, and that was a dependency of `apollo-server-core`. 

We've since changed this, so `lru-cache` is now a dependency of `apollo-server-caching`. Could you try `rc.7` and see if that fixes this for you? If not, is there anything special about your setup?

**Comment by mattwexa** [comment]
Yes I updated to rc.7 and this solved the issue. Thank you!
