### ISSUE TITLE
Creating Directives Replacing field.type with a custom GraphQLScalarType

### ISSUE THREAD

**Issue by yussenn** [apollographql/apollo-server#1350]
I am creating a custom directive based on the next documentation:
https://www.apollographql.com/docs/apollo-server/v2/features/creating-directives.html#Enforcing-value-restrictions
and a have a question about the comment  "Replace field.type with a custom GraphQLScalarType th ...."

```
...
 visitFieldDefinition(field) {
    this.wrapType(field);
  }

  // Replace field.type with a custom GraphQLScalarType that enforces the
  // length restriction.
  wrapType(field) {
    if (
..
```

The example creates a new GraphQLScalarType and replace the initial type, so I am losing the initianl Type (String, ID, etc)

How Can I use _visitInputFieldDefinition_ without replaces the initial type? Is it posible to use method resolve? like in method  _visitFieldDefinition_

**Comment by hwillson** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
