### ISSUE TITLE
Server side caching based on a field in a response

### ISSUE THREAD

**Issue by Maxim-Filimonov** [apollographql/apollo-server#1400]
We are putting GraphQL in front of REST API and trying to implement server-side caching based on a field in the response.
We have an entity called document which has `updatedAt` property. To get a document, we use `/document/:documentId` which is a fast query.
However, each document has positions inside which are retrieved via separate calls(paginated list) to `/document/:documentId/positions/:offset` which is a slow 5+ queries.I'd like to cache positions on the server for a specific document until `updatedAt` has been changed to a new one.
We are using RESTDataSource to access the REST api. Unfortunately, we don't have control over the API and it doesn't provide `ETag` or `Last-Modified`, moreover the API even sets headers `Cache-Control` to `no-cache` for some unknown reason.

**Comment by abernix** [comment]
@Maxim-Filimonov The `RESTDataSource`'s `get` method supports a `ttl` override in the `init` options (third argument).  Would that be helpful at all?  For example, if you had knowledge of what the `updatedAt` was for a specific document prior to making the request to `/document/:documentId/positions/:offset`, perhaps you could pass that in?

e.g. (very roughly)

```js
const lastKnownUpdatedAtForDocument = {
  'document-id-123': '2018-10-18 18:12:34',
};

class DocumentAPI extends RESTDataSource {
  constructor() {
    super();
    this.baseURL = "https://host/";
  }

  // ... other methods, most likely!

  async getDocumentPosition(documentId) {
    const updatedAt = lastKnownUpdatedAtForDocument[documentId];
    const ttl = new Date(updatedAt) - Date.now();
    return await this.get(`document/${documentId}/positions/",
      {},
      {
        cacheOptions: { ttl }
      }
    );
  }
}
```

Just thinking out loud here, but curious how this would work for you!

**Comment by Maxim-Filimonov** [comment]
Hm. I didn't know about TTL. I'll give it a try next week. 
Thanks !

**Comment by abernix** [comment]
@Maxim-Filimonov 	Any updates on this?  Assigning to you for now, but feel free to un-assign yourself if you're not able to circle back to it!

**Comment by jbaxleyiii** [comment]
Thanks for reporting this issue originally!

If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!
