### ISSUE TITLE
Apollo-server-koa individual methods for middlewares in ApolloServer 

### ISSUE THREAD

**Issue by Vincz** [apollographql/apollo-server#1447]
At the moment, everything happens in the `applyMiddleware` method of the `ApolloServer` object. Every middleware is added one by one (the health check, the cors, the body parser, the file upload middleware, and the playground/graphql middleware).
It's great, to have this "all-in-one" shortcut but it would be nice to have all this middlewares has separate methods on ApolloServer object, like : "getUploadMiddleware", "getGraphqlMiddleware", etc... this way, we could use them in different context (in my case for example, I have a specific system able to handle koa middleware but the routing system is different, so I just need the `(ctx: Koa.Context, next: Function) => {...}` part) 

I'm willing to split the code if you're ok with it.

**Comment by alexFaunt** [comment]
I agree, I'm just upgrading to version 2 and I find the pattern a little grating that all the packages I used to use have been obscured into this all in one black box which I have to pass my server into, rather than integrating into my server.

Would've preferred a pattern more similar to that of apollo-boost which is a "standard" set of smaller packages for a speedy upstart, but importantly all the individual elements are still available.

**Comment by sbrichardson** [comment]
I added my kind of hacky [solution](https://github.com/apollographql/apollo-server/issues/1308#issuecomment-411643390) on #1308. It extends the ApolloServer with a custom applyMiddleware

**Comment by hwillson** [comment]
Tracking in https://github.com/apollographql/apollo-server/issues/1308. Thanks!
