### ISSUE TITLE
Be explicit about which argument had an unexpected type

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-server#1448]
I'm debugging a query with multiple arguments and the only error message I get is,

> Expected type Int, found undefined

It would be much more helpful if the server specified *which* parameter had the wrong type.

**Comment by abernix** [comment]
Completely agree, though this would seem to be an issue with `graphql-js`, not `apollo-server` since that particular validation is likely happening within its `validate` method.

That said, I'm pretty sure they've made a lot of improvements in regards to error messages in the last year, and in particular within `graphql@14`.  I don't think this will get resolved at this level though, and while we could probably augment it with some additional clarity ourselves, it would certainly be better resolved upstream in order to fix tooling, etc.
