### ISSUE TITLE
Cannot find module TS error when using apollo-server-micro

### ISSUE THREAD

**Issue by vespertilian** [apollographql/apollo-server#1455]
I kept getting: 

Cannot find module '@apollographql/graphql-playground-html/dist/render-playground-page' when trying to build my Apollo server with typescript.

I fixed it by installing `"@apollographql/graphql-playground-html"` the dependency it was looking for.

I am not sure if this is the correct fix, or if `apollo-server-core` is not referencing the module correctly. 
The type error was appearing in `apollo-server-core/dist/playground.d.ts`

**Comment by jbaxleyiii** [comment]
Thanks for reporting this issue originally!

If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!
