### ISSUE TITLE
Playground tabs options seem ignored

### ISSUE THREAD

**Issue by lpellegr** [apollographql/apollo-server#1457]
Let's say you create a new `ApolloServer` instance as follows:

```
new ApolloServer({
        playground: {
            settings: {
                'editor.reuseHeaders': true,
                'editor.cursorShape': 'line'
            },
            tabs: [{
                query: 'test'
            }]
        }
});
```

The query value is not used as the default query in the first tab that opens. The same seems to apply for all properties under `tabs`. Also, defining a default Authorization header based on the query parameter (as it was possible with GraphiQL) looks not possible since we do not have access to `req` while configuring playground options.

**Comment by ericclemmons** [comment]
I found that it doesn't work without `responses: ["{}"]` defined as well.

**Comment by abernix** [comment]
Similarly to https://github.com/apollographql/apollo-server/issues/1549:

> We may not have been running the latest version of GraphQL Playground at that time, but we're currently completely up to date.  Please try the latest version of Apollo Server (v2.6.8, as of this writing) and if this problem persists, please open an issue on the [GraphQL Playground repository](https://github.com/prisma/graphql-playground/issues).

Also, as I wrote on https://github.com/apollographql/apollo-server/issues/1982#issuecomment-508770482:

> GraphQL Playground should support the setting of `tabs` to any valid `Tabs[]` setting, which should include the ability to set options like `endpoint`, `variables`, `headers`, etc.:
>
> From the [GraphQL Playground documentation](https://github.com/prisma/graphql-playground#usage):
>
> * `tabs` `Tab[]` - An array of tabs.
>
> ```ts
> interface Tab {
> 	endpoint: string
> 	query: string
> 	name?: string
> 	variables?: string
> 	responses?: string[]
> 	headers?: { [key: string]: string }
> }
> ```
> 
> And this should be possible to set within the Apollo Server constructor `playground` options.  Please report back with a runnable reproduction (e.g. CodeSandbox, Glitch or a clone-able GitHub repository which can be `npm start`ed) if this is not the case on the latest version of Apollo Server, and we'll be happy to investigate further.

This issue is now quite old, but if this problem persists, please ping for a re-open, but please include a runnable reproduction (e.g. link to CodeSandbox or Glitch, or a clone-able GitHub repository which can be ran with `npm start`), and someone can try to look into it further.  Thanks!

**Comment by Moisei-Shkil** [comment]
Hi, got the same issue.
Any updates on it?
I'm using nestJS if it matters.

```json
"apollo-server-core": "^3.6.3",
"apollo-server-express": "^3.6.3",
"@nestjs/apollo": "^10.0.5",
```


```js
{
    ...apolloOptions,
    typeDefs: this.sdl,
    introspection: true,
    playground: {
    tabs: [
	    {
		    name: 'Tab 1',
		    endpoint: 'version/id',
		    query: 'query { status }',
	    },
    ],
 }
```

Thanks in advance Moisei 😁

**Comment by glasser** [comment]
@Moisei-Shkil  In Apollo Server 3, Playground is an optional plugin rather than a built-in top-level ApolloServer constructor option. (I recommend using TypeScript instead of JavaScript, which would make this obvious as passing `playground` would now be a compilation error.) See https://www.apollographql.com/docs/apollo-server/migration/#graphql-playground for details on migrating to the plugin when you upgrade. (I also recommend that you migrate off of Playground to something like Explorer as exposed by the new default landing page, as Playground is not a maintained project, but you can go one step at a time.)

**Comment by Moisei-Shkil** [comment]
Thanks, worked like a charm 😎
