### ISSUE TITLE
Should Author have "name" aside from books?

### ISSUE THREAD

**Issue by koukimetal** [apollographql/apollo-server#1463]
https://www.apollographql.com/docs/apollo-server/v2/essentials/data.html#resolver-map
And id as well?
Also
https://www.apollographql.com/docs/apollo-server/schemas/types.html#Mutation-type
type Query {
addTodo(user: ID, todo: String): Response
}
Should it be Mutation instead of Query?

If I'm correct, I'd like to contribute.

**Comment by koukimetal** [comment]
And id as well?

**Comment by koukimetal** [comment]
Also
https://www.apollographql.com/docs/apollo-server/schemas/types.html#Mutation-type
type Query {
  addTodo(user: ID, todo: String): Response
}
Should it be Mutation instead of Query?

**Comment by koukimetal** [comment]
If I'm correct, I'd like to contribute.

**Comment by justinanastos** [comment]
Thanks for the issue @koukimetal ! I think for `Author` that an absolutely minimum example is sufficient. We totally _could_ have a name and some kind of identifier if we wanted; but I don't think that enhances the example. 

As for the `addTodo` being in a mutation; you're totally right! I think that was updated since this issue was created. If you find any issues like this then totally make a pull request! We love community support :)

In the meantime I'm going to close this issue; feel free to ping me if you think it should be re-opened.
