### ISSUE TITLE
Playground seems lost cookies.

### ISSUE THREAD

**Issue by Josaber** [apollographql/apollo-server#1500]
Hi team,

Since we upgraded the Apollo-Server to **version 2**. Our server shows that `Server cannot be reached` and we cannot query anything in the playground. But all the codes are similar.
And we did some investigation, it seems apollo-server playground lost cookies. If there are no cookies it will call authentication API.

Also, we can use postman client to query data when we add cookies to the query request.

![image](https://user-images.githubusercontent.com/40235859/43825918-8f8fe278-9b28-11e8-84ba-edd62cb2409a.png)

Could anyone explain it? Is this an issue in apollo-server 2?

**Comment by frederikhors** [comment]
Maybe this: https://github.com/prismagraphql/graphql-playground/issues/748

**Comment by Josaber** [comment]
@frederikhors Thanks, I will comment on that issue.

**Comment by ivan-kleshnin** [comment]
This is fixed in playground 1.7.2 but `apollo-server` ships 1.6.6.

**Comment by abernix** [comment]
We ship the latest version now, so if this is fixed upstream, it should be fixed in the latest version of Apollo Server as well.  Just to make sure, please try Apollo Server `2.7.0-alpha.8` (or newer, if you find one exists!) and if this is still giving trouble, please let us know so we can re-open this issue.  Please make sure to include a runnable reproduction within CodeSandbox or Glitch, using the latest version of Apollo Server, when requesting a re-open!

Thanks!
