### ISSUE TITLE
Unable to log request data (ip address)

### ISSUE THREAD

**Issue by pho3nixf1re** [apollographql/apollo-server#1506]
I have a custom logging extension function:

```js
class LogExtension {
  constructor(logger) {
    this.logger = logger;
  }

  requestDidStart({
    request,
    queryString,
    parsedQuery,
    operationName,
    variables,
  }) {
    const requestId = request.headers['X-Request-Id'] || '-';
    const ipAddress = ???;

    this.logger.info(
      {
        requestId,
        operationName,
        ipAddress,
      },
      'IP Address'
    );

    return errors => {
      if (errors && errors.length) {
        this.logger.error({
          requestId,
          operationName,
          key: 'errors',
          data: errors,
        });
      }
    };
  }
}

export default LogExtension;
```

### Expected
To have access to either the node Request data or Koa `ctx` in relevant extension hooks.

### Actual
The `request` is missing all headers and it doesn't have the normal node Request object values rendering it of little to no value.

Is there a way to access the actual Koa request `ctx` or otherwise get real request data?

**Comment by TidyIQ** [comment]
Same issue here. Did you ever figure it out?

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Comment by dandv** [comment]
@jbaxleyiii: while those support avenues may be more appropriate, they are also far harder to search. Almost two years later, a Google search for "get client IP apollo-server" produces this issue, and a StackOverflow question about getting the IP from a subscription (which doesn't answer this question).

All in all, at least 3 people on this issue have been wasting their time trying to figure out something as basic as getting the IP of the client. Does this have to be that complicated and bureaucratic to not be simply answered in this issue (if possible at all)?

**Comment by dandv** [comment]
`request.socket.localAddress`, there you go. Works for me at least.

**Comment by pbandjs** [comment]
Anybody have any luck with this?

**Comment by dandv** [comment]
@pbandjs: I posted a link to the correct solution in my comment above.

**Comment by ghostoy** [comment]
As I walked through the code, it's **impossible** to get the client ip on plugin side. The only arguement passed to plugin side per request is `GraphQLRequestContext<BaseContext>`. The raw http request was filtered out by [`convertNodeHttpToRequest`](https://github.com/apollographql/apollo-server/blob/655c1ca35514683fb6364519ec53846b86400042/packages/apollo-server-express/src/ApolloServer.ts#L168), which left only `headers`, `method` and `url`, before passed as `http` of context.

@jbaxleyiii Please consider to add the raw http request as part of graphql context, so that plugins could obtain the original client ip from http.

**Comment by glasser** [comment]
You have access to the raw request in your own `context` function.
