### ISSUE TITLE
RESTDataSource has double caching

### ISSUE THREAD

**Issue by uarsovic** [apollographql/apollo-server#1511]
It stores all caches in cache implementation InMemory, Redis, Memcache and also in Map object. Second time if you send same request it will return the cache value from the Map. This will override ttl config. Not sure also how this is safe, in terms of memory, how big the map object will be if it stores all responses.

**Comment by martijnwalraven** [comment]
This is by design. Data sources are instantiated per request, so the internal map is meant as a short lived memoization cache that avoids duplicate backend fetches. The actual cache is shared and long-lived, so that's where the TTL is respected.

**Comment by uarsovic** [comment]
@martijnwalraven I have example where I extend RESTDataSource and we use get for fetching the data from 3rd party. When we get different response data it is always cached in "memoizedResults" and that map will be evergrowing. Or am I missing something? is that map ever going to be freed?

**Comment by martijnwalraven** [comment]
@uarsovic Because data sources are instantiated per request, `memoizedResults` won't live beyond the duration of the current request.

**Comment by uarsovic** [comment]
@martijnwalraven In my case, my map has e.g. three elements in it. And i can continue to grow it easily.

**Comment by martijnwalraven** [comment]
@uarsovic Could you elaborate on what you mean here? The map is only kept for the duration of a single GraphQL request, so I don't see the issue.

**Comment by uarsovic** [comment]
@martijnwalraven I have done three graphQL POST requests with three different id values. And had only one instance of RESTDataSource and map had three different values in it. And if I continue to make more graphQL POST requests with different id's it will continue to grow.
One more question. Where is datasource instantiated? Somewhere internally? Since i pass instance in the configuration of the ApolloServer

**Comment by martijnwalraven** [comment]
@uarsovic You pass a function that instantiates your data sources to the `ApolloServer` constructor under a `dataSources` key, and the server will call that function for every request and configure the data source so it has access to the context and cache. See [the example](
https://www.apollographql.com/docs/apollo-server/v2/features/data-sources.html#Accessing-data-sources-from-resolvers) in the docs.

Is that not what you were doing?

**Comment by uarsovic** [comment]
@martijnwalraven In index.js I have:

- const myService = require('./MyServiceRedis');
- dataSources: () => {   return { myService: myService };  }

In my service I have:
- class MyServiceRedis extends RESTDataSource
- methods calling this.get
- module.exports = new ANPServiceRedis();

**Comment by martijnwalraven** [comment]
@uarsovic Yeah, that's not how data sources are meant to be used. You should export the class from your other module and instantiate it in the `dataSources` function.

Sharing a data source between requests will be guaranteed to lead to trouble, because it means you don't have access to the current request's context through `this.context` for example. And we plan on extending data sources with more features that require them to be bound to a request, like tracing of backend calls.

**Comment by wa4-fearless-otter** [comment]
I think this should be somehow documented, I had the same problem.

**Comment by rfgamaral** [comment]
I'm still a bit confused about the "double caching" implemented in `RESTDataSource` and instead of opening up a new issue and I'm going to post my questions here, hoping @martijnwalraven will see them :)

Right now `RESTDataSource` implements two caching mechanisms, one is based on memoization and is initialized with every request (short-lived) and then there's an HTTP cache as well (long-lived). Based on `RESTDataSource.ts` file, it seems to me that `httpCache` will be hit first here:

https://github.com/apollographql/apollo-server/blob/90b9386b07cd4011e0340b45ba491b62b8dcaddb/packages/apollo-datasource-rest/src/RESTDataSource.ts#L257

Followed by `memoizedResults` here:

https://github.com/apollographql/apollo-server/blob/90b9386b07cd4011e0340b45ba491b62b8dcaddb/packages/apollo-datasource-rest/src/RESTDataSource.ts#L269

Now I'm trying to understand the scenario in which both of these caches will be used...

The `httpCache` is shared by Apollo Server and is long-lived because it will be available for as long as the Apollo Server instance is running (assuming a memory cache). This cache will be shared by all requests for this Apollo Server instance and return request responses from the HTTP cache if they are available. If I make the same request multiple times in an hour or day, the response will most likely come from the HTTP cache (assuming it wasn't removed). Correct?

Now, the `memoizedResults` cache is meant to be used only for request deduplication since it will be initialized every time a `RESTDataSource` is initialized. Correct? However, if `dataSources` are initialized with every GraphQL request (as mentioned above) how exactly does deduplication of requests will work here? I mean, say I do two quick requests with `curl`, Postman or a script with Axios or something, these are 2 requests, 2 GraphQL requests, 2 initializations per `dataSource` and 2 initializations of `memoizedResults`. How exactly does this cache work then? I'm confused.
