### ISSUE TITLE
apollo-server-cloudflare is building at >1MB

### ISSUE THREAD

**Issue by GregBrimble** [apollographql/apollo-server#1572]
Using the latest version of `apollo-server-cloudflare` (`2.0.2`), a minimal app builds to greater than 1MB, [which is the limit of Cloudflare Workers (so cannot be deployed)](https://developers.cloudflare.com/workers/writing-workers/storing-data/).

A project build with `1.0.0-beta.0` builds to less than 350KB.

See `1.0.0-beta.0` example at https://github.com/jbaxleyiii/apollo-server-cloudflare. Then, install the latest version, and see the new size of `dist/app.js`.

---
*Update*: Still an issue as of `2.2.2` (2018-11-13)

**Comment by bsbechtel** [comment]
@GregBrimble Did you make it past this issue? I'm interested in trying out the cloudflare workers with an apollo server, but haven't heard any updates recently. I'm worried the project may be abandoned.

**Comment by GregBrimble** [comment]
@bsbechtel - no. I just used pinned to the `1.0.0-beta.0` version, which continued to work fine. However, I doubt this is abandoned, since Cloudflare Workers are still being actively developed, and the Apollo Server Cloudflare package was only developed this summer, but I don't know for sure.

**Comment by bsbechtel** [comment]
Ok cool. I've been hesitant to try it out because it hasn't been officially released yet, and I haven't heard much from the community regarding if it's working well for them. Are you using it with a db connection and it's working effectively?

**Comment by GregBrimble** [comment]
I tried connecting to Firebase, but again, the script ballooned above the 1MB limit. I'm in the new Cloudflare Workers KV beta though, so will be trying out that soon.

I was successful in proxying requests however, serving Apollo, and using other APIs are data-sources, behind the scenes.

**Comment by bsbechtel** [comment]
@GregBrimble Ok awesome. I may try it out then. My backend is Mongo. If using the mongo driver or Mongoose puts it over the limit, Mongo offers Stitch as an API alternative.

**Comment by gcoda** [comment]
I do not need uploads, so i just aliased `busboy` to null in `webpack.config.js`, barely fits(968KiB) but works

**Comment by signalnerve** [comment]
hi all, dev advocate for the workers team here 👋 we recently pushed some updates to how we bundle scripts at deploy time in workers – after some testing, it looks to me like deploying an apollo server on workers... works! (again)

would love someone to double-check my work who has been running into this issue in this thread – here's an example project you can configure: https://github.com/signalnerve/workers-graphql

**Comment by GregBrimble** [comment]
@signalnerve, looks to have done the trick 🎉 Build size for your example repo was 452KB, and worked perfectly.

Many thanks to the team for the work done, and to you for following up here! I'll close down this issue ✔️

**Comment by dkolba** [comment]
> @signalnerve, looks to have done the trick 🎉 Build size for your example repo was 452KB, and worked perfectly.
@GregBrimble how did you get the bundle size to 452KB? I get 1.559MB without modifying the code.

**Comment by GregBrimble** [comment]
@dkolba, sorry I wasn't clear. My Worker script was also ~1.5MB locally, but I believe that the work that @signalnerve and co. did, gzips the script as it deploys. It was this file that was 452KB. Did you try deploying the 1.559MB worker with Serverless, as in @signalnerve's repo?

**Comment by dkolba** [comment]
@GregBrimble I deployed it via CloudFlare's [wrangler](https://github.com/cloudflare/wrangler), which worked and is also pretty nice. Apollo queries and GraphiQL seem to work fine but now I get the warning `Your script is too large. The maximum file size is 1MB.` in CloudFlares Worker editor. Is this expected behaviour @signalnerve?

**Comment by vladinator1000** [comment]
This is a problem for me when I use TypeScript, here's [an example](https://github.com/vladinator1000/cf-gql) that produces a 2MiB build. I've also logged an issue in @signalnerve's [repo](https://github.com/signalnerve/workers-graphql-server/issues/19)

**Comment by vladinator1000** [comment]
Here's how my bundle looks like, it has 1.5 MiB of dependencies.

![image](https://user-images.githubusercontent.com/1226564/82755005-cad1f980-9dc8-11ea-92c1-9cc38b78b05a.png)

When I use [bundle optimize helper](https://webpack.jakoblind.no/optimize/) it says these deps are not tree shakeable because they're not using ES modules.

inherits | 753 Bytes
safe-buffer | 1.63 KB
process | 5.29 KB
buffer | 47.45 KB
minimalistic-assert | 252 Bytes
cipher-base | 2.17 KB
events | 12.95 KB
apollo-server-env | 1.26 KB
apollo-server-errors | 6.75 KB
randombytes | 1.54 KB
core-util-is | 2.95 KB
buffer-xor | 206 Bytes
process-nextick-args | 1.06 KB
evp_bytestokey | 1.16 KB
apollo-server-types | 281 Bytes
crypto-browserify | 2.87 KB
md5.js | 4.5 KB
util-deprecate | 1.58 KB
ripemd160 | 4.47 KB
brorand | 1.47 KB
fast-json-stable-stringify | 1.8 KB
isarray | 132 Bytes
graphql-extensions | 5.95 KB
stream-browserify | 3.54 KB
timers-browserify | 1.97 KB
create-hash | 736 Bytes
minimalistic-crypto-utils | 1.11 KB
bn.js | 87.87 KB
os-browserify | 975 Bytes
assert | 15.62 KB
base64-js | 3.85 KB
ieee754 | 2.02 KB
apollo-cache-control | 4.82 KB
apollo-tracing | 2.43 KB
lru-cache | 7.99 KB
yallist | 8.43 KB
apollo-server-caching | 3.13 KB
string_decoder | 10.74 KB
hash-base | 98.26 KB
sha.js | 18.57 KB
setimmediate | 6.32 KB
readable-stream | 69.53 KB
create-hmac | 2.49 KB
pbkdf2 | 6.17 KB
browserify-cipher | 1.97 KB
des.js | 15.69 KB
browserify-aes | 25.7 KB
browserify-des | 1.47 KB
miller-rabin | 87.72 KB
diffie-hellman | 99.44 KB
browserify-rsa | 86.47 KB
hash.js | 28.62 KB
hmac-drbg | 2.92 KB
elliptic | 194.42 KB
vm-browserify | 3.98 KB
asn1.js | 127.71 KB
parse-asn1 | 10.83 KB
browserify-sign | 107.38 KB
create-ecdh | 87.92 KB
public-encrypt | 91.06 KB
randomfill | 2.93 KB
deprecated-decorator | 5.63 KB
uuid | 6.07 KB
zen-observable | 15.49 KB
graphql-tools | 212.49 KB
loglevel | 8.41 KB
ws | 175 Bytes
core-js | 46.73 KB
node-fetch | 709 Bytes
node-libs-browser | 14.33 KB
url | 23.08 KB
querystring-es3 | 5.06 KB
apollo-env | 3.14 KB
@apollographql | 8.06 KB
browserify-zlib | 27.09 KB
object-assign | 2.06 KB
util | 19.78 KB
pako | 183.62 KB
apollo-engine-reporting-protobuf | 369.35 KB
@protobufjs | 23.66 KB
@apollo | 50.2 KB
async-retry | 1.14 KB
retry | 5.85 KB
lodash.sortby | 70.91 KB
graphql | 545.53 KB
apollo-graphql | 18.56 KB
apollo-engine-reporting | 33.47 KB
fs-capacitor | 5.38 KB
path-browserify | 8.54 KB
http-errors | 5.74 KB
depd | 1.48 KB
setprototypeof | 384 Bytes
statuses | 3.82 KB
toidentifier | 490 Bytes
object-path | 7.08 KB
graphql-upload | 12.01 KB
backo2 | 1.37 KB
eventemitter3 | 8.93 KB
subscriptions-transport-ws | 25.26 KB
graphql-tag | 5.13 KB
apollo-server-core | 63.27 KB
apollo-server-cloudflare | 5.21 KB
apollo-datasource-rest | 15.17 KB
http-cache-semantics | 23.23 KB

**Comment by GregBrimble** [comment]
@vladinator1000 , how are you deploying? [Like I said above](https://github.com/apollographql/apollo-server/issues/1572#issuecomment-503232910), (for me at least), although the build itself is ~1.5MB, once it is gzipped, it shrinks down to 452KB, so [wrangler](https://github.com/cloudflare/wrangler) is able to deploy just fine.

**Comment by vladinator1000** [comment]
@GregBrimble I used `cargo publish` in [this repo ](https://github.com/vladinator1000/cf-gql)

**Comment by GregBrimble** [comment]
Ah, I can reproduce now. Yes, looks like TypeScript & Apollo Server are too large together. (I haven't tried setting up a repo from scratch myself, but your example one looks correct from a quick skim).

In my own projects (which are just about all exclusively TypeScript), I've been using [`graphql`](https://github.com/graphql/graphql-js) directly, avoiding Apollo Server entirely. The build sizes were getting too large as soon as I began introducing anything sizable beyond a simple proof-of-concept. [Here's an example file which loads the schema/resolvers, and responds to GET/POST requests](https://github.com/GregBrimble/workers.sh/blob/master/packages/server/src/graphql/index.ts#L50-L86) (sorry that I don't have a more minimal example to hand).

**Comment by vladinator1000** [comment]
This looks like a nice approach @GregBrimble I bet with a bit of codegen it can become even easier
