### ISSUE TITLE
Contributing guide in README.md is outdated and npm link in project root is broken

### ISSUE THREAD

**Issue by elnygren** [apollographql/apollo-server#1575]
Hi! First I'd like to thank Apollo for making such a nice product. I'd like to contribute a small fix but before I can do that (or before we should even discuss that), I came across some problems:

### Readme.md is outdated 

It tells you to:
```
git clone https://github.com/[your-user]/apollo-server
cd apollo-server
```

although such a dir does not exist. I'm assuming the current way develop apollo-server is:

```
https://github.com/apollographql/apollo-server.git
cd apollo-server
npm link
```

### NPM link is broken

However, running `npm link` like that fails due to several reasons:

**1. non existing deps** 

some packages like `apollo-server-koa` and `apollo-server-micro` declare dependencies such as these:
```
"@apollographql/apollo-upload-server": "^5.0.3",
"@apollographql/graphql-playground-html": "^1.6.0",
```
that fail. I'm assuming they are your internal repos?

**2. non existing types**

```
> apollo-server-micro@2.0.4 compile /Users/elnygren/Work/apollo-server/packages/apollo-server-micro
> tsc

../../node_modules/graphql-request/dist/src/index.d.ts(11,18): error TS2304: Cannot find name 'Headers'.
../../node_modules/graphql-request/dist/src/index.d.ts(22,14): error TS2304: Cannot find name 'Headers'.
../../node_modules/graphql-request/dist/src/types.d.ts(8,14): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(10,12): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(11,19): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(12,13): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(13,16): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(14,16): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(15,22): error TS2304: Cannot find name 'RequestInit'.
../../node_modules/graphql-request/dist/src/types.d.ts(16,17): error TS2304: Cannot find name 'RequestInit'.
```

EDIT: found after fixin 1, 2:
**3. apollo-upload-server types are missing**
```
src/ApolloServer.ts(17,31): error TS7016: Could not find a declaration file for module 'apollo-upload-server'. '/Users/elnygren/Work/apollo-server/node_modules/apollo-upload-server/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/apollo-upload-server` if it exists or add a new declaration (.d.ts) file containing `declare module 'apollo-upload-server';`
src/index.ts(46,47): error TS7016: Could not find a declaration file for module 'apollo-upload-server'. '/Users/elnygren/Work/apollo-server/node_modules/apollo-upload-server/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/apollo-upload-server` if it exists or add a new declaration (.d.ts) file containing `declare module 'apollo-upload-server';`
```

**Comment by abernix** [comment]
Sorry for the struggles with contributing that you ran into, and further apologies for how long it's taken to respond to this!  There's a couple things worth noting:

> Readme.md is outdated
> It tells you to:
> 
> git clone https://github.com/[your-user]/apollo-server
> cd apollo-server

This is correct, but relies on you having cloned the repository — which is noted in the bullet-point prior to that:

![image](https://user-images.githubusercontent.com/841294/60517820-fe0b2600-9ce8-11e9-9350-45412a828ae0.png)

Once the repository is "forked" then `your-user` would exist.  I admit that the instructions could be much more explicit, but the instruction is crudely correct.  A PR to improve this would certainly be very much appreciated!

> ```
> "@apollographql/apollo-upload-server": "^5.0.3",
> "@apollographql/graphql-playground-html": "^1.6.0"
> ```

These definitely _do_ exist, so I'm not sure why you had problems using them.

Lastly, `npm link` has been very much a frustrating experience for a long time, and it's not entirely because of Apollo Server either.  `npm link` in general has been broken for some time, and despite rumors that it will be fixed in npm@7, I'm no longer confident that will be happening since that was suggested to come out over a year ago.

To be honest, while doing manual symlinking often works best, writing a test is often works quite well and doubles as... well, actual tests for a contribution! :)

If you're trying to contribute and running into problems, please take a fresh look at the `README.md` and also [`CONTRIBUTING.md`](https://github.com/apollographql/apollo-server/blob/master/CONTRIBUTING.md).  If you still run into problems, please start a thread on the [Apollo Server channel on the Apollo Spectrum.chat](https://spectrum.chat/apollo/apollo-server) and I (or someone) will be happy to help with any contribution.  They are important to us!
