### ISSUE TITLE
Schema doesn't load on remote server

### ISSUE THREAD

**Issue by ryanzjohnson** [apollographql/apollo-server#1587]
We recently upgraded to Apollo server 2.0, with that we have ran into an issue where on our remote servers for Dev and Test, the schema doesn't load in (see picture.) We can't replicate this issue at all locally.

![image](https://user-images.githubusercontent.com/35502607/44683777-14c35b00-a9fc-11e8-823f-90e2a8820499.png)

Do you have any advice on how to fix this issue.

**Comment by ryanzjohnson-ms** [comment]
The underlying issue is that our server is behind Auzre Active Directory authentication just to even hit the server, and AAD is blocking us due to CORS, since we can't add our server URL to the Azure Active Directory accepted urls in cors, is there a way to have the schema not load in by hitting the server, and revert that one part back to the 1.x way of doing it?

**Comment by ryanzjohnson** [comment]
Any update on this?

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
