### ISSUE TITLE
RESTDataSource - fetch timeout

### ISSUE THREAD

**Issue by shinyaohira** [apollographql/apollo-server#1594]
I am using RESTDataSource to fetch data and want to set timeout for it. But RequestInit in apollo-server-env doesn't have timeout option.

**Comment by sbrichardson** [comment]
I haven't checked it out yet, but it looks like it could be supported, since I believe `apollo-server-env` uses `"node-fetch": "^2.1.2",`. It looks like timeout is an extension on node-fetch, 

From the node-fetch library [source link](https://github.com/bitinn/node-fetch/blob/master/src/request.js?ts=2#L70):

```js
let inputBody =
  init.body != null
    ? init.body
    : isRequest(input) && input.body !== null
      ? clone(input)
      : null

Body.call(this, inputBody, {
  timeout: init.timeout || input.timeout || 0,
  size: init.size || input.size || 0,
})
```

And the apollo-server-env [source link](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-env/src/fetch.d.ts#L32)
```js
export declare class Request extends Body {
  constructor(input: Request | string, init?: RequestInit);

  readonly method: string;
  readonly url: string;
  readonly headers: Headers;

  clone(): Request;
}

export interface RequestInit {
  method?: string;
  headers?: HeadersInit;
  body?: BodyInit;
  mode?: RequestMode;
  credentials?: RequestCredentials;
  cache?: RequestCache;
  redirect?: RequestRedirect;
  referrer?: string;
  referrerPolicy?: ReferrerPolicy;
  integrity?: string;
  // Cloudflare Workers accept a `cf` property to control Cloudflare features
  // See https://developers.cloudflare.com/workers/reference/cloudflare-features/
  cf?: {
    [key: string]: any;
  };
}
```

Here is [a link](https://github.com/bitinn/node-fetch/blob/master/test/test.js#L734-L780) to some tests on `node-fetch` for the timeout extension. But again, I'm not too familiar with it, or tested.

```js

it('should allow custom timeout', function() {
  this.timeout(500)
  const url = `${base}timeout`
  const opts = {
    timeout: 100,
  }
  return expect(fetch(url, opts))
    .to.eventually.be.rejected.and.be.an.instanceOf(FetchError)
    .and.have.property('type', 'request-timeout')
})

it('should allow custom timeout on response body', function() {
  this.timeout(500)
  const url = `${base}slow`
  const opts = {
    timeout: 100,
  }
  return fetch(url, opts).then(res => {
    expect(res.ok).to.be.true
    return expect(res.text())
      .to.eventually.be.rejected.and.be.an.instanceOf(FetchError)
      .and.have.property('type', 'body-timeout')
  })
})

```

**Comment by shinyaohira** [comment]
@sbrichardson I've confirmed it works. Thank you!
I'm using TypeScript so I submitted PR #1602 for node-fetch extensions typings.

**Comment by sbrichardson** [comment]
@shinyaohira Awesome, would you mind sharing an example of the timeout setting you used, or the config object? Thanks
