### ISSUE TITLE
Feature Request: NOT_FOUND error

### ISSUE THREAD

**Issue by kgoggin** [apollographql/apollo-server#1624]
I love the move towards standardizing specific error scenarios introduced in 2.0 with `AuthorizationError`, `ForbiddenError`, and `UserInputError`. I'd like to propose a new standard error: `NotFoundError`.

## Use Case
Mutations to update or delete an entity nearly always require the entity's ID to be passed in as an argument, and usually the first step in the resolver logic is to look the entity up and verify that it actually exists before modifying/deleting it. This error could be used to handle the scenario when, for whatever reason, the entity referenced in the mutation arguments didn't actually match any known entity. Of course, this could also be extended to queries where we're looking for a specific entity.

I think this use case differs enough from the `UserInputError` to make it worthwhile as my understanding is that that error is intended to be used for validating input arguments that were likely input by a user. In many scenarios the entity ID provided to a mutation is not actually a "user input" and therefore I feel that that error is not appropriate for this scenario (in most cases).

## Implementation
Looking at the code [for the existing custom errors](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-errors/src/index.ts#L177), I can't see any reason why this error would need to be any different. Specifically I'd propose this:

```js
class NotFoundError extends ApolloError {
  constructor(message: string) {
    super(message, "NOT_FOUND");

    Object.defineProperty(this, "name", { value: "NotFoundError" });
  }
}
```
If there's agreement on including this, I'm more than happy to submit a PR with the implementation.

**Comment by defunkt1721** [comment]
I was just working on improving my error handling and wondered the same thing. It makes no sense why there's no standard NotFound/404 error.

Seeing that we already have `AuthorizationError`, `ForbiddenError `and `UserInput `error, it does not make any sense not to have a `NotFoundError`.

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
