### ISSUE TITLE
where is `graphiqlKoa` in v2

### ISSUE THREAD

**Issue by sibelius** [apollographql/apollo-server#1646]
- [x] feature

on v1, we could do something like this:

```
router.all(
  '/graphiql',
  graphiqlKoa({
    endpointURL: '/graphql',
    subscriptionsEndpoint: `ws://localhost:${process.env.GRAPHQL_PORT}/subscriptions`,
  }),
);
```

how can we do the same on v2?

**Comment by hugoserrana** [comment]
Hi @sibelius,
On mine, the GET on /graphql is returning Graphiql.
I don't know if this is the new design of Apollo-Server....

**Comment by hugoserrana** [comment]
I found this in the docs: https://www.apollographql.com/docs/apollo-server/whats-new.html#GraphQL-Playground

**Comment by sibelius** [comment]
could be related to this one https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28167

**Comment by Dknightsure** [comment]
Have a problem with V2
Error: has no exported member 'graphiqlKoa'

**Comment by BengBu-YueZhang** [comment]
> Have a problem with V2
> Error: has no exported member 'graphiqlKoa'

https://stackoverflow.com/questions/52402396/has-no-exported-member-graphqlkoa-and-have-tried-all-the-config-options

**Comment by JeffWong16** [comment]
You don't neet to use graphiqlKoa, just visit 'localhost:4000/graphql' .

**Comment by evenfrost** [comment]
Mine returns `404`. Any update on this?

**Comment by abernix** [comment]
Apollo Server 2.x ships with GraphQL Playground; we no longer ship GraphiQL with Apollo Server.  As of Apollo Server 2.7.0 (currently in _alpha_ via #2937), we now provide a `getMiddleware` method (#2435) on Koa and Express to expose the composed middleware that Apollo Server would otherwise apply via `applyMiddleware`.  This should allow more refined customization when using Apollo Server with Koa.  It still won't use GraphiQL though, so if that's of interest to you, I recommend setting `playground: false` and attaching your own GraphiQL Koa middleware (e.g. https://github.com/expo/koa-graphiql).
