### ISSUE TITLE
POST /graphql requests do not share session or cookies with main app

### ISSUE THREAD

**Issue by rosshadden** [apollographql/apollo-server#1657]
Other people don't seem to have this workflow problem, so it must be something I'm doing wrong or lacking information. Say I have the following middleware (koa, but I don't know if that matters):

```javascript
app.use((ctx, next) => {
  console.log(ctx.method, ctx.originalUrl, ctx.isAuthenticated());
  return next();
});
```
Assume I add a `GET /` endpoint. It is not important what it does, as the logging happens in the middleware above.

The following logs are printed in their given situations:

- `GET /`, with authenticated session:
  - `GET / true`
- `GET /`, when logged out:
  - `GET / false`
- `GET /graphql`, with authenticated session:
  - `GET /graphql true`
- `POST /graphql`, with authenticated session:
  - `POST /graphql false`

Since the Apollo playground runs the last executed query upon load, loading `/graphql` in my browser actually plays both the `GET` and the `POST` requests above. As you can imagine, the auth cookies are passed in the `GET` request, but are not in the `POST` request.

I'm not saying this is a bug, but asking a question. How can I make this work the way I expect? When I make a GQL query for example, I need to have access to the authenticated user inside the body for that query.

By the way, yes I have a `context` function which returns the koa context, but it obviously doesn't have the authenticated session either because the core problem I explained above occurs first. So anything that happens afterward is just a byproduct of this issue.

**Comment by ksmithut** [comment]
I have a similar issue. It might have to do with the way the routes are getting mounted, because everything I put onto `req` is gone, unless I put it onto `res.locals`, which can then be accessed by `req.res.locals`. I think it has to do with this function: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/nodeHttpToRequest.ts

I'm not sure how it works if you only use apollo-server, but at least with apollo-server-express my workaround is to have a middleware before I `apolloServer.applyMiddleware({ app })` that just adds whatever I want in my context to the `res.locals` object. I don't necessarily like that since that object has historically be used to pass variables to express views, but it works.

**Comment by ksmithut** [comment]
maybe that function has nothing to do with it, because now I don't know why the res.locals thing works.

**Comment by rosshadden** [comment]
I tried what you are saying, @ksmithut. In fact that was my intent with making the middleware. The equivalent with koa is adding things to `ctx.state`. But pretend that middleware in the OP is adding something to res.locals/state. If the GQL request isn't authenticated (like it's not in my OP example) there's nothing I can add. What do I add to res.locals if their is no authenticated user at that point?

**Comment by ksmithut** [comment]
You could add `ctx.state.isAuthenticated = ctx.isAuthenticated()`, then in your resolvers, use that to see if the request is authenticated. It's possible that the cookie isn't being sent, but if they're on the same host you logged into, it should work... unless the http request being made doesn't have the "sendCredentials" or whatever the option is to send cookies and auth headers. If you want to debug it, you can log what the headers are to see if the cookie is being sent in the graphql requests. I'll see if there are some options you can set for that in the graphqlPlaygrounds config.

**Comment by rosshadden** [comment]
My point though is that inside that middleware, `ctx.isAuthenticated()` (for example) is `false` for GQL POST requests from the playground. Therefore in the resolvers it is false too.

The cookies are not being sent in the GQL requests. Only the page loads, like when you load the playground. My guess is the playground does not set `sendCredentials` like you mentioned. Might be an easy thing for me to test.

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.  At this point, it's also gone unanswered for so long (sorry!) that we need to clean up some older issues and this doesn't appear to have much in the way of 👍 s indicating that it's been a recurring problem.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
