### ISSUE TITLE
Implementing Relay Connections for Paging

### ISSUE THREAD

**Issue by RehanSaeed** [apollographql/apollo-server#1669]
I'm not using Relay but do like its `Connection` pagination model. Is it possible to implement this with Apollo Server and if so, are there any examples out there I could follow?

**Comment by dmerrill6** [comment]
Hi Rehan, we implemented a library for doing exactly that here: 

https://github.com/Terminal-Systems/apollo-cursor-pagination

It's composed of a builder and a ORM connector in order to work with different ORMs/Query builders. Currently the Knex connector is implemented, but it should very straightforward to connect to different ORMs by creating new connectors.

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
