### ISSUE TITLE
Loosely typed API = can't compile TS app

### ISSUE THREAD

**Issue by 19majkel94** [apollographql/apollo-server#1755]
I have a small TypeScript app and I want to use Apollo Server 2.0 for exposing my GraphQL API through HTTP. However the `context` API is typed as `any` so I'm not able even to run the example from docs:

```js
new ApolloServer({
	typeDefs,
	resolvers,
	context: ({ req }) => ({
		authScope: getScope(req.headers.authorization)
	}),
});
```

as I have `noImplicitAny` enabled:

![image](https://user-images.githubusercontent.com/10618781/46300721-b6623d00-c5a4-11e8-8d8c-0401491414cf.png)

And I even don't know from typings which properties I can expect in the callback:

```ts
export type Context<T = any> = T;
export type ContextFunction<T = any> = (
  context: Context<T>,
) => Promise<Context<T>>;
```

I've digged in the source code and I've found it it's called with many arguments:

```ts
this.context({ connection, payload: message.payload })
```
```ts
this.context(integrationContextArgument || {})
```
```ts
return super.graphQLServerOptions({ req, res });
```

And I think that they should be explicitly provided to `ContextFunction` callback type to support both subscriptions context and express context.

**Comment by abernix** [comment]
I've verified that this should be fixed with more recent versions of Apollo Server, though I'm not specifically sure which PR fixed it.

![image](https://user-images.githubusercontent.com/841294/60531010-babdb100-9d02-11e9-9642-9d06a6bdadf6.png)


Possibly fixed by #2350, but in general, should be fixed.  Thanks for reporting this originally!
