### ISSUE TITLE
Receiving null when attempting query of Rest API

### ISSUE THREAD

**Issue by Oba-One** [apollographql/apollo-server#1779]
Hi! I'm using the instagram API to fetch hashtag data but when I test a query in playground I'm receiving null. Here's what the instagram API should return along with my schema and resolvers. Thanks for the help!

```
// Instagram API Response
{
data: {
	name: "kobe",
	media_count: 5764274
},
meta: {
	code: 200
}
}



// Schema 
const typeDefs = gql`
  type Tag {
      media_count: Int
      name: String
    
  }
  type Query {
      tag(tag: String!): Tag
    
  }
`;

export default typeDefs



// Resolver
const baseURL = `https://api.instagram.com/v1/tags`;

const resolvers = {
  Query: {
    tag: async (_, args) => {
      const {tag} = args
      const response = await fetch(`${baseURL}/${tag}?access_token=${process.env.INSTAGRAM_ACCESS_TOKEN}`);
      return response.json();
    }
      
  }
};

export default resolvers;
```

**Comment by jsegaran** [comment]
Thanks for reporting this issue originally!

If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!
