### ISSUE TITLE
Is it possible to use MongoDB on Apollo Server without the use of anything related to Express?

### ISSUE THREAD

**Issue by bchehraz** [apollographql/apollo-server#1781]
Hello,

This might be a super general and vague question to ask- I just want to know if it's possible to set up Apollo Server/GraphQL & also run MongoDB (using Mongoose) in the same project. I'm new to all this tech.

I was under the impression that you'd be able to run Apollo Server and MongoDB without Express, but every tutorial I find online is using both Apollo Server AND Express. I was under the impression that Express and Apollo did the same job and that there was no reason to have both...

Thank you

**Comment by selipso** [comment]
I don't think this is how Apollo Server works. Although Apollo adds a GraphQL wrapper around a node server to handle GraphQL queries, you still need a node server to wrap around underneath (provided by Express, Koa, and other frameworks that Apollo is compatible with).

If you are looking for a more batteries-included solution, you may want to look at [Prisma](https://github.com/prisma/prisma), which will soon release the beta version of its MongoDB connector that you can follow along [its progress here](https://github.com/prisma/prisma/issues/1643). Prisma uses Apollo Server underneath the hood and sets up a graphql-express server for you with nice default values.

**Comment by eberhara** [comment]
As @selipso said, `apollo-server` is a graphql wrapper around a nodejs server, which is commonly an `express` server.
The choices you make behind the graphql wrapper is really up to you. So yes, it is definitely possible to use mondogb along with apollo. However, you still need a nodejs server.

**Comment by jasonpaulos** [comment]
Hi everyone, I'm going to close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I recommend directing further questions to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
