### ISSUE TITLE
Can I exclude introspection query from processing in context function?

### ISSUE THREAD

**Issue by vroad** [apollographql/apollo-server#1805]
I'd like to disable authentication on introspection queries and enable it for other kinds of queries, so that I can see schema in GraphQL playground, even when no valid authorization header is present.
If I just throw exception when no valid authorization is present, playground fails to load schema because introspection query fails.

The only way to get around from this problem seems to be not throwing authentication errors at all if NODE_ENV is development. There is no way to check whether GraphQL query is introspection or not inside context function, isn't it?

```js
const server = new ApolloServer({
    schema,
    context: () => {
        // throw authentication error if authorization header is not present or invalid
        throw new AuthenticationError("Invalid authorization header");
    }
});
```

**Comment by eberhara** [comment]
My understanding is that, in this case, you should not validate user authentication on the `context` callback.
As per the [docs](https://www.apollographql.com/docs/guides/access-control.html#schema-auth):
> We would want to do this only on very restrictive environments where there is no public access to the schema or any fields, like an internal tool or maybe an independent micro service that we don’t want exposed to the public.

Did you take a look on [Resolver auth](https://www.apollographql.com/docs/guides/access-control.html#resolver-auth)? Maybe it fits better with your case.

**Comment by vroad** [comment]
Hi, @eberhara , Sorry for the late reply.

Is that only way? I'd like to handle authentication in a single place on an API gateway server. It already has executable GraphQL schema from underlying APIs, so I didn't want to duplicate resolvers/mutations at API gateway level.

**Comment by jbaxleyiii** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
