### ISSUE TITLE
How to implement Multi-tenant architecture?

### ISSUE THREAD

**Issue by thardy** [apollographql/apollo-server#1808]
I'm looking for one or both of the following features...

**The ability to tell ApolloServer which schema to use for a given request at runtime**
I would like to be able to tie multiple schemas/resolvers to ids, then have the Apollo middleware identify which schema to use based off a value I provide in the request.

**The ability to update schemas at runtime**
When a schema changes, I'd like to be able to rebuild it for Apollo at runtime.

I'm open to alternative approaches.  What options do I have currently?  I'd appreciate some help identifying the possible paths to success here, so I can start heading down the shortest one.

**Comment by thardy** [comment]
A little more info about what I have already...

I've already got a ContentApi up and running using MongoDb.  All the tenant's data is in a customData collection, where every doc has an orgId and a contentType.  The contentTypes are described in a customSchemas collection.

I can easily handle everything via a single resolver (or single set of resolvers).  What I'm struggling with is exposing each tenant's custom schema for graphQL.  I can piece together the typedef for a tenant, but hot-swapping those schemas at runtime is where I'm currently coming up short.

Any help will be appreciated.

**Comment by sbrichardson** [comment]
Yes, it can work, here's a quick (informal) screen recording of it working in an app we are developing.

https://youtu.be/l3CS2DwK38g

It's a little bit more difficult in Apollo Server 2.0, you need to patch applyMiddleware with an async function to return the schema instead of using the schema stored when instantiating the ApolloServer instance.

**Comment by capaj** [comment]
@thardy yeah I don't think this is possible with apollo-server 2.x.x. If you don't need apollo-server with all bells and whistles-you could just implement this:
https://github.com/capaj/apollo-server/blob/a619a8cd288cb46364dd6285469717b79ca939ba/packages/apollo-server-express/src/expressApollo.ts#L34

yourself and you certainly can always supply any schema you have at the moment in your middleware.

**Comment by JakeDawkins** [comment]
This issue seems a bit stale. We don't really see anyone asking for this behavior in our conversations or this issue, so for now, I think we'll close this. 

We don't generally recommend using a single endpoint to access multiple distinct schemas. We'd probably recommend 2 endpoints, and let the clients do the switching between the two somehow.

**Comment by larsbuch** [comment]
I am exploring the same challenge.
I have 70+ customers who can define and change their schema themselves primarily amount of properties but also their hierarchy. The flexibility is core selling point for the product.

Has the reply changed from last time it was asked?

As a fallback I am half considering spinning a container with apollo server up for each customer if the spinning up apollo server on request has too high latency
