### ISSUE TITLE
No way to catch errors on server.listen() (e.g., EADDRINUSE)

### ISSUE THREAD

**Issue by ezyang** [apollographql/apollo-server#1819]
- [X] feature

I'd like to setup `apollo-server` to search for the first open port available and use it. This does not seem to be possible. I've tried a few things:

1. Server does not support `on` method, so I cannot register a callback `on("error", ...)` which is the API a normal server gives
2. I've tried giving listen a callback; this callback does not seem to be called on error
3. I've tried attaching an error handler to the returned promise. The promise does not seem to get this error.

**Comment by jasonpaulos** [comment]
Hi @ezyang, thanks for originally opening this issue. In order to have your OS assign an arbitrary unused port to your server, you can pass in 0 for the port number to ApolloServer's `listen` method. As stated in the [Apollo documentation here](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apolloserverlistenoptions-promise), ApolloServer passes its arguments to the underlying Node `net.Server.listen` method. This method's documentation [can be found here](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback).

I hope this answers your question.
