### ISSUE TITLE
apolo server 2 hot reload docs

### ISSUE THREAD

**Issue by ZikDead** [apollographql/apollo-server#1823]
I`m using pure apollo-server 2, after first tutorial. But how do I enable hot reload for this? Can u add response to FAQ, or some guide? I cant find solution to work with apollo-server 2

**Comment by justinanastos** [comment]
:wave: I’ll close this since this doesn’t appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I’d ask that you take this question to the _Apollo Server_ channel within [the Apollo community Spectrum](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
