### ISSUE TITLE
Return warnings?

### ISSUE THREAD

**Issue by davidbarratt** [apollographql/apollo-server#1839]
I'm using Apollo Server at [graphql.wmflabs.org](https://graphql.wmflabs.org/) ([source](https://gerrit.wikimedia.org/g/labs/tools/graphql)), I see the [error handling](https://www.apollographql.com/docs/apollo-server/features/errors.html) documentation, but I was wondering if there's a way to pass _warnings_ to the user? the [MediaWiki Action API](https://www.mediawiki.org/wiki/API:Main_page) will sometimes return warnings for deprecations, etc. And I would like to pass this on to the user (it should appear similar to the way Errors appear in the documentation).

Main task: https://phabricator.wikimedia.org/T207349

**Comment by hwillson** [comment]
Sorry for the long delay in responding to this @davidbarratt. Would it be possible to convert the warning into an error, throw that error, then handle it specially on the client side? You could consider [augmenting the error with extra details](https://www.apollographql.com/docs/apollo-server/features/errors/#augmenting-error-details) that show it's a warning, then handle it accordingly. 

I'll close this issue for now since we're trying to keep issues here reserved for bugs, but if you have any questions please reach out via [Spectrum](https://spectrum.chat/apollo). Thanks!
