### ISSUE TITLE
Docs for developing Apollo Server itself

### ISSUE THREAD

**Issue by eberhara** [apollographql/apollo-server#1840]
Maybe there are already docs about it and I simply did not find, but here it goes anyway.

Whenever I try to contribute to apollo-server packages, I find it very difficult to test my changes against a real node (express, for example) server.

I believe we could have a better documentation on this development process.

**Comment by capaj** [comment]
there's this: https://github.com/apollographql/apollo-server#apollo-server-development

so assuming you can get npm to link it, it may be exactly what you need. Please let me know if you succeed at making the link.

**Comment by eberhara** [comment]
Yeah, I've seen that, and they are correct.

However, I believe we should have a section for "development process" with more visibility than the last piece of the main readme file.

Also, we should not believe everybody has all global dependencies in order to run/compile apollo packages. Maybe it would be good to have some steps for installation + running local.

What do you think @capaj ?

**Comment by justinanastos** [comment]
Hi @eberhara 👋! I'd love to know what other additions you think would make setting up the development process for `apollo-server` easier to understand. 

Our goal is to make it easy for anyone to contribute; what can we add to those instructions to make it easier to follow?

**Comment by JakeDawkins** [comment]
Thanks for the feedback! We have a plan this quarter to improve the development process around Apollo-server. I know we have a couple things in-flight around this, and we'd love to hear any suggestions you have. If you have any questions, or would like to get onboarded in the meantime, we'd love to hear from you in our [spectrum community](https://spectrum.chat/apollo).

Since this isn't technically an issue about the product as-is, I'm going to close this.
