### ISSUE TITLE
Large mutation raises OOM exception and server crash.

### ISSUE THREAD

**Issue by mjasnikovs** [apollographql/apollo-server#1846]
I faced interesting result wile posting large mutation.

mutation contains object
```JavaScript
{
   10 keys
   key: [~list of 200 objects]
}
```
Actual size is not large
```JavaScript
app.use(bodyParser.urlencoded({extended: true, limit: '2mb'}))
app.use(bodyParser.json({limit: '2mb'}))
```

GraphQL produces errors, something like this
```JavaScript
Field "Batch" is not defined by type OrderLineType at value[0].[object Object]Variable "$order" got invalid value [SENT OBJECT]
```

But, as i have list, there is 200+ errors.
So, for every single error, grapqhl provides full copy of posted object. Error buffer gets to large and here is result
```
<--- Last few GCs --->

[1100:000001DBF36A3F60]   140557 ms: Mark-sweep 8188.8 (8323.5) -> 8188.8 (8323.5) MB, 81.6 / 0.0 ms  allocation failure GC in old space requested
[1100:000001DBF36A3F60]   140651 ms: Mark-sweep 8188.8 (8323.5) -> 8188.8 (8320.5) MB, 94.5 / 0.0 ms  last resort GC in old space requested
[1100:000001DBF36A3F60]   140740 ms: Mark-sweep 8188.8 (8320.5) -> 8188.8 (8320.5) MB, 89.2 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001222EC25879 <JSObject>
    1: DoJoin(aka DoJoin) [native array.js:~94] [pc=000000572D3B0E46](this=00000307B0A822D1 <undefined>,o=000003A4E9EF66D9 <JSArray[268]>,p=268,D=00000307B0A82371 <true>,z=000003E3FA7A5259 <String[2]: , >,y=00000307B0A823E1 <false>)
    2: Join(aka Join) [native array.js:~119] [pc=000000572D3B1ABE](this=00000307B0A822D1 <undefined>,o=000003A4E9EF66D9 <JSArray[268]>,p=268,z=000003E3FA7A5259 <St...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::AsmJsScanner::IsNumberStart
 6: 000000572D2043C1
```

Increasing --max-old-space-size=8192, dose not help. Node still crashes.

**Comment by abernix** [comment]
Thanks for reporting this, though I've changed the subject to something which accurately represents the issue rather than an editorialized headline.

This isn't a DDoS, but seems to be producing an out-of-memory condition which results in a server crash (DoS, okay. [DDoS, no.](https://www.webopedia.com/TERM/D/DDoS_attack.html)).  Most production environments should automatically recover from conditions like these by running the server with something like [`forever`](http://npm.im/forever), but its worth better understanding the shape of the resulting data.  For example, have you evalualted whether similar conditions are encountered when running this mutation directly with `graphql-js`?

Is there a way you could put together a simple reproduction, either as a GitHub repository or an [Apollo CodeSandbox](https://codesandbox.io/s/) or [Glitch](https://glitch.com/edit/#!/remix/apollo-launchpad)?

Also, it's probably worth mentioning: In the event that this were an actual _DDoS_ or security vulnerability, we'd ask that you disclose the problem responsibly to core maintainers by e-mailing `security@` our domain, `apollographql.com`, or via a discussion with a core maintainer on [Apollo Slack](https://www.apollographql.com/slack).

Thanks!

**Comment by mjasnikovs** [comment]
@abernix Thank you, just tested, problem is in graphql-js.

**Comment by JasonLi914** [comment]
@mjasnikovs - Do you happen to know what the issue was in graphql-js?

**Comment by mjasnikovs** [comment]
@JasonLi914 here is reproduction code: https://github.com/mjasnikovs/mutation

**Comment by goldcaddy77** [comment]
Hitting this issue as well.  Has anybody opened the issue with `graphql-js`?

**Comment by mjasnikovs** [comment]
@goldcaddy77 I did, but nobody cares. Until somebody starts crashing servers, I don't think there will be fix 🗡
