### ISSUE TITLE
Apollo-server-express - Error in context middleware provide an empty graphQLErrors in a catch statement

### ISSUE THREAD

**Issue by mi-mazouz** [apollographql/apollo-server#1848]
Hello!!

I'm trying to catch a graphql error from context middleware.

For first I throw an ApolloError in context middleware, like this:

```
module.exports = ({ req }) => {
  throw new ApolloError('NOT_FOUND', 404)
}
```

In the front side, I'm running the onError middleware, like this:

```
onError(({ networkError, graphQLErrors }) => {
 console.log(graphQLErrors)
}
```

In my saga middleware I do the request:

```
try {
      const { data } = yield call(graphqlClient.query, {
        query: myQuery,
        variables: myVariables
      })

       .....
    } catch (error) {
      console.log(error.graphQLErrors)
      .....
    }
```

Inside the catch error.graphQLErrors is empty, what I see in my console:

![screen shot 2018-10-23 at 14 12 05](https://user-images.githubusercontent.com/24244248/47359703-af26de80-d6cd-11e8-8b7c-5410f1d857dc.png)

So, I don't understand why graphQLError is good in the onError middleware and empty in my catch statement. I want to precise that it's happening only when I throw an error in the context middleware, it works well when the error is from resolvers.

Also I'm getting a 400 status code instead a 404!

Thanks!!

**Comment by ayushnawani** [comment]
@mi-mazouz  how did you solve this issue? I am also facing the same issue.

**Comment by jsegaran** [comment]
Thanks for reporting this issue originally!

If this is still a problem, could someone who's experiencing this problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!
