### ISSUE TITLE
length directive example doesn't work

### ISSUE THREAD

**Issue by tuananh** [apollographql/apollo-server#1886]
https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Enforcing-value-restrictions

I couldn't make the example work. there's no error but directive just does not works.

i want to validate argument so i add `ARGUMENT_DEFINITION`

    directive @length(max: Int) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION | ARGUMENT_DEFINITION

However, I'm getting this error from the playground

    Uncaught Error: Invalid or incomplete schema, unknown type: LengthAtMost5. Ensure that a full introspection query is used in order to build a client schema.

**Comment by jbaxleyiii** [comment]
`LengthAtMost5` isn't in the directive you setup?

👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
