### ISSUE TITLE
Adonis support for Apollo Server 2

### ISSUE THREAD

**Issue by jpcbarros** [apollographql/apollo-server#1897]
Hello Guys,

Just noticed you are already supporting some frameworks like hapi and express. So, is there anyone already working on supporting [Adonis](https://adonisjs.com) too? Of course I'm talking about Apollo Server version 2.

If not, is there any kind of documentation or process for developing such an integration? If yes, please share here and maybe I can help with that.

PS: Already saw #1088 but wasn't able to find all answers there.

Cheers,

**Comment by enniel** [comment]
Support for Adonis Framework added in PR #1937.

**Comment by msadeghifard1989** [comment]
Hello, please, I beg you earlier the new version apollo-server-adonis support apollo-server 
 
https://libraries.io/npm/apollo-server-adonis

**Comment by hchuff** [comment]
Due to the overhead of supporting multiple HTTP frameworks, we have decided not to 
maintain integrations with specific frameworks in Apollo Server 3.
We are encouraging contributors to publish their own apollo server integrations as they find appropriate.
We intend to make these integrations easier and more natural in the future versions of Apollo Server.
