### ISSUE TITLE
how to avoid multiple root query call in single request?

### ISSUE THREAD

**Issue by c2pig** [apollographql/apollo-server#1913]
Wonder what is the proper way to avoid multiple root query call? For example :- 

Schema/Resolver
```
const typeDefs = gql`
  type Query {
    hello: String
  }
`;
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};
```

query.json
```
[{"query":"{\n  hello\n}\n"},{"query":"{\n  hello\n}\n"}, ... ]
```
`curl --header "Content-Type: application/json" -X POST --data @query.json host/graphql`

I have scenario where my GraphQL server being attack using pattern above (ie: hundred query embedded in one array to exhaust backend API)

**Comment by Fallion** [comment]
Hi have a look at: https://medium.com/workflowgen/graphql-query-timeout-and-complexity-management-fab4d7315d8d

**Comment by martijnwalraven** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
