### ISSUE TITLE
Cannot use PORT defined by environment variable at runtime for Meteor app

### ISSUE THREAD

**Issue by cmoses8626** [apollographql/apollo-server#1919]
I'm using Apollo Server in a Meteor app. When setting up to deploy to Heroku, the [docs](https://www.apollographql.com/docs/apollo-server/deployment/heroku.html#Setting-up-the-project) say to pass the PORT environment variable into the server.listen() function. When passing in no value (`server.listen()`), Apollo Server starts fine. But passing in the environment variable as recommended (`server.listen({ port: process.env.PORT || 4000 })`), results in the following error:

<img width="599" alt="screen shot 2018-11-04 at 4 19 20 pm" src="https://user-images.githubusercontent.com/1293068/47969991-7849b480-e04d-11e8-9be7-b3b0e7039864.png">

The code for reproducing the error is available [here](https://github.com/cmoses8626/apollo-resolutions/blob/master/imports/startup/server/register-api.js).

This works fine if I'm not using Meteor.

**Comment by abernix** [comment]
You'll likely need to take a different approach here since Meteor also has its own server which would be binding to `PORT` first.

A common successful pattern we've seen that combines Meteor and Apollo is that which is enabled by the incredible [`swydo:ddp-apollo`](https://github.com/Swydo/ddp-apollo) Meteor package.

That technique is likely to be the most well-documented, full-featured and battle-tested technique for using Meteor with Apollo (and also leverages the existing DDP WebSocket!), though there are other approaches which could bring the Apollo Server middleware into the existing Meteor middleware chain and leverage the same `PORT` that Meteor itself is bound to (using Meteor's `WebApp.connectHandlers`; the `WebApp` symbol can be imported from the core `meteor/webapp` package), and that's documented in [our documentation](https://www.apollographql.com/docs/react/recipes/meteor/#server).
