### ISSUE TITLE
Avoid loading already loaded child properties

### ISSUE THREAD

**Issue by christianrondeau** [apollographql/apollo-server#2024]
Let's say I have a query like this:

```
query {
  order(id: "1234") {
    lines {
      id
    }
  }
}
```

And on the server, I have two services: one to return an order, which contains its list of lines with only their IDs, and another to load all line details. So the former would look like this:

```
{
  lines: [
    { id: 'line1' },
    { id: 'line2' }
  ]
}
```

In that case, currently, Apollo will load every line from the server even though it _already_ has everything the request requires (the `line` object already has the `id` property).

This is a simple use case but one that comes up very often. In the previous case, I actually even have a little bit more info on each line (the current status, and a few other properties) in the parent call that I can use as-is, and therefore avoid making another backend call.

To achieve this, I'm going through the `GraphQLResolveInfo` and attempt to match all properties on the parent object. If everything matches, I can simply return the parent's property as is. Here's an example in a resolver, in practice for a `project.user.id` tree:

```
    Project: {
        user: async (project, _args, { dataSources }, info) => {
            if (containsRequestedProperties(project, 'user', info)) {
                return project.user;
            } else {
                return dataSources.myAPI.getUser(project.user.id);
            }
        }
    }
```

This seems like something that could be built-in Apollo, like properties that are automatically matched with the resolved objects when no resolver are defined for them. I also have the code (already generic enough to be PRed) and tests,

I was wondering however, how should this be applied?

1. Automatically, so if the data exists, we use it? In the vast majority of use cases, that will work, but would remove the ability to say "don't do that" except on a global settings level.
2. Manually, in every resolver methods. That's what I'm doing now, but it creates noise in resolvers since this same if/else directive ends up everywhere.

I'd like to hear what you think before moving forward with a PR. Is there interest in such a functionality? Do you have any suggestions about how I should be implementing this in Apollo Server?

**Comment by christianrondeau** [comment]
Just a quick update, my implementation uses a helper method that reduces boilerplate:

```
    MyParentEntity: {
        child: async (parent, _args, { dataSources }, info: GraphQLResolveInfo) => {
            return skipIfLoaded(parent, 'child', info, () => dataSources.myAPI.getChild(parent.childId));
        }
    }
```

So the overhead is not that bad once the code is written, so if you're uncomfortable skipping the resolver methods, providing the utility as part of Apollo might also be an interesting option (though discoverability is lower this way)

**Comment by davidmwhynot** [comment]
This issue is old but is still open so I'm wondering if it is solved by some new feature of apollo server I'm unaware of. If not, is there any plan to implement this? I have the same issue in my project.
In the meantime, I'm curios to know how you solved this issue @christianrondeau so I may do the same for my project.

**Comment by christianrondeau** [comment]
@davidmwhynot I have a helper method like this. Note that while this works for our needs, it has issues such as how we do recursive checks and whether types match.

```typescript
import graphqlFields from 'graphql-fields';
import { GraphQLResolveInfo } from 'graphql';
import { UserInputError } from 'apollo-server';

export function skipIfLoaded<TParent, TChild extends keyof TParent>(
    parent: TParent,
    prop: TChild,
    info: GraphQLResolveInfo,
    load: () => Promise<TParent[TChild]>
): Promise<TParent[TChild]> {
    if (childContainsRequestedProperties(parent, prop, info)) {
        return Promise.resolve(parent[prop]);
    } else {
        return load();
    }
}

function childContainsRequestedProperties<TParent>(
    parent: TParent,
    prop: keyof TParent,
    info: GraphQLResolveInfo
): boolean {
    const child = parent[prop];

    if (child === undefined) {
        return false;
    }

    const selections = getChildRequestedFields(info);

    return selections.every(s => {
        const childValue = child[s];
        if (childValue === undefined) {
            return false;
        }
        return true;
    });
}

function getChildRequestedFields(info: GraphQLResolveInfo): string[] {
    return Object.keys(graphqlFields(info, {}, { excludedFields: ['__typename'] }));
}
```

**Comment by abernix** [comment]
It sounds like you're looking for something like [`graphql/dataloader`](https://github.com/graphql/dataloader)?

**Comment by glasser** [comment]
Users of Apollo Server get a lot of flexibility in how they structure their resolvers and what kind of data they return from resolvers that return object types.  The default resolver (which reads the value of a GraphQL field by looking for a JS field of the same name on the parent object) is a nice convenience that allows you to leave out very simple resolvers from your app (though it does mean that "find references" on your data types won't find what is arguably the most important use of a field, publicly exposing it in your API — personally I prefer writing out all resolvers explicitly instead of using default resolvers anyway).  But as soon as you're writing custom code for a field's resolver, the default resolver isn't used at all. To me that seems to be a much simpler model than "the default resolver always runs and then if some condition is met it uses that instead of your customer resolver" — should the condition be that the field is absent? that its value is not `undefined`? that it is neither `undefined` nor `null`?

It's not a huge burden to put these checks directly in your resolver or to write your own resolver wrapper that applies whatever the flavor most appropriate to your graph is. I don't think we are likely to change this behavior in Apollo Server.
