### ISSUE TITLE
Omitted optional input set to null causes backward incompatibility

### ISSUE THREAD

**Issue by strblr** [apollographql/apollo-server#2056]
Hello,

This issue is related to https://github.com/apollographql/react-apollo/issues/1569
I recently upgraded the version of apollo-server for a professional project, and the fact that omitted optional inputs are now passed as "null" made the app break.

For exemple, I have a query that looks like this : 
```editProfile(id: ID!, name: String, job: String, bio: String, avatar: String)```

In the previous versions, omitting an argument client-side gave "undefined" on the server-side, which I used to determine which field should be updated in the database. If an input field is "undefined" in the resolver, then just update the other fields !

However, after the upgrade, all the "undefined" became "null", which in my case meant setting the explicit "null" value in the database. Therefore, with this client-side query...
```editProfile(id: "4fd52f1s", name: "Carl")```
... the avatar, the job and the bio fields were set to null, even if I just wanted to change the name.

If that's an intented change and not a bug, I have the following options : 
- Rewrite my massive client to always explicitly send all the inputs, and get rid of optionality
- Find a specific value other than undefined or null to signify that an optional field was omitted
- Switch back to a previous version of apollo-server

I choose option 3.

**Intended outcome:**

Omitted optional inputs are set to undefined in resolvers. I mean, I just need a way to tell my server the difference between an omitted optional input, and an optional input explicitly set to "null".

**Actual outcome:**

They are set to null, which is a valid explicit value for some optional inputs.

**Comment by yashrajpchavda** [comment]
I have the same problem with apollo-client@2.6.4, any idea about the fix?

**Comment by glasser** [comment]
Unfortunately this old issue does not have a reproduction so it's hard to tell if it's still an issue or not. (It is also likely that the observed change was a change in `graphql-js` rather than Apollo Server.)

Note that there is a distinction between not providing a *variable value* and not providing a *field argument*. So for example, in the operation `query Q(x: ID) { field(arg: $x) }` the argument `arg` is always provided (perhaps null) even though the variable `$x` isn't always provided; this is different from `query Q2 { field }` where the argument is not provided.

Without a reproduction there is no way to evaluate this further, so I have to close it.
