### ISSUE TITLE
HEROKU: "error": "Failed to fetch schema. Please check your connection"

### ISSUE THREAD

**Issue by romucci** [apollographql/apollo-server#2059]
Hey there I added introspection to my config...

```
const graphQLServer = new ApolloServer({
  context: ({ req, res }) => ({
    models
  }),
  introspection: true,
  playground: true,
  resolvers,
  typeDefs
})
```

but it still it gives me the failed to fetch fetch schema in heroku.

I added NODE_ENV - production to my settings and everything else seems to be fine, everything works totally fine locally.

**Comment by DaoudBoulad** [comment]
Did you reach a fix?

**Comment by Boltmerz** [comment]
Did you reach a fix?

**Comment by JakeDawkins** [comment]
I think I know what's going on here. For Heroku, you need to use the port that the ENV specifies. You can do that in the `server.listen` command. More info in our [deployment guide](https://www.apollographql.com/docs/apollo-server/deployment/heroku/#setting-up-the-project)

**Comment by HGZdev** [comment]
In my case, I got three problem to overcome:
1) Database has to be well deployed and db:migrate triggered to define the db schema.
2) If `1)` is fulfilled, then make sure whether your graphql path points to `server url` not to `localhost:<port>`, The easiest way to check that is via browser/devtools/network query. 
3) (optional) I use ApolloClient and my rule `process?.env?.NODE_ENV ? 'prod_url' : 'dev_url'` didn't work because of missing vars definitions in webpack:
```	
new DefinePlugin({
	'process.env': {
		NODE_ENV: JSON.stringify(process.env.NODE_ENV),
	},
}),```
