### ISSUE TITLE
Apollo server in azure functions does not work, missing functions in packages?

### ISSUE THREAD

**Issue by meds** [apollographql/apollo-server#2063]
Following the example here: https://www.apollographql.com/docs/apollo-server/v1/servers/azure-functions.html

I found that graphqlAzureFunctions and graphiqlAzureFunctions both don't actually exist.

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  The Azure Functions package has received quite a bit of love since this was opened (thanks to @michael-watson) and this may no longer be a problem.  Thanks!
