### ISSUE TITLE
Light theme colors for the playground

### ISSUE THREAD

**Issue by abdelhedydev** [apollographql/apollo-server#2117]
When you are using the light theme and you type 'CTRL+F' to make a search , the word that you have typed is not readable due to his color .

**Comment by abernix** [comment]
Ref: (To myself?) https://github.com/prisma/graphql-playground/issues/649

**Comment by abernix** [comment]
The above issue I linked to wasn't quite right and this problem still exists with `graphql-playground` upstream so I dug into it a bit and seem to have fixed it with https://github.com/prisma/graphql-playground/pull/1051, which I opened upstream.

However, since we maintain a fork, I also went ahead and applied it to our fork and made a new release on the upcoming 2.7.0 release line, and this has been included in `2.7.0-alpha.8`.  Please try it out and report back if it's not working, but I'm pretty confident this can be resolved (and we will apply whatever the final upstream result is back to this when/if it lands there).

Thanks for reporting this originally!
