### ISSUE TITLE
[apollo-server-lambda] Missing additional properties when throwing inside custom scalar's parseValue/parseLiteral

### ISSUE THREAD

**Issue by livingmine** [apollographql/apollo-server#2155]
**Intended outcome**: 
The error response inside errors's extensions should contain the additional properties when throwing the error using ApolloError inside a custom scalar's parseValue/parseLiteral.

**Actual outcome**: 
It does not contain the additional properties.
![image](https://user-images.githubusercontent.com/7286614/50679797-92951400-1037-11e9-805e-d192da46a630.png)

**How to reproduce the issue**: 
Using apollo-server-lambda v2.3.1 and graphql v14.0.2, have a custom scalar that throws ApolloError inside its parseLiteral/parseValue like the following:
```
parseLiteral(ast): string | boolean {
    ...
    throw new ApolloError('An error', 'DELETE_FAILED', {// additionalProperties
        test: 'test'
    });
}
````

**Additional Information**: 
Replacing the ApolloError with GraphQLError instead results the intended outcome.
```
throw new GraphQLError(
      'An error',
      null,
      null,
      null,
      null,
      null,
      {test: 'test'}
    );
```
![image](https://user-images.githubusercontent.com/7286614/50680122-0f74bd80-1039-11e9-81eb-3a98f901b776.png)

Also, throwing the same ApolloError from one of the resolver instead results the intended outcome.

**Comment by michaeldzjap** [comment]
I have a similar problem. I am throwing a custom error in `parseLiteral`, which in turn is triggered by a custom schema directive applied to the argument of a type query (i.e. in order to check that the ID of my type is in UUID format). All logic works as desired, but I get strange / incomplete error responses when throwing an error in a custom type that inherits from `GraphQLScalarType`. If I use `ApolloError` like so:

```ts
throw new ApolloError('some error message', 'VALIDATION_ERROR');
```

the response I get back is:

```json
{
    "errors": [
        {
            "extensions": {
                "code": "VALIDATION_ERROR"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 13
                }
            ]
        }
    ]
}
```

So although I do seem to be getting part of the error, I am missing the message passed as the 1st argument to `ApolloError` and there is no stacktrace, even though I have set the debug property to true and my `NODE_ENV` is set to "development". I have to mention that I am using Apollo Server 2, but using it as a middleware instead of via `ApolloServer`. Perhaps this is related to #1439?

Anyway, the only way I can get a satisfactory error response is if I use:

```ts
throw new GraphQLError(error.message, ast, null, null, null, null, {code: error.code, message: error.message, exceptions: {stacktrace: error.stack}});
```

which gives me

```json
{
    "errors": [
        {
            "extensions": {
                "code": 422,
                "message": "The id is not a valid UUID.",
                "exceptions": {
                    "stacktrace": "Error: The id is not a valid UUID.\n    ..."
                }
            },
            "locations": [
                {
                    "line": 2,
                    "column": 13
                }
            ]
        }
    ]
}
```

So I can work around it, but I still would like to know why throwing an `ApolloError` gives me such a minimal error representation as response. Something seems not completely right there.

**Comment by vale981** [comment]
Try upgrading `graphql-tools` to the latest version.

**Comment by glasser** [comment]
We've removed the ApolloError class in Apollo Server 4 in favor of using GraphQLError directly, which you've said is exactly what fixes your problem. Sorry for the delay!
