### ISSUE TITLE
Error: Cannot find module 'graphql'

### ISSUE THREAD

**Issue by marcospgp** [apollographql/apollo-server#2208]
If GraphQL is a dependency this should be mentioned in the readme.

Thanks!

**Comment by zackzachariah** [comment]
It is mentioned in the docs linked to from the readme:
[Here's an example in the lambda setup docs](https://www.apollographql.com/docs/apollo-server/deployment/lambda.html#Setting-up-your-project)

However, I agree it would be much clearer to put it into the `package.json`'s `dependencies` or `peerDependencies` arrays rather than `devDependencies` where it currently is. Can anyone on the Apollo team speak to why it's in dev and not peer or prod deps?

**Comment by dnalborczyk** [comment]
@marcospgp @genuinezack it is a peer-dependency: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server/package.json

the project is using [lerna](https://github.com/lerna/lerna), where the root usually contains all dev dependencies for all `project-packages`, whereas the packages itself contain the dependencies, or peer dependencies.

**Comment by genuinezack** [comment]
@dnalborczyk Acknowledged! However, in the root `graphql` is again listed in `devDependencies` and not as a `peerDependencies`. My understanding is that the whole purpose of `peerDependencies` is to cause the dep management tools to throw a warning if a given package is not present _before_ you get to the runtime stage. I think that @marcospgp and my complaint is that, because the Apollo-Server-Monorepo (root project) and the Apollo-Server package (the one the documentation actually points you to) only list `graphql` in its `devDependencies`, it can appear that things are working perfectly locally in development but then cause confusion when you get to production.

Is the a reason not to list it in `peerDependencies` for these two `package.json`'s? My instinct is that wouldn't add any pain or cost but would solve a lot of headaches for people who are coming to the package any way other than the step-by-step tutorial?

**Comment by abernix** [comment]
If it's missing somewhere, please do open a PR for that location (all those pages should be publicly PR-able!)

**Comment by genuinezack** [comment]
Thanks @abernix - over and out.
