### ISSUE TITLE
Custom scalars don't run when using modules

### ISSUE THREAD

**Issue by mgeraci** [apollographql/apollo-server#2218]
Hi! We are using [Apollo Server modules](https://github.com/apollographql/apollo-server/blob/ad4240295469821c24aaf2f1032b12882dd3b6f9/packages/apollo-server-core/src/ApolloServer.ts#L232-L233) to organize our code at OkCupid, and as I looked into adding custom scalars to our graph, it appears that they don't quite work with modules.

I took [this example from the Apollo Server docs](https://www.apollographql.com/docs/apollo-server/features/scalars-enums.html#graphqlscalartype), added a few console logs, and updated it to pass the `typeDefs` and `resolvers` in as a module instead of on the top level.

```.js
const { ApolloServer, gql } = require('apollo-server');
const { GraphQLScalarType, Kind } = require('graphql');

const myCustomScalarType = new GraphQLScalarType({
  name: 'MyCustomScalar',
  description: 'Description of my custom scalar type',
  serialize(value) {
    console.log("serialize");
    let result;
    // Implement custom behavior by setting the 'result' variable
    return result;
  },
  parseValue(value) {
    console.log("parse");
    let result;
    // Implement custom behavior here by setting the 'result' variable
    return result;
  },
  parseLiteral(ast) {
    console.log("literal");
    switch (ast.kind) {
      case Kind.Int:
      // return a literal value, such as 1 or 'static string'
    }
  }
});

const schemaString = gql`
  scalar MyCustomScalar

  type Foo {
    aField: MyCustomScalar
  }

  type Query {
    foo: Foo
  }
`;

const resolverFunctions = {
  MyCustomScalar: myCustomScalarType,
  Query: {
    foo: () => {
      return { aField: 1 };
    },
  },
};

const scalarModule = {
  typeDefs: schemaString,
  resolvers: resolverFunctions,
};

const server = new ApolloServer({
  modules: [ scalarModule ],
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`)
});
```

I expect the docs to reflect the new type, and for the `serialize` log on line 8 to run when a request is made in playground. But while I see the the `MyCustomScalar` type details, the description doesn't come through. And when I execute a request, none of the `myCustomScalarType` functions run.

Thanks in advance for your time, and thanks for making a great tool! Please let me know if there's anything else I can provide to help debug this. I'm also quite new to GraphQL, so let me know if I've misunderstood something here!

**Comment by digitaljohn** [comment]
I just ran into this now. I'm trying to create a standard Date scalar that I can use across my modules with no luck.

**Comment by mgeraci** [comment]
For what it's worth, a solution that I found is to just... not use modules. The code in the server config becomes a little more complex, but you can do the following:

```.js
import { ApolloServer, makeExecutableSchema, gql } from "apollo-server-express";
import { merge } from "lodash";

// an example module
import user from "modules/user";

const schema = makeExecutableSchema({
	typeDefs: [
		user.typeDefs,
		// etc.
	],
	resolvers: merge(
		user.resolvers,
		// etc.
	),
});

const server = new ApolloServer({
	schema,
});
```

This also fixes another bug with modules — if you make a union type when using modules, Apollo doesn't tell you about (or run) the `__resolveType` function for them. So I'd recommend moving to the method above, even though it's more verbose.

**Comment by digitaljohn** [comment]
Nice one @mgeraci... That's exactly what I ended up doing just now!

**Comment by abernix** [comment]
Thank you for reporting this issue!

As you've both found here, this is currently a limitation of the `modules` implementation in Apollo Server which internally leverages [`@apollographql/apollo-tools`'s  `buildServiceDefinition`](https://github.com/apollographql/apollo-tooling/blob/ba39cdafa4a7e438cf5fd12fb0599028f2f78245/packages/apollo-tools/src/buildServiceDefinition.ts) rather than [`graphql-tools`'s `makeExecutableSchema`](https://github.com/apollographql/graphql-tools/blob/67d03a94667bd5fba2e93d286cd7918d937a3907/src/makeExecutableSchema.ts) which supports custom `scalar`s directly in the resolver map.

Longer-term, we suspect that we'll land on a more effective module approach with `buildServiceDefinition` than that is currently possible with `makeExecutableSchema`, but the patterns you've adopted above may be better suited in for some scenarios (e.g. custom `scalar`s) in the short-term.

This is all to day, it's on our radar, particularly as we move to introduce further modularization for federation support.

**Comment by stephenhandley** [comment]
I'm not sure if this is a related issue since we aren't using modules but instead are passing `{typeDefs, resolvers, formatError, context, introspection, cors, debug}` directly, but after bumping the underlying dependency of `graphql` (graphql-js) from `0.13.2` to `14.1.1` our previously working Scalar Resolvers stopped working: `parseDefault`, `parseLiteral`, and `serialize` are no longer getting called)

I've tried the solution suggested by @mgeraci to explicitly call makeExecutableSchema however that doesn't address the issue. I've confirmed this is an issue with both apollo `2.4.6` and `2.0.4`. For reference, the reason for the `graphql` version bump was that with the previous version, primitive scalar types weren't being properly validated (more details available [here](https://github.com/apollographql/apollo-server/issues/2375)). 

@abernix if you could provide any information on ETA on a fix or other potential workarounds that would be very much appreciated. Currently our options of  either`validate primitive scalars` or `validate custom scalars` isn't workable.

**Comment by abernix** [comment]
@stephenhandley That's not related to this issue.  I think you've done the correct thing by opening the issue that you did above (https://github.com/graphql/graphql-js/issues/1755) on the `graphql-js` repository.  It might be useful if you updated that repository with a minimal reproduction though, because I'm sure that I've seen `parseLiteral` and `serialize` working on `graphql@14.x` versions.

**Comment by stephenhandley** [comment]
@abernix thx and sorry for the noise, as I mentioned on the linked ticket, it turns out it was the interaction between a lib of mine `graphql-validated-types` which was extending `GraphQLScalarType` and `graphql` where the changed implementation in `14.x.x` broke my implementation

**Comment by chrischen** [comment]
Ran into this same issue and thought I was doing __resolveType wrong... What are thoughts on using https://github.com/Urigo/graphql-modules as a nearly identical replacement?

**Comment by Siyfion** [comment]
Oh wow this caught me out big-time today! 😢 (The `__resolveType` function not being called when using modules)

I guess this is another thing to add to my tweet about module support and where is it going? @abernix / @trevor-scheer What is the recommendation in the meantime? Just stay away from modules?

**Comment by adnanfajlur** [comment]
nitip sandal

**Comment by no1melman** [comment]
So is this going to be fixed?

This seems crazy that it has been open for so long and is an extremely _surprising_ limiting feature

**Comment by dfee** [comment]
Solved.

The answer is to use `modules`, but not on `ApolloServer` (in the config), but instead to use `@apollo/federated`.

tl:dr;
```ts
// Change this
// const server = new ApolloServer({
//  modules: [ scalarModule ],
// });

// To this
const server = new ApolloServer({
  schema: buildFederatedSchema([ scalarModule ]),
});
```

Where `buildFederatedSchema` comes from `@apollo/federated`.

Alas, this appears to be an issue with copy-pasta code, that has evolved in only one implementation:

#### the type for `ResolverMap` in `apollo-tools`:
```ts
export interface GraphQLResolverMap<TContext> {
  [typeName: string]: {
    [fieldName: string]:
      | GraphQLFieldResolver<any, TContext>
      | {
          requires?: string;
          resolve: GraphQLFieldResolver<any, TContext>;
          subscribe?: undefined;
        }
      | {
          requires?: string;
          resolve?: undefined;
          subscribe: GraphQLFieldResolver<any, TContext>;
        }
      | {
          requires?: string;
          resolve: GraphQLFieldResolver<any, TContext>;
          subscribe: GraphQLFieldResolver<any, TContext>;
        };
  };
}
```

#### the type for `ResolverMap` in `apollo-federation`:
```ts
import { GraphQLFieldResolver, GraphQLScalarType } from "graphql";

export interface GraphQLResolverMap<TContext = {}> {
  [typeName: string]:
    | {
        [fieldName: string]:
          | GraphQLFieldResolver<any, TContext>
          | {
              requires?: string;
              resolve: GraphQLFieldResolver<any, TContext>;
            };
      }
    | GraphQLScalarType
    | {
        [enumValue: string]: string | number;
      };
}
```

#### the type for `IResolvers` (the root config option for `resolvers` when creating a new ApolloServer):
```ts
export interface IResolvers<TSource = any, TContext = any> {
    [key: string]: (() => any) | IResolverObject<TSource, TContext> | IResolverOptions<TSource, TContext> | GraphQLScalarType | IEnumResolver;
}
```

Three different ways to pass resolvers, three different backing implementations. 🤷‍♂

**Comment by no1melman** [comment]
Yeah that has also been a massive issue with the differing types. I think IResolvers needs to be used because it supports GraphQLScalarType

**Comment by dfee** [comment]
@no1melman so does the `ResolverMap` as exported from `@apollo/federation`. Indeed, it's more fully typed, too.

**Comment by no1melman** [comment]
I used the federation packages - and it appears to work

**Comment by glasser** [comment]
The `modules` option (which confusingly had almost the same behavior as `typeDefs` and `resolvers` but with a completely different implementation under the hood, leading to issues such as this one) has been removed in Apollo Server 4. See the migration guide for details: https://www.apollographql.com/docs/apollo-server/migration/#modules
