### ISSUE TITLE
How to validate input with resolver?

### ISSUE THREAD

**Issue by marcospgp** [apollographql/apollo-server#2222]
For example regarding the custom `Date` scalar: https://www.apollographql.com/docs/apollo-server/features/scalars-enums.html

If I fail to validate the input as a date, should I throw an error? What happens if I throw an error inside, for example, `parseValue`?

If I return the value as null, does it cause an error if the value is required?

How should I validate a custom scalar? By throwing an error or returning null?

**Edit:** Issue number 2222 😄

**Comment by marcospgp** [comment]
So saying a value is required only means it has to be present in the request, it doesn't mean the input actually has to resolve to a non-null value? Ok that makes sense, though indeed there's not much info on this in the docs.

Could you perhaps share some code on how you go about creating and throwing the custom error?

Thanks!

**Comment by rlarcher** [comment]
Sure, suppose you want to have a custom scalar for a rating that's just an int 1-5, then it could be defined like this
`const throwInvalidInput = () => throw new Error("Invalid input");

const validateRating = (rating) => {
  if (rating < 0 || rating > 5) {
    throwInvalidInput();
  }
  return rating
};

const Rating = new GraphQLScalarType({
    description: "1-5 Rating for Restaurant",
    name: "Rating",
    parseValue: validateRating,
    serialize: validateRating,
    parseLiteral(ast) {
      if (ast.kind === Kind.INT) {
        return validateRating(ast.value);
      }
      throwInvalidInput();

      return null;
    },
  }),`

This is a simple example, so I'm just using the same function to validate and serialize. The function for throwing an error could be made more complex to give a more specific error, but you get the idea.

**Comment by jsegaran** [comment]
👋 I'm going to close this since it appears to be a question about how to use it.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
