### ISSUE TITLE
Subscriptions: Authorization via JWT with very short expiration time

### ISSUE THREAD

**Issue by saerdnaer** [apollographql/apollo-server#2234]
The JWT from our login service have a 15 minutes expiration time, so we need to check e.g. before transmission of a notification if the receivers token is still valid. 

Should there be a dedicated message type, with with the client transmits the updated token to the server, e.g. an addition to the GraphQL spec or would you solve the problem by terminating the connection every 15 minutes?

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
