### ISSUE TITLE
Hard coded check for process.release.name === 'node' causing issues

### ISSUE THREAD

**Issue by nyteshade** [apollographql/apollo-server#2356]
9 days ago in the following commit you added a check to see if the `process.release.name === 'node'`. This is causing our deploys to fail because we use nsolid. Please help!

https://github.com/apollographql/apollo-server/commit/3f7a7f3d67a9587517efb539966d7f1a28643831#diff-c710f70502c84a5d7779daee202dbddb

**Comment by nyteshade** [comment]
This was rolled into 2.3.3. Anybody using `nsolid` instead of `node` will not be able to update their version of apollo-server due to the hard string check.

**Comment by abernix** [comment]
Thanks for reporting this!  It should be fixed in v2.4.6 via #2357.  I think relaxing of the `process.release.name` check seems reasonable since we're already checking for the presence of the `process.versions.node` property, which based on my inspection of the `nodesource/nsolid:carbon-latest` Docker image, should still be guaranteed on `nsolid`.

We could consider another technique, but let's see how this works! I'm certainly open to any expert `nsolid` input you might have if you think there are better ways to make this determination.
