### ISSUE TITLE
Apollo server remote schema casts object to [object Object] where string is expected.

### ISSUE THREAD

**Issue by marhub** [apollographql/apollo-server#2383]
Given schema
```
input InputObject{
logo: String
}
updateEntry(input: InputObject){
(...)
}
```
when I send as input:
```
{"input":{
"logo":{}
}}
```

I'm using remote schema.

Actual result: before passing to other service logo is casted to string and "[object Object]" is sent ( and remote server receives string ).
Expected result: server should complain on wrong input!

**Comment by marhub** [comment]
And that expected result is only valid result as stated in 3.5.3 of Graphql Specification here https://facebook.github.io/graphql/June2018/#sec-Response
 "When expected as an input type, only valid UTF‐8 string input values are accepted. All other input values must raise a query error indicating an incorrect type."

**Comment by abernix** [comment]
Thanks for opening this originally.

Please consider using [federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/) ([blog post](https://blog.apollographql.com/apollo-federation-f260cf525d21)) rather than schema stitching, as this is just one of many bugs which exist in the current stitching implementation.  Since we feel federation is a much more sustainable, we won't be putting any more attention on bugs of this nature (which is in fact [in `graphql-tools`](https://github.com/apollographql/graphql-tools/), not here in `apollo-server`)
