### ISSUE TITLE
Cannot listen error, if installSubscriptionHandlers was called

### ISSUE THREAD

**Issue by shkim** [apollographql/apollo-server#2439]
I cannot catch any listen() exception such as EADDRINUSE, if installSubscriptionHandlers was called previously.

```
const httpSvr = http.createServer(app);
server.installSubscriptionHandlers(httpSvr);

httpSvr.on('error', (err: any) => {  console.log('cannot catch error here'); });
httpSvr.listen({ port: 4000 }, () => { console.log('Server running...'); });
```
if installSubscriptionHandlers is not called, above error handler will work.

I could catch the error by setting the on handler before installSubscriptionHandlers call,
but then my app gets same error twice: one for on() handler, the other I cannot catch.

```
const httpSvr = http.createServer(app);
httpSvr.on('error', (err: any) => {  console.log('can catch error but cannot suppress the other'); });
server.installSubscriptionHandlers(httpSvr);
```

How can I gracefully handle exceptions for listen() call?

**Comment by nick-keller** [comment]
Actually have the same issue. Thx for the temporary fix.

**Comment by jsegaran** [comment]
Thanks for reporting this issue originally!

If this is still a problem, could you or anyone else who is experiencing this problem mind building a reproduction of the problem into [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

Building reproductions takes a large portion of core contributor's and issue triager's time, particularly when trying to determine if an issue has been resolved in a newer version of Apollo Server, so this would be tremendously helpful.

If this problem is resolved, please feel free to close this issue, otherwise, we will close it if we don't hear back with a reproduction.  Thanks!
