### ISSUE TITLE
File upload with JSON object using apollo server

### ISSUE THREAD

**Issue by hanmant83** [apollographql/apollo-server#2449]
I want to pass files with JSON object.Please help me

singleUpload (input: uploadFileInput, file:Upload!): File
 input uploadFileInput{
    practiceId:String!
  }

**Comment by sbrichardson** [comment]
```gql
  scalar Upload

  type FileItem {
    id: ID!
    filename: String
    type: FileType
    url: String
    mimetype: String
    encoding: String
    size: Float
    key: String
  }

  input FileUploadInput {
    type: FileType
    owner_id: ID
    filename: String
  }

  extend type Mutation {
    uploadFile(file: Upload!, input: FileUploadInput): FileItem
  }
```


```js
const uploadFileMutation = `
  mutation uploadFile($file: Upload!, $input: FileUploadInput) {
    result: uploadFile(file: $file, input: $input) {
      id
      filename
      type
      url
      mimetype
      encoding
      size
      key
    }
  }
`

// in upload event handler
const variables = {
  file,
  input: {
    filename: this.state.filename.value || null,
    // ...
  },
}

const res = await uploadFunc({
  variables,
})
```

**Comment by martijnwalraven** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
