### ISSUE TITLE
Build error using Parcel: runHttpQuery.js: Property name expected type of string but got null

### ISSUE THREAD

**Issue by lucasvfventura** [apollographql/apollo-server#2453]
Hi everyone,

My current project uses "apollo-server-express": "^2.4.8" and while building the project I get error:  runHttpQuery.js: Property name expected type of string but got null. 

It might be related to the following code lines:
for (const [name, value] of response.http.headers) {
    responseInit.headers[name] = value;
}

Any clue on how to fix it?

**Comment by Megajin** [comment]
There is more entangled into this. Some of the sourcemaps require the source files, which are missing. See https://github.com/parcel-bundler/parcel/issues/2185 and https://stackoverflow.com/questions/52949515/apollo-client-with-parcel-warnings. However those are "only" warnings. But the error you are stating is currently breaking my whole development + build process if I use Apollo and Parcel with the latest versions.

**Comment by abernix** [comment]
Thanks for reporting this issue!

As requested in the [issue template](https://raw.githubusercontent.com/apollographql/apollo-server/master/.github/ISSUE_TEMPLATE.md), GitHub Issues should include simple, runnable reproductions.   This means either a GitHub repository that anyone can clone and run and see the problem or an example built [using the Apollo Server CodeSandbox template](https://codesandbox.io/s/apollo-server) or by ["re-mixing" the Apollo Server Glitch template](https://glitch.com/edit/#!/remix/apollo-launchpad).

Building reproductions takes a large portion of core contributor's and issue triager's time and without a runnable reproduction, we'll close this issue in the next 7 days.  I hope you understand.

If nobody is able to supply a runnable reproduction, we're happy to re-open this later on when one can be provided.  Regardless, thanks again for filing the issue since, reproduction or not, this information could be useful for a future visitor!

**Comment by abernix** [comment]
Happy to re-open this with a runnable reproduction!
