### ISSUE TITLE
如何去除重复数据

### ISSUE THREAD

**Issue by nixinxin0518** [apollographql/apollo-server#2474]
如何利用apollo graphql 根据对象id去处重复的数据

**Comment by martijnwalraven** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
