### ISSUE TITLE
Apollo DataSource to handle custom REST API's Token Authentication 

### ISSUE THREAD

**Issue by yeswanth** [apollographql/apollo-server#2480]
I'm using custom Token-based authentication with my REST APIs. So, every REST API will have a different token that need to be sent. This is a function of _API URL_, _API method_,  _authToken_ and _body_(incase of POST request). 

I'm building a GraphQL wrapper over the REST APIs, but unable to use the custom authentication mechanism of my REST APIs, because I don't get to know the API URL

Is there any way to achieve this?

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Comment by ceecer1** [comment]
@yeswanth  were you able to solve your issue ?
