### ISSUE TITLE
Calling deleteToSchema in __resolveObject

### ISSUE THREAD

**Issue by vivianymchan** [apollographql/apollo-server#2500]
Currently building a graphql gateway. Trying out the experimental feature __resolveObject. Delegate schema is not working because info object has field nodes as the `id` field under rocket instead of the `rocket` itself. If I traverse the schema and operation to rebuild info for rocket field, delegateToSchema works as expected.

```
Rocket: {
    async __resolveObject(object, _a, context, info) {
      return await delegateToSchema({
        schema: context.schemas.remoteSchema,
        operation: 'query',
        fieldName: 'rocket',
        args: {
          id: object.id,
        },
        context,
        info: overrideInfo,
      });
    }
  }

```

For a query,
```
query getFoos {
  foos {
    edges {
      rocket {
        id
        name
      }
    }
  }
}
```

**Comment by martijnwalraven** [comment]
I answered in more detail in a thread on our Spectrum, but this is expected behavior. Object resolvers don't receive field arguments because that would couple them to a particular parent field resolver. The second argument is indeed a list of field nodes, because that tells the object resolver which fields have been requested, and that can be used to optimize fetching. Again, all of this is experimental and likely to change, so you may want to stay away from it for now :)
