### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by cristiandley** [apollographql/apollo-server#2534]
Apollo: 

```
"apollo-server": "2.4.8",
```

Im having the same issue similar to [Issue 2339](https://github.com/apollographql/apollo-server/issues/2339)   but i already implemented `apollo-upload-client`

**From Client im getting my data being sent**

![Screen Shot 2019-04-05 at 09 59 40](https://user-images.githubusercontent.com/1873659/55632754-4e79f280-5791-11e9-9cbe-b7acbf14a8f1.png)

**But on my server im getting an empty object**

{
  documentacion: {}
}

**This is my ApolloServer:**

```
const apolloServer = new ApolloServer({
  cors: true,
  typeDefs: graphqlDefs.typeDefs,
  resolvers: graphqlDefs.resolvers,
  introspection: true,
  context: myAuthConext,
});
```

**this is my graphqlDefs**

```
const typeDefs = gql`
  ${dateTypeDef}
  ${usuarioTypeDef}
  ${someOtherDef}
`;

const resolvers = merge(
  DateTime,
  GraphQLObjectId,
  usuarioResolver,
  someOtherResolver
);
```

**Tried to:**

- Add logger in the context and actually theres a promise...
- Tried to `promiseAll` as the [apollo-upload-example](https://github.com/jaydenseric/apollo-upload-examples/blob/884f6719974ef41ef34f3cc5b016c83a867ca44b/api/resolvers.mjs) shows, but no luck.
- Result still {}

- Downgrade to 2.1.0
- Result still {}

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community Spectrum](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.

Thanks for your understanding!
