### ISSUE TITLE
Apollo testing - query finish event

### ISSUE THREAD

**Issue by asfernandes** [apollographql/apollo-server#2537]
When using `apollo-server-express`, I open the context (a database connection) that needs to be closed. So I do it in this way:

```ts
const server = new ApolloServer({
    schema,
    context: (req: express.Request) => req.res.locals.context
});

const app = express();

app.use((req, res, next) => {
    logger.debug('Query start');
    res.locals.context = new Context();

    next();

    res.on("finish", () => {
        logger.debug('Query finish');
        const context: Context = res.locals.context;
        context.connection.close();
    });
});

server.applyMiddleware({ app });
```

When using `createTestClient` of `apollo-server-testing` I do not known how to close it. Here is the code:

```ts
const server = new ApolloServerBase({
    schema,
    context: () => new Context()    //// FIXME: not closing
});

const client = createTestClient(server);
```

So the database connection is not closed. How to have a hook/event informing that execution ended?

Also looking into the code, it seems the `context` function is called many times, so I'm not sure it's the way to put a resource into the testing server.

I don't found anything in the documentation regarding that matter.

**Comment by zionts** [comment]
The new request pipeline that's in progress has support for setting up lifecycle hooks for opening and closing database connections both on server startup and during request handling in Apollo Server 3.0 roadmap (#2360). You can see the [WIP documentation](https://github.com/apollographql/apollo-server/pull/2008) for these lifecycle hooks and try them out, too! We're going to be tracking these features on the roadmap item rather than spreading them out over issues, so I'll close this out for now. Thank you for the report!
