### ISSUE TITLE
Upgrade GraphQL playground to latest version

### ISSUE THREAD

**Issue by chrisbrooks** [apollographql/apollo-server#2559]
Is it possible to upgrade playground to the latest version to allow the latest features to work with Apollo Server?

**Comment by FluorescentHallucinogen** [comment]
@martijnwalraven @abernix Why do you [forked](https://github.com/apollographql/graphql-playground) `graphql-playground` package and don't update it to the actual version? Does the fork contain any fixes that cannot be for some reason merged into [original repo](https://github.com/prisma/graphql-playground)?

@timsuchanek @huv1k, cc.

**Comment by variousauthors** [comment]
I'm using `apollo-server-express@2.6.2` and the graphql playground doesn't:

1. persist the query when I refresh the page (very annoying)
2. persist the history when I refresh the page

Maybe the thinking here is that because graphql playground polls there is no reason to refresh the page? Regardless, it means that when I sit down to work after shutting down my computer over night I need to re-type all the queries I have been using. I've been reduced to keeping a text file open with a manual graphql history in it, like an animal.

There are closed issues relating to persistence in the graphql-playground repository, ie [this one]. Is it possible to upgrade graphql-playground to the latest version?

[0]: https://github.com/prisma/graphql-playground/issues/312

**Comment by FluorescentHallucinogen** [comment]
@variousauthors Just try the following: :wink:

```js
const server = new ApolloServer({
  schema,
  playground: {
    version: '1.7.20'
  }
})
```

**Comment by abernix** [comment]
This should be resolved with the next Apollo Server.  See #2937 for more details, and try the `alpha` today!

**Comment by axhamre** [comment]
@FluorescentHallucinogen  Your suggestion doesn't work  on 2.8.1

@abernix  What alpha-version are you referring to?

**Comment by abernix** [comment]
@axhamre 	At the time it was `2.7.0-alpha.14` but no override should be necessary on the latest version.  If you're still running into an issue, please open a new issue!
