### ISSUE TITLE
Question: cursor pagination can not support arbitrary page jumping

### ISSUE THREAD

**Issue by linxiaowu66** [apollographql/apollo-server#2587]
Question as title, I just want to confirm my guess。the usage scenario of  cursor pagination mostly in mobile device ? is it right ?

**Comment by trevor-scheer** [comment]
👋 Hey @linxiaowu66, I'm going to close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
