### ISSUE TITLE
Execute some function before each query or mutation?

### ISSUE THREAD

**Issue by rico345100** [apollographql/apollo-server#2609]
Hello, thanks for making great stuff.

I'm making some kind of auth related stuffs. I want to check that the session exists in some queries, however I can't find any related feature that can implement this.

In Express(or Koa/Connect), I can do that with middleware, and I can check the session exists and when it is empty, response as unauthorized request before actual query.

In here, Apollo-Server, middleware is totally different thing, it seems more like "adaptor" or "plugin" stuff that can works with other types of HTTP server.

I don't care what you are calls it, however I just want to process before actual response. How do I execute the function before each query or mutation? Also in that function, is it possible to access "koa context" which session located?

**Comment by abernix** [comment]
These docs are in progress (#2008), but you should be able to do what you want with Apollo Server Request Pipeline plugin.  You can view a preview of them here: https://deploy-preview-2008--apollo-server-docs.netlify.com/docs/apollo-server/features/plugins.html.

If you have any questions, the best place to ask would be on the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) since GitHub Issues are reserved for bugs.

Thanks!
