### ISSUE TITLE
restify: does it work for subscriptions?

### ISSUE THREAD

**Issue by anmolagar** [apollographql/apollo-server#2619]
I am able to follow the README [here](https://www.npmjs.com/package/graphql-server-restify) and was able to get `query` and `mutations` working but subscription is not working.
Am i missing something?

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.  The Restify integration _claims_ to support subscriptions, though I'm not sure if it's been validated or tested.  Is it possible that you're being affected by #1638?

Anyhow, rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
