### ISSUE TITLE
exporting Typedef and resolver Apollo-server

### ISSUE THREAD

**Issue by SleamJ** [apollographql/apollo-server#2630]
Hi all I'm tryng to export typeDefs and resolver to a root folder to create Apollo-server but I have error

```
export const server = new ApolloServer({
                      ^
TypeError: _apolloServerExpress.default is not a constructor
```

I know that I need babel for using ES5 syntax and I have installed it but anyway I got this tipe of error 

I have everithig ready one problem is exporting schema

exporting code:
```
export const server = new ApolloServer({
  typeDefs,
  resolvers 
});
```

**Comment by k3v3n** [comment]
Please share a full example so we can help you with. What's your package.json look like ?

**Comment by martijnwalraven** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
