### ISSUE TITLE
apollo-server 2.5.0 cors initialization error.

### ISSUE THREAD

**Issue by technanimals** [apollographql/apollo-server#2667]
**Apollo Server Version**: 2.5.0
I was working on a blank project using the getting started from https://www.apollographql.com/docs/apollo-server/getting-started.
**Intended outcome**:
The server should start successfully
**Actual outcome**:
```
Router.use() requires a middleware function but got a Object","stack":"TypeError: Router.use() requires a middleware function but got a Object
```
**How to reproduce the issue**
clone this repo https://github.com/technanimals/chatnology then run
`yarn && yarn start`

**Comment by abernix** [comment]
Everything starts working if you merely delete the `src/cors.ts` file from the attached reproduction.

This is because you've chosen to use a [TypeScript `baseUrl` of `./`](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url) and only reference the files on disk in your project using exact module IDs, rather than relative paths (e.g. `./cors`).

That's certainly your prerogative, but that pattern is in direct conflict with Node.js's own module resolution and you're essentially stomping on packages by the same name.  In this case, you've created your own `cors` module by placing a `src/cors.ts` file within your project.  That might be fine if there wasn't an actual (quite standard, in fact) [`cors`](https://npm.im/cors) package within the project dependency tree.  In this case, Apollo Server uses it, but this configuration causes literally any package which has transitive dependencies on `cors` to use your own implementation instead.

Here's the patch that fixes it.

```patch
diff --git a/src/cors.ts b/src/cors.ts
deleted file mode 100644
index b24f7e7..0000000
--- a/src/cors.ts
+++ /dev/null
@@ -1,20 +0,0 @@
-import { CorsOptions } from 'apollo-server';
-
-const  allowedHeaders = [
-  'Origin',
-  'X-Requested-With',
-  'Content-Type',
-  'Accept',
-  'Accept-Encoding',
-  'Accept-Language',
-  'Access-Control-Request-Headers',
-  'Access-Control-Request-Method',
-  'Authorization',
-];
-const methods = ['POST', 'GET', 'OPTIONS'];
-const cors = (origin: string): CorsOptions => ({
-  allowedHeaders,
-  methods,
-  origin,
-});
-export default cors;
diff --git a/src/server.ts b/src/server.ts
index a29a7f2..3d3ac32 100644
--- a/src/server.ts
+++ b/src/server.ts
@@ -1,9 +1,5 @@
 import { ApolloServer } from 'apollo-server';
 
-import {
-  context,
-} from 'context';
-import cors from 'cors';
 import { resolvers } from 'resolvers';
 import { typeDefs } from 'schema-loader';
 interface ServerConfig {
```
