### ISSUE TITLE
Is gql compatible with typescript's interface

### ISSUE THREAD

**Issue by keyiis** [apollographql/apollo-server#2673]
I used  typescript+koa to dev backend,I has many define interface for query api,now I want use graphql,but i won't rewrite typeDefs,because  typeDefs similar to my interface,so I was wondering if there was an easy way to convert my interface to typeDefs?
![QQ截图20190515085257](https://user-images.githubusercontent.com/7766085/57741318-e521c380-76ee-11e9-8cbb-c2e1c8d442e0.jpg)

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
