### ISSUE TITLE
Child resolver args is empty

### ISSUE THREAD

**Issue by dwalintukan** [apollographql/apollo-server#2683]
version: apollo-server 2.0.4

**Problem**
Given the following resolver:
```
module.exports = {
  Query: {
    myQuery = (parent, args, context) => {
      // args.queryParam is defined
      returns arrayOfItems
    }
  },

  Item: {
    myResolver: async (parent, args, context) => {
      const { queryParam } = args;
      // queryParam is undefined here
      if (queryParam) {
        return { ... omitted }
      }
      return null;
    },
  },
};

query {
  myQuery(queryParam: "mystuff") {
    ...
  }
}
```

I have checked when `myResolver` is called and the second params `args` is always empty. Even when passing the the param when running the query.

I have checked the `args` of `myQuery` and it successfully passes the arg there, but it does not show up on `myResolver`. I was under the intention that `myResolver` should have this arg as well. I even remember it working before, but it has stopped working for me.

As a workaround I am using `myQuery` to set the arg in the `context` and then I can get it from `myResolver.context`.

**Expected**
`myResolver` to have the arg `queryParam` when calling the query with it.

**Comment by rv-alake** [comment]
I'm also seeing this on apollo-server-express 2.4.8. The args param is always empty on child resolvers.

**Comment by JakeDawkins** [comment]
Thanks for logging this concern originally.  I'm going to close this issue since It hasn't received a lot of feedback or traction since it was first opened, and we've changed substantial portions of Apollo Server since then, including a major bump to support Apollo Server 2.x.

If this is still a problem, feel free to ping me back and I (or someone) will be happy to re-open it.  Thanks again!

**Comment by Jricci1** [comment]
This also happened to me but I also manage to work around it by adding the crucial parts of the args in to the context object.

**Comment by xamgore** [comment]
Faced the same issue recently, my workaround was like this:

```
module.exports = {
  Query: {
    myQuery: () => ({ })
  },

  Item: {
    myResolver: async (parent, args, context) => {
      const { queryParam } = args;
      ...
    },
  },
};
```

**Comment by evansmwendwa** [comment]
What was the solve for this? I am getting empty args in resolver

**Comment by ndelvalle** [comment]
> Thanks for logging this concern originally. I'm going to close this issue since It hasn't received a lot of feedback or traction since it was first opened, and we've changed substantial portions of Apollo Server since then
> 
> If this is still a problem, feel free to ping me back and I (or someone) will be happy to re-open it. Thanks again!

This is still a problem.

**Comment by JMA12** [comment]
Yeah its still a problem

**Comment by smolinari** [comment]
I think I'm also seeing this. Repo here: https://github.com/smolinari/gql-modules-test

It's using GraphQL-Modules and TypeGraphql, but the schema being fed to Apollo is good. 

Scott

**Comment by chnoack** [comment]
By intention the query is never passed from the parent resolver to the child resolver, because child resolvers could have their own query.

`fragment ProductFragment on Product {

  currentPricing(currency: $currency) {
    price {
      value
    }
    cause
  }
}

query getSingleProduct(
  $articleNumber: String
  $currency: Boolean
) {
  product(articleNumber: $articleNumber) {
    ...ProductFragment
  }
}
`
