### ISSUE TITLE
Please update the @defer blog post

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-server#2700]
Not sure where to file this to get the appropriate attention:<sup>[1]</sup>

The [Introducing @defer](https://blog.apollographql.com/introducing-defer-in-apollo-server-f6797c4e9d6e) blog post got my colleague all excited about the feature, only to waste a good amount of time figuring out it was actually removed and on the roadmap for 3.0.

Please add a status notice at the top of that blog post.

[1]: [Comments left to this end on the post itself](https://medium.com/@flavienvolken/what-is-the-current-status-of-defer-aa2bac8831bf) did not get attention

**Comment by abernix** [comment]
Thank you very much for opening this, @dandv, and apologies to your colleague for the time they had to expel while digging into this.  I had some changes made to the blog post, including what I hope is a very clear warning that it's experimental and not production ready (and not in any current release!), which will hopefully save future readers.

We are still planning the re-introduction of `@defer`, but it's dependent on some other architectural changes to both the client and the server, in order to make sure that `@defer` can be supported end-to-end by client, server, tooling, Apollo Engine, etc.
