### ISSUE TITLE
The built-in Playground Query delivers the wrong parameter order to Resolver.

### ISSUE THREAD

**Issue by hmmhmmhm** [apollographql/apollo-server#2708]
Let's assume that I create a query of the blabla as follows.

```gql
type Query {
    blabla(text: String!): Boolean
}
```

```javascript
const resolvers = {
  Query: {
    blabla: (parent, arg, context ) => {
       //
    }
  }
}
```

```gql
query {
   blabla(text: "hi?")
}
```
If I use Apollo-client or Axios, I can get { text: "h?" } for the second argument of the blabla function in the Resolver. However, if I generate the same query in the built-in Playground, I can get the value from the blabla function as the first argument, **not the second factor**. and the second arguments having wrong data like a `_extensionStack:~ GraphQLExtensionStack {` blablabla...

Why does the built-in Playground ignore the parent argument of Resolver? It's very weired...

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Comment by hmmhmmhm** [comment]
Hmm.. I see! 👋 I posted my issue on spectrum.chat  https://spectrum.chat/apollo/testing/the-built-in-playground-query-delivers-the-wrong-parameter-order-to-resolver~82da55d2-ef4e-436d-89db-6f05d772d848

**Comment by hmmhmmhm** [comment]
I couldn't give up the Built-in Playground, so I decided to make and operate a simple Workound function.
```typescript
function field(callback){
  return function checker(...param){
      return (param.length == 3) ?
          callback(null, ...param) : callback(...param)
  }
}
const resolvers = {
  Query: {
    blabla: field((parent, arg, context ) => {
       //
    })
  }
}
```

The example above is a typescript function, and in vanilla js you can use the following function.
```javascript
function field(callback){
    return function checker(){
        return (arguments.length == 3) ?
            callback(null, ...arguments) : callback(...arguments)
    }
}
```
If anyone has the same problem as me, use the function above, this will solve the problem simply.
