### ISSUE TITLE
GraphQl Error 400

### ISSUE THREAD

**Issue by Fahime** [apollographql/apollo-server#2729]
Hi
I have used GraphQl to fetch Data from server but I get Error 400. what is my problem? how can I resolve problem?
`
  input FlightInput {
        des: String!
        Date: String!
        rangeType: String!
        scope: String!
        src: String!
    }

 extend type Flight {  
    PDate: String!
    weekdaynumebr: Int!
    Date: String!
    MinPrice: Int!
    flight_date: Int!
  }

  extend type Query {
    getFlights(data: FlightInput!): [Flight]
}

const getFlights = gql `
  query getFlights($data: FlightInput!){
    getFlights(data: $data) {
      PDate
      weekdaynumebr
      Date
      MinPrice
      flight_date
    }
  }
`;

      <Query
        query={getFlights}
        variables={{
          data: {
            des: 'MHD',
            Date: '2019-06-03',
            rangeType: 'month',
            scope: 'local',
            src: 'THR',
          },
        }}
      >
        {
          ({ loading, error, data }) => {
......
`

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
