### ISSUE TITLE
Sharing context typescript issue with Gateway

### ISSUE THREAD

**Issue by Andre153** [apollographql/apollo-server#2786]
When creating a new Apollo server I am adding shared context with build Service. I am getting an error on willSendRequest. Please find my code below:

```js
const { schema, executor } = await new ApolloGateway({
  serviceList: [{ name: "account", url: "http://localhost:4000" }],
  buildService({ name, url }) {
    return new RemoteGraphQLDataSource({
      url,
      willSendRequest({ request, context }) {
        request.http.headers.set("user-id", context.userId);
      }
    });
  }
}).load();

```

This does not happen in runtime. My IDE is complaining about, and when doing a build. I am using:

```js
import {ApolloGateway} from '@apollo/gateway'
```

Here is the error:

```
Argument of type '{ url: string; willSendRequest({ request, context }: { request: any; context: any; }): void; }' is not assignable to parameter of type 'Partial<RemoteGraphQLDataSource> & object & ThisType<RemoteGraphQLDataSource>'.
  Object literal may only specify known properties, and 'willSendRequest' does not exist in type 'Partial<RemoteGraphQLDataSource> & object & ThisType<RemoteGraphQLDataSource>'.

37                     willSendRequest({request, context}) {
```

**Comment by JacksonKearl** [comment]
Problem is the fields in `RemoteGraphQLDataSource` are all marked `protected`. This is probably carried over from things like `RESTDataSource`, which is extended by subclassing rather than a config object. See [docs](https://www.apollographql.com/docs/apollo-server/features/data-sources/#intercepting-fetches). We can either change the fields to be public, or change the docs to use the subclassing strategy.

**Comment by jbaxleyiii** [comment]
@JacksonKearl let's make them public!
