### ISSUE TITLE
[Federation] Enum Type resolvers are not working

### ISSUE THREAD

**Issue by Pruxis** [apollographql/apollo-server#2790]
When defining enum resolvers they are not executed like they would with a regular schema.

This sandbox shares a bugreport of interfaces / unions, but the point is clear. Query animals with a type and you'll see that we never hit the resolver.

https://codesandbox.io/s/apollo-server-z8vml?fontsize=14

**Comment by trevor-scheer** [comment]
Thanks for this one as well, @Pruxis!

I've made a couple small changes in a fork, the most noteworthy change being that I had to pass a literal value instead of a function for the enum resolver. I was able to reproduce this.
Related docs: https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values

1) Toggle between federated and non-federated schema
2) Note difference in log (federated ignores the `DOG: "dog"` mapping and just logs "DOG"

https://codesandbox.io/s/apollo-server-m30d7

**Comment by Pruxis** [comment]
Hey @trevor-scheer thanks for taking the time to check this, I can use __isTypeOf for now as in the end it covers the same functionality only difference is that the code is more spread out over different types.

**Comment by hannesj** [comment]
I think the root cause is the same as in https://github.com/apollographql/apollo-server/issues/2832

**Comment by JacksonKearl** [comment]
Closed in #1345.

**Comment by ahouzzer** [comment]
If I use `graphql` function from `graphql.js` directly like this
```js
graphql(
            federatedSchema,
            query,
            {},                 // root value
            context,
            variables,
            null                // operation name
        )
```
Enum resolvers won't work either.

How can I apply middlewares as https://github.com/apollographql/apollo-server/pull/1345/files#diff-c635668124bc43d28885aa7d04c99342R96 did?

My use case does not use Apollo Server.

**Comment by krvajal** [comment]
@Pruxis did you get it working?
