### ISSUE TITLE
Retrieving uploaded files(static images) from Apollo-Server

### ISSUE THREAD

**Issue by nakiscia** [apollographql/apollo-server#2897]
Hello guys, 

I am using Apollo-Server without using express or any other framework. I have successfully upload files to my server but I cannot get these files(images) from client side. Since I am not using express, I searched for how to set static folder in Apollo-Server like in express server but  I did not find any clear response. 

My question is do I have to use express with apollo-server and is there a way to define a endpoint to serve static files? 

Here is my server setup: 

```
const bodyParser = require("body-parser");
const {resolvers} = require("./graphql/resolvers/index");
const {typeDefs} = require("./graphql/schema/index");
const mongoose = require("mongoose");
const isauth = require("./middleware/is-auth");
const { ApolloServer} = require('apollo-server');
const User = require('./models/user')
const jwt = require("jsonwebtoken");

const server = new ApolloServer({ cors: {
    origin: '*',            // <- allow request from all domains
    credentials: true}, typeDefs, resolvers, uploads: {
    maxFileSize: 10000000000, // 10 MB
    maxFiles: 4
  },
  context:({req})=>{
      try {
        const authorization = req.headers.authorization || '';
        const token = authorization.split(' ')[1]
        const decodedToken = jwt.verify(token, "my super secret key");
        //console.log(decodedToken)
        return User.find({_id:decodedToken.userId}).then(user=>{
            return {user}
        })
    } catch (error) {
        return {}
      }
  },  playground: true,
 },);


mongoose.connect(`
mongodb+srv://somekeyformongo__retryWrites=true
`, {useNewUrlParser: true})
.then(() => {
    server.listen().then(({ url }) => {
        console.log(`🚀  Server ready at ${url}`);
    });
}).catch(err => {
    console.log(err);
})
```

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
