### ISSUE TITLE
upsert_one with apollo server

### ISSUE THREAD

**Issue by kasparov112000** [apollographql/apollo-server#2916]
any here has been able to implement upsert_one with apollo server and client,  I am currently saving my data to local storage using redux state management, here is the code at the client that I am trying to replace

` @Effect({ dispatch: false })
  persistQuestions = this.actions$.pipe(
    ofType(QuestionActionTypes.UPSERT_ONE, QuestionActionTypes.DELETE_ONE),
    withLatestFrom(this.store.pipe(select(selectQuestions))),
    tap(([actions, questionsState]) =>
      this.localStorageService.setItem(QUESTIONS_KEY, questionsState)
    )
  );`

Instead of localstorageService I will create an http service that will call the graphql server, but I am not sure if upsert_one is possible in graphql/apollo

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
