### ISSUE TITLE
apollo-server-plugin-base depends on apollo-server-core but doesn't include it as a dependency

### ISSUE THREAD

**Issue by mohsen1** [apollographql/apollo-server#2964]
As it was discovered here:

https://github.com/yarnpkg/berry/issues/271#issuecomment-507407938

I see in package.json apollo-server-core  is a dev dependency. is this a bug or was it intended?

**Comment by JacksonKearl** [comment]
Left a comment on the attached issue. In short: it's a dev dependency because it only uses the typings, but I'm not sure what the appropriate way to express that is.

**Comment by abernix** [comment]
The primary reason we don't want to make `apollo-server-plugin-base` have a regular (vs. dev) dependency on the `apollo-server-core` package is to maintain separation between the `apollo-server-plugin-base` package and _specific_ versions of `apollo-server-core` (and other integrations), in order to allow plugins to evolve at their own rate while still being compatible at least the major version of Apollo Server.

This may be, yet another, use-case for an `apollo-server-types` package!

**Comment by abernix** [comment]
I've opened https://github.com/apollographql/apollo-server/issues/2970 to track the actual chore necessary to make that happen, but closing this bug is dependent on that getting resolved!
