### ISSUE TITLE
Send new access token based on refresh token in subscription onConnect event.

### ISSUE THREAD

**Issue by cybercoder** [apollographql/apollo-server#2992]
I need to send new ```accessToken``` based on ```refreshToken``` to client. But i can't find how i can do this in documents.

```javascript
const subscriptions = {
  onConnect: async (connectionParams, webSocket) => {
    let { refreshToken, accessToken } = connectionParams;
    // Psudo Code
   if (invalid accessToken but valid Refresh token)
         webSocket.emit(newTokens);
  }
};
```
Something like this.

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
