### ISSUE TITLE
Get operationName and variables in willSendResponse, also type

### ISSUE THREAD

**Issue by rico345100** [apollographql/apollo-server#3026]
I'm trying to log user's activity, so wrote LogExtension:

```javascript
class LogExtension {
  willSendResponse(args) { ... }
}

const server = new ApolloServer({
  resolvers,
  typeDefs,
  extensions: [
    () => new LogExtension
  ]
});

```

The problem is, I want to write the log right before response to client. What I want to log are operationName, variables, errors, success or not, just like common http server log like this:

``` text
200 POST /user
```

I want to put like this:

```text
[SUCCESS] mutation userAdd { ...variables... } 
[ERROR] mutation userAdd { ...variables... } errors { ...errors... }
```

Actually I will write into JSON, anyway I want to know operation name and variables, and if possible, I want to figure out it was query or mutation.

But to response after processed graph ql request, I had to use "willSendResponse", but there is no operationName and variables in there. Those parameters only exists in "requestDidStart". So if there is a multiple request at once, using both "requestDidStart" and "willSendResponse" mess up the log, there's no way to figure out which "willSendReponse" is result of "requestDidStart".

How do I get operationName and variables in willSendResponse? And If possible, how do I determine request was query or mutation? Thanks.

**Comment by robross0606** [comment]
I can't believe this is an open ticket with no solution.  What good is "context" on a response without any context information about the request that triggered it?

**Comment by abernix** [comment]
The `extensions` API (noted above in the OPs) is being deprecated in favor of `plugins`, which I believe should entirely support the use-case here and, unlike `extensions`, is intended to be a public API and is documented as such.

Please try this after consulting the [plugins documentation](https://www.apollographql.com/docs/apollo-server/integrations/plugins/).  You can certainly get the information about the request (and the operation name, and the operation itself) in the `requestContext` of the Plugin API.

**Comment by chrisbrantley** [comment]
I think this should be reopened because I'm not able to figure out how to do this. I just want to log the top-level operations (corresponding to my resolvers). I am using the plugins API.

Take this example query:
```
query {
  firstUser: userByEmail(email: "first@gmail.com") {
    id
    firstName
    lastName
  }
  secondUser: userByEmail(email: "second@gmail.com") {
    id
    firstName
    lastName
  }
}
```

What I'm looking for is the set of operations that the user requested, as in `["userByEmail", "userByEmail"]`. I do NOT want the aliases ("firstUser" and "secondUser") because those aliases are user input and could change at any time.

I've scoured the the `requestContext` to find this and I can't seem to find anything that indicates the operations without parsing the entire body myself.

Is this possible?

**Comment by chrisbrantley** [comment]
You know that thing where you ask a question and then almost immediately find the answer? Yeah, that just happened.

For people who stumble on this issue like I did:
Turns out the entire AST is on `requestContext` which is available in all of the ApolloServer plugin hooks. It's on `requestContext.document`. The data structure is pretty complex, which is why I didn't find what I was looking for previously.

This website was very helpful: https://astexplorer.net/#/gist/79a260c7422cc5abac3d4f90302873be/f2f8980f71e8e17351eaf0fffa45f8e5108e65e3
