### ISSUE TITLE
SchemaDirective in subscription.

### ISSUE THREAD

**Issue by cybercoder** [apollographql/apollo-server#3048]
It seems this is a bug ( Maybe not ).
According [this](https://www.apollographql.com/docs/graphql-tools/schema-directives/) document i made my Auth SchemaDirective like this:

```javascript
class RequireAuthDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const { resolve = defaultFieldResolver } = field;
    field.resolve = async (...args) => {
      let [, params, { req, res, connection }] = args;
      let { user } = req || connection.context;
      if (!!user) {
        return await resolve.apply(this, args);
      } else {
        throw new AuthenticationError('You must be signed in to view this resource.');
      }
    };
  }
}
```
This works fine in every ```Query```, ```Mutation```, ```Subscription```

But when i use an external async method to check authorization like this:
```javascript
class RequireAuthDirective extends SchemaDirectiveVisitor {
  visitFieldDefinition(field) {
    const { resolve = defaultFieldResolver } = field;
    field.resolve = async (...args) => {
      let [, params, { req, res, connection }] = args;
      let { user } = req || connection.context;
      if (!!user) {
        if (await isAllowed(user.id, field.name, params)) return await resolve.apply(this, args); // ChkPoint
        throw new AuthenticationError('You are not authorized to access this resource.'); 
      } else {
        throw new AuthenticationError('You must be signed in to access this resource.');
      }
    };
  }
}
```
In Queries and Mutation it works fine but not in subscriptions!

Note: if i remove the ```ChkPoint``` condition ( Which is returning true ) it will works in subscription.

**Comment by glasser** [comment]
Right now we are planning to remove support for `schemaDirectives` in Apollo Server 3, because the project that implements it (graphql-tools) considers it to be a legacy API. Folks who want to use `schemaDirectives` or its non-legacy replacement `schemaTransforms` can use `@graphql-tools/schema` directly to create a schema passed in with `new ApolloServer({schema})`;  issues relating to these options should probably be opened in the graphql-tools repo.

We're also removing the incredibly skimpy integration of subscriptions into Apollo Server in v3, which led to many problems like this one. We hope to restore an actually integrated subscription implementation later.
