### ISSUE TITLE
tests spits out console.error

### ISSUE THREAD

**Issue by DxCx** [apollographql/apollo-server#306]
during tests, there are prints like `Error in formatError function: Error: I should be catched`
which are printed to console.
we should add hook that enusres there are no "unhandled errors" during tests,
so:
 1.console.error won't be spited to screen, instead it should be captured to an array.
 2.each test can run `handleErrors((errors) => expect(....))` which will clean the array and let the user assert for expected errors.
 3. after each test we should make sure the unhandled errors is cleaned.

**Comment by abernix** [comment]
Jest, which has been implemented since this was originally opened, handles this differently than `mocha` did.  For example, `console.error` (specifically) is certainly output during test execution and correlated with the test that produced it.

I'll close this as I'm not sure it's still relevant, but happy to reopen if you disagree. :smile:
