### ISSUE TITLE
/* istanbul ignore next */ is not working

### ISSUE THREAD

**Issue by DxCx** [apollographql/apollo-server#307]
because tsconfig.json now has `removeComments: true` istanbul does not get ignore next comment.
we need to remove it from main tsconfig.json and add another npm script that will run compile with removeComments.

**Comment by soda0289** [comment]
I think a good way to solve this is to use the newer nyc tool. https://github.com/istanbuljs/nyc
It allows for requiring in code, such as ts-node or babel polyfills, before code coverage is run. I have tested this out and we should be able to set removeComments to false for code coverage.

I can submit a PR with this change.

**Comment by DxCx** [comment]
cool i didn't know there is a new tool :)
yes, please submit a PR thanks :)

**Comment by soda0289** [comment]
#327 We have an issue with dependencies that are precompiled and included as node_modules. Still need to so more testing.

**Comment by abernix** [comment]
Happy to re-open if anyone disagrees, but I don't believe this is necessary anymore, particularly since all of our test coverage is now handled through `jest`.  While I think `j est` still uses `istanbul` internally for code coverage instrumentation (via `babel-plugin-istanbul`), I don't think we have any `/* istanbul ignore next */` annotations in our code.
