### ISSUE TITLE
graphql-extensions - reading request.headers[*] crashes apollo-server

### ISSUE THREAD

**Issue by mthomasuk** [apollographql/apollo-server#3076]
**Using versions:**
apollo-server-koa: 2.7.0-alpha.9 OR 2.7.0-alpha.14
graphql-extensions: ^0.8.0-alpha.3 OR import from `apollo-server-koa`
node: 10.13.0

**Setup:**
Docker container, `nodemon` running `koa` using apollo server `getMiddleware` (alpha release). Using a custom extension class that profiles v8. Class checks if the request contains a specific header in `requestDidStart` ala

```
if (
      request.headers &&
      request.headers[DEBUG_PROFILE_HEADER]
 ) {
```
and then starts up the profiler for that request

**N.B:** works without checking headers

**Expected:**
The server will start and stay up.

**Actual:**
The whole thing just crashes. No stack trace. No nothing, just `[nodemon] app crashed - waiting for file changes before starting...`. 

console.logging the request works, console.logging the request.headers works, and technically console.logging the specific key in headers works but _then_ crashes

Incredibly weird, can anyone give any insight?

**Comment by abernix** [comment]
Thanks for reporting this issue!

As requested in the [issue template](https://raw.githubusercontent.com/apollographql/apollo-server/master/.github/ISSUE_TEMPLATE.md) when you submitted this issue, GitHub Issues need to include simple, runnable reproductions.   This means either a GitHub repository that anyone can clone and run and see the problem or an example built [using the Apollo Server CodeSandbox template](https://codesandbox.io/s/apollo-server) or by ["re-mixing" the Apollo Server Glitch template](https://glitch.com/edit/#!/remix/apollo-launchpad).

Building reproductions takes a large portion of core contributor's and issue triager's time and without a runnable reproduction, we'll have to close this issue in the next 7 days.  Hope you understand!

If you aren't able to supply a runnable reproduction, we're happy to re-open this later on when one can be provided.  Regardless, thanks again for filing the issue since, reproduction or not, this information could be useful for a future visitor!

**Comment by mthomasuk** [comment]
apologies @abernix should've paid more attention to the template - can't reproduce in glitch so feel free to close 🙇

**Comment by abernix** [comment]
@mthomasuk 	All good! If you're able to reproduce it in an actual project and can provide a link we can clone, someone (me?) could take a peak as well. 😄  Happy to re-open if you continue to struggle with it and feel free to jump on the [Apollo Server channel of Apollo's Spectrum.chat](https://spectrum.chat/apollo/apollo-server) for more help as well!
