### ISSUE TITLE
Avoid the need to mention variables multiple times when using directives

### ISSUE THREAD

**Issue by freakomonk** [apollographql/apollo-server#3080]
When a query is formed with directives, we would be declaring the variables 3 times in the query. 

For example 

``user($isFirstNameReqd: Boolean!){
       firstName @include(if: $isFirstNameReqd)
       lastName
       country
  }
variables : { isFirstNameReqd: true } ``

I don't seem the understand the reason to have the variable name at 3 places. Its making the query look bloated. Won't it be easier to check the presence of a variable once its encountered in `@include` and then parse the value provided in variables field to check if its falsy or truthy ?

**Comment by abernix** [comment]
Great question, though probably one that I won't be able to answer in enough clarity within this issue.  Nothing you're questioning here is truly unique to Apollo, Apollo Server, GraphQL or really programming languages in general.

There are a lot of things that theoretically "bloat" (your words, not mine!) the example you've provided: Words, braces, parenthesis, whitespace.  If you're curious, [the GraphQL specification](https://graphql.github.io/graphql-spec/) has explanations and justifications for many of them.  And while the example you provided above is malformed (perhaps you meant to use `query` in place of `user`?), briefly, the explanation for the _three_ uses of the variable name in your example is:

The first use of `isFirstNameReqd` is the declaration and provides the typing for the variable — in this case, `Boolean`.  In a strongly typed query language like GraphQL this is particularly important so that the incoming value, which is supplied _separate_ from the operation in the `variables` map when the operation is executed, can be validated against the declared type.  If the type of the provided value doesn't match the type it's intended for, a validation error will occur which prevents execution.  In the case of the example you provided, the supplied value is `true` — a `Boolean`, but also could have been any value if not properly validated!

The remaining instance of `isFirstNameReqd` is the use-site, within the `@include` directive, where the actual value of the variable is utilized to decide conditionally whether or not the field will be included.

You'll probably note that strictly declaring the type here is the most pressing reason for the third occurrence and in an entirely dynamic language (JavaScript, for example!), perhaps it could be foregone.  Of course, that'd be at the sacrifice of the strong typing that makes GraphQL such a pleasure to use with other strongly-typed languages and tooling.  While this still leaves I'm not sure what could be done about the two remaining instances.

None of this is super likely to change, but if you're looking to iterate on the specification, you could consider opening a proposal with the [GraphQL Specification](https://github.com/graphql/graphql-spec/) repository and bringing it up at a [GraphQL Working Group](https://github.com/graphql/graphql-wg/) meeting.

**Comment by freakomonk** [comment]
That's great explanation @abernix . Thanks ! We had a requirement to dynamically generate GQL queries for which `@include` is a nice solution, so I was having lot of variables declared 3 times in my query, hence the reason to raise this issue.
