### ISSUE TITLE
Mocking Documentation for "Customizing Mocks" is Incorrect

### ISSUE THREAD

**Issue by LoganVS** [apollographql/apollo-server#3086]
https://github.com/apollographql/apollo-server/blob/master/docs/source/features/mocking.md#customizing-mocks

In the first paragraph under "Customizing Mocks", the last sentence reads:
> By default, the functions in mocks will overwrite the resolvers in resolvers. In this example hello will return 'Hello' and resolved will return 'Resolved'.

This is incorrect.  In this example both `hello` and `resolved` will return `Hello`.  

Would open a PR but CONTRIBUTING.MD said not to.  I will if you agree though!

Cheers!
Logan

**Comment by abernix** [comment]
Hmm, this seems to fall into either the [_Improving the documentation_](https://github.com/apollographql/apollo-server/blob/master/CONTRIBUTING.md#improving-the-documentation
) or the [_Small bug fixes_](https://github.com/apollographql/apollo-server/blob/master/CONTRIBUTING.md#small-bug-fixes) category of `CONTRIBUTING.md`, but I hope we can adjust `CONTRIBUTING.md` if you felt otherwise.

Put another way, please do open a PR that fixes this, and please also [open a PR to `CONTRIBUTING.md`](https://github.com/apollographql/apollo-server/blob/master/CONTRIBUTING.md) if this sort of small change seemed unwelcome. 😄 

Thank you very much! 🤗

**Comment by LoganVS** [comment]
Hey @abernix,

Upon rereading `CONTRIBUTING.MD` it does look like this sort of change was welcome.  My fault for misreading.

PR is here: https://github.com/apollographql/apollo-server/pull/3103


Thanks!
Logan

**Comment by abernix** [comment]
Thanks!  Fixed by https://github.com/apollographql/apollo-server/pull/3103
