### ISSUE TITLE
GraphQLPlayground is not defined

### ISSUE THREAD

**Issue by VladimirHumeniuk** [apollographql/apollo-server#3107]
![image](https://user-images.githubusercontent.com/20288162/62136420-5d5a5700-b2e4-11e9-97ae-09a390bb80e9.png)

Dependencies:
```
    "dependencies": {
        "apollo-server": "~2.8.0",
        "graphql": "~14.4.2",
        "graphql-tag": "~2.10.1"
    },
```

Server config:
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  engine: {
    apiKey: process.env.ENGINE_API_KEY
  },
  introspection: true
});
```

I run server, and playground does not work. Looks like CDN just didn't return the files.
I have seen similar issues, but the solutions presented in them do not work.

**Comment by abernix** [comment]
This seems like a network error that prevented the loading of the necessary assets because of SSL errors, as you can see in your console.  The certificate for `cdn.jsdelivr.net` does appear valid to me.  Are you behind a corporate proxy or something?   Can you load `https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.10/build/static/js/middleware.js` and share the certificate details that are shown by your browser (i.e. when you click on the "🔒" in your browser's location bar)?

Happy to discuss further even though I'll close this, but this doesn't appear to be a bug in Apollo Server.
