### ISSUE TITLE
[apollo-server-cloud-functions] WARNING: You didn't provide an endpoint and don't have a .graphqlconfig. Make sure you have at least one of them.

### ISSUE THREAD

**Issue by lookfirst** [apollographql/apollo-server#3113]
Seeing this notice when I'm running the playground. I definitely have the file.

```
import {ApolloServer, PlaygroundConfig} from 'apollo-server-cloud-functions';
import * as functions from 'firebase-functions';

// GraphQL API
const apolloServer = new ApolloServer({
	playground: {
		settings: {
			"schema.polling.enable": false,
		}
	} as PlaygroundConfig,
	typeDefs,
	resolvers,
	context: ({req, res}) => ({
		headers: req.headers,
		req,
		res,
	}),
});

// Cloud Functions export
export const qraphql = functions.https.onRequest(apolloServer.createHandler());
```

**Comment by abernix** [comment]
Hello,

This issue which you've filed here doesn't _appear_ to be a bug with Apollo Server, but rather a question about how to use it.  (Alternatively, it's just too vague to tell if it's a bug, a feature request, or just a question.)

As explained in the [issue template](https://raw.githubusercontent.com/apollographql/apollo-server/master/.github/ISSUE_TEMPLATE.md) when you submitted this issue, GitHub Issues should include:

- [ ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem.  Other great ways to demonstrate a reproduciton are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

However, **instead of opening a new issue**, I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Still though, **sharing a runnable reproduction would be useful**!

Thanks for your understanding!
