### ISSUE TITLE
I don't understand why @provides must be associated with @external

### ISSUE THREAD

**Issue by hugues33** [apollographql/apollo-server#3119]
Hi,

I'm trying to understand why fields defined in a @provides directives have to be marked @external in the associated type.

Here is what I'm trying to do based on provides.test.ts integration test:
``` 
  extend type Query {
    topReviews(first: Int = 5): [Review]
  }

  type Review @key(fields: "id") {
    id: ID!
    body(format: Boolean = false): String
    author: User @provides(fields: "username deathDate")
  }

  extend type User @key(fields: "id") {
    id: ID! @external
    username: String @external
    deathDate: String
    reviews: [Review]
    numberOfReviews: Int!
  }

  extend interface Product {
    reviews: [Review]
  }
```

With the following resolver added:
```
  User: {
    deathDate(user) {
      const found = usernames.find(username => username.id === user.id);
      return found ? found.deathDate : null;
    }
  }
```

And the definition:
```
const usernames = [
  { id: '1', username: '@ada', deathDate: '1852-11-27' },
  { id: '2', username: '@complete', deathDate: '1954-6-7' },
];
```

If I disable validation on provides directive, I get a my expected result.

Do you think my use case is valid?

Complete example is here https://github.com/apollographql/apollo-server/compare/master...hugues33:provides?expand=1

**Comment by jbaxleyiii** [comment]
@hugues33 in the example above, the service that adds the `deathDate` fields is part of the same one where the `@provides` directive is found. The purpose of provides is to hint to the query planner that work normally intended for other services (in your case the `username` field which is normally resolved the the account service) isn't needed because the service it is already fetching from can include that field in the response.

To fix the validation errors, all you need to do is remove the `deathDate` in the provides directive here since that service can provide all of its added fields through normal graphql execution
