### ISSUE TITLE
Express getMiddleware and express-serve-static-core type not found

### ISSUE THREAD

**Issue by CallMeLaNN** [apollographql/apollo-server#3222]
Package name: apollo-server-express
Version: v2.9.0, 5 days ago
TS version: 3.5.3

Expected behavior: No error

Actual behavior: Cannot find module 'express-serve-static-core' when I use `applyMiddleware` and compile using tsc.

Description:

The `apollo-server-express/dist/ApolloServer.d.ts` contain this function signature:

    getMiddleware({...}?: GetMiddlewareOptions): import("express-serve-static-core").Router;

The generated `import("express-serve-static-core")` as explicit return type here is not accurate. When I dig into express core definition, I believe it should be `@types/express-serve-static-core`.

Any instruction to compile this package on my local?

**Comment by JacksonKearl** [comment]
These type definitions are automatically generated by the TypeScript compiler. The `import("express-serve-static-core")` will actually resolve to `@types/express-serve-static-core` when TS interprets the file, so I don't think that is the issue here. Could you have somehow not installed the required ` "@types/express-serve-static-core"` dependency? This is implicitly required through `@types/express`.

**Comment by CallMeLaNN** [comment]
@JacksonKearl my bad, I forgot that TS will look trough `node_modules/@types/*` by default, flattened for all inner dependencies.

I'm not sure if TS will always infer the return type explicitly for generated `*.d.ts` but I just notice it is about [Yarn  PnP](https://yarnpkg.github.io/berry/features/pnp) which doesn't use `node_modules`.

This issue doesn't have a problem for yarn 1.17 with `node_modules` but only for yarn v2. I was about to report to them, probably because of `@types/*` resolution within packages.

**Comment by CallMeLaNN** [comment]
It was fixed by #3230

**Comment by abernix** [comment]
@CallMeLaNN Glad that worked! 😄
