### ISSUE TITLE
buildFederatedSchema breaks when minified

### ISSUE THREAD

**Issue by dncrews** [apollographql/apollo-server#3335]
There seems to be an issue when using buildFederatedSchema while minified.
[Per the documentation](https://www.apollographql.com/docs/apollo-server/federation/introduction/), when you're using federation, you are expected to use
the `extend` keyword on types that will be merged with other schemas:
```graphql
extend type Query {
  ping: String!
}
```
This syntax breaks when minified, causing the error:
```
Error: Cannot extend type "Query" because it is not defined.
```

Steps to replicate:

- [ ] [Clone this repository](https://github.com/dncrews/federation-minification-bug-9-24-19)
- [ ] run `yarn` or `npm install` to install the depedencies
- [ ] run `yarn start` or `npm start` to run the non-minified code. You will see the output line "Built"
- [ ] run `yarn bug` or `npm run bug` to minify and run the minified code. The expected result would be to see "Built" again. The actual result is that it errors out with the aforementioned error.

**Comment by dncrews** [comment]
You may be tempted to ask:
> but why would you minify your Apollo Server?
to which I would reply
> serverless performance

**Comment by abernix** [comment]
Can you [attach a debugger](https://nodejs.org/de/docs/guides/debugging-getting-started/) and investigate what is different at runtime between the two scenarios?

**Comment by abernix** [comment]
Ah, okay: In case it saves you from the debugger, this is due to the way that we're disabling particular validation rules via leveraging `Function.prototype.name` rather than object equality:

https://github.com/apollographql/apollo-tooling/blob/933c3d44b9e5fb7e3c0b462f60ce5b2d7875b15d/packages/apollo-graphql/src/schema/buildSchemaFromSDL.ts#L35-L43

Of course, the `Function.prototype.name` is not stable during minification, and thus the rules which should be by-passed are still being enforced.

**Comment by abernix** [comment]
Once we release the (landed/merged outside this repo) fix from https://github.com/apollographql/apollo-tooling/pull/1551 and update `apollo-graphql` within Apollo Server, this can be closed.
