### ISSUE TITLE
reporting to apollo engine is too slow, causing my lambda to timeout

### ISSUE THREAD

**Issue by khaledosman** [apollographql/apollo-server#3456]
![image](https://user-images.githubusercontent.com/2937633/67774458-b198e280-fa5d-11e9-9549-7fca2cad5306.png)
I'm using apollo-server-lambda with Apollo Engine enabled, however reporting the traces from the lambda to engine's API is too slow that it causes my lambda to timeout sometimes.

`"apollo-server-lambda": "^2.9.7"`

CloudWatchLogs:
```
12:55:02 pm
START RequestId: 93522068-45e7-4e6b-8f84-99dc32949dea Version: $LATEST
12:55:02 pm
2019-10-29T11:55:02.383Z	93522068-45e7-4e6b-8f84-99dc32949dea	WARN	Type "TeamInterface" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
12:55:02 pm
2019-10-29T11:55:02.405Z	93522068-45e7-4e6b-8f84-99dc32949dea	INFO	using cached connection
12:55:02 pm
2019-10-29T11:55:02.405Z	93522068-45e7-4e6b-8f84-99dc32949dea	INFO	creating handler
12:55:12 pm
END RequestId: 93522068-45e7-4e6b-8f84-99dc32949dea
12:55:12 pm
REPORT RequestId: 93522068-45e7-4e6b-8f84-99dc32949dea	Duration: 10010.13 ms	Billed Duration: 10000 ms	Memory Size: 1024 MB	Max Memory Used: 330 MB	
XRAY TraceId: 1-5db82896-215c6ebea39d24bf8325673e	SegmentId: 3e58aa846155ac61	Sampled: true	
12:55:12 pm
2019-10-29T11:55:12.369Z 93522068-45e7-4e6b-8f84-99dc32949dea Task timed out after 10.01 seconds
```
Example X-Ray trace (shows 3 seconds delay to call engine api:
![image](https://user-images.githubusercontent.com/2937633/67774846-5b786f00-fa5e-11e9-8016-5dc6db7591b9.png)

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!

Additionally, we've done a lot of work since 2020 on making Studio reporting more efficient; the fieldLevelInstrumentation usage reporting option may be helpful.
