### ISSUE TITLE
Feature requests: custom logger class for gateway/server/etc

### ISSUE THREAD

**Issue by nurdism** [apollographql/apollo-server#3467]
I'm currently using fastify with apollo-server & apollo-gateway, I'd like to unify the loggers as there are several parts of my app that implement their own logging, I'd like to be able to pass my own logging class to the gateway to use for logging.

**Comment by eliw00d** [comment]
This would be very useful for apollo-gateway when using apollo-server plugins with a specific logger to keep logging consistent.

**Comment by abernix** [comment]
This feature recently landed with https://github.com/apollographql/apollo-server/pull/3894, including the possibility to access the `logger` provided to Apollo Server from plugins.  This is currently published on the `next` npm tag and can be installed with `npm install <package>@next` for either `apollo-server-*` or `@apollo/gateway`.

Since server and gateway are (currently) instantiated separately, for the time-being, it will still be necessary to pass the `logger` to both `ApolloServer` and `ApolloGateway` during their setup.  The one made available to Apollo Server will be on the request context, for both `RemoteGraphQLDataSource`s and for plugins.  The `logger` passed to `ApolloGateway` will be used for non-request specific logging.  Roughly, though I haven't tested this, it should work as such:

```js
const logger = console; // Needs `debug`, `info`, `warn` and `error`.

const gateway = new ApolloGateway({
  logger,
});

const server = new ApolloServer({
  logger,
  gateway,
  plugins: [
    requestDidStart({ logger }) {
      logger.warn("Your own message from your own plugin!");
    }
  ],
});

```
