### ISSUE TITLE
@apollo/gateway doesn't include node-fetch in its dependencies

### ISSUE THREAD

**Issue by migueloller** [apollographql/apollo-server#3471]
When using `@apollo/gateway@0.10.8`, TypeScript fails because it can't find the types for `node-fetch`. This happens specifically [here](https://github.com/apollographql/apollo-server/blob/73cdf0d533908894282debdb6dc5444186af27a6/packages/apollo-gateway/src/index.ts#L41). It looks like `node-fetch` should be added as a dependency, or at least `@types/node-fetch`.

**Comment by msheakoski** [comment]
I ran into this recently and had to add `@types/node-fetch` to my `devDependencies` in order to fix failing builds. Depending on the order that you add/update dependencies, node-fetch usually manages to sneak in, but if you `rm -rf node_modules yarn.lock && yarn install`, the missing node-fetch error happens pretty consistently.

I don't use `node-fetch` directly in my project, and since you can't have comments in package.json, the dependency will end up becoming one of those random things that everyone needs to remember in order to not break builds.

I really hope this gets fixed soon for better DX and reduced element of surprise.
