### ISSUE TITLE
isObject receives string in gateway/RemoteDataSource

### ISSUE THREAD

**Issue by ahouzzer** [apollographql/apollo-server#3541]
Consider this line https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/datasources/RemoteGraphQLDataSource.ts#L71

In my cases, `body` is always a string instead of a parsed object. Therefore, I have to do
```
body = JSON.parse(body)
```
before this line to make it work.

**Comment by trevor-scheer** [comment]
@ahouzzer this is expected. Since not all datasources necessarily use JSON encoding, it's up to you to parse your response into an object.

For reference, see the snippets in the docs here:
https://www.apollographql.com/docs/apollo-server/federation/implementing/#customizing-outgoing-responses

Our recommendation is to extend `RemoteGraphQLDataSource` and implement your `didReceiveResponse` like so:
```js
async didReceiveResponse(...args) {
  const body = await super.didReceiveResponse(args);
  // ...
  return body;
}
```
This takes care of the body parsing (and some error handling) for you.

https://github.com/apollographql/apollo-server/blob/8881d45dfbc6409b27c0ea0fcc30c8b2ff2caebb/packages/apollo-gateway/src/datasources/RemoteGraphQLDataSource.ts#L94-L104

**Comment by ahouzzer** [comment]
Thanks. But this topic deserves a better title. The title of this section is not straight forward enough for me to know what it's talking about.

**Comment by ahouzzer** [comment]
Or maybe the error message should point users to this doc at least. Our company is planning to deploy federation at a large scale and we end up hacking the source code a bit.

**Comment by ahouzzer** [comment]
@trevor-scheer After I applied `didReceiveResponse`, I indeed was able to parse the body. However, the headers of the original request from the client was lost and wasn't send to downstream implementing services. I can't find a good example of this question in the doc and in the Spectrum forum.
