### ISSUE TITLE
Option to fail hard & hit a debugger?

### ISSUE THREAD

**Issue by borekb** [apollographql/apollo-server#3556]
Is there a way to start Apollo Server in such a way that it fails hard when an error is thrown somewhere? I understand that by default, it's a very good idea to recover from errors and keep running, but it also makes debugging harder.

If there's no such option, what would you think about adding it?

**Comment by glasser** [comment]
Sorry for the delay.  I think the answer to this depends on what you mean by "somewhere". If you mean "within a resolver", the design of GraphQL is that different fields can fail more differently (though it would be nice to be able to [cancel execution](https://github.com/graphql/graphql-js/issues/3764) of an operation. If you mean during startup (eg loading a schema) this has been improved by the addition of the (required since v3) async `start()` method.
