### ISSUE TITLE
How to send an error message from the apollo-server

### ISSUE THREAD

**Issue by MilikoDarkion** [apollographql/apollo-server#3575]
this my code

in apollo clients I use useMutation.

**apollo clients**

```
  const [addTodo, { loading, error, data }] = useMutation(gql);
```

**apollo-server**

```
 Mutation: {
    signUp: async (_, formSignUp, { models: { User }, res }) => {
      try {
        const user = new User(formSignUp);
        await user.save();
        const token = await user.generateAuthToken();
        res.cookie("darkAmasia", token, {
          httpOnly: true
        });
        return "string";
      } catch (error) {
        ?????????
      }
    }
  }
```

I heard that throw new ApolloError is used for these purposes.But I do not know how to do it.
when i use throw new ApolloError I get an error in the console. How to make this not happen?

**Comment by glasser** [comment]
There are several approaches to error handling in GraphQL. If the error is common, you may want to represent it explicitly in your schema rather than using a GraphQL error! Otherwise, you can `throw new GraphQLError('message')` (imported from the `graphql` package); in Apollo Server 4 there's no special `ApolloError` subclass of `GraphQLError`.
