### ISSUE TITLE
Middleware path gives 404

### ISSUE THREAD

**Issue by timscott** [apollographql/apollo-server#3578]
I am using `apollo-server-koa` version 2.9.12. My site is hosted at a path, not the root domain. Here's my code (abbreviated for clarity):

```javascript
const app = new Koa();
server.applyMiddleware({
  app,
  path: '/my-path/graphql'
});
app.listen({port}, () => {
  console.log(server.graphqlPath);
  // /my-path/graphql
});
```

GET or POST to `http://mydomain.com/my-path/graphql` give a 404. This seems like a bug or missing/incorrect documentation.

Maybe `apollo-server-koa` does not support custom paths and I need to use `apollo-server-express` instead?

**Comment by mcewball13** [comment]
Did this ever get resolved?

**Comment by glasser** [comment]
I don't know, but the concept of our middleware having opinions about what paths it acts on instead of just using your web framework's standard ability to mount middleware at specific paths was very confusing and bug-prone, and it is entirely removed in the upcoming Apollo Server 4 (which just went into alpha).
