### ISSUE TITLE
apollo-server-express@2.9.12 doesn't include node-fetch in its dependencies

### ISSUE THREAD

**Issue by localnet** [apollographql/apollo-server#3580]
After upgrade from `apollo-server-express@2.9.9` to `apollo-server-express@2.9.12`, TypeScript fails because it can't find the types for `node-fetch`:

```
node_modules/apollo-env/lib/fetch/fetch.d.ts(6,195): error TS7016: Could not find a declaration file for module 'node-fetch'. '/home/Proyectos/server/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`
```

Similar to: https://github.com/apollographql/apollo-server/issues/3471

EDIT: The trouble continue in version `apollo-server-express@2.9.15`

**Comment by trevor-scheer** [comment]
Hey @localnet, thanks for reporting this. Would you (or anyone) with a reproduction handy please provide me with steps to reproduce or a reproduction that I can clone? I'm having a hard time triggering this error myself.

Another useful bit of information for me would be the output of `npm ls apollo-env`. Based on the error, I'm wondering if `apollo-env` is stuck on an incompatible version and/or duplicated within your project due to a bad `package-lock.json` update.

**Comment by localnet** [comment]
The requested repository: https://github.com/localnet/apollo

```
npm install
npm run build

node_modules/apollo-env/lib/fetch/fetch.d.ts(6,195): error TS7016: Could not find a declaration file for module 'node-fetch'.
```

**Comment by trevor-scheer** [comment]
Hey @localnet, thanks for the report and quick follow up. Can you please try out `apollo-server-*@2.9.16` and let me know your results? Everything appears to be working for me now.

**Comment by localnet** [comment]
Yeah, it is solved. Thanks @trevor-scheer.
