### ISSUE TITLE
Please add functional directive style

### ISSUE THREAD

**Issue by bionicles** [apollographql/apollo-server#3647]
I like the Vanilla Apollo Server because it just works. We’d like to make lots of little helper directives for ABAC AuthZ but the current OOP style is a bit verbose to make And Maintain a ton of quality directives 

Would it be possible to simply register functions as directives instead of making a class?

Key desiderata would be:
1. User makes a function into a directive as quickly as possible 
2. User can specify if a directive function executes before or after the resolver

If it’s easier to make these directives then the community can come together to extend Apollo in useful ways

**Comment by bionicles** [comment]
Also I would love to drop the key inside the directive

Ex:

@public(“CRUD”)

vs

@public(ops=“CRUD”)

A minor tweak to simplify multiplied across thousands of devs making thousands of directives would save us all lots of time in the long run (and probably improve latency)

**Comment by glasser** [comment]
Seems like there's two things here:
- Wanting to change the syntax of the GraphQL SDL directive feature. That would be a request against https://github.com/graphql/graphql-spec and I don't think this would be likely to change, as named arguments have been a pretty core part of GraphQL field and directive syntax since day 1.
- Something about how to write functions in your server that process your schema based on directives. Apollo Server no longer (since ASv3 last year) has much of an opinion on how you put together your schema's code; it focuses on binding to web frameworks and providing a plugin API for observing and affecting operations. The code that used to be in Apollo Server around processing directives is now in the `@graphql-tools/schema` project (or related `graphql-tools` projects) which provide all sorts of tools for building schemas such as instrumenting them based on directives.
