### ISSUE TITLE
unable to compile TS app - missing @types/type-is apollo-server-express

### ISSUE THREAD

**Issue by fenos** [apollographql/apollo-server#3691]
After installing `apollo-server-express` and running `tsc` to compile the app i get the following error:

```
Error: Command failed with exit code 2: ./node_modules/.bin/tsc -p tsconfig.build.json
node_modules/apollo-server-express/src/ApolloServer.ts(20,20): error TS7016: Could not find a declaration file for module 'type-is'. '/Users/fabriziofenoglio/Documents/gg/node_modules/type-is/index.js' implicitly has an 'any' type.
  Try `npm install @types/type-is` if it exists or add a new declaration (.d.ts) file containing `declare module 'type-is';`
    at makeError
```

I can manually solve this by installing `@types/type-is` but, this surely should be included in the `devDependencies` of `apollo-server-express`

apollo-server-express version: ^2.9.16

**Comment by abernix** [comment]
The `apollo-server-express` package is part of a monorepo setup in this GitHub repository, so the `type-is` reference is in the `devDependencies` at the root of the monorepo with all the other `devDependencies`, as seen here:

https://github.com/apollographql/apollo-server/blob/24e342a20564cbdbad35c1de7e9403125ee21de7/package.json#L85

If you checkout this repository and run `npm install` from the root, it should build correctly.  It shouldn't be necessary to run `npm install` in `apollo-server-express` and doing so would fail to build the dependencies on other bits, like `apollo-server-core`, which is in a directory alongside `apollo-server-express`.

To be honest, I'm a bit confused as to how you're encountering this since it appears you're using a `tsconfig.build.json` which _is_ at the root of the monorepo.  Perhaps you can provide some more clarity into what you're trying to do and how you're getting there?

**Comment by itmayziii** [comment]
I am also getting this error on apollo-server-express 2.9.13. I'm getting this error from using apollo-server-express in my code and I'm not quite sure why because my TSConfig is set to `skipLibCheck`. 

full tsconfig.json file
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "strict": true,
    "sourceMap": true,
    "target": "es6",
    "moduleResolution": "node",
    "module": "commonjs",
    "rootDir": "src",
    "lib": [
      "ES2015",
      "ES2016",
      "ES2017.Object"
    ],
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by abernix** [comment]
@itmayziii Thanks for the details.  Can you provide a small runnable reproduction that can be cloned from GitHub which demonstrates this problem when running `npm install` + `npm start`?

**Comment by bwlt** [comment]
Hi, this is a reproduction of the above error: https://github.com/bwlt/apollo-server/tree/repro-3691
I'm having the same issue. The scenario is:
```typescript
// main.ts
import { ApolloServer } from "apollo-server";
import { context } from "./context";
import { typeDefs } from "./schema";
import { resolvers } from "./resolvers";
import { mocks } from "./mocks";

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context,
  mocks: process.env.NODE_ENV === "production" ? undefined : mocks,
});
```

```typescript
// context.ts
import { ExpressContext } from "apollo-server-express/src/ApolloServer";

export interface Context extends ExpressContext {
  ...
}

export const context: ContextFunction<
  ExpressContext,
  Context
> = function context(expressContext) {
  ...
}
```

The problem occurs when I import { ExpressContext } from "apollo-server-express/src/ApolloServer"

**Comment by shellscape** [comment]
@abernix we're over a year now since the reproduction was provided. Still an issue. could we get some eyeballs on this please?

**Comment by glasser** [comment]
Importing from `package/src/somefile` or `package/dist/somefile` is not officially supported.  We do our best to choose what gets exported from the top level of a package and everything inside is an implementation detail. (Some other Apollo projects like Apollo Client explicitly set up deeper exports, but Apollo Server doesn't.)

The symbol in question `ExpressContext` has been exported from `apollo-server-express` since v2.19.2, so you can now just do `import { ExpressContext } from 'apollo-server-express'` and it should just work.  (I looked at the reproduction, upgraded it to v2.19.2 and changed the import line, and it worked. It also works with 3.3.0.)

@shellscape , are you running into this with the same symbol or a different one?
