### ISSUE TITLE
Reduce code duplication in permission verification

### ISSUE THREAD

**Issue by LeonYanghaha** [apollographql/apollo-server#3695]
According to [this document](https://www.apollographql.com/docs/apollo-server/security/authentication/), I have done permission verification, which is successful, but I have a doubt. In every ```resolve function```, I need to write the following codes, and these codes are repeated. I want to find other good solutions to reduce code duplication. Do you have any good idea? Please let me know . thank you.

```javascript
users: (parent, args, context) => {
// every resolve needs an if to judge, which is very troublesome
 if (!context.user) {
      return null
};
// some code 

}

```

**Comment by codecog** [comment]
Reading the next few parts of that section in the documentation should give enough information on how you could structure your server code to not have to do the conditional user check, in every resolver.

https://www.apollographql.com/docs/apollo-server/security/authentication/#authorization-in-data-models

**Comment by glasser** [comment]
I agree with @nonewcode (a more current link is https://www.apollographql.com/docs/apollo-server/security/authentication/#in-data-models)

Additionally, Apollo Server no longer (since ASv3 last year) has much of an opinion on how you put together your schema's  resolver code; it focuses on binding to web frameworks and providing a plugin API for observing and affecting operations. Other projects like `@graphql-tools/schema` and `graphql-middleware` provide tools for avoiding repetition within your resolver code.
