### ISSUE TITLE
Align default `ttl`s for `KeyValueCache`, `RedisCache`, `MemcachedCache`, etc.

### ISSUE THREAD

**Issue by abernix** [apollographql/apollo-server#3731]
Currently, while all cache stores support the notion of a TTL, the distributed
cache stores have a default TTL of `300`, while the `KeyValueCache`, which
uses an `InMemoryLRUCache`, lacks any TTL by default.

There are of course two directions here:

* Removing the default TTLs from the distributed caches.
* Adding a default TTL to the in-memory LRU cache.

The alignment is primarily for the sake of developer sanity, since it's
confusing to have different defaults across the different implementations
without concrete reasoning (of which I'm unable to find any!).

Feedback welcome! But generally speaking, just logging this so we can target
this for a future breaking version change.

**Comment by glasser** [comment]
We no longer maintain KeyValueCache implementations other than an in-memory one and a thin adaptor around your favorite Keyv implementation. The in-memory cache has no default TTL.  I don't believe that common Keyv implementations including `@keyv/redis` and `@keyv/memcache` apply a default TTL either. So that solves your problem.
