### ISSUE TITLE
API key per variant in Apollo

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-server#3734]
Hi. As of now, Apollo Federation provides API Key at a graph level to push or do any operations with the registry.

But, when you have different environments like development, staging, production, etc. you typically want to have them as different variants **with different API keys**. But, as I see now, variant is not being used during API Key generation.

This is kind of critical when you don't want the development key to be used to push to production variant which is currently possible (unless you separate them out as separate graphs)

**Comment by abernix** [comment]
Absolutely agree about the importance of this and you're not alone in your desire for this!  However, this would be feature request for our platform, Apollo Graph Manager so it's best to request this functionality through its support channels.  No changes should be necessary to Apollo Server once this change ships.

I'll close since it's not actionable by the Server team, but I have linked this to our internal product tracking for the feature.  Thanks for opening this, as I'm sure others will find it helpful if they're searching with the same concern.

**Comment by tvvignesh** [comment]
Hi @abernix - Just thought of following up on this. While I understand that this is not related to this repo, may I know if there is any tentative date that this would be available? Thanks.
