### ISSUE TITLE
Feature Request: Send request context to formatError (like formatResponse)

### ISSUE THREAD

**Issue by scottc-netflix** [apollographql/apollo-server#3738]
I need to integrate Apollo Server with my company's internal metrics service, but there is no way to get the request & context information from inside the formatResponse function in newer versions. This means I can't get information like the operationName and timing information that I add to the request object for every request that comes in.

**Comment by jdolle** [comment]
You could use `GraphQLExtension`'s to accomplish this.
Ref: https://github.com/apollographql/apollo-server/blob/master/packages/graphql-extensions/src/index.ts#L31

**Comment by abernix** [comment]
While `formatResponse` does receive the context, that's because it's an Apollo based feature while `formatError` is intended to match the underlying `graphql` library which provides a function by the same name ([see here](https://github.com/graphql/graphql-js/blob/master/src/error/formatError.js)).  Therefore, it doesn't receive the Apollo Server context.

@jdolle is correct that there are other approaches to getting this, however the `graphql-extensions` package — originally an internal package and having never been documented — is slated to be deprecated in favor of the already implemented [Apollo Server plugin API](https://www.apollographql.com/docs/apollo-server/integrations/plugins/) which has been around for some time now (and is documented!).  The shared context should be available on all the methods in that API and I suspect you can accomplish what you're aiming to achieve with it.

Could you take a look at that plugin API and see if it covers your needs?  If it's not, I'm super happy to assist or re-open this issue.

Thanks!
