### ISSUE TITLE
Using an extended class as a resolver throw in server init

### ISSUE THREAD

**Issue by SuliacLEGUILLOU** [apollographql/apollo-server#3776]
Good afternoon !

I am trying to create an class based resolver system with you library so I can have a more generic interface for my types definition

I am working with node 12.14.1 and using the ES6 system, with "apollo-server-express": "^2.9.16"

I work with a `ResolverGql` class, setting itself up to generate the same interface as the documentation recommand, with a subclass that just set the bit of specific code needed (at the moment, it should just have to set its own gqlClassName, that is matching it with its model and schema entry)

In the `addResolveFunctionsToSchema`, the lib throws an error: "Error: "gqlClassName" defined in resolvers, but has invalid value "subClass". A resolver's value must be of type object or function."

when I get to that point with the debugger, I can see that the resolvers variable contains 
```Json
Object {Query: Object, Mutation: Object, Action: Object, Admin: Object, gqlClassName: "subClass", …}
Action:Object {}
Admin:Object {}
capClassName:"SubClass"
data:Object {}
gqlClassName:"subClass"
Mutation:Object {createAction: , createAdmin: , updateAdmin: , …}
Query:Object {actions: , action: , admins: , …}
Upload:GraphQLScalarType {name: "Upload", description: "The `Upload` scalar type represents a file upload.", serialize: , …}
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
```

It looks like it has something to do with the way the resolvers object is generated from the array given to the apolloServer init. The debugger shows me that the array I insert into the apollo server looks fine, with every object providing the correct Query/Mutation interface

Example: https://codesandbox.io/s/vibrant-babbage-mj56u

Thanks you and have a nice day

**Comment by abernix** [comment]
👋 This doesn't appear to be a bug with Apollo Server, but rather a question about how to use it.

These are better asked in the [_Apollo Server_ channel within our Spectrum.chat community](https://spectrum.chat/apollo/apollo-server) or on StackOverflow rather than here on GitHub where our efforts are focused on fixing bugs and adding new features.

We're happy to re-open this if you can demonstrate that it is in-fact a bug!  Also, if you find that the answer to your question wasn't in the documentation, opening a PR here with fixes to our documentation is certainly welcome and the documentation lives within the "/docs" directory in this repository.

I'll close this, but thanks for your understanding!
