### ISSUE TITLE
GraphQL lambda throwing "module.require is not a function" after minor bump

### ISSUE THREAD

**Issue by montamal** [apollographql/apollo-server#3808]
### Description
**Package name:** apollo-server-lambda
**Version:** 2.10.0

Updated apollo-server-lambda using yarn (version was specified with a caret "^") and my nodejs12.x lambda stopped working.
There seems to be a breaking change from the **previous working version**: 2.4.0.

CloudWatch gives me the following:
```
{
    "errorType": "TypeError",
    "errorMessage": "module.require is not a function",
    "stack": [
        "TypeError: module.require is not a function",
        {...}
     ]
}
``` 

Leading me to find this line in [createSHA.ts](https://github.com/apollographql/apollo-server/blob/8b02c0c440928d6b1d4e8c6d79a9d27f2a528666/packages/apollo-server-core/src/utils/createSHA.ts#L7) that seems to be the culprit: 
```javascript
return module.require('crypto').createHash(kind);
```

This piece of code somehow ends up in my bundle after the update while previously located in `apollo-env/lib/utils/createHash.ts` and never bundled.

Also using [serverless-plugin-optimize](https://www.npmjs.com/package/serverless-plugin-optimize) and the latest versions of @babel/polyfill + @babel/preset-env.

### Expected behavior
No breaking changes in between minors.

### Actual behavior
Breaks previously working lambdas.

**No repro**

**Comment by abernix** [comment]
Thanks for reporting this and providing a clear explanation and estimation of the problem.

While that piece of code is certainly triggering the error, that line cannot the culprit since `module.require` should certainly exist in a Node.js runtime — as AWS Lambda claims to be!

If `module.require` — a method which has been core to Node.js [since way back in Node.js v0.5.1](https://nodejs.org/api/modules.html#modules_module_require_id) — is missing, then that would point to intentional omissions in the runtime itself (surely possible, as this is custom Amazon runtime, but unlikely because of what it would break) or, alternatively and more plausibly, that `module` is being redefined by a bundler plugin which emits the entirety of the source code inside a closure.  That's certainly not unlike what [Node.js does itself](https://nodejs.org/api/modules.html#modules_the_module_wrapper), but it's usually done to provide module-like behavior where the notion of modules don't exist — typically in browsers or plain V8 environments (like Cloudflare Workers) where `require` doesn't exist and bundling is mandatory.  In those cases though, we wouldn't be meeting the expectations of [`isNodeLike`](https://github.com/apollographql/apollo-server/blob/9420aa049471f0c5e8df62a0924fd94678508a2a/packages/apollo-server-core/src/utils/isNodeLike.ts#L1-L12) and `module.require` wouldn't be getting invoked.

Without a reproduction that shows the resulting bundle, it's hard to figure out precisely, but this quick test in the AWS Lambda console without a bundler confirms that `module.require` certainly exists in AWS Lambda v12.x:

![image](https://user-images.githubusercontent.com/841294/74938736-40f44800-53f7-11ea-814d-0a842d9f8165.png)

Therefore, if `module.require` is getting destroyed, it must be in the bundling, which isn't something that Amazon or Apollo controls.  I'd suggest digging into that logic, because merely using `module.require` doesn't by itself necessitate a breaking change when the expectation that it exist has been consistent throughout the life-time of Apollo Server.

**Comment by montamal** [comment]
@abernix Many thanks for your thorough response, it must be playing badly with "serverless-plugin-optimize", I'll make sure to look into it and report it to their author.

**Comment by vijaych1209** [comment]
Hi,
I am stuck at this exact issue, just wanted to see if there is a solution found for this.
Here are the list of plugins I am currently using.

```
- serverless-plugin-typescript
- serverless-tscpaths
- serverless-plugin-optimize
- serverless-offline
- serverless-domain-manager
```
I am thinking there is a usage of serverless-webpack here but currently researching on it.
minify is set to true

**Comment by insaindesign** [comment]
This may be due to the bundling that is happening with webpack, I'm having the same issues with Parcel.

Each module is being wrapped with a `function(require, module, exports) { ... }`, of which `module` doesn't have a require. Is it possible to just test for `nodeLike && "require" in module`?
