### ISSUE TITLE
Serializing response with JSON.stringify blocks event loop under load

### ISSUE THREAD

**Issue by msoule-cb** [apollographql/apollo-server#3815]
Under load prettyJSONStringify uses a non-trivial amount of eventLoop time. It becomes a problem under load, even with modestly sized JSON bodies. It's not the most significant source of eventLoop blocking but it is a low hanging fruit.

Streaming is a possible solution: https://nodejs.org/uk/docs/guides/dont-block-the-event-loop/#blocking-the-event-loop-json-dos

Reproduction steps with Node Clinic:

- Clone https://github.com/msoule-cb/apollo-server-perf-test
- `npm install -g clinic`
- `clinic flame --collect-only -- node index.js`
- Run load testing using autocannon, ab, or any other tool of choice. I provided a JMeter test config.
- Stop graph server.
- `clinic flame --visualize-only .clinic/<pid>.clinic-flame` (<pid> printed when stopped graph server)
- View the `.clinic/<pid>.clinic-flame.html` file and note that prettyJSONStringify appears as a hot spot.

source: https://clinicjs.org/documentation/flame/03-first-analysis/

Alternatively with Chrome dev tools:

- Clone https://github.com/msoule-cb/apollo-server-perf-test
- Start graph server with `--inspect` like `node --inspect index.js`.
- Nagivate to `chrome://inspect`. The server should appear as an available target.
- Start recording.
- Run load testing using autocannon, ab, or any other tool of choice. I provided a JMeter test config.
- Stop recording.
- Note that prettyJSONStringify is a relatively heavy function.

source: https://nodejs.org/de/docs/guides/debugging-getting-started/

**Comment by theGlenn** [comment]
+1 Substitute `prettyJSONStringify` by a schema-backed serialization like [fast-json-stringify](https://github.com/fastify/fast-json-stringify) would quite fitting given graphql's schema-first philosophy.

**Comment by wanton7** [comment]
Would it make sense to make JSON (de)serializer pluggable in a way that you could yield back to event loop? So you could use something like https://github.com/ibmruntimes/yieldable-json (not sure if this is production ready) or alternatives.

**Comment by gregbarcza** [comment]
In some cases, our event loop gets blocked for up to 30 sec - which is insane. Is there any fix/workaround for this one? I'm really interested in how production-ready graphql apps dealing with this issue.

**Comment by glasser** [comment]
Sure, it might make sense to allow the stringifier to be a pluggable async function.

In what context is your event loop blocked for 30 seconds? By any chance, is this a context where you have [inline tracing](https://www.apollographql.com/docs/apollo-server/api/plugin/inline-trace/) enabled (eg, a federated subgraph)?

**Comment by glasser** [comment]
I think this is still worth considering if this continues to cause issues for people. That said, I suspect this tends to be more of a problem with inline tracing than with other responses, and we've made it easier to disable inline tracing or only apply it to some requests (see the fieldLevelInstrumentation option).

Streaming the response is nice, but it does mean that the response can't have a content-length header (unless you still buffer the response as strings in memory before sending them). And it's not like execution itself is streamable — the response still needs to be kept in memory all at once.

It's also possible that the experimental `@defer` and `@stream` GraphQL features may help in this case.

I'm going to close this because it doesn't seem to have hurt too many people recently, but happy to reconsider.

**Comment by AndrejGajdos** [comment]
+1
