### ISSUE TITLE
Multiple Operations within a Single Document Batching

### ISSUE THREAD

**Issue by JoeTravisKiva** [apollographql/apollo-server#3851]
@apollo/gateway - 0.11.7

I don't know that this is really a bug, so it may be more of a feature request. We have noticed that when sending a single document with multiple operations to the federation gateway, it is splitting those operations into individual documents for processing by the downstream services. In our case, the same downstream service is responsible for handling all of the operations within the original document, so we're increasing the concurrent load on the downstream service by 5-10x.

Would it be possible for the query execution plan to take into consideration operations that are processed by the same service and batch them together (provided they are at the appropriate level)?

**Comment by abernix** [comment]
It'd be great to share your motivation and use-case for using batching in the first place to understand this better.  I can imagine there are other interesting ways of solving that, perhaps. 


Overall, the use of batching incurs overhead in many places (parsing, validation, and execution, just to name a few), which is why including as much as po
ssible in a single operation is best.  That overhead would extend to query planning since merging operations (taking into account duplicated fields, aliases, etc.) would be additional overhead in the near-term until we optimize that out (whereas today if batching is particularly important you could just horizontally scale the subgraphs). 

I'm going to close this since this feature request hasn't received any other support since it was opened, and it's unlikely that we would change the query planner to introduce such complexity anytime in the foreseeable future.

Happy to hear more about other use-cases like this in the future (please include more details about your use for batching, too!).  And thanks for opening this inquisition in the first place.  Thanks!
