### ISSUE TITLE
Support for federation query param hook

### ISSUE THREAD

**Issue by nitin302** [apollographql/apollo-server#3853]
https://github.com/apollographql/apollo-server/pull/2892 provides support to add custom headers during schema fetch and buildService helps add custom headers for any graphql queries. How do we pass through query params we get from input graphql gateway endpoint and pass through to the implementing services?

**Comment by abernix** [comment]
Anything preventing you from doing it same way as headers but replacing `headers` with `url` (and treating it as the `String` it is rather than `Headers` map/implementation)?

The documentation here should help: https://www.apollographql.com/docs/apollo-server/api/apollo-gateway/#remotegraphqldatasource

**Comment by nitin302** [comment]
yes this works. @abernix thank you.
