### ISSUE TITLE
[Federation] Preserve extensions field in the gateway

### ISSUE THREAD

**Issue by a-ursino** [apollographql/apollo-server#3893]
Hi

To try to bypass the limitation around the Headers class from `node-fetch` and multiple `set-cookie` headers and how AWS Lambda accommodate this requirement with the `multiValueHeaders` field as described here https://github.com/apollographql/apollo-server/issues/3040#issuecomment-590501477,
I was thinking to return from the micrograph the cookie headers in a custom `extensions` field and map them into the `multiValueHeaders` in the apollo-gateway with a `willSendResponse` plugin. 

Using the demo https://github.com/apollographql/federation-demo and adding a simple plugin to the account service that returns a fake field into the extensions I'm able to see the extensions field when I query the customer endpoint directly at http://localhost:4001. However, using the same query with the federated gateway endpoint http://localhost:4000 the `extensions` field is undefined. I've tried to enable tracing in the gateway just to see the behaviour and the response was an empty object. 

Is this the intended behaviour? Do I need to enable any feature flag in the gateway?

**The expected behavior**
See the `extensions` field in the gateway response

**The actual behavior**
No `extensions` field is present in the gateway response

**A **simple**, runnable reproduction**

[federation-demo.zip](https://github.com/apollographql/apollo-server/files/4338125/federation-demo.zip)

**Comment by rherber** [comment]
I have noticed this issue as well. The federated sub-graph adds warnings to the extension response and I confirmed that gateway gets the extension object in buildService.didReceiveResponse. However, the extensions from federated graphs are lost somewhere before gateway's formatResponse.

Any idea on how to have gateway preserve all extensions from sub-graphs?

**Comment by jhampton** [comment]
@rherber You've identified the correct place to capture the downstream headers (`buildService.didReceiveResponse`), and I would recommend storing those in context and formatting the response as you see fit.  An example of this pattern is located here: https://github.com/apollographql/apollo-server/blob/570f548b88750a06fbf5f67a4abe78fb0f870ccd/docs/source/federation/gateway.mdx#customizing-responses

While I agree that this might not feel like a "batteries included" implementation, I believe gateway owners should have the option to implement custom logic to surface these kinds of data based on concrete use cases rather than needing to _override_ Apollo's chosen/default behaviors as often as possible.

I'm going to close this issue for now, but please re-open or submit a PR if you think there's a more complete and flexible pattern or implementation.

Thank you!
