### ISSUE TITLE
Use ``` to comment before extend type will get  "Unexpected BlockString"

### ISSUE THREAD

**Issue by VictoriaChou** [apollographql/apollo-server#3915]
Here is my example:
```
"""
The query root of XXX GraphQL interface.
"""
extend type Query {
    """
    Gets info about apple
    """
    Apple {
    }
}
```
And the first comment is not allowed and return  Unexpected BlockString 
If i remove ```extend``` or if i use ```#``` instead of ```"""``` it will be all right
The second comment is ok.

**Comment by mainpart** [comment]
can confirm that :)

**Comment by glasser** [comment]
This is spec-compliant. You can see in the spec that [`Description` is part of `ObjectTypeDefinition`](http://spec.graphql.org/draft/#sec-Objects) but [not part of `ObjectTypeExtension`](http://spec.graphql.org/draft/#sec-Object-Extensions).

I think this makes some sense, because if you provide a description both on the type definition and on a type extension (or on multiple type extensions) then it would need to know how to combine the descriptions. One could imagine it being legal as one as there is only one anywhere, but that's not the choice that was made.

More discussion on the spec itself at https://github.com/graphql/graphql-spec/issues/900
