### ISSUE TITLE
Unnecessary dependencies graphql-tools and @types/aws-lambda in apollo-server-lambda

### ISSUE THREAD

**Issue by idevelop** [apollographql/apollo-server#4020]
Hey folks, while auditing the size of simple AWS lambda function bundle zip that uses `apollo-server-lambda`, I came across these included packages that I'm hoping someone can review, as I don't think they should be marked as dependencies:

- `@types/aws-lambda` - I think this should be a dev dependency
- `graphql-tools` - this seems to be [imported only to be re-exported](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-lambda/src/index.ts#L21), but not actually used by `apollo-server-lambda` itself. I think this shouldn't be the case, and it should be up to the developers to decide if they need this library and install it explicitly if that's the case

Thanks!

**Comment by idevelop** [comment]
Similarly, `apollo-server-core` depends on `@types/graphql-upload` and `@types/ws` which bring in a whole bunch of other downstream type definition packages, all of which end up in the final serverless package bundle. By explicitly excluding `node_modules/@types` in serverless.yml, I was able to cut 1 MB from the lambda bundle zip file.

**Comment by abernix** [comment]
Thanks for the PR contribution attempts, but it's best to discuss these in issues prior to opening PRs.

In particular, this type of change isn't something that we're looking or able to accept PRs for right now.  To the extent that I'm aware, and at the mercy of _many_ failures to include the correct typings as `dependencies` (vs `devDependencies`) in the past TypeScript declarations (including specifically, the addition of `@types/aws-lambda` into `dependencies` in https://github.com/apollographql/apollo-server/issues/2351) are very much necessary to be shipped with Apollo Server packages at this time.

If this pattern changes in the future or you can prove they're not necessary, I'd be happy to reconsider, but the ones I've spot-checked are necessary!

**Comment by idevelop** [comment]
Thanks for your time reviewing this @abernix, I'll admit I'm still wrapping my head around the Typescript ecosystem myself. I'll go through your explanation on my PR and try to understand if this is a failure of the npm ecosystem or it's just me being dumb about how things are supposed to work.

**Comment by abernix** [comment]
Yeah, hope my review helps!  I know it is actually a bit surprising at first, but I'm pretty confident in my understanding of it at this point and the costs that you're pointing out (e.g. bytes in bundles).

The most precise way I've been able to frame it is: If it's _in the emitted `.d.ts` declaration files_ (you can browse [see them here, for example](https://www.jsdelivr.com/package/npm/apollo-server-express?path=dist)), then the `@types/` need to be in `dependencies` so that consuming applications `tsc` invocation will be able to find them.  That's made true than ever because of the fact that `npm install` doesn't install every `devDependencies` all the way down your dependency tree, only the `devDependencies` for the package you're running `npm install` in.
