### ISSUE TITLE
Uncaught ReferenceError: GraphQLPlayground is not defined. Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by khanhbui96** [apollographql/apollo-server#4027]
Following the getting started guide (https://www.apollographql.com/docs/apollo-server/getting-started) gets me to this error, when opening the server in the browser: 
![Screen Shot 2020-04-23 at 6 42 06 PM](https://user-images.githubusercontent.com/47818986/80096154-50c50f80-8593-11ea-8f76-abb71feec403.png)

I've tried several clean installs of the project, but I'm just getting a blank dark background page, when calling the server each time.

I hope you can help me, thanks.

**Comment by abernix** [comment]
It seems you're being blocked from accessing the static assets which are required to serve the Playground page or are otherwise unable to access them.  A firewall, perhaps? 
 They are served from that `cdn.jsdelivr.net` address which is linked on the right of the first error message about the `ERR_CONNECTION_REFUSED` error.

If you don't have network access to that asset, you'll probably want to consider using a separate interface — perhaps a client that you can install locally, [like Insomnia](https://insomnia.rest/) or [Postman](https://www.postman.com/).
