### ISSUE TITLE
Plugins Typescript Compatibility

### ISSUE THREAD

**Issue by no1melman** [apollographql/apollo-server#4032]
**Package**: apollo-server-plugin-base

The typings have 

```typescript
didResolveOperation?(
    requestContext: WithRequired<
      GraphQLRequestContext<TContext>,
      'metrics' | 'source' | 'document' | 'operationName' | 'operation'
    >,
  ): ValueOrPromise<void>;
```

Using the http property from the GraphQLRequestContext, it has this type

```
export interface GraphQLRequest {
  query?: string;
  operationName?: string;
  variables?: VariableValues;
  extensions?: Record<string, any>;
  http?: Pick<Request, 'url' | 'method' | 'headers'>;
}
```

It says there, that `query` is a string, but whenever I console log its value, it is always the GraphQL AST. It has:

```
"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"
```

I know that is technically a string - but that really doesn't tell me much!

Secondly, the `didResolveOperation` returns `ValueOrPromise<T> = T | Promise<T>;`, but the docs only mention returning a function, `(err) => {}`, so here the typing feelslike it is wrong again.

**Comment by abernix** [comment]
In the future, generally speaking, even outside this repository, it's usually a best-practice to open separate issues for separate concerns and use a non-general title for each.

For your _first_ concern:

> ```
> "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"
> ```

This is not a GraphQL AST, this is string of the document.  What do you want to know about it?

> Secondly, the `didResolveOperation` returns `ValueOrPromise<T> = T | Promise<T>;`, but the docs only mention returning a function, `(err) => {}`, so here the typing feelslike it is wrong again.

The [documentation here](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#didresolveoperation) does not mention returning a function like you're suggesting.  What are you referring to?

Happy to reply further to this issue, but closing as both of these seem normal.

**Comment by no1melman** [comment]
It does here: https://www.apollographql.com/docs/apollo-server/integrations/plugins/#end-hooks

I would have expected the query to show something like:

```
getProduct(id: "23") {
   name
   price
}
```
That "document" that is outputted, as you can agree, doesn't give me any information...

I was also expecting the operationName to give the `getProduct` in this instance as well.

I agree two issues, but the broader issue, is I believe this plugins part just isn't finished, it feels inadequate - there are expectations from reading the types, but the output doesn't quite meet that.

**Comment by no1melman** [comment]
I think what I'm seeing is actually the Apollo Playground introspection stuff muddying the water.. so we can ignore that document, because I'm getting the write document through - although not getting the operationName at all.

So I think this issue can either be closed - and I will reopen for the type issues or we change this one to the type issues one

**Comment by abernix** [comment]
> That "document" that is outputted, as you can agree, doesn't give me any information...

I don't agree, as that is all the information that I'd expect to gain from the query and you haven't suggested more precisely what it is you're looking for.  That is the entirety of the `query`.  If you're looking for the AST, it is available on the `document` property.  The `query` in this case gives you exactly what was sent into it, in `string` form, as the type suggests.

> It does here: [apollographql.com/docs/apollo-server/integrations/plugins/#end-hooks](https://www.apollographql.com/docs/apollo-server/integrations/plugins/#end-hooks)

It doesn't.  The documentation says (emphasis mine):

> Event handlers for **the following events** can optionally return a function that is invoked after the corresponding lifecycle phase ends:
>
> * `parsingDidStart`
> * `validationDidStart`
> * `executionDidStart`

None of those three life-cycle hooks are the `didResolveOperation` that you're talking about, so none of them would return a function and the typings are correct.  Unlike third-party types (e.g. those from DefinitelyTyped; `@types/*`), all of Apollo Server is written in TypeScript and we package the types with it so there none of the idiosyncrasies that are associated with external types.

Furthermore, as the source-of-truth types show, the `didResolveOperation` method does _not_ return the function, and the documentation reflects that, so I'm not sure what could be disputed here.

> I believe this plugins part just isn't finished, it feels inadequate - there are expectations from reading the types, but the output doesn't quite meet that.

Thus far the `query` is returning a `string`, as the types _define is expected_, and as your demonstration has proven with its stringified output of the query you sent in (yes, the `IntrospectionQuery` is still a query, transmitted in a string form from GraphQL Playground.  You can disable that in GraphQL Playground's preferences if it's making the experience less enjoyable for you, or leading to the confusion, but keep in mind that `IntrospectionQuery` is a _still_ a string, [even in `graphql-js`'s source code](https://github.com/graphql/graphql-js/blob/278bde0a5cd71008452b555065f19dcd1160270a/src/utilities/getIntrospectionQuery.js#L35-L129)).

> I would have expected the query to show something like:

The `query` would be what you sent in from GraphQL Playground on the left-hand side.

> ```
> getProduct(id: "23") {
>    name
>    price
> }
> ```
> 
> I was also expecting the operationName to give the `getProduct` in this instance as well.

`getProduct` is _not_ the `operationName`, it's the name of the field.  An `operationName` is the `MyOperationName` in the following query:

```graphql
query MyOperationName {
  getProduct(id: "23") {
    name
    price
  }
}
```

Please don't open any new issues unless they concretely demonstrate a bug in the implementation or a misalignment in the documentation.  The source code and documentation should inform what those expectations are.

Lastly, before you call anything here inadequate, consider explaining precisely what it is you are trying to achieve in the first place since it will help with mutual understanding of a solution.
