### ISSUE TITLE
getDirectiveDeclaration not sufficient to declare directives

### ISSUE THREAD

**Issue by mfellner** [apollographql/apollo-server#4074]
According to https://www.apollographql.com/docs/graphql-tools/schema-directives/#declaring-schema-directives when implementing the `getDirectiveDeclaration` on a custom `SchemaDirectiveVisitor`, it is not necessary to declare the directive in the SDL.

However this is no longer the case with graphql-tools >= 4.0.0 and graphql-js >= 14.0.0. Related issues are
* https://github.com/ardatan/graphql-tools/issues/957
* https://github.com/ardatan/graphql-tools/issues/1022

Support for the documented solution is only considered for the next release of graphql-tools (https://github.com/ardatan/graphql-tools/issues/1337).

The docs should be updated to reflect that.

**Comment by yaacovCR** [comment]
We are moving away from considering support for the documented solution, as the problem is with graphql-js v14 and the spec, not the tooling, and the available workarounds seem sufficient.

See https://github.com/ardatan/graphql-tools/issues/1022#issuecomment-628113031

The independent docs at graphql-tools should eventually be updated to reflect that.

**Comment by glasser** [comment]
Right now we are planning to remove support for `schemaDirectives` in Apollo Server 3, because the project that implements it (graphql-tools) considers it to be a legacy API. Folks who want to use `schemaDirectives` or its non-legacy replacement `schemaTransforms` can use `@graphql-tools/schema` directly to create a schema passed in with `new ApolloServer({schema})`;  issues relating to these options should probably be opened in the graphql-tools repo.
