### ISSUE TITLE
apollo-tracing 0.10 -> 0.11 have a breaking change

### ISSUE THREAD

**Issue by kamilchm** [apollographql/apollo-server#4177]
Upgrade from a version `0.10.0` to `0.11.0` will result in compilation error and a general incompatibility of dependent code (extension -> plugin):
```
error TS2305: Module '"../../../../node_modules/apollo-tracing/dist"' has no exported member 'TracingExtension'.
```
According to semver this should be a major version upgrade to `1.0.0`.

**Comment by abernix** [comment]
The semantic versioning specification states quite clearly:

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. ([Ref](https://semver.org/#spec-item-4))

And...

> 5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes. ([Ref](https://semver.org/#spec-item-5))

Pre-1.0, the second digit (`11` in this case) acts as the major in terms of ranges, which is why we bumped it.  With caret versioning, `^0.10.0` would not have automatically updated to `^0.11.0`, so this shouldn't have been automatically brought in as a transitive dependency to anything.  You can play with this with the [semver calculator](https://semver.npmjs.com/).

If you're using it directly, you'll need to change the API and expecting breaking changes is something to be considered when updating `0.x.x` packages.

In all other cases, if this is something affecting Apollo Server, please provide a reproduction.  Thanks!
