### ISSUE TITLE
Azure Functions local debug cors header.

### ISSUE THREAD

**Issue by johnnliu** [apollographql/apollo-server#4178]
When running ApolloServer for AzureFunctions in local debug, the CORS header for Access-Control-Request-Headers is lowercase, and the current ApolloServer implementation needs a tiny tweak.

https://github.com/apollographql/apollo-server/blob/4fb348102e1248f78f6df5c70090147c5ceb7300/packages/apollo-server-azure-functions/src/ApolloServer.ts#L108

The "access control request headers' -header is lower case.  Similar to how origin is handled.

```corsHeaders['Access-Control-Allow-Headers'] = req.headers['Access-Control-Request-Headers'] || req.headers['access-control-request-headers']```

**Comment by glasser** [comment]
Hmm. Looking for two specific casings seems wrong to me; HTTP headers are case insensitive. Either we should find a method that lets us be case-insensitive, or we should find Azure docs that say that you should always look up by the lowercase version (and we should just do that rather than the `||` you suggest).

I [asked a question on a related upstream issue](https://github.com/Azure/azure-functions-nodejs-worker/issues/274#issuecomment-812092354).

**Comment by glasser** [comment]
OK, instead of waiting for Azure people to tell me how it's supposed to work, I just converted all header names to lowercase in #5401.
