### ISSUE TITLE
Fix for Node 14 Uploads

### ISSUE THREAD

**Issue by zsolt-dev** [apollographql/apollo-server#4190]
After upgrading to Node 14 (from 13), apollo-server-express uploads stopped working.

Here is the fix, so you will not have to spend hours trying to fix it:

package.json before (in node 13)
```
  "resolutions": {
    "fs-capacitor": "5.0.0"
  },
```

package.json that works with node 14:
```
  "resolutions": {
    "fs-capacitor": "6.2.0"
  },
```

If you are upgrading from node 8, also add this to your package json, so the resolutions will be used:
```
  "scripts": {
    "preinstall": "npx npm-force-resolutions",
    ....
```

**Comment by strigona-worksight** [comment]
We're using yarn and this worked for us as well.

Just a quick note, that if you're using yarn workspaces, the `resolutions` needs to be in the root `package.json` not the graphql package itself.

**Comment by abenhamdine** [comment]
Great solution thx for a regular install.
Unfortunately, npx doesnt' seem to work in github action and npm install --only=dev, which breaks our CI.
If someone has a solution...

**Comment by glasser** [comment]
We've made changes in v2.21 that changes how we load the graphql-upload functionality and what versions are supported, so I'm going to close this unless somebody can show a reproduction of a current problem with this.

Note that the graphql-upload integration is being removed in Apollo Server 3; folks who want to keep using it can just use that package directly rather than deal with the old version that we are pinned to for back-compat reasons.
