### ISSUE TITLE
Cors option not enabled by default inside apollo-server-koa 

### ISSUE THREAD

**Issue by rahul22048** [apollographql/apollo-server#4193]
cors is not enabled by default when using apollo server koa middleware, but the same is enabled by default in apollo-server-express. Cors headers like access-control-allow-origin are missing when using apollo-server-koa

**Comment by glasser** [comment]
Are you sure of this? It certainly [looks like the default is to have cors middleware](https://github.com/apollographql/apollo-server/blob/1bb051f63d67617488a18061971c9a83027b65f5/packages/apollo-server-koa/src/ApolloServer.ts#L145-L147) (since before this issue was filed) and in fact we have #4859 filed which lodges the opposite concern.
