### ISSUE TITLE
Unable to create nested type in GraphQl

### ISSUE THREAD

**Issue by techyaura** [apollographql/apollo-server#4211]
In the database, I am keeping the Parent Child relationship following one of the pattern by simply using  **_parent_** field that refers  to the primary Id of the same table/collection.

Eg -

```
{
    "_id" : ObjectId("5eda4a37ba3b704016627597"),
    "isCompleted" : false,
    "scheduledAt" : ISODate("2020-06-05T00:00:00.000Z"),
    "isDeleted" : false,
    "title" : "Aeisdodfodf fdc",
    "createdAt" : ISODate("2020-06-05T13:35:51.058Z"),
    "updatedAt" : ISODate("2020-06-05T13:35:51.058Z"),
    "parent" : ObjectId("5eda491dba3b704016627596")
}

{
    "_id" : ObjectId("5eda491dba3b704016627596"),
    "isCompleted" : false,
    "scheduledAt" : ISODate("2020-06-05T00:00:00.000Z"),
    "isDeleted" : false,
    "title" : "Your Todos",
    "createdAt" : ISODate("2020-06-05T13:31:09.401Z"),
    "updatedAt" : ISODate("2020-06-05T13:31:09.401Z"),
    "parent" : null
}

```

Now I m using simple **GQL** Todo Type that contains a key `subTasks` thats again can array of the same type. But it' not working.
```
type TodoType {
  title: String!
  isCompleted: Boolean
  createdAt: Date!
  updatedAt: Date
  scheduledAt: Date
  subTasks: [TodoType]
}
```

So what's wrong in the above type, Isn't it should work fine?

**Comment by abernix** [comment]
👋 I'll close this since this doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!

**Comment by techyaura** [comment]
Thanks @abernix  for the update. But Isn't 'it should be handled by Apollo.
If we just take an example for Typescript, it basically a valid way if define a interface like I mentioned above.
So as in GraphQl, as we are using types , So isn't if it supported the nested type like I mentioned above. It will be more refinement way.
