### ISSUE TITLE
cache hints are not working as described in the docs

### ISSUE THREAD

**Issue by dnmahendra** [apollographql/apollo-server#4235]
❗️ Want to report a potential bug
This snippet is pulled from apollo server docs regarding cache hints,

>  Hints on a type apply to all fields that return objects of that type (possibly wrapped in lists and non-null specifiers). For example, the hint @cacheControl(maxAge: 240) on Post applies to the field Comment.post, and the hint @cacheControl(maxAge:1000) on Comment applies to the field Post.comments. 

I have similar typeDefs on which I am trying to use cache hints,

```
type SavingsAccount @cacheControl(maxAge: 10) {
   name: String,
   ratings: [Rating]
}

 type Rating @cacheControl(maxAge: 100) {
    averageMonthlyCost: Float
    costRating: Float
    flexRating: Float
    flexScore: Float
    overallRating: Float
  }
```

The cache-control for SavingsAccount.ratings return 10 instead of 100 as described in the docs.

apollo-server-express: `2.14.3`
apollo-server-plugin-response-cache: `0.5.2`

**Comment by klaaz0r** [comment]
Doesn't the maxAge come from the lowest given field? So this works as intended?

**Comment by glasser** [comment]
The way cache control works is subtle, so it's important to provide a complete self-contained reproduction (an entire server that can run rather than just a snippet, an exact operation to execute, etc). There isn't enough information here to help diagnose what's going on (especially with such a delay — sorry!).
