### ISSUE TITLE
@apollographql/graphql-playground-html@1.6.25 broken jsdelivr path

### ISSUE THREAD

**Issue by owenallenaz** [apollographql/apollo-server#4238]
Ran into this issue running `apollo-server@2.4.0` which I know is an older version, but it utilizes recently published `@apollographql/graphql-playground-html@1.6.25`. That version is not linking correctly to jsdelivr.

If we examine the previous version at https://unpkg.com/browse/@apollographql/graphql-playground-html@1.6.24/dist/render-playground-page.js it contains the line

```
"/graphql-playground-react" + (version ? "@" + version : '') + "/build/static/css/index.css\"
```

Which results in /graphql-playground-react@x.x.x/build/static/css/index.css or in the browser https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.10/build/static/css/index.css

While in 1.6.25 it has the following line

```
"/" + packageName + "/" + (version ? "@" + version + "/" : '')
```

Which results in https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react/@1.7.10/build/static/css/index.css .

The key difference is it needs to be graphql-playground-react@ and not graphql-playground-react/ .

**Comment by abernix** [comment]
Ah, thanks for reporting this! Newer versions specify exact versions of `@apollographql/graphql-playground-html` but older versions did use the caret operator, so that explains why you experienced this before we actually released a version of Apollo Server with the fix!

I just published `@apollographql/graphql-playground-html@1.6.26` with https://github.com/apollographql/graphql-playground/commit/5e5a9d7023ee318d0a8db4a17d889c7a0d7f797f, which should — I hope — fix this for you!  Please report back if that's not the case, and thanks again for reporting.
