### ISSUE TITLE
[Hapi] Allowed methods configuration (GET/POST)

### ISSUE THREAD

**Issue by TdyP** [apollographql/apollo-server#430]
On the Hapi version of graphql server, allowed methods are [hardcoded](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-hapi/src/hapiApollo.ts#L59).

I'm currently trying to implement upload with [apollo-upload-server](https://github.com/jaydenseric/apollo-upload-server) on Hapi and need to allow only `POST` requests (more details about that on this [issue](https://github.com/jaydenseric/apollo-upload-server/issues/5)).

Is there any particular reason for hardcoding this?
I'm willing to help and submit a PR for that, but I'm not sure to get all the consequences if one disable `GET` or `POST`

**Comment by helfer** [comment]
Hi @TdyP, I don't know hapi very well, but is it possible to put a middleware in front of the graphql endpoint that would reject GET requests?

**Comment by TdyP** [comment]
@helfer 
Unfortunately no. Hapi just crashes if I add some POST-related configuration (like payload) on a route where GET is allowed. The error comes up when server is started, before any request may come in.

**Comment by abernix** [comment]
Thanks for opening this issue originally.  It hasn't received a lot of feedback or traction since it was first opened, and we've changed the `apollo-server-hapi` implementation substantially since that time, including a major bump to support Apollo Server 2.x.

If this is still a problem, feel free to ping me back and I (or someone) will be happy to re-open it.  Thanks again!
