### ISSUE TITLE
Subscription do not trigger hooks set in plugins

### ISSUE THREAD

**Issue by Sytten** [apollographql/apollo-server#4354]
When using subscriptions, the server does not currently trigger the hooks of the installed plugins. This means that if I user decided to handle errors in `didEncounterErrors` for example, it will completely bypass it and the user might never be alerted of errors in production (It does however call `formatError`).

**Comment by Nedomas** [comment]
I understand this is in part because `subscriptions-transport-ws` is not part of the `apollo-server` (as queries/mutations are). Is there any thoughts on merging subscriptions into `apollo-server` or having a way to handle errors? (there's not enough data to log errors in `formatError`, only error message without context)

**Comment by Sytten** [comment]
Yes the query validation does (during subscription setup), but not when doing the actual execution.

**Comment by glasser** [comment]
Yes, Apollo Server's support of subscriptions is not very deep; it mostly just glues an instance of `subscriptions-transport-ws` onto the side.  It is not integrated into the request pipeline or plugins, nor does it integrate with the gateway or usage reporting, etc.

Our current plan for Apollo Server 3 is to remove the current superficial subscription integration (and document how to use `subscriptions-transport-ws` to achieve the same limited support).  I do hope that after AS3, we are able to put a real effort into bringing coherent subscriptions support to the entire Apollo platform.

Because we don't intend to improve the current subscription integration, I'm going to close this issue.  I am sure that a future platform-wide subscription project would include integrating subscription support into the plugin API.

**Comment by spencerwilson** [comment]
Thanks for the confirmation, @glasser ! Not sure where else to put the following comment; sorry for keeping a closed issue going 😬 

> (and document how to use subscriptions-transport-ws to achieve the same limited support)

This sounds good, just have one request: Do this, but with `graphql-ws`. Since https://github.com/apollographql/subscriptions-transport-ws/commit/76d9777f45823673cd57918df258cfc35aa81480, it seems the maintainers of `subscriptions-transport-ws` are recommending the newer thing. No idea how compatible the new thing's interface is with the old thing. Hopefully this doesn't complicate things too much.

**Comment by glasser** [comment]
Good call. Gonna track that suggestion in https://github.com/apollographql/apollo-server/issues/4960

**Comment by RMHonor** [comment]
> Yes, Apollo Server's support of subscriptions is not very deep; it mostly just glues an instance of `subscriptions-transport-ws` onto the side. It is not integrated into the request pipeline or plugins, nor does it integrate with the gateway or usage reporting, etc.
> 
> Our current plan for Apollo Server 3 is to remove the current superficial subscription integration (and document how to use `subscriptions-transport-ws` to achieve the same limited support). I do hope that after AS3, we are able to put a real effort into bringing coherent subscriptions support to the entire Apollo platform.
> 
> Because we don't intend to improve the current subscription integration, I'm going to close this issue. I am sure that a future platform-wide subscription project would include integrating subscription support into the plugin API.

Is this something worth capturing in the docs for plugins?

**Comment by glasser** [comment]
These days I feel like the docs are pretty clear that subscriptions are a third-party package bolted on to the side which don't interact with the plugin system at all. We're about to rewrite the subscriptions doc to recommend a newer third-party package and I can try to make sure that it's even more explicit about this.
