### ISSUE TITLE
Add support for other probes

### ISSUE THREAD

**Issue by kevin-lindsay-1** [apollographql/apollo-server#4357]
The default health check endpoint is fine, but it would be nice to have an extra endpoint or two by default for things such as [readiness](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), with a similar API for overriding them.

**Comment by glasser** [comment]
You can add this using your favorite web framework just like you would with any other web server. In fact, because Apollo Server's job is to execute GraphQL operations, we removed the health check feature entirely in Apollo Server 4. https://www.apollographql.com/docs/apollo-server/migration/#health-checks
