### ISSUE TITLE
Pretty-print response

### ISSUE THREAD

**Issue by amatiushkin** [apollographql/apollo-server#4359]
It would be nice to provide a configuration option to generate JSON response in human-readable format.

As far as I can understand the implementation, it mostly uses `JSON.stringify(value)` and does not provide a way to specify a third `space` parameter to control indentation ([doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)).

**Comment by glasser** [comment]
This isn't a bad idea, though I think it would be best be implemented as an option to `new ApolloServer` called something like `stringifyResult` that takes a `FormattedExecutionResult` and returns a string, rather than providing further tweaks like `space`.  The default would basically be `prettyJSONStringify(orderExecutionResultFields(r))`.

Providing additional control over response output is related to #3815 as well, which suggests that perhaps this function should be async.

**Comment by dfperry5** [comment]
@glasser  - any chance this is an issue that could still be worked on? :)

**Comment by trevor-scheer** [comment]
@dfperry5 if you'd like to open a PR for it that's inline with what @glasser's suggested I'd be happy to review and land that change. Seems reasonable to me.

**Comment by dfperry5** [comment]
I will take a shot :)

**Comment by dfperry5** [comment]
@trevor-scheer  - if its not too much to ask, do you mind taking a peak here? https://github.com/apollographql/apollo-server/compare/main...dfperry5:Issue-4359-Pretty-Print-Response?expand=1

It's my first attempt, and just want to make sure I am following the above suggestion (at least as I understood it).

**Comment by trevor-scheer** [comment]
@dfperry5 looks like what I'd expect. Go ahead and open a PR and I'll give it a real review. Please add tests that demonstrate the new behavior.

**Comment by dfperry5** [comment]
@trevor-scheer  -- Thanks! Here it is: https://github.com/apollographql/apollo-server/pull/7634
