### ISSUE TITLE
Consider export-ing `DataSources` type

### ISSUE THREAD

**Issue by shellscape** [apollographql/apollo-server#4389]
I'd like to request that the `DataSources` be exported via `types.d.ts`. At present we're having to use the extremely fragile and feelsbadman approach of

```ts
import { DataSources } from 'apollo-server-core/dist/graphqlOptions';
```

We're doing some wrangling and fancy things and our only two options are presently to import directly from a `dist` location or redefine the type locally to match. Neither are good.

**Comment by abernix** [comment]
Sounds like a worthy consideration.  Can you show how you're needing the type directly as an example?  i.e., Is this important because you're defining the data-sources separately from the constructor where the map of `DataSource`'s would be automatically inferred?

(Fwiw, it appears we have the `DataSources` type defined in two places ourselves — in `graphqlOptions` — which is mostly legacy — and `requestPipeline` — which is not.)

**Comment by glasser** [comment]
The concept of DataSources (as a special part of your context value that works slightly differently than the rest of it) was [removed from Apollo Server in v4](https://www.apollographql.com/docs/apollo-server/migration/#datasources).
