### ISSUE TITLE
Response headers set on willSendResponse plugin are ignored on batched requests

### ISSUE THREAD

**Issue by nathanmarcos** [apollographql/apollo-server#4403]
Version: 2.19.13

When the server receives requests from the client with `BatchHttpLink`, the response headers set on `willSendResponse` plugin are ignored when sending the response to the client.

You can check on this [codesandbox](https://codesandbox.io/s/nostalgic-almeida-m8h2f?file=/index.js:362-363).
- When `USE_BATCH_HTTP_LINK` is `true` the client doesn't get the header `response.http.headers.set("x-foo": "bar")` set by that plugin:
`MY RESPONSE HEADER IS "null" WHEN BATCH HTTP LINK IS "true"!`

- Otherwise, when using the `HttpLink` the header is present:
`MY RESPONSE HEADER IS "bar" WHEN BATCH HTTP LINK IS "false"!`

The problem is actually in the `runHttpQuery.ts` class:
The [responseInit](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/runHttpQuery.ts#L270) is initialized, this is the response that will be send to the client.
- For a single operation (no batch), it iterate over the operator response headers and set those headers to the `responseInit` as you can see it [here](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/runHttpQuery.ts#L324).
- For multiple operators via batch: The operation response is [returned right away](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/runHttpQuery.ts#L289) without the header processing and exactly on this moment the headers are not forwarded to the client response. 
- The problem doesn't happen when the client performs multiple operations within the same request while using the `HttpLink`.

**Comment by abernix** [comment]
Thanks for opening this! I agree that the behavior here for batches is incongruent with the non-batched behavior.

As far as the solution: Given that a batched request has only one set of response headers but are each processed entirely independently from a GraphQL perspective (including separate invocations of the `willSendResponse` hook because of the way the request pipeline is currently wired up) would we just allow headers that have been written in the most recent (last) request be permitted to stomp on previous headers and leave any protections up to the user?  Should such stomping trigger a warning on the console?  How could that warning be silenced if it was intentional?

**Comment by glasser** [comment]
The implementation of HTTP batching is simpler in Apollo Server 4 (it's a layer on top of single-operation execution rather than a copy and paste of its code). Setting headers [should work](https://github.com/apollographql/apollo-server/blob/f11d55a83cf0300cf31674311e72cb7703c70040/packages/server/src/httpBatching.ts#L47-L50), with the semantics that if multiple operations set the same header, the last one wins.

If this issue still exists in AS4, please let us know!

**Comment by glasser** [comment]
It looks like this was specifically fixed in AS v3.0.0. (But in a way that ended up leading to #4760.)
