### ISSUE TITLE
Trying to create a bilingual schema

### ISSUE THREAD

**Issue by nsdeschenes** [apollographql/apollo-server#4414]
So I'm trying to get the request information for creating a schema that has bilingual descriptions to do this, I am trying to re-build the schema upon request using `const { ApolloServer } = require('apollo-server-express')`.

```javascript
  const server = new ApolloServer({
    schema: ({ req, res }) => {
      internationalization.activate(req.language)
      const schema = new GraphQLSchema({
        query: createQuerySchema(internationalization),
        mutation: createMutationSchema(internationalization)
      })
      return schema
    },
    context: ({ req, res }) => {
      return {
        req,
        res,
        ...context,
      }
    },
  })
```
However when trying to run this I meet with this error message:
```
UnhandledPromiseRejectionWarning: Error: Unexpected error: Unable to resolve a valid GraphQLSchema.  
Please file an issue with a reproduction of this error, if possible.
```

However if I remove the function and just assign the schema right away I don't receive any errors:
```javascript
  const server = new ApolloServer({
    schema: new GraphQLSchema({
        query: createQuerySchema(internationalization),
        mutation: createMutationSchema(internationalization)
    }),
    context: ({ req, res }) => {
      return {
        req,
        res,
        ...context,
      }
    },
  })
```
Wondering if this is possible or any ideas that may help fix this issue.

**Comment by glasser** [comment]
Apollo Server doesn't really support having an entire schema be incredibly dynamic based on individual requests. The schema is the strength of GraphQL; it lets you expect what operations will be valid, use tooling like code generators, etc. I'm not clear what you're trying to accomplish with the internationalization here — is it about what resolvers do, or about the actual schema itself (eg changing field descriptions based on the language)? Since I'm not sure what your goal is I'm going to close this issue. Sorry for the delay!
