### ISSUE TITLE
feat(gateway): CSDL fields arguments should be parseable as-is

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-server#4479]
Right now, the `fields` argument on the schema directives in the CSDL format follow the format we've always used in federation, a la `@key(fields: "id info { name }")`

Unfortunately for tooling, this can't always be parsed as a valid query (the implementor must wrap this string with an additional set of `{}` in order for it to be considered a valid AST and parseable by tooling.

This is not a problem in TypeScript, where the ownership of the string is not a consideration for the implementor, however, in Rust this creates an entire set of ergonomic issues related to creating a `String` on the fly, and who owns it once that `String` is consumed.

With CSDL being a composition artifact intended for consumption by tooling, I propose that we save implementors the extra step and just include the `{}` ourselves when building the document. This saves implementors the trouble, since they're going to parse it as a query before breaking it down anyway.

**Comment by jbaxleyiii** [comment]
@trevor-scheer this does seem pragmatic and should probably encourage us to revisit the current FieldSet abstraction (cc @queerviolet). I don't love that we will have a differing authoring format from output format but since we support such a limited set of what we support in FieldSets (just fields, not fragments or variables) I think this is probably a safe thing for the internal IR that is the CSDL

**Comment by abernix** [comment]
Closed by #4489, but worth noting that #4512 still exists, related to the concern by @jbaxleyiii here and my same/similar concern in https://github.com/apollographql/apollo-server/pull/4489#pullrequestreview-472835140.
