### ISSUE TITLE
reportSchema, should it use the proxy provided or not?

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#4529]
Hi team, awesome feature. I have one question about it and one thing which isnt working for us but i want to understand why.

bug we have: connection timeouts
We do pass requestAgent to Apollo server which is an HttpsProxyAgent. Reporting itself to Studio works perfectly with it. But i noticed on startup we have connection timeouts for pushing the schema (activated with 'reportSchema') and i was wondering if it is supposed to use the requestAgent or not.

question: is it possible to only sent schema once?
locally i tested the feature perfectly, but i saw (also in code) it sents it with a delay over and over again. Is it possible to have an option to only do it once successfully? We deploy our app when having new schema so just boottime is perfect.

Maarten

**Comment by glasser** [comment]
You can override how schema reporting talks to Apollo's servers by passing the `fetcher` option to `ApolloServerPluginSchemaReporting`.  (The `requestAgent` option you mention was specific to *usage* reporting and was somewhat redundant with *its* `fetcher` option; it was [removed in Apollo Server 4](https://www.apollographql.com/docs/apollo-server/migration/#requestagent-option-to-apolloserverpluginusagereporting).)

We also document how to [use `global-agent`](https://www.apollographql.com/docs/apollo-server/security/proxy-configuration) to enable proxies automatically for most HTTP uses in your whole process.

The design of schema reporting includes this ping, because our servers decide that your schema has been updated when it sees the new schema reporting and the old schema *not* reporting.  Note that it doesn't send the full schema unless our server's don't have it, just an ID.
