### ISSUE TITLE
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

### ISSUE THREAD

**Issue by ariusxi** [apollographql/apollo-server#4551]
Hi

I'm trying to create an app with apollo-server-lambda using @apollo/federation with him, but when i try to run my application he's returning the following error. In my case the attribute "resolutions" of the package.json isn't solving, and when i try to rollback some versions of the libs they still with the same error.

![image](https://user-images.githubusercontent.com/15126865/92498638-3f427400-f1d1-11ea-9590-61ea153912e7.png)

![image](https://user-images.githubusercontent.com/15126865/92498786-6b5df500-f1d1-11ea-9217-2f51460e8bab.png)

Node version: 12.16.1
NPM version: 6.14.5
Yarn version: 1.21.5

**Comment by abernix** [comment]
We don't ship `graphql` with any of our packages because of a design decision by the `graphql` package that require it to be defined within `peerDependencies` of packages that rely on it and necessitate that it be installed separately.  I will note that you shouldn't need to install `apollo-server` and `apollo-server-lambda` separately, though that shouldn't be the cause of the problem either.

If you run `yarn why graphql`, you should be able to see the two locations where it is installed.  Make sure that you only have one copy of `graphql` installed in your dependency graph.  Keep in mind that it might be a globally installed module!  Regardless, this shouldn't be a problem with `@apollo/federation` or `apollo-server`
