### ISSUE TITLE
Datasources reinitialized for every operation in a request

### ISSUE THREAD

**Issue by joearasin** [apollographql/apollo-server#4587]
I'll put an example together soon, but it appears that, while context is initialized once-per-request (even if there are multiple operations in a request), datasources are reinitialized once for each operation, defeating the benefits of request-level batches and caches in datasources.

The expected behavior is that datasources should have the same lifecycle as context, and the datasources method is run once-per-request and not once-per-operation.

**Comment by bdentino** [comment]
Would also love to see the same parameters passed to the dataSources function as are passed to the context function. We currently aren't really able to use dataSources effectively because some of our sources require arguments from the request context (e.g. authorization headers, trace parameters etc) for initialization so we end up having to set them up in the context function.

**Comment by veswill3** [comment]
I also ran into this issue and would love an official solution. I am trying to make my components on the front end as decoupled as possible and I love the idea of letting them define their own data needs, but when a series of components that happen to be on the same page batch together, they can result in many duplicate calls to the backend service because each operation in the batch gets its own datasource with its own `memoizedResults` map.

In other words, the RESTDataSource will automatically deduplicate GET requests in the same operation, but not across operations in a single batch, which seems like an oversight.

I did figure out a workaround, which is basically memoizing the memoizer 😆 
Where you setup your server:
```ts
const apolloServer = new ApolloServer({
  schema,
  dataSources,
  context: () => {
    // context is created once per request/batch
    return {
      // create memoizedResults to share with your datasources across operation in this request
      memoizedResults: new Map<string, Promise<any>>(),
    };
  },
});
```

then use it in your datasource:
```ts
willSendRequest(request: RequestOptions) {
  if (this.context?.memoizedResults) {
    // instead of per operation, use the one from context to span operations in this request/batch
    this.memoizedResults = this.context.memoizedResults;
  }
}
```

**Comment by glasser** [comment]
In Apollo Server 4, we will be removing the special magical treatment of data sources; you'll just put them on your context like anything else, which solves this problem.

It's slightly more challenging to do this in AS3 because your context function is provided directly to your ApolloServer's constructor but in order to pass the cache to the data source, you have to wait for ApolloServer to be created so you can write `server.requestOptions.cache`. In AS4, the context function is not part of the ApolloServer constructor, so that solves this issue.  (In AS4, instead of a subclass for your web framework integration like Express, there is only one ApolloServer class and framework integrations are provided by separate functions or classes that you pass your ApolloServer object to. The context function is passed to that function, which makes sense because its precise type depends on your integration.)

I don't think we will be changing anything about this in AS3 (if nothing else, it would be backwards incompatible) so I'm going to close this.

**Comment by glasser** [comment]
Er, actually it's not too hard to do this in AS3; you just have to hang on to your cache yourself.

```
const cache = new WhateverCacheImplementation();

class MyContext {
  public moviesAPI: MoviesAPI;
  constructor({ req, res }: ExpressContext) {
    this.moviesAPI = new MoviesAPI();
    this.moviesAPI.initialize({ cache, context: this });
    // initialize other context fields here too...
  }
}

new ApolloServer({
  cache,
  context: (expressContext) => new MyContext(expressContext),
  // ...
})
```

Note that it's helpful to use a class for your context type so that you can pass `this` to the data source even before constructing it is done, essentially fixing the circular dependency issue. (This is sort of cheating from a type perspective because `this` might not be a "complete" `MyContext` before the constructor is done, but works in practice here since RESTDataSource doesn't actually look closely at the context value in its constructor.)
