### ISSUE TITLE
[apollo-server-lambda] - Current package doesn't support APIGatewayProxyEventV2

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-server#4594]
It would seem that the `apollo-server-lambda` only has support for the old `APIGatewayProxyEvent` which is part of the v1 AWS API Gateway. If you deploy a new AWS lambda today and connect it to API Gateway, you will consistently get the same error:

```
Apollo Server supports only GET/POST requests.
```

This is because the incoming `event` is a `APIGatewayProxyEventV2` and associated with the `APIGatewayProxyHandlerV2`.  

[This comment](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46689#issuecomment-673928697) from the `@types/aws-sdk` repo gives a good explanation.

I'm opening this issue to solicit feedback from the community. This is a breaking change for anyone running on v1 AWS API Gateway.

I will also be creating a branch and testing this out. Feel free to comment on this issue with any feedback or concerns.

**Comment by diegobfernandez** [comment]
Hello, is there anything pending for this to be merged?
I have patched the changes in my node_modules for now.

**Comment by glasser** [comment]
This was fixed as part of Apollo Server 3 (by switching from our own implementation of parsing Lambda events to `@vendia/serverless-express`).

And now, Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. (You know this because you built it.)
