### ISSUE TITLE
Add a migration guide for users to switch from express-graphql

### ISSUE THREAD

**Issue by ravishivt** [apollographql/apollo-server#464]
It would be nice to provide a document to help users transition from express-graphql over to graphql-server.  If such a document (including third party articles or blog posts) already exists, we could add that to the README.  I was not able to find one.

**Comment by helfer** [comment]
Hi @ravishivt 

Yeah, we could definitely add that to the readme. IIRC the only differences are that `graphiql` runs on a different path, there's no option to pretty print and instead of `extensions` (which almost nobody uses) people have to use `formatResponse`.

PS: That reminds me that we should probably deprecate `formatResponse` in favor of some more limited function like `extensions`.

**Comment by DanielRSnell** [comment]
This would be extremely helpful as I am struggling converting schema over from express-graphql to apollo server. Not sure if I am doing it wrong or what but I am rather new and would benefit majorly from a readme.

**Comment by hchuff** [comment]
If you are still interested in switching from express-graphql, please join [Apollo Community on Spectrum](https://spectrum.chat/apollo/).
