### ISSUE TITLE
Yandex Cloud Functions integration

### ISSUE THREAD

**Issue by nikolaymatrosov** [apollographql/apollo-server#4707]
I propose to add an integration plugin similar to #1752.
For your information: [Yandex Cloud](https://cloud.yandex.com) is a big regional cloud provider. I assume that there are many Yandex Cloud users interested in this plugin.

**Comment by antonydevanchi** [comment]
+1

**Comment by glasser** [comment]
Apollo Server 4 has a simple stable API for building your own framework integrations, so that sounds great! Check out https://github.com/apollo-server-integrations/ if you'd like to put your integration in the community integration GitHub and npm orgs.

**Comment by antonydevanchi** [comment]
Wow, after 2 years really moved in  «completed»? 🦄

**Comment by glasser** [comment]
Yep, sorry for the delay. The overall design of Apollo Server 4 was "make it possible for issues like this one to be completed by enabling people who actually use the environment in question to write the best integration rather than forcing it to either not exist or be maintained by non-experts on the core team", but getting there was non-trivial :)
