### ISSUE TITLE
With HTTP batching, cache-control header is set based on the last operation

### ISSUE THREAD

**Issue by maapteh** [apollographql/apollo-server#4760]
Hi, on a single query we see that cache-control is working perfectly. So using the directive worked and stores correctly in our Redis cluster and the cache control hints work fine. 

BUT.

Now we activated batched queries in some clients and we expected the query with the correct cache-control would not pass our resolver anymore. But it does.

So foo has cache control directive and works fine and is not resolving on second call:
```
query foo {
   foo(id: 1) {
       id
       title
   }
}
```

Now besides foo we have bar which has cache control headers set to private, which results in foo to also always be dynamically being executed (not processed out of cache).
```
query fooBar {
   foo(id: 1) {
       id
       title
   }
   bar {
      loginState
   }
}
```

cacheControl is set like so (edited after remark below!):
```
type Foo @cacheControl(maxAge: 6000, scope: PUBLIC) {
  id: ID!
  title: String!

type Bar @cacheControl(maxAge: 0, scope: PRIVATE) {
  id: ID!
  loginState: String!
}
```

Why cant the cache-control implementation respect the cache settings when the query 'foo' is part of a batch?

**Comment by maapteh** [comment]
If you need reproduction please tell so.

**Comment by haroldwaste** [comment]
@maapteh You probably have one query which is not cached. If you define

`
type query {
  foo: [Foo] @cacheControl(maxAge: 5000, scope: PRIVATE)
  bar: [Bar]
}
`

and launch a batched query, the batched query won't have any cache and both resolvers will be called. But if you cache the two queries, the batched query will be cached as well. This behavior is somewhat rationnal since the headers need to specify caching for the whole request.

**Comment by maapteh** [comment]
Yes 'bar' is not cached since its private and we do 0 caching on it.

I dont care if that makes the header to be 0 as an end result, because thats the overhead of having a batch.

But what i do care about is that foo is still hitting the resolver logic, while we give it caching. It should not go to any service when getting the hit for that part.

**Comment by haroldwaste** [comment]
Actually it makes sense as well, not setting the http headers but still querying redis instead of the database... In this case I would set manually the corresponding logic in your resolver to query the right database. But Apollo is very limited on server caching so far.

**Comment by glasser** [comment]
This might have been sort of improved at some point (AS3 or AS4) because batching works a bit better with setting HTTP headers now, but it might just be that you end up setting the cache-control HTTP header based on the *last* operation rather than combining them all.

Actually, hmm. Maybe this is sort of a regression. We need to look further into this, but #4403 suggests that maybe AS3 didn't set cache-control headers at all for batched operations, whereas AS4 might now set sorta incorrect headers.

**Comment by trevor-scheer** [comment]
Resolved via @glasser's work in https://github.com/apollographql/apollo-server/security/advisories/GHSA-8r69-3cvp-wxc3
