### ISSUE TITLE
Defer & Stream now that they are part of graphql.js 

### ISSUE THREAD

**Issue by AndreasHald** [apollographql/apollo-server#4769]
Hi, now that Defer & Stream are becomming a part og graphql.js (https://github.com/graphql/graphql-js/pull/2319)(given still an experimental branch) what's the process for integrating it into apollo server / client?

**Comment by johnculviner** [comment]
Looking forward to this one! I'm seeing it on GQL libs for Java, Scala and Ruby now too.

This solves one of my biggest gripes with GQL - your response performance is limited to the performance characteristics of the slowest resolver dependency unless you issue multiple queries which really limits the ability of GQL to serve as a near perfect abstraction over legacy APIs etc.

**Comment by acao** [comment]
we now have reference implementations for the first transport spec for `@defer` and `@stream` [`IncrementalDelivery`](https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md)

it will involve handling partial responses, which is not going to be easy with the way `apollo-server-core` is decoupled from output, which worked fine up until now because responses weren't iterative. 

the [`express-grapql` PR](https://github.com/graphql/express-graphql/pull/726) makes it look easy because of how tightly we're coupled to express

you'd think we could follow a similar pattern to multipart upload, however [`IncrementalDelivery`](https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md) specifies a `request` protocol, not a `response` protocol

**Comment by acao** [comment]
> your response performance is limited to the performance characteristics of the slowest resolver dependency unless you issue multiple queries which really limits the ability of GQL to serve as a near perfect abstraction over legacy APIs etc.

this!

**Comment by acao** [comment]
seems that @abernix has an effort afoot to rearchitect for this feature!

https://github.com/apollographql/apollo-server/issues/3184

**Comment by hwillson** [comment]
We're working on `@defer` / `@stream` support and will be tracking progress in https://github.com/apollographql/apollo-server/issues/5893. Thanks!
