### ISSUE TITLE
visitArgumentDefinition of SchemaDirectiveVisitor is never called when an enum resolver exists

### ISSUE THREAD

**Issue by thomasttvo** [apollographql/apollo-server#4810]
## The Problem

Below is the code of a super simple apollo server (you can also refer to the codesandbox with the link all the way down below)

The `TrimDirective` class contains the method `visitArgumentDefinition`. This method is called if we don't have the enum resolver. Once the enum resolver is added, `visitArgumentDefinition` is never called.

```javascript
const { ApolloServer, gql, SchemaDirectiveVisitor } = require("apollo-server");

class TrimDirective extends SchemaDirectiveVisitor {
  visitArgumentDefinition(argument, details) {
    console.log("visiting ARG"); // This doesn't run ❗️❗️❗️❗️❗️
  }

  visitFieldDefinition(field, details) {
    console.log("visiting FIELD");
  }
}

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }

  directive @trim on ARGUMENT_DEFINITION | FIELD_DEFINITION

  type PlaygroundResponse {
    testVar1: String
    testVar2: String @trim
  }

  type Mutation {
    playground(testVar1: String @trim, testVar2: String): PlaygroundResponse
  }

  enum TestEnum {
    TEST
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: (root, args, context) => "Hello world!"
  },
  Mutation: {
    playground: async (parent, { testVar1, testVar2 }, { user, req }) => {
      return { testVar1, testVar2 };
    }
  },
  /**
   * Adding this enum def here causes visitArgumentDefinition to never fire
   */
  TestEnum: { TEST: "123" }
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  schemaDirectives: {
    trim: TrimDirective
  }
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

## Versions

Verified not working on `^2.2.3` and `2.9.7`. I have not yet tested other versions.

## Live Code Example
Go to this codesandbox and remove the enum resolver in the highlighted lines.
Afterwards you should see "visiting ARG" text showing in the console indicating the `visitArgumentDefinition` method is now called:
https://codesandbox.io/s/apollo-visitargumentdefinition-bug-jnw4u?file=/index.js:969-1085

**Comment by harshil4076** [comment]
https://github.com/apollographql/apollo-server/issues/4894#issue-801431830

**Comment by glasser** [comment]
Wow, that does seem like a surprise. I'm starting to ramp up on helping keep up to date with this project's issues and PRs. schemaDirectives is not a part of Apollo Server I'm personally super familiar with, so this issue and #4894 seem like a great way for me to start to appreciate this part of AS.

**Comment by glasser** [comment]
I looked into this. Apollo Server links in an old version of the `graphql-tools` package (v4) which is what it uses to implement schema directives (and more broadly, combining your schema with resolvers).  In this old version, providing any enum values executes a transformation of the schema, which eventually ends up making a clone of the argument object [in the function argumentToArgumentConfig](https://github.com/ardatan/graphql-tools/blob/v4.0.8/src/stitching/schemaRecreation.ts#L263-L280). Most of the similar functions in this file copy over a reference to the original astNode but this file doesn't.

Later versions of graphql-tools fix this issue both by not doing a transformation of the schema at all for enum values and by including the `astNode` field. However, because the API of graphql-tools is exported directly from AS2, we can't upgrade the built-in version of `graphql-tools` to get this bug fix.  (We will probably upgrade in AS3 (https://github.com/apollographql/apollo-server/issues/4923) and also will stop exporting the API so that it becomes more of an internal implementation detail that lets us upgrade more easily.)

Because of this, I don't think we can fix this bug in AS2. The good news is that the use of `graphql-tools` in Apollo Server is pretty limited and you can use your own newer version if you want.  Install `@graphql-tools/schema` and do this:

```
import { makeExecutableSchema } from '@graphql-tools/schema';
new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs,
    resolvers,
    schemaDirectives,
    parseOptions,
  }),
});
```

where the four options passed to makeExecutableSchema are the same as the options passed to `new ApolloServer`.

Caveat: this will skip a bit of magic that ApolloServer does to add some stuff to your schema, so if you rely on either of the features that need it you'll have to add them back.  (Maybe AS3 can come up with a cleaner way to implement this.) If you use the cacheControl feature, you'll need to manually add this to your schema

            enum CacheControlScope {
              PUBLIC
              PRIVATE
            }

            directive @cacheControl(
              maxAge: Int
              scope: CacheControlScope
            ) on FIELD_DEFINITION | OBJECT | INTERFACE

If you use the built in `graphql-upload` integration (which is going to disappear in AS3; I encourage you to disable the built-in integration with `uploads: false` and install the newest version of `graphql-upload` yourself instead) you will need to add `scalar Upload` to your schema and add a resolver for Upload to resolvers, as shown in https://www.npmjs.com/package/graphql-upload#examples
