### ISSUE TITLE
Can you not set/clear cookies with apollo-server?

### ISSUE THREAD

**Issue by joshbedo** [apollographql/apollo-server#4828]
I just switched from apollo-server-express to apollo-server because the subscription support seemed better but not I'm having issues where all of the express methods don't exist for cookies. I need to set a cookie with our refresh token so people can login and I also need to clear the cookie so they logout. This was pretty easy with apollo-express but I've spent hours and can't figure out how to touch cookies with Apollo Server. whats the best way to set cookies and clear them with apollo server? I added req/res to the context but I'm not seeing anything for cookies besides req.headers.cookie

**Comment by maapteh** [comment]
If you have it set on the context you can just use it's api no, i never thought it would be different?

`res.setHeader('set-cookie', ...)`

**Comment by abernix** [comment]
Thanks for reporting this issue originally!  I'm going to close this due to inactivity — though the above suggestion should work.  If you can't clear the cookies using roughly the same — if not exactly the same — pattern, then that would seem like a bug.

If this is still a problem, would someone who's experiencing the problem (or anyone who comes across this issue and is able to assist) mind building a reproduction of the problem in to [a runnable CodeSandbox reproduction](https://codesandbox.io/s/apollo-server) using the latest version of Apollo Server and sharing the link to that CodeSandbox in this issue?

I'm happy to re-open if this is still occurring and someone can provide a reproduction.  Thanks again!

**Comment by ahmed-sharief5** [comment]
If your looking for aws-server-lambda answer [here](https://stackoverflow.com/questions/65554993/how-to-clear-an-set-cookies-with-apollo-server/71823954#71823954) is the solution for that
