### ISSUE TITLE
Integrating Apollo-graphql-express with Lambda

### ISSUE THREAD

**Issue by pbishnupuri** [apollographql/apollo-server#4849]
I want to deploy my apollo graphql using lambda. However, currently I use express as a middleware, so I use apollo-graphql-express. If I switch to apollo-graphql-lambda, I can't use server.applymiddleware. How can this be done? Is it possible?

**Comment by antoniopacheco** [comment]
I would love an answer to this, I also build my app around `apollo-server-express` and will like a tutorial on how to migrate from there. or how to be able to switch between the two, so I won't loose the ability to test locally in my express serer

**Comment by glasser** [comment]
I'm not sure exactly what you're asking. Are you just asking "if I have an ApolloServer and I'm applying it to an express app with `applyMiddleware`, how do I apply it in Lambda instead"? If so, the answer is roughly "instead of `applyMiddleware`, you use `createHandler`". There are more details in [the README](https://www.npmjs.com/package/apollo-server-lambda) or in our [deployment docs](https://www.apollographql.com/docs/apollo-server/deployment/lambda/) though note that the latter expects that you're using the `serverless` framework.

If you're asking "I have an express app where I've done a lot of things, including applying my `apollo-server-express` middleware; how do I move this entire app to Lambda", then I think that's a different question.  In that case my guess is you'd want to find a more generic way to use Express with Lambda, and continue to use `apollo-server-express` with it. For example, [this Bitbucket blog post](https://bitbucket.org/blog/deploy-an-express-js-app-to-aws-lambda-using-the-serverless-framework) has an example of how to use `serverless` to deploy express to Lambda; I'm not familiar with it myself but it seems plausible.

Re being able to switch a single app between `apollo-server-express` and `apollo-server-lambda`, I think [this post from the Apollo blog](https://www.apollographql.com/blog/building-a-portable-apollo-server-config/) might be interesting!
