### ISSUE TITLE
AS3: Make CORS default behavior more consistent and perhaps different

### ISSUE THREAD

**Issue by iambumblehead** [apollographql/apollo-server#4859]
Apollo Server's default behavior around CORS is inconsistent across integrations. For example, `apollo-server`, `apollo-server-express`, and `apollo-server-koa` set `access-control-allow-origin: *` by default, whereas `apollo-server-lambda` does no CORS by default.

We should definitely make the behavior more consistent in Apollo Server 3.

We should consider what that consistent behavior should be.

There's a good argument to be made that the default should be no special CORS stuff at all (with a good docs page explaining how to set up CORS properly).

Another idea would be to make the default be `access-control-allow-origin: *` (for ease of onboarding), but also log a message saying that this is happening (which can be suppressed without behavior change by passing `cors: true`). This is also something that can be done in AS2 as mentioned in #5076 for the integrations that have that default already.

We could also make the default depend on `NODE_ENV` or the `debug` option, but I think that's more likely to be confusing than helpful.

Finally, we can consider fully ripping out CORS customization from Apollo Server (or at least from the packages that are not `apollo-server`).  There's something to be said for having a default of `access-control-allow-origin: *` that leads to a log message and a way to disable either the log message or the header setting, but to leave any other customization up to your own framework code (ie, just do `cors` yourself).  Or having the default be to do nothing and the only thing that's built in being an easy way to set the `*` header.  This probably entails ensuring there's an easy way to apply the `cors` npm package to things like `apollo-server-lambda` (ie, the lack of middleware for the serverless integrations is harmful).

(There is a separate issue #5076 around improving the docs and making backwards-compatible changes in AS2; this issue is about potential AS3 backwards-incompatible changes.)

**Comment by glasser** [comment]
The original description of this issue by @iambumblehead was

>Without any participation or permission from my application, apollo-server-koa automatically searches for and loads and calls '@koa/cors'. Please advise if there is a solution to this.
>
>I do not want cors loaded for production deployments.

I'm updating this to make it more general.

**Comment by jonesmac** [comment]
Thanks @glasser for pointing me to this thread.  I think I finally see the value proposition of AS including CORS; providing a fully functional graphql server out of the box.  That being said, I would like to propose another option where AS allows a valid CORS configuration to be passed as part of the initial config, it will use it.  Otherwise, it can throw a warning saying that CORS has not been setup **OR** it could provide a sane default for projects that might choose to include one (i.e. lambda).  Essentially, AS will proxy any provided CORS config to the cors lib that is installed.

I see the following benefits:

1. It puts the responsibility of the end user to provide both a valid config and the correct corresponding version of the CORS lib / types themselves.  
1. Alleviates the worry of CORS types or CORS lib upgrades accidentally becoming breaking changes introduced by AS.
1. Still allow each package to provide a fully functional graphql server without being opinionated regarding CORS version.

I am totally new to AS so I apologize if any of this is naive.  Love to know your thoughts.

**Comment by glasser** [comment]
So part of the inconsistency got resolved for free when I converted `apollo-server-lambda` and `apollo-server-cloud-functions` to be wrappers around `apollo-server-express` instead of having their own bespoke cors implementations.

#5297 makes things more consistent by also changing `apollo-server-azure-functions` to default to `ACAO: *` instead of no CORS, and changing `apollo-server-koa` to default to `ACAO: *` instead of reflected origin.  Now all integrations which have cors support at all have the same default (micro and cloudflare have no cors support).

I think it is reasonable for now to keep `*` as the default. It still would be a good idea to make sure this is more loudly documented, and maybe log a warning in production? That can be added after 3.0.0 though.
