### ISSUE TITLE
Inconsistent behavior when throwing error in query resolver

### ISSUE THREAD

**Issue by doomsower** [apollographql/apollo-server#488]
Here is an example: https://launchpad.graphql.com/9wq4q70qr

Lets say I have simple query resolver which just throws (e.g. because user is not authorized):
```js
const resolvers = {
  Query: {
    hello: (root, args, context) => {
      throw new Error('Something bad happened!');
    },
  },
};
```

When query result type is non-nullable, like in this example
```graphql
type Query {
  hello: String!
}
```
The output does not contain `hello` field:
```json
{
  "errors": [{ ... }],
  "data": null
}
```

When I change `hello` result type to be nullable:
```graphql
type Query {
  hello: String
}
```
then the output contains `hello` field:
```json
{
  "errors": [{...}],
  "data": {
    "hello": null
  }
}
```

This looks weird to me. Is it bug or intended behavior?

**Comment by jskorepa** [comment]
I think that this is intended behaviour. If you have something which is not nullable it bubbles up (and it does not matter if it is null because you threw an Error or because you returned null).

Think about it this way: if you throw an error it sets the field to null. And because the field is not nullable only reasonable thing to do is to go one level up and set that to null.

**Comment by yogesh-kamble** [comment]
In my application if field throw the error then I want to return only error to Client and Ignore the partial data. (Basically once User login successful then we are adding one more field in the Schema but if resolver for that field throw error then just want to return the error and server should not send the partial data of user. is it possible to achieve this ?)

**Comment by JacksonKearl** [comment]
We try to never return null for non-nullable types, so yes this is expected. Thanks for taking the time to ask!
