### ISSUE TITLE
Healthcheck does not work for apollo-server-lambda when using an API gateway custom domain

### ISSUE THREAD

**Issue by iannickb** [apollographql/apollo-server#4891]
If you run your service with a custom domain and you use a path in your mapping, you will get a 400 response.

**The expected behavior:**
Return the healthcheck status

**The actual behavior.**
A 400 response with `GET query missing.`

This is probably due to how the path is passed from Cloudfront to APIG. One way to fix it would be to check if the path endsWith "/.well-known/apollo/server-health" in this file:
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-lambda/src/ApolloServer.ts#L176

I can create a PR if this could be useful for others.

- [x] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [x] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [x] The expected behavior.
- [x] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).

**Comment by glasser** [comment]
I've published a release with this to version `2.21.1-alpha.0`. My plan is to release 2.21.1 on Monday. If you want to test that this fix works before then, try running the prerelease yourself, and provide feedback on https://github.com/apollographql/apollo-server/pull/4990

**Comment by glasser** [comment]
The idea of having our server parse URL paths and do a health-check that's unrelated to the actual GraphQL processing was pretty flawed, since the server doesn't really know the base URL in cases like this one. In Apollo Server 4 we are fully removing the health-check feature as well as path parsing entirely. I recommend you use "GraphQL-level health checks" as described in [the docs](https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/) rather than this doomed "HTTP-level health checks" feature.
