### ISSUE TITLE
Missing support of async cors configuration for Fastify

### ISSUE THREAD

**Issue by Sikora00** [apollographql/apollo-server#4911]
Fastify cors package with version 5.2.0 has support for async configuration [check here](https://github.com/fastify/fastify-cors/issues/106). It would be great if apollo will support that as well.

I think the result something like this should work:

``` ApolloServer.ts
#ApolloServer.ts
          if (cors === true) {
            instance.register(require('fastify-cors'));
          } else if (cors !== false) {
            if (typeof cors === 'function') {
              instance.register(require('fastify-cors'), () => cors);
            } else {
              instance.register(require('fastify-cors'), cors);
              }
          }
```

**Comment by glasser** [comment]
Thanks @Sikora00! This sort of feature request for more in-depth integrations for the more niche web frameworks is something that the Apollo Server core team is unlikely to work on ourselves, but a PR would definitely be interesting.  (For the most part, I think it makes sense for integration features to be built by people who plan to run that integration themselves, rather than the core team hoping that they have a solid understanding of a web framework they don't use.)

**Comment by Sikora00** [comment]
Totally makes sense. Just wanted to make sure that PRs are open for this feature. I will make one soon.

**Comment by trevor-scheer** [comment]
For further developments on AS integration with Fastify please visit the new AS4 Fastify integration repo:
https://github.com/apollo-server-integrations/apollo-server-integration-fastify
