### ISSUE TITLE
AS3: Consider upgrading to the latest graphql-tools

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#4923]
Apollo Server uses `graphql-tools` to convert from typeDefs/resolvers/schemaDirectives/parseOptions to a schema, and to implement mocks/mockEntireSchema.  (We also re-export all of its symbols from all the integration packages, but we've already removed that from AS3.) We currently depend on `graphql-tools@4. They moved on to v5 last April (and also split the package into more packages). We should probably update to the latest stable version and depend on the sub-packages (`@graphql-tools/schema` and `@graphql-tools/mock`).

Alternatively we should consider whether graphql-tools is necessary or whether there's a more direct way to implement AS's API (or if the API should change). Probably we just want to upgrade though!

**Comment by Urigo** [comment]
@glasser feel free to talk to us if you need anything from `graphql-tools` like preventing certain changes or breaking into smaller pieces or even connecting our builds together.
Just as a note, we separated `graphql-tools` into scoped packages so that might help with certain changes and keeping up with versions.

**Comment by glasser** [comment]
@Urigo Absolutely! Always a pleasure getting to work with you :)

**Comment by glasser** [comment]
See #4237

**Comment by glasser** [comment]
Fixed on release-3.0
