### ISSUE TITLE
Registry plugin + Playground?

### ISSUE THREAD

**Issue by sarink** [apollographql/apollo-server#4935]
If you are using the registry plugin and forbidding unregistered operations, how can you still utilize the playground?

It seems to me that there are two problems:
1. The introspection query itself is unregistered and therefore forbidden, and
2. The playground is not a registered client, so any queries run from it will also be forbidden

I know that we could include a magic header that allows anything, but I don't really like that approach. We have some sensitive data and don't want to have a magical "allow anything" key floating around our organization.

To solve the first problem, I was able to write some code that detects if the query is an introspection query, and allow it.

For the second problem, I was hoping we could find a way to have the playground emulate one of the registered clients (this would also be useful in testing and verifying that only certain clients can access certain operations).

Is this possible? I thought all it would take is passing the `"apollographql-client-name"` and `"apollographql-client-version"` headers, but that doesn't appear to do it. How else does the registry plugin identify a client?

**Comment by glasser** [comment]
You're right that forbidding unregistered operations is not very compatible with using a client like graphql-playground that depends on introspection to be useful.

One option would be to explicitly register the particular introspection operation that graphql-playground uses. Another option would be (since you're using Apollo Studio anyway in order to use the operation registry) to use Studio's Explorer instead of graphql-playground; Explorer uses the schema in the Apollo schema registry rather than depending on introspection.

I'm not sure what you're referring to with "registered clients"; I wasn't aware that the operation registry feature has a concept of registered clients?

That said, the operation registry feature has not been under very active development, and its development is more part of the Studio product than the open source Apollo Server project (the plugin just lives in this repo for convenience).  I don't think that having open issues on this repo about the operation registry is likely to lead to improvements.
