### ISSUE TITLE
Design an API that lets you use graphql-upload with apollo-server-lambda

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#4951]
We will remove the direct integration with `graphql-upload` from Apollo Server 3.

It's easy to plug your favorite version of `graphql-upload` back in to a middleware-style web library like Express in front of Apollo Server's middleware, but that's not the case for environments like Lambda (the second most popular place to use Apollo Server).  We should add some hooks to `apollo-server-lambda` that allow people to use (among other things!) graphql-upload.  The Apollo Server core team is happy to review such a PR but since we are not Lambda users ourselves, we aren't best situated to write that PR.

Ideally we can get this new API out in ASv2 so that folks who want to use `graphql-upload` with Lambda can migrate to the new API before the old integration is removed in v3.

See https://github.com/apollographql/apollo-server/issues/3508#issuecomment-784537359 for some thoughts on how to implement this.

**Comment by jaydenseric** [comment]
Probably it's best for `apollo-server-lambda` not to prescribe an approach for file uploads until there is a reliable serverless API available from [`graphql-upload`](https://github.com/jaydenseric/graphql-upload), here are the enhancement issues:

- Support AWS Lambda: https://github.com/jaydenseric/graphql-upload/issues/155
- Support Google Cloud Functions: https://github.com/jaydenseric/graphql-upload/issues/129

Unfortunately serverless environments tend to buffer the whole multipart request into memory, then pass that into the function after. This means the file uploads can't be processed while they stream in, and memory requirements balloon by whatever the size of the files is. Existing hacks using the [`processRequest`](https://github.com/jaydenseric/graphql-upload#function-processrequest) function in AWS Lambda are not ideal, for reasons explained here:

https://github.com/jaydenseric/graphql-upload/issues/155#issuecomment-632998596

> Since AWS will gather the whole request in memory before passing it on to your function, any workarounds to try to simulate a request stream for `processRequest` which then buffers it to "disk" all over again via `fs-capacitor` would be a performance tragedy.
>
> For propper AWS Lambda support we could publish a function that processes an event into something that can be passed into existing GraphQL handlers, without using `fs-capacitor`. It would read the [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec) form data (Base64?) string provided in the Lambda event, and extract the files and query and variables, putting them together to look like a regular GraphQL POST request for popular GraphQL handlers (e.g. [`apollo-server-lambda`](https://npm.im/apollo-server-lambda)) to consume.
>
> I haven't thought a lot about the details, and don't plan to work on it personally anytime soon as I don't have a need for it for any of my work or personal projects. I prefer to process file uploads as the stream in, for a much faster response time:
>
> https://github.com/jaydenseric/graphql-multipart-request-spec/blob/master/sync-vs-async-graphql-multipart-request-middleware.svg
> 
> A function for Lambda should actually be a much simpler implementation that the current `processRequest` implementation for HTTP requests that stream in, because you can tell up front if the form data is malformed or not and you know all the files are there; you don't have to handle all the problems of expected files never arriving, disconnects part way through, multiple resolvers consuming the same file streams etc.

Ideally the new serverless API would be agnostic to all the serverless environments that exist (and might exist in the future) and instead of supporting specific vendors by name, can easily be adapted to either AWS Lambda or Google Cloud Functions. Maybe by processing a raw request body string?

The Apollo community is welcome to contribute ideas for the above issues and submit a PR.

**Comment by glasser** [comment]
Thanks @jaydenseric. I do agree that using today's graphql-upload with Lambda isn't optimal. On the other hand, people actually do use it, so my main goal is not completely breaking those folks when the built-in integration is removed in AS3.

I think my ideas in https://github.com/apollographql/apollo-server/issues/3508#issuecomment-784537359 are generic enough that they may just generally make apollo-server-lambda more usable, while also solving the graphql-upload integration issue.  Hopefully the same hook would also support a non-capacitor graphql-upload implementation!

**Comment by glasser** [comment]
One other approach here would be to completely replace `apollo-server-lambda` with something that uses something like https://github.com/vendia/serverless-express to wrap `apollo-server-express`. So the extension API for `apollo-server-lambda` would be the same as the extension API for `apollo-server-express`, and we would make sure that this supports graphql-upload as well.
