### ISSUE TITLE
Request header {Content-Type : application/json, Content-Length: 188 ,}throw error SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Darfion** [apollographql/apollo-server#4968]
when in Request I use header {Content-Type : application/json, Content-Length:  188 ,} the server throws an error.

>SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\body-parser\lib\types\json.js:89:19)

this my code

***index.ts***

    import { ApolloServer } from "apollo-server-express";
    import cookieParser from "cookie-parser";
    import cors from "cors";
    import { config } from "dotenv";
    import express from "express";
    import { express as voyagerMiddleware } from "graphql-voyager/middleware";
    
    import models from "./models";
    import resolvers from "./resolvers";
    import typeDefs from "./schema";
    import authorization from "./toolses/authorization";
    import adminInitializeApp from "./toolses/function/adminInitializeApp";
    import {} from "./toolses/function/globalType";
    
    config();
    (async () => {
      const app = express();
    
      const { PORT, FRONT_PORT, APOLLO_PATH } = process.env;
    
      const corsOptions = {
        origin: FRONT_PORT,
        credentials: true,
      };
    
      app.use("/voyager", voyagerMiddleware({ endpointUrl: "/graphql" }));
      app.use(cors(corsOptions));
      app.use(cookieParser());
    
      const server = new ApolloServer({
        typeDefs,
        resolvers,
        context: async ({ req, res }) => {
          const currentUser = authorization(req, res);
          const db = adminInitializeApp();
          return { res, req, db, currentUser, models };
        },
      });
    
      server.applyMiddleware({ app, path: APOLLO_PATH, cors: false });
    
      app.listen({ port: PORT }, () => {
        console.log(Apollo Server on http://localhost:${PORT}/graphql);
      });
    })();

***header***

    Content-Type: application/json
    Content-Length: 188

**Comment by glasser** [comment]
I'm not sure I follow what's going on here. This isn't a full reproduction, so I can't see it myself; bug reports are more actionable if they come with a *complete* reproduction that I can trivially run on my own machine just following explicit instructions instead of getting creative (eg, instructions that start with `git clone`, or which use something like codesandbox.io).

content-length is supposed to be the length of the body, but you're not sharing the body that you're POSTing here. Perhaps your body is longer than 188 bytes? I think this is almost certainly an error on the *client* side of your GraphQL request, not the server side.

(content-length counts bytes, not characters, so if your body is non-ASCII and you're accidentally setting content-length to a character count (which would be smaller than a byte count) then you most likely would get an unexpected end of input error like this).)

I'm happy to reopen this issue if you share with me a complete reproduction recipe!
