### ISSUE TITLE
Plugin event callbacks should be async

### ISSUE THREAD

**Issue by jsshapiro** [apollographql/apollo-server#4999]
All currently defined event callbacks for plugins are synchronous. This means, for example, that one cannot wrap operations in a transaction if the database connection is in turn async.

The fix is to add await at all of the callback invocations in processGraphQLRequest in apollo-service-core/requestPipeline.ts, which is already an async function. await has no effect if called on non-async functions, so this should be completely backwards compatible.

If there is interest in adopting this change, I'll be happy to create a mergeable repo.

In abstract, the transaction could be started in a context factory. The problem is that there's no clean way to close the transaction connection on completion in that approach.

**Comment by glasser** [comment]
Can you name an example of a synchronous event callback? I'm pretty sure most of them are async (or well, they're an odd "you can make them sync or async" thing).

**Comment by jsshapiro** [comment]
So I get all of what you’re saying. Problem is: this means middleware
cannot correctly wrap execution in current Apollo-server. Deferring that to
AS3 seems unfortunate, as I’d bet there’s a fair bit of ignorantly broken
code in the field on this one.

**Comment by glasser** [comment]
AS3 will hopefully be in the not too distant future!

**Comment by abernix** [comment]
I don't know what the original motivation was but the choosing of sync hooks appears to be somewhat intentional, since the hooks (even in the new Plugin aPI) which are _still_ synchronous are wrapping underling functions calls into `graphql` (e.g., `parse` and `validate`) which are themselves synchronous.  Just mentioning this though, and I certainly wouldn't challenge an opportunity for there to be a future that changes that!

However, for today (in case it's useful!) this was an example solution that was drawn up some time back by @queerviolet that worked to solve a particular desire to wrap _execution_ in a transaction by one of our users — note there is also an _imperative_ example below the first _block_ example:

https://gist.github.com/queerviolet/41c01c6b7b5198f688c0b6e10523e735

Note though this is just wrapping execution, though as a matter of principle, I'm not sure if you actually want to be wrapping your parsing and validation invocations in a database transaction.

Anyhow, hope this is helpful!

**Comment by jsshapiro** [comment]
Thank you, @aberniz.

Even when a hook wraps something synchronous, that doesn't mean that the hook function wants to be synchronous. We may need to do async things _around_ the parse function (like I/O) even if the parse function itself is synchronous.

If you read it more closely, you'll see that the code you cite illustrates the _problem_, not the solution.

First, that code isn't building a transaction; it's building a _promise_ for a transaction. If that approach is used, every single use of the transaction connection in the resolvers must await the transaction. This is necessary exactly (and only) because it _can't_ be awaited from inside a non-async plugin callback.

Second, neither variant is executing any cleanup code at the end of the transaction, which was my original goal.

Third, if something goes wrong setting up the transaction, the exception context will be bizarre.

Have another look at that code and ask yourself what happens if the plugin acquires and releases a database connection from a pool for each operation (which it definitely _should_ be doing). Ask yourself where it is possible to put the required connection release that won't leave you with an unresolved promise when an exception occurs during release (and yes, _that_ can happen). Note that in up-coming versions of Node, unresolved promises will be treated as server-fatal errors.

Then ask yourself how you would make that approach work if a mutation transaction aborts because of a read or write conflict and needs to be re-tried. _That_ can't be solved with the plugin/callback approach. It truly requires wrapping the execute function so that the execute function can be called again - something that is relatively easy to do in `graphql-js` but does not seem to be possible in ApolloServer. Though perhaps I just can't figure out how.

@glasser: Could you please give a moment's thought to my transaction retry example? Unless I'm missing something, that can't be done with the plugin approach. Do you want another bug opened to expose the execute function similar to graphql-js `customExecuteFn`?

**Comment by glasser** [comment]
For what it's worth, the `gateway` argument does allow you to override execution. (I have personally been skeptical of our choice to not just use the plugin interface for that purpose, though I'm not planning to change that decision.)

**Comment by glasser** [comment]
See #4051 and #4050.

**Comment by glasser** [comment]
#5295 makes all plugin APIs (except `willResolveField`) async (not optionally async, just async). Will be released in AS3. Thanks!
