### ISSUE TITLE
Apollo Server: verifying web socket origin. 

### ISSUE THREAD

**Issue by rrajarajan** [apollographql/apollo-server#5038]
In Apollo-Sever I need to be able to verify incoming web socket requests and be able to check the Origin of the header.
Is there a easy way to do this.

**Comment by glasser** [comment]
Apollo Server support for websockets is really just a superficial integration of `subscriptions-transport-ws` (and will be removed in Apollo Server 3).  So the answer to this question is "however you do it in `subscriptions-transport-ws`". The whole integration is here: https://github.com/apollographql/apollo-server/blob/19f01083ea6aa5a66a1619741c70d2e453f7f264/packages/apollo-server-core/src/ApolloServer.ts#L645-L711

My guess is the answer is "something to do with `onConnect`". A cursory glance at https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts suggests that `onConnect` handlers will receive as a third argument a `connectionContext` which has a `request` field which probably has headers on it, and you can pass that `onConnect` to Apollo Server's built-in integration via `new ApolloServer({subscriptions: {onConnect}})`. (Though I'd encourage you to use `subscriptions-transport-ws` directly, or perhaps the more maintained `graphql-ws` package, because as I mentioned we will be removing the superficial integration soon.)
