### ISSUE TITLE
Incompatibility with AWS Cloudfront and AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by esperancaJS** [apollographql/apollo-server#5041]
Running on AWS Elastic Beanstalk works fine with a simple setup.

But delivering the load balancer over AWS Cloudfront outputs: 400 Bad Request > GET query missing.

I can confidently say the error lies somewhere with the apollo-server since the same AWS setup with AWS Elastic Beanstalk's Basic node app example works well.

**Comment by glasser** [comment]
Thanks for sharing this. Unfortunately there is no way that we can investigate and debug this issue, because there's no way to reproduce it for ourselves. If you are able to provide a clear set of instructions for setting up exactly the situation you're seeing that I can follow without having to be creative, I'd definitely be interested in looking into it.

In addition to explaining exactly how to set this up (ideally starting with "Create an AWS IAM user and an API key, run git clone and npm install in this repository, and then..."), I'm not sure what requests are failing. Is an attempt to actually run GraphQL operations failing, or just loading graphql-playground over HTTP?

I will note that `GET query missing.` is the error that occurs when you try to send a request to the actual GraphQL API endpoint with a `GET` but you do not provide a query parameter named `query`. AWS Cloudfront [requires you to explicitly configure it to pass query parameters to your server](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/QueryStringParameters.html) so if you haven't done this then executing GraphQL operations with GET requests will not work (though you can still execute GraphQL operations with POST requests, which put the operation information in the body of the request rather than the query parameters).

**Comment by esperancaJS** [comment]
Thanks @glasser!

Your tip on passing the query parameters through CloudFront seems to be the main issue.
Changing the cache and origin request policy has made HTTP requests now function properly.
However, HTTPS ones return 502 Bad Gateway.

I'm staying really close to the most basic tutorials for both elasticbeanstalk and Appolo-server.

Here is the apollo-server code: [https://codesandbox.io/s/zen-satoshi-nrsms](https://codesandbox.io/s/zen-satoshi-nrsms).

Here is the Cloudfront config: 
![image](https://user-images.githubusercontent.com/1115163/111766438-73dc6a00-889d-11eb-8492-adf4ce6a12d3.png)

**Comment by glasser** [comment]
Unfortunately debugging CloudFront configuration isn't really a great fit for the Apollo Server team, though perhaps other community folks may be able to help you on this closed issue, or AWS support could help you figure out where to view logs associated with bad gateway addresses. If those logs indicate any error message from Apollo Server, perhaps we could help more.

**Comment by esperancaJS** [comment]
I understand, was just providing the steps you requested in your first comment.
Thanks @glasser, I really appreciate the help :)

I'm still playing the trial and error DevOps game. Once I know the solution I'll update here. This might be relevant to anyone trying to get the most basic tutorial examples to function on AWS.
