### ISSUE TITLE
Aliases cause multiple resolves node error

### ISSUE THREAD

**Issue by fschucht** [apollographql/apollo-server#5052]
## Current behavior
We noticed that we receive multiple resolves errors from node in our production apps. This happens whenever we batch and alias the same query in the same request. This error only seem to happen if the resolver throws an error. If the promise succeeds no error is logged. 

At the moment it's not clear to us if the issue causes any issues within our production codebase. However from our understanding it might hint at a potential error source if the multipleResolves is triggered. So we want to report it so that it can be fixed if necessary.

This error was originally reported for `nestjs/graphql` but can be reproduced with just `apollo-server`:  https://github.com/nestjs/graphql/issues/1422 

## Expected behavior
We would not expect to see the multiple resolves error.

## Minimal reproduction of the problem with instructions
1) Clone the repository: https://github.com/fschucht/apollo-multiple-resolves
2) Install dependencies
3) Start the server with `node index.js`
4) Run the following query:
```
query {
  a: entity
  b: entity
}
```
5) You should see a log output similar to this:
```
MULTIPLE RESOLVES:  Error: Some error occured
```

## Version
apollo-server: 2.21.2

**Comment by glasser** [comment]
Interesting, I'll look into this on my next "look into things that require research or learning" day. Thanks for the great reproduction.

The [documentation for the multipleResolves event](https://nodejs.org/api/process.html#process_event_multipleresolves) says that it's not necessarily an error, though, so it's possible the resolution will just be "yep, this isn't an error"? Do folks tend to rely on multipleResolves events never being fired?

**Comment by glasser** [comment]
This issue isn't specific to aliases; it can happen any time two fields at the same level both async-fail. So eg, taking your example and replacing the constructor call with 

```ts
const server = new ApolloServer({
  typeDefs: `
    type Query {
      entity: Boolean!
      entity2: Boolean!
    }
  `,
  resolvers: {
    Query: {
      entity: async () => {
        throw new Error('Some error occured');
      },
      entity2: async () => {
        throw new Error('Some other error occured');
      },
    },
  },
});
```

and using the query `{entity entity2}` has the same issue.

I think this is just because [graphql-js uses Promise.all to run multiple Promise-returning fields on the same object in parallel](https://github.com/graphql/graphql-js/blob/7f40198a080ab3ea5ff3e1ecc9bf7ade130ec1bf/src/jsutils/promiseForObject.js#L13) and [Promise.all can trigger multipleResolves when multiple arguments fail](https://github.com/nodejs/node/issues/24321). So this is just how multipleResolves works and there's not much we can do to improve that situation.
