### ISSUE TITLE
Error: [typeName].[fieldName] defined in resolvers, but not in schema

### ISSUE THREAD

**Issue by robguida** [apollographql/apollo-server#5054]
I am new to Apollo/GraphQL and am getting an error that I cannot figure out. I have been looking online for about 1/2 hour so far, and not finding much. So, I am posting the errors in hopes someone can help me through this.

Here is the code:

**Resolver**
```
const { User, UserPasswordReset } = require('../../database/models');

module.exports = {
    Mutation: {
        async passwordReset(root, {input}, context) {
            const {email} = input;
            const user = await User.findOne({where: {email}});
            if (user) {
                return UserPasswordReset.create({user_id: user.user_id});
            }
            throw "No user found for email: '" + email + "'.";
        }
    },
};
```

**Schema**

```
const {gql} = require('apollo-server-express');

module.exports = gql`
    type UserPasswordReset {
        user_id: Int!
        security_key: String!
        date_expire: String!
        date_created: String!
    }

    extend type Mutation {
        passwordReset(input: PasswordResetInput!): PasswordResetResponse
    }
    
    input PasswordResetInput {
        user_id: Int!
    }

    type PasswordResetResponse {
        user_id: Int!
        security_key: String!
        date_expire: String!
        date_created: String!
    }
`;
```
I am hoping someone can point out why I am getting this error.

**Comment by robguida** [comment]
I did fix one issue, but still getting the same result. In the schema I had:
```
input PasswordResetInput {
        user_id: Int!
}
```
However, the function requires email, so I changed the code:
```
    input PasswordResetInput {
        email: String!
    }
```

**Comment by glasser** [comment]
Hi @robguida. Unfortunately, it turns out that just providing snippets of code is usually not enough for me to figure out what your problem is. What I need is a series of instructions that allow me to see the issue without needing to be creative at all. Generally these instructions start with `git clone` or use something like codesandbox.io. The instructions should also show how you need to interact with the server to cause the problem (if that's required) and show the exact error you're seeing. I'm happy to reopen this issue if you provide this full reproduction recipe!

**Comment by glasser** [comment]
Perhaps #2656 is relevant.

**Comment by robguida** [comment]
Thanks this helps. You can close this out.
