### ISSUE TITLE
'sendVariablesValues.exceptNames' reporting option GraphQL input fields is not working

### ISSUE THREAD

**Issue by c4c1us** [apollographql/apollo-server#5059]
Hi,

First of all, Apollo is great, big fan !

But I'm having an issue regarding the *sendVariablesValues.exceptNames* options of the report engine. The option works well on query parameters but not on *GraphQL Input fields*.

I'm using `apollo-server` and `@apollo/gateway`, the code below is from my gateway and the query is implemented in one of my services.

### Dependencies
`"apollo-server": "^2.21.2"`

### Code
```js
const server = new ApolloServer({
    gateway,
    engine: {
            apiKey: APOLLO_KEY,
            sendVariableValues: {
              exceptNames: ["biography"]
            }
          },
   ...
});
```

### Query
```graphql
mutation userUpdateProfile($input: UserUpdateProfileInput!) {
  userUpdateProfile(input: $input) {
    biography
  }
}
```

### Schema
```graphql
...
input UserUpdateProfileInput {
  ...
  biography: String
  ...  
}
```

### Actual Behaviour
Operation trace on Apollo Studio

<img width="661" alt="Screenshot 2021-03-25 at 17 12 09" src="https://user-images.githubusercontent.com/20277610/112505714-558ad880-8d8d-11eb-8aa8-238e78bed710.png">

### Expected Behaviour

```json
{
  "input":{}
}
```

**Comment by glasser** [comment]
The name of your variable is `input`.

`biography` is not a variable name: it's an input field name.

I do agree that wanting to filter based on input field names is reasonable, but it's not directly supported by the API. You can implement it yourself with the `transform` option.  One of our internal servers actually does that. At the very least it would be a nice thing to add to the examples in the docs, or as a separate package that people can import to generate `transform` functions (perhaps not actually part of the Apollo Server project).

**Comment by c4c1us** [comment]
Hi,

Thanks for your reply, okay I understand it's not a bug.

I tried to use the `transform` option. Unfortunately when I used it, the data sent from the gateway to my services is transformed too.

### Code
![Screenshot 2021-03-25 at 20 19 24](https://user-images.githubusercontent.com/20277610/112531353-c212d100-8da7-11eb-939b-9372e7235f3e.png)

### Playground
![Screenshot 2021-03-25 at 20 23 40](https://user-images.githubusercontent.com/20277610/112531574-069e6c80-8da8-11eb-99eb-441b4bc3dbac.png)

**Comment by c4c1us** [comment]
Maybe I should create an issue on the @apollo/gateway repository @glasser  ?

**Comment by glasser** [comment]
Oof, that is surprising. I don't think it's specific to the gateway, though.

Specifically, what's going on is that you're mutating stuff nested under the `variables` argument in your `transform` callback. This happens to be the same value used internally to actually execute the query (whether via gateway or direct execution).

I'm not sure of the best thing to do here. We can always do some sort of deep clone operation on `variables` before passing to the callback, but that can have a performance impact, and if you somehow have something in your `variables` that isn't easily cloneable (not sure how likely this is) then that can cause its own problems. Another alternative would be to just more clearly document that the transform operation should regard `variables` as read-only (perhaps in TypeScript using something like the workarounds at https://github.com/microsoft/TypeScript/issues/13923)

For your own code, you can change the assignment line to:

```
variables.input = {...variables.input, biography: "HIDDEN"};
```

(It's OK to mutate fields on `variables` itself because you've already copied it above.)

I'll open an issue about this.

**Comment by glasser** [comment]
See #5060 and #5061.

**Comment by c4c1us** [comment]
Understood ! Thank you for your answer !
