### ISSUE TITLE
CDN is broken for GraphiQL package

### ISSUE THREAD

**Issue by kchang409** [apollographql/apollo-server#506]
Hi guys,
The [CDN link](https://unpkg.com/graphiql@0.11.2/graphiql.min.js) for GraphiQL package seems to be broken and does not work. Although I'm not sure if this happens only on my end, I'm using [graphiql-app](https://github.com/skevy/graphiql-app) as an alternative for now.

**Comment by shoaibmerchant** [comment]
Yep there is some issue, I am facing a different error with this file

```https://unpkg.com/react-dom@15.6.1/dist/react-dom.min.js```

At the EOF you will find a 'ret' token, that is resulting in a syntax error

**Comment by pukapukan** [comment]
https://github.com/facebook/react/issues/10465

**Comment by stubailo** [comment]
Sounds like we should link to a specific version instead of `@15` to avoid this issue! Anyone want to file a PR to update that?

**Comment by pukapukan** [comment]
you can use //unpkg.com/react-dom@15.6.0/dist/react-dom.min.js inside /node_modules/apollo-server-module-graphiql/dist/renderGraphiQL.js as a quick workaround.

**Comment by stubailo** [comment]
Looks like that wouldn't fix it: https://github.com/unpkg/unpkg-website/issues/54

**Comment by pukapukan** [comment]
The file on CDN is up again.

**Comment by stubailo** [comment]
OK let's have any future discussion on #295

**Comment by sunwukonga** [comment]
This can also occur if you're sending authorization headers on your browser as you access the /graphiql endpoint. unpkg.com objects to the authorization header and rejects the request.

Since I use auth headers to identify the caller to my endpoint and I still want to test that through graphiql, I did the following:

1. Turn off the extension that was setting auth headers.
2. Access the unpkg.com resources that were being rejected (putting it into the cache).
3. Turn extension back on. Fixed.

The only reason this popped up for me was because I cleared my browser cache.
