### ISSUE TITLE
onHealthCheck not available in apollo-server-express

### ISSUE THREAD

**Issue by david-wb** [apollographql/apollo-server#5096]
The title says it all.  `ApolloServerExpressConfig` does not have an `onHealthCheck` property while the standalone config does. This is a bug right? I'm using `apollo-server-express` version 2.22.2.

Thanks

**Comment by glasser** [comment]
`onHealthCheck` is an argument to `applyMiddleware` in `apollo-server-express` rather than the constructor. (It's in the constructor for `apollo-server` because that package takes care of the equivalent of `applyMiddleware` for you.)

This is not particularly documented well. In fact in general, we do a bad job of documenting all of the different package APIs fully accurately (despite the fact that, about the same number of projects use `apollo-server-express` directly as use `apollo-server`). I'm hoping to overhaul our docs as part of our current work on Apollo Server 3; see https://github.com/apollographql/apollo-server/issues/5097
