### ISSUE TITLE
Documentation Request: Meteor Integration on Apollo Server Docs

### ISSUE THREAD

**Issue by ginglis13** [apollographql/apollo-server#5202]
While looking into contributing to apollo-server documentation, I was told by a mod in the discord channel and was pointed to  https://www.apollographql.com/docs/apollo-server/integrations/middleware/ as a potential spot for contribution. I notice there is no article for integrating with Meteor in the server docs, but there is in the React client docs here, with examples and documentation for both client and server integration with Meteor: https://www.apollographql.com/docs/react/v2/integrations/meteor/

Would it be worthwhile to add the server side documentation from the client docs to the server docs? I would be happy to work on this if this addition is appropriate.

**Comment by glasser** [comment]
I think this might be something that would fit better in Meteor's docs, perhaps with a link from Apollo Server? As far as AS is concerned Meteor is just another Node server platform, albeit one that unfortunately still uses the otherwise-barely-used `connect` web framework. We have been trying to keep `apollo-server-express`'s Connect support working for Meteor's sake, but I'm not sure it warrants a major section in the docs to maintain.
