### ISSUE TITLE
formatResponse(response, options)  field options.context.request is undefined

### ISSUE THREAD

**Issue by TheEhsanSarshar** [apollographql/apollo-server#5261]
## I want to access the request URL inside formatResponse handler.
```Javascript
const server = new ApolloServer({
  // schema, context, etc...
  formatResponse: (response, options) => {
    const parsed = url.parse(options.context.request.url);
    const query = querystring.parse(parsed.query);

    if(query.crunch && response.data) {
      const version = parseInt(query.crunch) || 1;
      response.data = crunch(response.data, version);
    }

    return response;
  },
});
```
but the request field is undefined inside `const parsed = url.parse(options.context.request.url);`
even typescript complains about it.

**Comment by ecerroni** [comment]
If you are using `apollo-server-express` you may do the following:

```
import url from 'url';
import querystring from 'querystring';
import { crunch } from 'graphql-crunch';

const server = new ApolloServer({
  // schema, context, etc...
  formatResponse: (response, options) => {
    const { context } = options;
    const { res, req: request } = context; // if you need to set headers/cookies you need to use "res", not "response"
   
    const parsed = url.parse(request.url);
    const clientQuery = querystring.parse(parsed.query);
    if (clientQuery.crunch && response.data) {
      const version = parseInt(clientQuery.crunch, 10) || 1;
      response.data = crunch(response.data, version);
    }

    return response;
  },
});
```

This is working for me on my setup using `apollo-server-express`.

However, if you're using apollo core or any other integration package (koa, hapi, etc.) the above code will not work because, unfortunately, every integration has is own set of params (response, context,) etc, for `formatResponse` function. Indeed you would have to figure out yourself how that is handled :+1:

**Comment by TheEhsanSarshar** [comment]
still not working the `req` is undefined.
I am using apollo-server-express

**Comment by TheEhsanSarshar** [comment]
Ok, I fix it by manually adding the request to the context. on the apollo server context handler
