### ISSUE TITLE
Audit Issue in apollo-server-koa

### ISSUE THREAD

**Issue by singhs020** [apollographql/apollo-server#5273]
Hey Team,

I am using apollo-server-koa in one of my projects and recently an audit check failed on the ws package which is a deep dependency of this package. Following is the trace:

```
# npm audit report

ws  5.0.0 - 6.2.1 || 7.0.0 - 7.4.5
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1748
fix available via `npm audit fix --force`
Will install apollo-server-koa@1.4.0, which is a breaking change
node_modules/subscriptions-transport-ws/node_modules/ws
  subscriptions-transport-ws  >=0.9.10
  Depends on vulnerable versions of ws
  node_modules/subscriptions-transport-ws
    apollo-server-core  2.0.0-beta.0 - 2.25.0
    Depends on vulnerable versions of subscriptions-transport-ws
    node_modules/apollo-server-core
      apollo-server-koa  2.0.0-beta.5 - 2.25.0
      Depends on vulnerable versions of apollo-server-core
      node_modules/apollo-server-koa

```

version of apollo-server-koa is: v2.25.0

**Comment by Amine27** [comment]
The same for apollo-server-express (apollo-server-express > subscriptions-transport-ws > ws).

**Comment by glasser** [comment]
We are removing Apollo Server's superficial integration with the unmaintained `subscriptions-transport-ws` package in Apollo Server 3.0, which we hope will be released this month. (We will recommend using the maintained `graphql-ws` package with AS3 instead.) Our time is being spent on getting that out instead of figuring out if it's easy to upgrade `subscriptions-transport-ws` to a more secure `ws` version.  I would review a PR to subscriptions-transport-ws that upgrades `ws`, though. In the meantime I suggest you avoid using the built-in AS subscriptions integrations (eg pass `subscriptions: false` to `new ApolloServer`) and use `graphql-ws` instead, though that won't fix your `npm audit`.

**Comment by glasser** [comment]
You can now upgrade to `ws@5.2.3` which has the security fix with no major version changes. Alternatively, you can upgrade to `subscriptions-transport-ws@0.9.19` which allows you to use `ws` 6 or 7; Apollo Server v2.25.1 updates all relevant dependencies.

**Comment by singhs020** [comment]
Thanks @glasser
