### ISSUE TITLE
[apollo-server-fastify] alpha version broke for preview version.

### ISSUE THREAD

**Issue by tkow** [apollographql/apollo-server#5278]
```shell
yarn: 1.22.10
```
If you using apollo-server-fastify@3.0.0-alpha.x, the apollo-server-fastify has dependency like this in package.json:

```
"apollo-server-core": "^3.0.0-alpha.3",
```

Thus, this resolve "version": "3.0.0-preview.0" maybe because 'p' is latter against 'a' and causes crush.
If we use alpha version, need migration to preview version because alpha version of apollo-server-fastify can't resolve apollo-server-core preview version api, or fix  version dependency as const.

![スクリーンショット 2021-06-05 21 40 34](https://user-images.githubusercontent.com/7004725/120892308-9aae6f00-c648-11eb-9dbc-305890118175.png)

I think it really widely affects many users to stop developing, so I want you to deploy new alpha version asap as based alpha 3 version or alpha 4 version with exact flag.

https://github.com/lerna/lerna/pull/426

[Current Solution]

If you use yarn, add such resolutions fields values to package.json.
```
 "resolutions": {
    "apollo-server-fastify/apollo-server-core": "3.0.0-alpha.4"
  }
```
and edit your yarn. lock file to exact version if it has version value as preview version.

**Comment by tkow** [comment]
@glasser

Could you check this?

**Comment by glasser** [comment]
Yeah, you should switch over to `preview` instead of `alpha`.

I first made some `alpha` prereleases. These packages depend on other Apollo Server packages with deps like `^3.0.0-alpha.3`.

As part of some other testing (not intended for broad use) I published some `html` and `lambda` prereleases. I did not realize that `^3.0.0-alpha.3` would match `3.0.0-lambda.2`! (Seems like poor design on npm's fault. Oh well.) This meant that users of `alpha` could end up accidentally pulling in these half-baked `html` and `lambda` prereleases.

So now I'm publishing `preview` releases instead. I suggest switching to preview from alpha.

I realize that Nest is suggesting that folks use our alphas from their production docs, which is an interesting choice. Hopefully 3.0.0 will be out quite soon and this will no longer be a concern.

**Comment by hayesmaker** [comment]
why is this closed? I've just installed the latest version and it's not working

`    "apollo-server-fastify": "^2.25.1",`

**Comment by glasser** [comment]
We use issue status to track when the work has concluded, not when it has been released.  `apollo-server-fastify` v2 does not support Fastify v3. AS v3 will, but has not yet been released.
