### ISSUE TITLE
Type error for ApolloServer with express app using @types/express@4.17.12

### ISSUE THREAD

**Issue by MJez29** [apollographql/apollo-server#5280]
**Package:** `apollo-server-express`
**Version:** `2.25.0`

I upgraded my `@types/express` package from `4.17.11` to `4.17.12` and now I get the following type error (which previously did not occur)

```
index.ts:12:26 - error TS2322: Type 'Express' is not assignable to type 'Application'.
  Types of property 'get' are incompatible.
    Type '((name: string) => any) & IRouterMatcher<Express, any>' is not assignable to type '((name: string) => any) & IRouterMatcher<Application, any>'.      
      Type '((name: string) => any) & IRouterMatcher<Express, any>' is not assignable to type 'IRouterMatcher<Application, any>'.
        Types of parameters 'name' and 'path' are incompatible.
            Type 'RegExp' is not assignable to type 'string'.

12 server.applyMiddleware({ app });
                            ~~~

  node_modules/apollo-server-express/dist/ApolloServer.d.ts:15:5
    15     app: express.Application;
           ~~~
    The expected type comes from property 'app' which is declared here on type 'ServerRegistration'


Found 1 error.
```

I created a basic example of the error here: https://github.com/MJez29/apollo-express-bug

**Comment by glasser** [comment]
We've had a *lot* of problems with the fact that the DefinitelyTyped packages for Express consists of multiple separate packages (notably `@types/express` and `@types/express-serve-static-core`) and that new versions of `@types/express` don't work unless you update `@types/express-serve-static-core` too but that the dependencies between them are not declared tightly enough. (Until recently it was just a `*` dependency; they had [one PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50554) that set a minimum dependency but haven't updated it since.

When I try your (excellent) reproduction, I'm able to get the `tsc` command to work if I add `npm dedup` before it. (You may want to also explicitly install the newest version of `@types/express-serve-static-core` in your app before deduping.) Does that work for you?

I wish I knew of a better way to work around "one of our dependencies has a bad habit of not updating its dependency version range when it matters". Please let me know if you have any advice here!

**Comment by MJez29** [comment]
Ah cool I didn't know `npm dedup` was a thing, thanks!
