### ISSUE TITLE
Some variable-related errors should be BAD_USER_INPUT rather than INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-server#5353]
The function `coerceVariableValues` in https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts can throw several errors if the provided variable values aren't good.  These are all bad user input, not server bugs, so Apollo Server should throw them as UserInputError rather than internal server errors. Unfortunately `graphql-js` doesn't give a great way of differentiating these errors from errors in server code and so we treat them like internal server errors.

In #5091 we fixed one of these errors (`Variable "$${varName}" got invalid value`) to throw UserInputError but other errors like `Variable "$${varName}" of required type "${varTypeStr}" was not provided` and `Variable "$${varName}" of non-null type "${varTypeStr}" must not be null` still show up as internal server errors. See https://github.com/apollographql/apollo-server/issues/3498#issuecomment-863949816 for a codesandbox that demonstrates both issues. We should make them both into UserInputError.

**Comment by glasser** [comment]
#5091 shows how to fix issues like this with tests. PRs welcome!

**Comment by 5achinJani** [comment]
I can take this up.
```
Unfortunately graphql-js doesn't give a great way of differentiating these errors from errors in server code and so we treat them like internal server errors.
```
I couldn’t find any issue in [graphql-js](https://github.com/graphql/graphql-js/issues) related to providing a way to differentiate bad input user validation errors from other errors. Wouldn’t it be great if graphql-js provides us a code in extensions like :
```js
      onError(
        new GraphQLError(
          `Variable "$${varName}" of non-null type "${varTypeStr}" must not be null.`,
          varDefNode,
          undefined,
          undefined,
          undefined,
          undefined,
          {code:"BAD_USER_INPUT"}
        ),
```
(I confirmed it by making this change and checking e.extensions.code == "BAD_USER_INPUT" and returning UserInputError in requestPipeline.js file. it works )
This would save us the effort of matching all the possible validation related error strings from this file : 
https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts
like :
- [`Variable "$${varName}" expected value of type "${varTypeStr}" which cannot be used as an input type.`,](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L90)
- [`Variable "$${varName}" of required type "${varTypeStr}" was not provided.`,](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L104)
- [`Variable "$${varName}" of non-null type "${varTypeStr}" must not be null.`](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L117)
- [`Variable "$${varName}" got invalid value ` + inspect(invalidValue);](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L129) - we've already handled this.

And I'm not if we also need to handle the errors coming from [getArgumentValues](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L160) cause they too look like bad user input errors :
- [Argument "${name}" of required type "${inspect(argType)}" was not provided.](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L181)
- [Argument "${name}" of required type "${inspect(argType)}" was provided the variable "$${variableName}" which was not provided a runtime value.](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L202)
- [Argument "${name}" of non-null type "${inspect(argType)}" must not be null.](https://github.com/graphql/graphql-js/blob/main/src/execution/values.ts#L214)

Let me know you inputs on this.
And if we want to go with the #5091 's way to handle this then would it be okay if we check for static error sentences in the error string like :
For error string : "Variable "$${varName}" of non-null type "${varTypeStr}" must not be null"
Code. : 
```js
if(e.message.includes(`Variable`) && e.message.includes(`of non-null type`) && e.message.includes(`must not be null`)
```
Reason for doing this instead of fetching the varName and varTypeStr and replacing it and then matching the string is figuring out the varTypeStr would be tricky. it can be of type array, string, or custom type.

**Comment by glasser** [comment]
I think for the long term it would be great if graphql-js had more machine-parseable errors (presumably adding something on `extensions`); if you open an issue over there, link it here!

In the short term we should probably do something like #5091 so we can make progress. The main reason I feel comfortable with #5091 is that it does have a test so we will learn if new graphql-js versions change the error messages. I do also like how we link together the node from the error to the error message...

I don't think we have to worry about the errors in `getArgumentValues` because those cases should all be caught either in the validation step (which compares an operation to the schema without paying attention to variable values) or in `getVariableValues`:

- required argument not provided should be caught by validation
- required argument provided a variable without a value either means the variable was declared nullable (in which case validation should fail because you can't use a nullable variable for a required argument) or it was declared non-nullable (in which case getVariableValues should have failed)
- argument of non-null type must not be null means either a null value is passed in the operation itself (validation failure) or we pulled a null value out of the variables map (same problem as previous bullet)

Note that right now, active development is being done on `release-3.0` rather than `main` (it should be merged in the next week or two).

**Comment by 5achinJani** [comment]
Hey @glasser I've linked a PR do let me know if there are any changes to be made in it. :)
