### ISSUE TITLE
Fastify - Provide an option to expose the playground under a different path

### ISSUE THREAD

**Issue by StarpTech** [apollographql/apollo-server#5370]
As titled. This makes it possible to differentiate the playground on the proxy to enable authentication.

**Comment by glasser** [comment]
So when I started to build this new landing page API for AS3, my original version allowed plugins to host multiple different HTML pages at different paths.

Unfortunately this turned out to be very untenable due to the complexity of supporting so many different web frameworks, all of which have slightly different router implementations, and including the fact that when integrating with your web framework you can opt to host your Apollo Server middleware at a sub-path without informing Apollo Server about that fact.  Fastify actually was one of the most challenging: as far as I can tell you can't actually use its router in a way that's sensitive to the `accept` header without adding a new "constraint" type which can only happen at the top level of your Fastify object (which AS doesn't control).  That's why the API I ended up with is path-agnostic.

That said, the whole idea of this landing page API is to be easy to set up, not necessarily to be flexible. It's not hard to use https://github.com/graphql/graphql-playground directly from your Fastify web app alongside Apollo Server if you'd like to do something more complex than the basic path-agnostic behavior provided by Apollo Server.

**Comment by StarpTech** [comment]
Do we talk about the same? I propose to expose the playground under a different route. That route path can be configured.

```js
 app.register(server.createHandler({
    playgroundPath: '/playground'
}));
```

> It's not hard to use graphql/graphql-playground directly from your Fastify web app alongside Apollo Server if you'd like to do something more complex than the basic path-agnostic behavior provided by Apollo Server.

There is no option to disable only the playground https://github.com/apollographql/apollo-server/blob/09dbe3e7029ea3ccdf16538699848f08bbed3904/packages/apollo-server-fastify/src/ApolloServer.ts

**Comment by glasser** [comment]
Still in the process of getting docs finalized (see eg #5363), but in Apollo Server 3 we've replaced "you can only use GraphQL Playground (a 'retired' project) or nothing" with a simple landing page plugin API (which defaults to a splash page).  To disable landing pages you can do:

```js
import { ApolloServerPluginLandingPageDisabled } from 'apollo-server-core';
new ApolloServer({plugins: [ApolloServerPluginLandingPageDisabled()]});
```

**Comment by StarpTech** [comment]
This doesn't solve my issue because we use Apollo 2.
