### ISSUE TITLE
Silent Error on Schema/GQL Parameter Mismatch

### ISSUE THREAD

**Issue by VikR1000** [apollographql/apollo-server#539]
The other day I had a parameter mismatch (param names and also the number of params) between the schema and the relevant GQL.  The system understandably failed to activate the resolver. I noticed no error message in the browser console or the server console. An error message in this circumstance could be helpful.

**Comment by abernix** [comment]
I'm going through and trying to cleanup some older issues which may no longer be problematic.  There's been a number of changes to Apollo Server since this was opened, and this doesn't appear to be continually affecting anyone.  That said, if you're still having problems, please feel free to ping back or open a new issue with a reproduction (preferably a runnable CodeSandbox/Glitch or GitHub repository which can be easily cloned and debugged!)
