### ISSUE TITLE
apollo-server-express - Apollo federation adaption

### ISSUE THREAD

**Issue by RelentlessExploration** [apollographql/apollo-server#5454]
Recently I've been working on a [project](https://github.com/RelentlessExploration/Your-Doge) that needs to use apollo federation to distribute servers and apollo-server-express to handle incoming authentication requests that can't be done without express.

After deciding to use apollo federation in the first place, I started looking for related integrations with apollo-server-express, and after watched the video/read through the blog by @mandiwise, and done some testing, I realized apollo-server-express could only be used as the gateway server, and not the services linked in the `serviceList` attribute of the gateway(always got 404 or host:port/graphql: 400 bad request).

Now I'm stuck because I do really need to use apollo-server-express for one of my servers. I hope you could consider adding such functionality to the express integration as this is a crucial part in my project and I believe more people would benefit from it as well.

**Comment by glasser** [comment]
I'm not sure what you mean by this. apollo-server-express works fine for a subgraph server. What led you to believe otherwise?

In AS v3 (on the verge of being fully released) we've improved the docs which explain the difference between the different top level packages: https://www.apollographql.com/docs/apollo-server/v3/integrations/middleware/
Does this help?

**Comment by RelentlessExploration** [comment]
Thank you for your response and assistance, I just solve the issue. I did not specify the path when applying the app middleware.
