### ISSUE TITLE
Remove dependency on `util.promisify`

### ISSUE THREAD

**Issue by alfaproject** [apollographql/apollo-server#5478]
Given that we only support newer versions of node, I don't believe this is still needed?

https://github.com/apollographql/apollo-server/blob/1de9af077bf0c992dd5a82d8ef48bc47dc8afbe7/packages/apollo-server-env/src/index.ts#L7

**Comment by glasser** [comment]
@abernix Thoughts? @alfaproject is correct that this shim isn't needed on any version of Node we currently support in AS3.

On the other hand, I think we vaguely attempt to support non-Node environments for some of our code?

On the other other hand, it looks like `promisify` is only used in `apollo-server-cache-memcached`. So if we remove this, we only break people trying to use `apollo-server-cache-memcached` in non-Node environments, and in that case they can just use the util.promisify shim themselves?

**Comment by alfaproject** [comment]
Yes, I don't think it should be in core because that shim imports a few other dependencies. `apollo-server-cache-memcached` could even just do a simple promise wrapper instead of needing that utility method anyway. It's 3 lines of code maximum.

**Comment by abernix** [comment]
@glasser I'm quite supportive of removing it in lieu of either some treatment within `apollo-server-cache-memcached` or just removal and put the burden on non-Node.js environment users (they typically require a bundler, anyhow).  It's been a while since I took this on, but I'd even claim that the continued inclusion is an oversight on my part in the upgrade to support only newer Node.js versions.  Perhaps our Node.js minimum version changed between the time that that initiative was taken on and when we actually released.

Overall, I'd be somewhat surprised if non-Node.js + Memcached was a popularized cohort.  I'd vote for removing it and I think we should get this into a 3.x bugfix ASAP.
