### ISSUE TITLE
ApolloServerPluginUsageReporting export/import

### ISSUE THREAD

**Issue by nmaves** [apollographql/apollo-server#5499]
Should `ApolloServerPluginUsageReporting` be exported from the `apollo-server` module?

I don't see why this should be excluded considering it is how apollo makes money :)

**Comment by glasser** [comment]
Hi @nmaves!

`apollo-server` is one of several entry points to Apollo Server; it's the "batteries-included" version, but there are also other entry points for different web frameworks, serverless environments, etc. See https://www.apollographql.com/docs/apollo-server/integrations/middleware/

Over time we found that maintaining the top level exports of all these packages to make them identical is a fair amount of overhead! So when we introduced the `ApolloServerPlugin*` plugins in v2.18, we decided that users should just import them directly from `apollo-server-core` where their code lives, instead of us carefully copying the list of every plugin into `index.ts` in the 10 entry point packages.  There are 24 functions and types now exported from the 'plugin' part of `apollo-server-core`... (Perhaps it would have been simpler to export a single `Plugins` object with the other plugins dangling off of it, but that's not the API we came up with.)

Did you find docs encouraging you to use `ApolloServerPluginUsageReporting` that don't make it clear you need to import it from `apollo-server-core`?

**Comment by nmaves** [comment]
Hey @glasser !  Thanks for the quick response.

The docs were clear as to which module it was located in.  I think the issue is with tools/IDEs.  I use Webstorm for development.  It tries to be clever and warns you when it sees an import from a module that you don't directly include as a dependency in your package.json.   Of course, I can add the `apollo-server-core` as a dependency and the warning will go away.  That feels like more of a peer dependency than what it really is.  

Maybe a better choice would have been to keep the `ApolloServerPluginUsageReporting` plugin in its own package or a `apollo-server-plugins` package.


Just my two cents.

**Comment by glasser** [comment]
Yeah, you should depend on `apollo-server-core` too.

We've found that the proliferation of packages in Apollo Server is more of a hindrance than a help; people end up accidentally getting multiple versions of packages installed more often due to how many helper packages we already have. We got rid of 4 helper packages in AS3 and hope to cut down more in the future.
