### ISSUE TITLE
What exactly is a connector for makeExecutableSchema?

### ISSUE THREAD

**Issue by GBcrazy** [apollographql/apollo-server#554]
My text editor's intellisense is telling me there's a connector property between resolvers and logger in the IExecutableSchemaDefinition

However, the docs at this moment do not mention it at all:
http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#makeExecutableSchema

What it does exactly?

**Comment by stubailo** [comment]
@GBcrazy it's deprecated, but essentially it was a thing that would attach "connectors" - classes used to fetch data - to your context. Similar to this idea: http://dev.apollodata.com/tools/graphql-tools/connectors.html#Factoring-out-fetching-details or this: https://github.com/apollographql/graphql-tools/blob/master/designs/connectors.md

But it turns out it's not that hard to attach stuff to context yourself, like this:

https://github.com/apollographql/GitHunt-API/blob/02269574b0ceef5a46e2b142ca62242951727dc9/api/server.js#L112-L119

**Comment by stubailo** [comment]
BTW, `makeExecutableSchema` is from `graphql-tools`: https://github.com/apollographql/graphql-tools
