### ISSUE TITLE
Catch subscription errors to log them in production

### ISSUE THREAD

**Issue by Mrtblg** [apollographql/apollo-server#5556]
Using version `2.23.0`

It would be great to have a callback function on any subscription error (js error, graphql schema error...) to provide easy production monitoring and alerting in case of bug.

On normal http requests we use plugins :

```javascript
requestDidStart({ context, request }) {
    return {
        didEncounterErrors({ errors }) {
            // log errors here
```

but this doesn't work for subscriptions.

After some research i suggest to add a `onError` param here : https://github.com/apollographql/apollo-server/blob/8a4cc583b692a30670d1893c01851259dbd70ce1/packages/apollo-server-core/src/ApolloServer.ts#L925

then invoking it here with `error` as a parameter :
https://github.com/apollographql/apollo-server/blob/8a4cc583b692a30670d1893c01851259dbd70ce1/packages/apollo-server-core/src/ApolloServer.ts#L988

And here update the interface : https://github.com/apollographql/apollo-server/blob/8a4cc583b692a30670d1893c01851259dbd70ce1/packages/apollo-server-core/src/types.ts#L56

How about this ?

**Comment by Mrtblg** [comment]
Note that I'm not satisfied with the workarround that would be to log them through `formatError` because :
* It's kind of dirty, not the right place to do it
* I can't separate normal requests errors from subscription errors here

**Comment by trevor-scheer** [comment]
Hi @Mrtblg, unfortunately in AS2, subscription support is somewhat bolted on and completely unintegrated in the request pipeline. We'd like to improve this in the future, but for now we've chosen to remove the "built-in" support in AS3 and instead provide documentation on how to "bring your own". This approach should provide the flexibility you're looking for here, since creating the `SubscriptionServer` is handled by you. We recently published a [migration guide](https://www.apollographql.com/docs/apollo-server/migration/) and updated our [subscriptions docs](https://www.apollographql.com/docs/apollo-server/data/subscriptions/) which should help you to make the switch.

Once you have access to the `SubscriptionServer` instance yourself, you have control over things like error handling.

In the future we'd like to provide 1st party support for subscriptions that plays nice with the request pipeline and just works. In the meantime, we feel this is a better solution than what was offered in AS2 primarily due to versioning concerns and configurability.

**Comment by Mrtblg** [comment]
@trevor-scheer thank you for your fast answer, I'm going to look into migrating to Appollo V3 👍
