### ISSUE TITLE
Cannot activate apollo-tracing

### ISSUE THREAD

**Issue by itpropro** [apollographql/apollo-server#5561]
I am using `"apollo-server-azure-functions": "^3.1.1",` and need traces to identify the duration of specific resolvers. Since v3 the apollo-tracing plugin was removed and I don't see any alternative for local graphs (running in development on localhost).
I tried with apollo studio, but metrics are not supported by dev graph in apollo studio and inline tracing isn't available in the "new" playground.
So I tried to use the workaround from the apollo documentation to get the old plugin to work (`require("apollo-tracing").plugin(),`).
I installed the `apollo-tracing` npm packet manually, but there I have found no way to activate tracing again, as `tracing: true,` is not available anymore and I have not found any documentation on the plugin constructor of this plugin.
Can anyone provide some guidance on how to enable tracing in local running GraphQL since v3?
Thanks!

**Comment by glasser** [comment]
The JSON trace format is pretty inefficient and was designed for an obsolete tool called engineproxy. I think your first instinct of seeing if Apollo Studio supports the current inline trace format was a good one, and it looks like the "Show inline traces" feature of Explorer is disabled by accident in Sandbox. I've reached out to the Studio team and I think we should be able to get the "Show inline traces" toggle added to Sandbox pretty quickly.

**Comment by itpropro** [comment]
Thanks for the reply, I totally understand the inefficiency of the old trace format, but unfortunately, there are hardly any information out there, how to get inline traces to work locally with the new parser. I only found the instructions for apollo studio, which doesn't support dev graphs for metrics.
If you have any guidance for local setup (as soon as the switch is available in the playground again) e.g. with the `APOLLO_KEY` and `APOLLO_GRAPH_REF` env variables, I would be very thankful :)

**Comment by glasser** [comment]
Hi @itpropro. Apollo Sandbox (https://studio.apollographql.com/sandbox) now lets you turn on inline tracing support. Do you think this serves your needs?

![image](https://user-images.githubusercontent.com/16724/128092982-4f1e0985-1d3c-4ff5-96eb-241c5358c2da.png)

Specifically, this is for letting you run a single operation and immediately see its trace. If you're just talking about general observability where you can get an aggregated look at all the operations running through your graph, I'd suggest you just use a deployed graph on Studio rather than a dev graph.  (Honestly I personally think that the newer "Sandbox" solves more or less the same problem that "dev graphs" were designed for (letting you play with a local graph without needing to create a permanent fully shared graph in the registry) and I don't personally know if there's much of a use case for dev graphs any more. This is just my personal intuition and not necessarily the opinion of the Studio team though!)

**Comment by itpropro** [comment]
Hey @glasser, thanks for the update! Seeing the trace for a single operation is exactly what I need. If you can provide a short guidance on how to view the trace or how to configure apollo server in addition to the plugin part that would be great. I turned on the switch in the sandbox, but there is no trace view visible. Here is my current config:

```typescript
const server = new ApolloServer({
  schema,
  dataSources,
  context,
  debug: true,
  introspection: true,
  cache,
  plugins: [responseCachePlugin(), ApolloServerPluginInlineTrace()],
});
```

**Comment by glasser** [comment]
That should work! After you run an operation, click where it says "Response" on the top right and select "Traces" instead.

![image](https://user-images.githubusercontent.com/16724/128095872-7a15cdf9-38b5-4b8b-ac65-80ea60e4862e.png)

**Comment by itpropro** [comment]
Thank you very much, I wasn't aware of that dropdown. The old playground had just another item to the right. Thanks again for the sandbox fix!
