### ISSUE TITLE
Cache control response extension in v3

### ISSUE THREAD

**Issue by shotor** [apollographql/apollo-server#5604]
I'm upgrading from v2 to v3 and read in the migration guide:

> Apollo Server 2 would include a cacheControl response extension inside your GraphQL response. This was used by the deprecated engineproxy server. Support for writing this response extension has been removed from Apollo Server 2. This allows for a more memory-efficient cache control plugin implementation.

Just to be sure: This means that v3 will never send out cache hints in the response body?

If so, is there any way to get the cache control hints back in the response in v3? We rely on them in parts of our application

**Comment by glasser** [comment]
Specifically, you want to know on a per-field level what hints have been set?

For performance reasons we decided to remove this in AS3, but there still is testing-specific code that can optionally build them up. I think we could take a PR to have an *opt-in* way of providing access to the full cache hint map (which is currently in `__testing__cacheHints` in `packages/apollo-server-core/src/plugin/cacheControl/index.ts`). I'm not sure the best place to store them: I suppose we can stick them back on the response extension like we used to, but I think it make more sense to put them somewhere on the request context (and you can write a willSendResponse plugin to put them on a response extension if that's what you want). Maybe as `requestContext.context.cacheHints`, rather than it being a top-level field on `requestContext` that is only set if one particular option is passed?
