### ISSUE TITLE
Unit testing graphqlLambda callbackFilter passes with unhandled promise rejection instead of failed assertion

### ISSUE THREAD

**Issue by iwllyu** [apollographql/apollo-server#561]
I have a lambda `handler(event, context, callback)`  and a callbackFilter on graphqlLambda.

Everything works when unit testing the handler and having passing assertions in the callback. But, when I have a failing assertion, instead of failing the test case it passes it with a message saying 

>UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: expected 'myExpectedResult' to equal 'notmyExpectedResult'

So is the callbackFilter doing something to the lambda callback that causes it to reject with a promise? How can I catch this promise?

If I invoke the callback directly it fails the test as expected.

I have a sample project here - https://github.com/iwllyu/graphql-lambda-callback-filter-failure

**Comment by abernix** [comment]
This issue hasn't seen much in the way of reactions or additional feedback recently and there have been a number of releases in Apollo Server since this was opened, including many updates to `apollo-server-lambda`.  If this problem persists, please feel free to open a new issue with a reproduction.  (For what it's worth, there was [this recent blog post](https://blog.apollographql.com/deploy-a-fullstack-apollo-app-with-netlify-45a7dfd51b0b) on the Apollo blog about using `apollo-server-lambda` through Netlify functions (which deploys to AWS), so perhaps that might be helpful to anyone getting started).

Thanks for reporting this originally!
