### ISSUE TITLE
Mocks not returning results dynamically

### ISSUE THREAD

**Issue by yoont4** [apollographql/apollo-server#5615]
## Summary
Hi, I'm trying to create a super bare bones mock server, but I can't seem to get dynamic mock data to work. All documentation, videos, and examples I've seen from the last years show that returning a mock object with function values should change with each request, but I always get the same result.

I've verified that the network request is sent each time too. 

## Expected Behavior
Every time I run the query

```gql
query {
  person {
    random
  }
}
```

I should get a random number.

## Actual Behavior

I get the same value each time, and I only see 1 console log, even when querying multiple times.

## Repro Repo

https://github.com/yoont4/broken-apollo-mock

### Package Version

`apollo-server: 3.1.2`

**Comment by glasser** [comment]
The `mocks` argument in Apollo Server is actually just a convenient way of using the mocking support of the GraphQL Tools library's mock support without directly setting up that package; the details of how it works on the inside are entirely defined by `@graphql-tools/mock`.

I'm not an expert but my understanding is that this is working as intended: that as described in the [docs for `createMockStore`](https://www.graphql-tools.com/docs/api/modules/mock_src#createmockstore), the mock support "stores generated mocks, so that, provided with same arguments the returned values will be the same".

See also the full docs at https://www.graphql-tools.com/docs/mocking though I'm not sure they're very clear about how the mock store works. I don't know if there's an easy way to keep a particular field out of the mock store.  To learn more about `graphql-tools`, file an issue on [their repo](https://github.com/ardatan/graphql-tools) or contact that project in another way.

**Comment by yoont4** [comment]
I see, thanks for the info!
