### ISSUE TITLE
If tracing is enabled dynamically, requests without tracing fail

### ISSUE THREAD

**Issue by jlai** [apollographql/apollo-server#562]
In my app, I'd like to set the `tracing` flag based on the request, for example only enable tracing if a particular header is included, to avoid leaking internal timing details to the public and to cut out the extra response data.

The problem is that apollo-server modifies the schema to add instrumentation, and once instrumented, the wrapper resolvers fail if context._traceCollector is not present:

```
Cannot read property 'startHrTime' of undefined
    at instrumentedFieldResolver (/project/node_modules/apollo-tracing/lib/instrumentation.js:42:55)
    at resolveFieldValueOrError (/project/node_modules/graphql/execution/execute.js:501:12)
```

Some possible solutions:
1. Update `apollo-tracing-js` instrumentation to check if _traceCollector exists, and run the resolver without saving the timing if it doesn't
2. Keep both the original schema and the instrumented schema using some kind of memoization and select the appropriate one based on request's tracing flag. One benefit is that there's zero execution overhead if tracing is disabled, but you have to be careful about leaking memory if someone does something silly like passing a new schema object on every request.

**Comment by martijnwalraven** [comment]
Yes, I can see how it makes sense to allow tracing to be enabled on a per-request basis. (If you're using the new version of Optics that's currently in EA, you would be running a proxy server in front, and that would filter out the tracing data.)

I think 1) would definitely be the easiest solution, so maybe we should just go with that until we determine the overhead is actually an issue.

**Comment by abernix** [comment]
While I think this made more sense previously, in Apollo Server 2.0, the `apollo-tracing` package (which injected the tracing information into the response which was then stripped by Apollo Engine Proxy) is no longer enabled by default.  It has been superseded by `apollo-engine-reporting` which sends the information to Apollo Engine.

Happy to re-open if this is still a concern, but I'll close this for now since it hasn't got traction in quite some time.

Thanks for reporting this originally!
