### ISSUE TITLE
AuthenticationError returns 400 instead of 200

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [apollographql/apollo-server#5636]
Hello,

in your documentation you stating that best place to handle authentication is in context creation function. However, throwing AuthenticationError  there leads to response status code 400 (because of this: https://github.com/apollographql/apollo-server/blob/34322a6523c34d2bde65e63b5d733befe86322da/packages/apollo-server-core/src/runHttpQuery.ts#L126-L142). This response is not handled by different plugins like refresh token plugin in flutter because it expects to get 200. 
All idealogy of graphql states that GQL should have only 2 responses - 200 and 500.

It would be nice if you change it or provide bette, centric place to handle authentication

**Comment by glasser** [comment]
I think it would be reasonable that if an HttpQueryError is thrown by a context function, that it is used directly here instead of translating to "Context creation failed" with 400 or 500.  I think we'll keep AuthenticationError as not an HttpQueryError (for compatibility reasons if nothing else).  I'd review a patch to do this.

Alternatively, as described at https://github.com/apollographql/apollo-server/issues/3039#issuecomment-902851382, you can avoid throwing in `context` altogether.  Throwing HttpQueryErrors from `requestDidStart` works properly, I think! If I understand correctly, there's a reason that this publicly-visible error message contains kinda weird internal terminology like "Context creation failed" — it's that ideally this error case would be avoided entirely in the app.  (Yet another alternative is to do the fallible part of your context function in an earlier middleware that adds its output to the request or something on success, and just have `context` move that structure from the request to the context object.)

**Comment by vytautas-pranskunas-** [comment]
Hello, i think first approach would be the best because requestDidStart not work so well because I need to pass user data after verifying token. So last option also not good.
For now I duplicated express Middleware and substituting response code leaving throw inside context.
When do you think you can take a look at this issue?

**Comment by glasser** [comment]
As I said, I think this is a good candidate for an externally-contributed PR.

**Comment by vytautas-pranskunas-** [comment]
Ok i see.
I have tried approach that you mentioned in another comment with requestDidStart but then it returns status code 500 nut not 200

**Comment by vytautas-pranskunas-** [comment]
Regarding `candidate for external PR` - this means - it will never be done because Apollo is huge maitainer of this and i doubt that there are many people willing to do this. Otherways it would be already done...

**Comment by glasser** [comment]
I think this AS4 change should solve this issue: #6857

**Comment by glasser** [comment]
Fixed on version-4 in #6857.
