### ISSUE TITLE
TypeError is thrown with NODE_ENV=production and a validation rule defined

### ISSUE THREAD

**Issue by LucasLongarini** [apollographql/apollo-server#5692]
### Package name/version
`Apollo-server-core: 3.3.0
`
### The Problem
When running Apollo-Server with `NODE_ENV=production` and a validation rule defined, I get an error: 
`TypeError: requestOptions.validationRules.concat is not a function`.

```
  const server = new ApolloServer({
    ...
    validationRules: depthLimit(10),
  });
```

 Removing the validation rule fixed the error.

### Expected behavior
The server should start up with no errors

### Actual behavior
A `TypeError` is thrown and the process exits

### Sandbox for reproduction
[https://codesandbox.io/s/pedantic-lake-40yf8](https://codesandbox.io/s/pedantic-lake-40yf8)

1. Run `yarn` to install all packages
2. Run `yarn build` to transpile to typescript to a `build` folder
3. Run `yarn start:production` to start node with `NODE_ENV=production`

**Comment by glasser** [comment]
I assume you closed this because you figured this out. We looked into it for a moment and I think what's going on it:

- validationRules takes an array, not a single item
- Our docs were misleading until @abias1122 fixed them a few weeks ago in https://github.com/apollographql/apollo-server/pull/5666
- You're using `graphql-depth-limit` whose [`@types` package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql-depth-limit/index.d.ts) defines its return value as `any`, so TypeScript is ignoring the fact that it's not an array.

If you're inspired to help others, I suggest sending a DefinitelyTyped PR to add a better return type for `depthLimit`.
