### ISSUE TITLE
To many listeners of type "SIGINT"

### ISSUE THREAD

**Issue by Manubi** [apollographql/apollo-server#5699]
Hi,

I am using apollo-server-micro "^2.25.2" with the latest next.js version. 

I am using it in the `/api/index.ts` route 
<img width="526" alt="CleanShot 2021-09-09 at 13 53 34@2x" src="https://user-images.githubusercontent.com/20935138/132681107-cc1af053-4fbb-4df9-b798-77d8f08f2b14.png">

I am getting the following maxListeners error quite often when I click threw the app too fast and too many listeners get created.
<img width="1582" alt="CleanShot 2021-09-09 at 13 50 14@2x" src="https://user-images.githubusercontent.com/20935138/132680895-fc1a5ff2-4174-407c-be0a-ca9bb20ce1b5.png">

Any advice how I can debug/fix the problem?

Thanks! :)

**Comment by glasser** [comment]
You are creating a new ApolloServer object for every request instead of creating one at startup time and reusing it across requests. (This will also lead to worse performance since you won't be sharing any startup costs or in-memory caching across requests.)

**Comment by glasser** [comment]
Oops, hit submit too early.

In Apollo Server 3, we improved our docs so that the main docs site has a [working example of how to use `apollo-server-micro` correctly](https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-micro). I encourage you to upgrade and try that; I'm not sure if the same code works in the previous version or not.

**Comment by glasser** [comment]
(Or, well, that might be what's happening — maybe this pattern doesn't create a handler every time? Can you try the suggested pattern linked above, though? I don't know what the `handler` function you're calling is, and you haven't provided a full reproduction example that I can easily try out myself.)
