### ISSUE TITLE
Getting this error 

### ISSUE THREAD

**Issue by kumarwa** [apollographql/apollo-server#5721]
@can some one help me to resolve this issue when I have setup test server using apollo-server-express and getting this error while trying to hit the /graphql endpoint

connect ECONNREFUSED 127.0.0.1:80

however it works fine locally when I was hitting localhost:8080/graphql but not in test environment

**Comment by trevor-scheer** [comment]
Hey @kumarwa, this is likely not an issue with apollo-server, but a configuration problem in your test environment. In any case, we need more details to help you resolve the problem.

Since this is probably not a bug, I'd recommend asking your question over in our Discourse forum: https://community.apollographql.com/
I recommend providing as much detail as possible in your question. This increases the likelihood that someone is able and willing to help you figure out the issue.

If you do think it's a bug, please provide us with a runnable, minimal reproduction so that we can diagnose and fix the issue. I'll reopen this if a reproduction is provided.
