### ISSUE TITLE
Dynamic Schema

### ISSUE THREAD

**Issue by cachila** [apollographql/apollo-server#5786]
Hello everyone,

I know this is an old discussion but I think it hasn't been addressed correctly.

### Situation
We have thousands of clients which have custom models that should be able to query. This means that one clients shouldn't have on the schema other clients' models.

I found on [this comment](https://github.com/apollographql/apollo-server/issues/2010#issuecomment-800218792) a way to serve a schema dynamically but it only works for introspection queries as the validation happens before the `responseForOperation` event.

Another solution would be to run multiple Apollo Servers (one for each client) and then select the correct one based on the request but I don't think is the correct way to do this as it would involve thousands of Apollo Servers.

On [this discussion](https://github.com/apollographql/apollo-server/discussions/4391) mgagliardo91 has almost the same situations and a solution for his issue would most probably work for us.

Thanks in advance

**Comment by glasser** [comment]
Changing the model of Apollo Server to support multiple active schemas at once isn't on our current roadmap.

**Comment by glasser** [comment]
Much of the value of GraphQL comes from having an agreed-upon schema for your service. This is what you can use to run static code generators against, the docs you can browse, something that you can track changes to over time, etc. It's understandable to want your graph to come in a few separate flavors and we are working on adding features to the Apollo Platform to allow for that. But to have a completely dynamic schema that can change arbitrarily on every request doesn't seem in line with the value of GraphQL. Are you sure this is necessary for your use case?

**Comment by glasser** [comment]
A year later, it still feels that GraphQL is best used with static schemas rather than making every single request a completely dynamic mystery schema. If your app has a few different flavors, you can run ApolloServers on multiple different URLs each serving different schemas (or use some other mechanism in your web framework to select between multiple different ApolloServer objects, esp in the almost-released Apollo Server v4 which provides a stable API for executing requests rather than just a fixed set of web framework integrations). For example, [contracts](https://www.apollographql.com/docs/studio/contracts/) (alluded to in my previous comment) are one approach to dividing up a single graph into multiple smaller schemas for different use cases, which still allows each schema to have a fixed identity and lifecycle rather than being completely chaotic and undetermined.

AS4 does make it easier to dynamically choose in a single process between multiple ApolloServer objects; I don't think at this time we're likely to extend Apollo Server's core model to build this feature in.
