### ISSUE TITLE
Apollo error subclass UserInputError is being wrapped inside a GraphQLError

### ISSUE THREAD

**Issue by sadokmtir** [apollographql/apollo-server#5810]
**The actual behavior**:

When I am using Apollo custom error classes, for example the `UserInputError` in my case, I was confused why the tests are breaking and not consistent between `UserInputError` being thrown by Apollo Server when the argument is required but it was not sent and between the errors i define them through the logic in my resolver and I throw them as a `UserInputError`.

I was surprised that, the ones on the schema level are throwing `UserInputError` as the parent error and the ones I throw are being set as `originalError` property on a `GraphQLError` object. 

When I did debug it, i found out that the function `locatedError` `node_modules/graphql/error/locatedError.js` is checking if the original error has a `path`  attribute being set as an array or not. In case it is not there the original error is wrapped inside the `GraphQLError`.

 ```
function locatedError(rawOriginalError, nodes, path) {
  var _nodes;

  // Sometimes a non-error is thrown, wrap it as an Error instance to ensure a consistent Error interface.
  var originalError = rawOriginalError instanceof Error ? rawOriginalError : new Error('Unexpected error value: ' + (0, _inspect.default)(rawOriginalError)); // Note: this uses a brand-check to support GraphQL errors originating from other contexts.

  if (Array.isArray(originalError.path)) {
    return originalError;
  }

  return new _GraphQLError.GraphQLError(originalError.message, (_nodes = originalError.nodes) !== null && _nodes !== void 0 ? _nodes : nodes, originalError.source, originalError.positions, path, originalError);
}
```
 **The expected behavior**:

I would expect that the path is being set by default from apollo server when I do `throw UserInputError("error")`.

**Versions involved** -

"apollo-server": "^2.9.7",
"apollo-server-express": "^2.9.7",
"graphql": "^15.4.0",

**Comment by glasser** [comment]
I'm finding it a bit of a challenge to figure out exactly what your concern is, since this issue is presented just as a code snippet, not as a complete reproduction example. My understanding is that the function you found (locatedError) is the mechanism that graphql-js and apollo-server use to put a `path` on errors: there's no way for the `new UserInputError` constructor to understand what the context it is being thrown in is, and the path is just added later if the resolver eventually throws the error.  It does this by copying the error because that's the most general way to extend an error. This differs from other kinds of bad input that aren't associated with specific paths is.  I'm not sure exactly what the problem you're trying to solve here is — is it that a particular callback or part of the response looks different from what you'd expect?

Additionally, Apollo Server 2 is no longer actively maintained except for security updates.

I'd be happy to reopen this issue if it comes with a full reproduction (eg, codesandbox.io sandbox or a git repository) that can demonstrate precisely what the problem is without me having to be creative, and if it's based on Apollo Server 3.
