### ISSUE TITLE
Docs Need Updates: Resolver arguments info core fields link obsolete

### ISSUE THREAD

**Issue by awx-dylan-xie** [apollographql/apollo-server#5812]
DOC URL: https://www.apollographql.com/docs/apollo-server/data/resolvers/#resolver-arguments

**SOURCE CODE URL:** https://github.com/apollographql/apollo-server/blob/main/docs/source/data/resolvers.mdx#resolver-arguments

**What was wrong?**
In the description for `info`, the link to the core fields is https://github.com/graphql/graphql-js/blob/main/src/type/definition.ts#L977-L986, which should be https://github.com/graphql/graphql-js/blob/main/src/type/definition.ts#L975-L984

**Comment by glasser** [comment]
I'd be happy to merge a PR to fix this (docs are in the `docs` subdir). This seems to be a bit of a treadmill though. Linking to a specific blob rather than main is bad because people want to see the latest definitions. Linking to a specific line number gets out of date quickly. GitHub does do syntax analysis on their files but I don't think you can link directly to a symbol.
