### ISSUE TITLE
@defer / @stream support

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-server#5893]
This is the main feature request tracking issue for adding `@defer` / `@stream` support to Apollo Server. More details will be broken out shortly.

**Comment by jacob-israel-turner** [comment]
Hi @hwillson!  I've been watching for `@defer` support to land for quite some time - over a year I'm sure.  Excited to see that the team at least still has this on their radar - but curious if you can provide any updates or timeline.

**Comment by glasser** [comment]
The current architecture of how Apollo Server's core logic relates to the web frameworks it can be embedded in makes it challenging to add features such as `@defer` which change GraphQL execution from a single request/response to something more intricate. As part of [Apollo Server 4](https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md) we will be improving this API to support features such as `@defer`. Whether we block 4.0.0 on ensuring that `@defer` works or just put the infrastructure in place to implement it in a follow-up minor release is tbd, so we're taking it out fo the milestone for now.

**Comment by jacob-israel-turner** [comment]
Hi @glasser! Thanks for your response and transparency here. Your hard work on this project is greatly appreciated.

However, this response does trouble me as well. I've been waiting for this functionality for a long time. The last time we heard updates from the Apollo team, the response was almost exactly the same, except referring to Apollo 3.0. The message was, "this will be much easier to implement once we have 3.0 released. We'll likely implement in a follow-up minor release after we finish the 3.0 release".

Is this actually something that's going to land in 4.0? Or are we going to hear the same story, except with 5.0?

**Comment by glasser** [comment]
We basically split 3.0 into two pieces, which will be 3.0 and 4.0.  Putting off everything that will come in 4.0 would have meant we didn't ship the original improvements of 3.0 last year.  The 4.0 roadmap is similar to 3.0; 3.0 ended up being mostly focused on removing integrations with unmaintained projects and enabling folks to use the latest versions of dependencies rather than the full HTTP level rearchitecture we'd originally intended.

The comment you found from me last year said that the `graphql-js` implementation was close to done and it is in fact still not merged in graphql-js or part of the spec :)

**Comment by hwillson** [comment]
Now being tracked in https://github.com/apollographql/apollo-server/issues/6671.
