### ISSUE TITLE
Feature Request: Add SvelteKit Integration

### ISSUE THREAD

**Issue by alexanderschau** [apollographql/apollo-server#5897]
Hey there! I was wondering if it would be possible to create an official SvelteKit Integration. SvelteKit is a framework for building web application (similar to NextJS). It allows you to create so called [Endpoints](https://kit.svelte.dev/docs#routing-endpoints) to run Server-Side Code.
I already build an [integration for myself](https://github.com/alexanderschau/apollo-server/blob/304c679db7d16d4bd17cd1db0fbcc7e95f4c9e8f/packages/apollo-server-svelte-kit/src/ApolloServer.ts), but it would be cool if we make it official, so everyone can use it.

What's your opinion on that?

**Comment by glasser** [comment]
Hi! I think we are a lot more likely to move Apollo Server in the direction of "a better defined and more stable API for integrating with web frameworks with far fewer integrations maintained by the core team in the apollo-server repo" than in the direction of "even more officially-maintained web framework integrations".  I'm planning to write this up as part of a proposal for a potential Apollo Server 4 sometime in the next week or so.  The need to be an expert on 10 (!) different web frameworks and serverless environments in order to make any change that interfaces with the web framework at all has been a huge amount of friction on the ability to actually add new features to Apollo Server and I don't think changing that to 11 is in the cards. But hopefully a better-defined and simpler base class can make it easier to maintain something like this as a popular community package.

**Comment by alexanderschau** [comment]
You're absolutely right!

**Comment by alexbjorlig** [comment]
> 

Hi @alexanderschau - would you mind share what solution you are using in sveltekit for your GraphQl endpoint?

**Comment by alexanderschau** [comment]
Sure, I built an npm package for that: https://github.com/alexanderschau/apollo-server-svelte-kit
