### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-server#5901]
Some of the package dependencies, e.g.
https://github.com/apollographql/apollo-server/blob/5f7fc7cbbe4913ff9e96fec8be03ed6e2cad20f0/packages/apollo-server-core/package.json#L30-L32
are quite outdated. Could these please be updated? Thanks!

(The rennovate bot only seem to update the top-level and docs packages, is this on purpose?)

**Comment by glasser** [comment]
I'm not sure what your concern is.  These ranges include the latest versions of all three of these graphql-tools packages. They aren't strict constraints.

If it's really important that these dependencies be at their latest version, you can install it in your app (and use npm/yarn's janky deduping stuff to make sure only one copy gets installed).  By keeping the dependency loose, it makes it a bit less likely that folks who also use these package directly will end up with two separate copies installed. Though FWIW, these packages are mostly used for convenience: eg, the one use of `@graphql-tools/schema` is just to allow you to write `new ApolloServer({typeDefs, resolvers})` instead of `new ApolloServer({schema: makeExecutableSchema({typeDefs, resolvers})})`.
