### ISSUE TITLE
Support graphql@16 by fixing dependency on apollo-graphql

### ISSUE THREAD

**Issue by sushantdhiman** [apollographql/apollo-server#5941]
As per https://github.com/apollographql/apollo-server/issues/5605 graphql@16 should already be supported but it doesn't look like this.

`apollo-server-core@3.5.0` currently dependent upon `apollo-graphql@0.9.5` which still requires `graphql@15` or below

```bash
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^14.2.1 || ^15.0.0" from apollo-graphql@0.9.5
npm WARN node_modules/apollo-server-core/node_modules/apollo-graphql
npm WARN   apollo-graphql@"^0.9.0" from apollo-server-core@3.5.0
npm WARN   node_modules/apollo-server-core
```

To properly complete support for `graphql@16`

- [ ] Support `graphql@16` for `apollo-graphql` (I don't know where this repo exists)
- [ ] Release `apollo-server-core` with fixed version of `apollo-graphql`

**Comment by glasser** [comment]
Good point. The best thing to do here is probably just to inline the small amount of code in `apollo-graphql` that apollo-server-core and apollo-server-plugin-operation-registry use directly into this repo and drop the dependency rather than do more releases of that package. There's no particularly good reason for "the usage reporting specific signature algorithm" and "the operation registry specific signature algorithm" to live far away from the usage reporter and the operation registry plugin.

**Comment by glasser** [comment]
(I will also say that while I do see the problem here, I'm confused as to why others haven't run into this yet... surely you are not the first person trying to combine the release of AS3 that is supposed to support graphql@16 with graphql@16...)
