### ISSUE TITLE
apollo-server-micro depends on private properties of `graphql`'s `GraphQLSchema` type

### ISSUE THREAD

**Issue by saevarb** [apollographql/apollo-server#6035]
When using `nexus` with `apollo-server-micro`(and `nextjs`), `nexus` generates a schema which has the type `NexusGraphQLSchema` which is compatible with `graphql`'s `GraphQLSchema` except for a few minor details:

```ts
export declare type NexusGraphQLSchema = Omit<GraphQLSchema, 'extensions'> & {
    extensions: {
        nexus: NexusSchemaExtension;
    };
};
```

However, `apollo-server-micro` expects `GraphQLSchema` from `graphql`, which(since 16) includes some `private` properties, which `NexusGraphqlSchema` lacks:

```ts

export declare class GraphQLSchema {
  // ..
  private _queryType;
  private _mutationType;
  private _subscriptionType;
  private _directives;
  private _typeMap;
  private _subTypeMap;
  private _implementationsMap;
  // ..
}
```

The result is that we get a type error because `NexusGraphQLSchema` has removed the private properties(this happens during `Omit`), but `apollo-server-micro` expects them to be there.

It's not 100% clear who should be responsible for handling this problem. `nexus` isn't doing anything wrong, but one could argue that either `apollo-server-micro` should have its own interface derived from the `GraphQLSchema` type which only includes exactly the things that it needs, or that `graphql` should provide an interface without the private properties. Either way, it doesn't seem right that `apollo-server-micro` is "demanding" private properties which are by definition internal implementation details which it can't do anything with.

The fix *could* be as easy as replacing `apollo-server-micro`'s `schema` type with something like:

```ts
type FixedGraphqlSchema = {
  [K in keyof GraphQLSchema]: GraphQLSchema[K];
};
```

Since the `keyof` will elide private properties.

For now, the fix I have gone with is just 

```ts
export const server = new ApolloServer({
  schema: schema as unknown as GraphQLSchema,
  // ..
  ```

**Comment by glasser** [comment]
Can you share what the error you're seeing looks like, or at least say which properties you're referring to? I don't see any reference to any of the private fields you've mentioned above in the Apollo Server codebase. You also don't mention what version of Apollo Server you're using. A great way would be to share a git repo or codesandbox.io sandbox demonstrating the issue. I'll be happy to reopen this when there's more details!

Are you saying that we are not actually *reading* these private properties or referring to them explicitly, but that they are still required to be there because that's how TypeScript works?

By the way, I don't recommend using apollo-server-micro with nextjs, even though I recognize that somebody once created an example for that combination that got copied into a bunch of examples.  Despite the fact that Micro and NextJS are created by the same company, NextJS doesn't actually use Micro at all, and so there's not a very compelling reason to use what is actually the least functional of the Apollo Server integrations with it.  I have [a PR](https://github.com/vercel/next.js/pull/30082) to change these integrations to use apollo-server-express and upgrade to Apollo Server 3 but the NextJS team hasn't made any progress on it.  (We're also currently planning an [Apollo Server 4](https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md) which will simplify the project so that there isn't a big gap between Express and Micro integrations.) That said my assumption is that whatever problem you're seeing is part of `apollo-server-core` rather than `apollo-server-micro` specifically.

**Comment by glasser** [comment]
OK, I put some effort into reproducing this and I see the issue.

I think `nexus` should be able to get away with

```
type NexusGraphQLSchema = GraphQLSchema & {
  extensions: GraphQLSchema['extensions'] & {
    nexus: NexusSchemaExtension;
  };
};
```

which as far as I can tell fixes the issue? Just don't Omit anything, be additive?

**Comment by saevarb** [comment]
Sorry for the poor example, and thanks for looking into it. I meant to go back to add a proper repro just about now, but you beat me to it.

Your solution seems like a good one, yes. I will report this to the nexus devs. 

As for the info regarding `micro` - thanks a lot for that. I have a project in production which is using `apollo-server-micro` and I freely admit that it is based on an example I found online. I also remember stumbling upon a discussion which mentions what you are saying regarding using express instead(it might even be your PR). I am however currently starting a new project using the same stack and I will follow your suggestions and use the `express` integration instead.
