### ISSUE TITLE
`apollo-server-azure-functions` how to add express middlewares ?

### ISSUE THREAD

**Issue by hexdecimal16** [apollographql/apollo-server#6091]
I have an apollo server based on express. I want to deploy it on azure as a serverless function. I have a few middlewares I am using namely, express. How to use it with azure functions?

**Comment by glasser** [comment]
Unfortunately our Azure Functions package isn't particularly extensible, as it's a full implementation of "translate AF HTTP objects into something more standard". And designing a generic method for building extensible Azure Functions apps seems way out of scope of the Apollo Server project.

For Lambda we use something called `@vendia/serverless-express` which lets you embed an Express app in Lambda. As you've found, there's a [PR](https://github.com/vendia/serverless-express/pull/484#issuecomment-1031227301) for that to support Azure Functions too! But I don't know how that's going.

There are some things out there that let you put Express in AF (https://www.npmjs.com/package/azure-function-express) or are their own middleware platform (https://www.npmjs.com/package/azure-functions-middlewares) but they haven't been updated in a few years and it's unclear if they support the latest AF versions.

We are planning to (as you [discovered](https://github.com/apollographql/apollo-server/issues/6032#issuecomment-1031232872)) transition Apollo Server Azure Functions to community support in Apollo Server 4, and I suspect that different community members might find different approaches to this attractive, so maybe there'll be multiple potential packages.

Since we don't plan to add a bespoke extensibility model to ASAF in AS3, and we plan to migrate ASAF to community maintenance in AS4, I'm going to close this issue.
