### ISSUE TITLE
apollo-server-micro doesn't seem to support cache

### ISSUE THREAD

**Issue by pkellner** [apollographql/apollo-server#6105]
I'm using `apollo-server-micro` with NextJS API routes, as i believe that is the recommended way based on the NextJS examples. (please let me know if there is a newer example). because of that I'm using 2.14.2

I have the following code and I get an error as if there is no cache object.

``` JavaScript
import { ApolloServer, makeExecutableSchema,  } from "apollo-server-micro";
import responseCachePlugin from 'apollo-server-plugin-response-cache';

const typeDefs = require("../../apolloserver/schema");
const { Query } = require("../../apolloserver/resolvers");

const resolvers = {
  Query
};

const schema = makeExecutableSchema({ typeDefs, resolvers });

const apolloServer = new ApolloServer({
  schema,
  context(ctx) {
    return {...ctx,prisma};
  },
  resolvers,
  plugins: [responseCachePlugin()]
});

export const config = {
  api: {
    bodyParser: false,
  },
};

export default apolloServer.createHandler({ path: "/api/graphql" });
```

And when I add the Cache Control to my resolver as follows, I get an error saying 

```
Cannot read property 'cacheControl' of undefined
```

``` JavaScript
async function codeCampYears(parent: any, args: any, context: any, info: any) {

  console.log(`[${new Date().toLocaleTimeString()}] Query.MyTable`);
  info.cacheControl.setCacheHint({ maxAge: 10 });

  const data = await context.prisma.MyTable.findMany();
```

**Comment by glasser** [comment]
> I'm using apollo-server-micro with NextJS API routes, as i believe that is the recommended way based on the NextJS examples. (please let me know if there is a newer example). because of that I'm using 2.14.2

There's a newer example in a PR at https://github.com/vercel/next.js/pull/30082
This example shows how to use AS 3, and switches away from apollo-server-micro to apollo-server-express. I have no idea why the original example used apollo-server-micro as NextJS does not actually use Micro and its docs explain how to integrate with Express.

I have not yet figured out who if anyone who has replied on that PR has the ability to merge it, nor have I heard feedback from the original author of the NextJS apollo-server-micro about why they made that choice.

I'd suggest you try apollo-server-express with Apollo Server 3 with those examples.

That said, I'm not sure what's going on with your specific issue around cacheControl. We did change some stuff about the internals of how cacheControl works in Apollo Server 3, but the way you access the dynamic cache control feature via `info.cacheControl` did not change.  Unfortunately your issue doesn't provide enough detail for me to reproduce it and figure out what the bug is.  I'd be happy to investigate a bit if you can provide a full reproduction recipe that doesn't require any creativity on my part (ideally starting with `git clone` or using a codesandbox.io sandbox).  Though I'd be even happier if you were using AS3 and apollo-server-express, as we are generally only maintaining AS2 for security issues at this point.

**Comment by pkellner** [comment]
@glasser you definitly have the right people on that pull request who should have reviewed it, but probably the number of examples scared them as they are pretty busy these days.

I tried to build the project but got an error with npm run dev about es2017.  If you don't mind leaving this issue open, I'll keep working on your examples and assuming they work well for me, I'll bug Tim and the folks over in NextJS land to merge your PR. I know Apollo is important to them so I'm surprised they let it be out there with issues like this.

Here is a link to someone having the same error and complaining no one on the Next team is looking at it.

`Error: error: top level await requires target to es2017 or higher and topLevelAwait:true for ecmascript`

https://github.com/vercel/next.js/discussions/11185#discussioncomment-1572325

This is the project I'm building:  ~/api-routes-apollo-server-and-client-auth

**Comment by glasser** [comment]
Are you setting target to es2017 in tsconfig.json and topLevelAwait in next.config.js like my examples do?

**Comment by glasser** [comment]
Or maybe this broke in a newer Next version? I'm not sure.

**Comment by pkellner** [comment]
This is the next.config.js and there is no tsconfig.json in the project. I'm not a webpack wizard, but it sounds like it has something to do with webpack 5 and config.

```
module.exports = {
  webpack: (config, options) => {
    config.experiments = {
      ...config.experiments,
      topLevelAwait: true,
      
    }
    return config
  },
}
```

**Comment by pkellner** [comment]
I just tested with NextJS 11 and that did work.   Arg :(.

**Comment by pkellner** [comment]
@glasser Thanks for weighing in here.  Clearly not your fault, but I'm quite disappointed now and feel like I've burned a lot of time on path that never would have worked properly.  I'm going to abandon NextJS for apollo server, keep it apollo client only and make a standalone server for reasons I mention here:  https://github.com/vercel/next.js/issues/34177#issuecomment-1034982890

**Comment by glasser** [comment]
Yes, it is strange to me that one would choose to build a server platform that doesn't contain the basic operation of "do some work on startup and don't let the server start serving responses if it failed". Hopefully NextJS will eventually come up with a way to allow that use case in their platform.

As part of the design for Apollo Server 4, we might come up with a way to make it a bit easier to use in platforms with poor error handling. Perhaps a flag like `new ApolloServer({ awaitingTheStartMethodIsNotPossibleSoAnyStartupErrorsWillCauseAllRequestsToFail: true })`

**Comment by pkellner** [comment]
:). You had me at `awaitingTheStartMethodIsNotPossible`

**Comment by pkellner** [comment]
I'm thinking you guys should pull apollo-server-micro from the docs page. Be easier to insist that the NextJS folks either remove or improve their apollo example.  I'm not the only one falling down this flight of stairs. @m-abdelwahab is doing a full end to end example for prisma.io that really should be a production ready example and I just don't see how that could be possible with the current bits and versions.  I'm guessing this is going to give Mahmoud heart burn now (sorry dude).

https://www.prisma.io/blog/fullstack-nextjs-graphql-prisma-oklidw1rhw

https://www.apollographql.com/docs/apollo-server/integrations/middleware/#apollo-server-micro
