### ISSUE TITLE
I try to disable the header Server and isn´t working

### ISSUE THREAD

**Issue by ErnestoCamilo** [apollographql/apollo-server#6118]
I working with this packages 
```
"apollo-server": "^2.21.1",
"apollo-server-express": "^2.21.1",
```
I need to remove this header from response headers
```
pragma: no-cache
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Origin, Accept-Encoding
x-content-type-options: nosniff
```
And right now with my configuration isn´t do it.
```
pragma: no-cache
server: Google Frontend
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Origin, Accept-Encoding
x-content-type-options: nosniff
```
I tried to disable like this
![image](https://user-images.githubusercontent.com/89998025/154072116-1cbab4b3-7f21-4174-b340-180b6cc3f691.png)
and with this other way too
![image](https://user-images.githubusercontent.com/89998025/154072248-620d4a26-10ff-4b65-acd1-d131f940eb8b.png)
Other configuration
![image](https://user-images.githubusercontent.com/89998025/154073219-d05f1257-1c18-43e5-9b4d-6621f7be8f78.png)

**Comment by glasser** [comment]
This is probably being added by your hosting provider, since there's nothing Google about Apollo Server or Express.  Do you see this locally or just when you deploy it somewhere, and if so, where?

(I don't think there's an Apollo Server bug here, and we also aren't actively maintaining Apollo Server 2.x for non-security concerns, so I'm closing this issue.)
