### ISSUE TITLE
Getting an error after upgrading apollo-datasource-rest

### ISSUE THREAD

**Issue by viniciuspalma** [apollographql/apollo-server#6144]
### Packages
```diff
-    "apollo-datasource": "3.3.0",
-    "apollo-datasource-rest": "3.5.0",
+    "apollo-datasource": "3.3.1",
+    "apollo-datasource-rest": "3.5.1",
```

### The expected behavior
Dependency errors disappear and build it without problems

### The actual behavior

Using yarn manager 3.1.1 missing dependencies lead to thesee errors:

```shell
➤ YN0002: │ apollo-datasource-rest@npm:3.5.1 doesn't provide graphql (p0a688), requested by apollo-server-errors
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ apollo-datasource-rest ➤ dependencies ➤ graphql: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
```

And generate errors on build time

```shell
    if (typeof firstError.pnpCode === `string`) Error.captureStackTrace(firstError);
                                                      ^
Error: apollo-server-errors tried to access graphql (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.


Ancestor breaking the chain: apollo-datasource-rest@npm:3.5.1
```

**Comment by glasser** [comment]
I'm not sure exactly what you're seeing here or why this tiny upgrade would cause problems. But the underlying thing happening here is an error message about a missing `graphql` peer dependency. When using Apollo Server you're expected to install `graphql` (graphql-js) yourself so that you can manage its major version upgrades. Have you done that in your app?

If that isn't enough to solve your issue, I'd be happy to reopen this issue and poke at it if you provide a *complete* (and ideally minimal) reproduction that requires no creativity on my part. These typically start with `git clone` or use codesandbox.io.
