### ISSUE TITLE
TypeError on requestCtx request.query

### ISSUE THREAD

**Issue by JRRS1982** [apollographql/apollo-server#6186]
Type error - requestCtx in ApolloServer.ts has string|DocumentNode type, but query is expecting a string

"apollo-server-core@2.25.3",

Expect no type errors in a core package.

Issue is that we would pass a DocumentNode as an argument to request.query, while it only expects a string, not a big issue, but worthwhile fixing.

Hope this helps - line 1302 of apollo-server-code@2.25.3, in ApolloServer.ts, feel free to reject if not helpful enough / ask any questions. 

```
    const requestCtx: GraphQLRequestContext = {
      logger: this.logger,
      schema: options.schema,
      schemaHash: options.schemaHash,
      request: {
        ...request,
        query:
          request.query && typeof request.query !== 'string'
            ? print(request.query)
            : request.query,
      },
      context: options.context || Object.create(null),
      cache: options.cache!,
      metrics: {},
      response: {
        http: {
          headers: new Headers(),
        },
      },
      debug: options.debug,
    };
```

**Comment by glasser** [comment]
I'm not sure I follow what you're reporting. Are you saying that when you try to build Apollo Server 2, you get a type error? Or some way in which you use it has an error? It would be easier to understand this if you provided a complete reproduction that requires no creativity for me to see it on my computer (eg, instructions starting with `git clone` or using codesandbox.io).

Additionally, Apollo Server 2 has not been actively maintained except for security issues since last June.

**Comment by JRRS1982** [comment]
Yes there is a type error in the source code. If its not actively maintained happy that its closed as only a minor point 👍🏻

**Comment by glasser** [comment]
Thanks. I am unable to understand exactly what the error is; with a reproduction I'd see whether it is worth a patch release to this old version.
