### ISSUE TITLE
400 Bad request when input incorrect?

### ISSUE THREAD

**Issue by davidNHK** [apollographql/apollo-server#6278]
According to document, Apollo server always use 200 status code by design. [docs](https://www.apollographql.com/docs/apollo-server/data/errors/#returning-http-status-codes)

But given to example code here, it would response 400 when input not match schema. 

https://github.com/davidNHK/apollo-server-issue-6278

**Comment by glasser** [comment]
In general, we provide 200 (unless specifically overridden by a plugin/HttpQueryError/etc) for operations that successfully get to the "executing a GraphQL operation" stage but use 4xx when the operation doesn't appear to be good GraphQL. I don't think the docs actually say otherwise? The main point is that we don't think some sort of application-level error should become a 4xx/5xx by default, just one at the layer of the overall processing of the HTTP request.

**Comment by trevor-scheer** [comment]
Closing this but happy to reopen if there's more to discuss here.
