### ISSUE TITLE
How to know if the request is came from HTTP or Websocket on context creation?

### ISSUE THREAD

**Issue by berkaey** [apollographql/apollo-server#6412]
Hi, I wonder how can I know if it the request is came from Websocket here;

```
new ApolloServer({
 context: (ctx)=>{
  // here
 }
})
```

before (Apollo 2) I can get that information as;

```
new ApolloServer({
 context: ({req, connection})=>{
   if (connection) {
    // socket
  }else{
   // http
  }
 }
})
```

**Comment by glasser** [comment]
Apollo Server 3 does not have built-in support for subscriptions, so you can know the answer by it always being "not websockets" :)

We do have [documentation for how to run an Apollo Server 3 server and a graphql-ws server with the same schema in the same HTTP server](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#operation-context); you pass separate `context` functions to the two servers, so that's how you know there.
