### ISSUE TITLE
graphql playground not working

### ISSUE THREAD

**Issue by RobinYang11** [apollographql/apollo-server#6441]
![image](https://user-images.githubusercontent.com/20513480/168973523-2287749e-267f-46a2-985c-203e53a2e4ca.png)

**Comment by trevor-scheer** [comment]
This seems like a connection issue on your end or maybe an issue with the cdn hosting the playground bundle. Is this still happening for you?

**Comment by sonofmagic** [comment]
I meet the same issue , and i think it may caused by the block of this host `cdn.jsdelivr.net` in china.

We china users can fetch neither `npm/@apollographql/graphql-playground-react@1.7.42/build/static/css/index.css` nor `npm/@apollographql/graphql-playground-react@1.7.42/build/static/js/middleware.js` in our network. 
The Chorme's console shows Error `net::ERR_CONNECTION_TIMED_OUT`.
Then as the title says: `graphql playground not work!`

**Comment by sonofmagic** [comment]
> Thanks for the info @sonofmagic. Did this error start happening recently?
> 
> jsdelivr claims support for China: https://www.jsdelivr.com/network
> 
> But it looks like there have been issues in the recent past: [jsdelivr/jsdelivr#18348](https://github.com/jsdelivr/jsdelivr/issues/18348)
> 
> ^this one _seems_ to have been resolved but honestly I can't tell for sure.

Thanks, May `cdn.jsdelivr.net` has been banned recently in china. i mentioned this issue https://github.com/jsdelivr/jsdelivr/issues/18402

I should like to ask is there any options for `@apollographql/graphql-playground-react` to switch CDN address or use local static resources? 
Thank you !

**Comment by glasser** [comment]
Have you considered using the default landing page for Apollo Server 3 instead of GraphQL Playground? Playground is unmaintained.

https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/

We're about to release a version that allows you to enable an embedded Apollo Sandbox which functions very similarly to GraphQL Playground: https://github.com/apollographql/apollo-server/pull/6397

**Comment by hanayashiki** [comment]
翻个墙有那么难吗？

**Comment by sonofmagic** [comment]
> 翻个墙有那么难吗？

我试过开vpn翻墙，也访问不了那些资源，很奇怪。

**Comment by blazestudios23** [comment]
I'm having the same issue and I'm in the US.

**Comment by glasser** [comment]
GraphQL Playground has been unmaintained by its maintainers for a while now. We do keep around an optional plugin for using it purely to help folks migrate from Apollo Server 2 (where this unmaintained software was the only provided UI) to AS3 (which has a plugin system for UIs) but if this unmaintained software has started to bitrot a little faster, we can really only suggest you stop using it.

**Comment by blazestudios23** [comment]
So it actually works for me in a service with these packages:

```
"@apollo/federation": "0.33.0",
    "@apollo/rover": "^0.6.0",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@kenchi/nexus-plugin-prisma": "^0.40.0",
    "@prisma/client": "3.6.0",
    "apollo-server-express": "^3.7.0",
```

And not in a service with these packages:
```
"@apollo/gateway": "^2.0.2",
    "@apollo/rover": "^0.6.0",
    "@sentry/node": "^6.13.3",
    "apollo-server-express": "^3.7.0",

```

Is there something I need to set up with rover? I just switch to Gateway 2.

**Comment by oachoor** [comment]
please share your configuration, I fixed it by moving `helmet` right after `apolloServer.applyMiddleware({ app });`
