### ISSUE TITLE
Validation rules runs before custom validation causing to exception 

### ISSUE THREAD

**Issue by idanwe** [apollographql/apollo-server#6563]
I'm using `graphql-depth-limit` package as a custom validation rule. 

![image](https://user-images.githubusercontent.com/3066423/173241089-73d6fb7f-026a-4594-9287-9f02c2a27c73.png)

Now, when using the API, and user performs a query with GraphQL Validation error, it doesn't validate the input with the GraphQL validation error first.

e.g. For a request with unknown fragment.
```
mutation createContact($input: ContactInput!) {
  createContact(input: $input) {
   contact {
      ...ContactFragment
    }
  }
}
```
The server returns error, as the `graphql-depth-limit` doesn't handle this case.
![image](https://user-images.githubusercontent.com/3066423/173241263-11b0cb62-7fbe-4683-b733-76ed06283097.png)

I can assume this is something that can be fixed in the plugin.
But, I'm expecting that the base validations will run first as mentioned here in [the docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#validationrules) that the validations in `validationRules`  are additional.
![image](https://user-images.githubusercontent.com/3066423/173241362-87d2803c-4cbc-40a8-b96d-cddec07dee39.png)

apollo-server-express: 3.7.0

**Comment by trevor-scheer** [comment]
I suppose you're talking about these lines of code specifically:
https://github.com/apollographql/apollo-server/blob/444c403011209023b5d3b5162b8fb81991046b23/packages/apollo-server-core/src/requestPipeline.ts#L464-L471

Is your expectation that we perform validation in 2 separate phases - the first using only `specifiedRules` and the second using `config.validationRules`? So if I update the function I linked to above that would look something like:

```ts
  function validate(document: DocumentNode): ReadonlyArray<GraphQLError> {
    const specifiedRuleErrors = graphqlValidate(config.schema, document, specifiedRules);
    // bail early if we get typical validation errors, don't run custom validations at all
    if (specifiedRuleErrors) return specifiedRuleErrors;

    // run custom validations
    return graphqlValidate(config.schema, document, config.validationRules);
  }
```

The problem with this approach is that we would no longer report all applicable validation errors at once (we'd be excluding any errors from custom rules that were provided), so a client would only potentially get a subset of the errors that pertain to the operation they sent.

My first instinct is that `graphql-depth-limit` shouldn't throw if it receives an invalid operation, but instead return `GraphQLError[]` (either an empty array or an actual error that said "invalid document" or something). _Validation_ rules should be able to handle all kinds of bad input without throwing since that's specifically their purpose. You should be able to just rewrite the `depthLimit` function to return an array in the `catch` clause https://unpkg.com/graphql-depth-limit@1.1.0/index.js

The repo for this rule no longer exists and this was last published 5 years ago. Maybe there's an active fork somewhere, but there's not a lot going on in the source so you could just paste it into your codebase with the changes I suggested.

**Comment by idanwe** [comment]
Thanks @trevor-scheer I copied a local version of it
