### ISSUE TITLE
FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.2.0' is installed

### ISSUE THREAD

**Issue by adilfaayiz** [apollographql/apollo-server#6757]
Fastify version
4.2.0

Plugin version
No response

Node.js version
18.7.0

Operating system
macOS

Operating system version (i.e. 20.04, 11.3, 10)
13 Ventura

Description
I'm using NestJS with GraphQL I've installed it as per their instruction but getting below error

```FastifyError: fastify-plugin: fastify-accepts - expected '3.x' fastify version, '4.2.0' is installed```

I'm clueless what to do here, I've tried every possible options so it's not working.

Also getting below warning

```warning " > apollo-server-fastify@3.10.0" has unmet peer dependency "fastify@^3.17.0".```

Steps to Reproduce
Installed the new NestJs and GraphQL and add GraphQLModule configuration on AppModule and start it, It will through the error in CLI.

Expected Behavior
It should run smoothly without any version error.

**Comment by glasser** [comment]
The Fastify project's approach to versioning makes it impossible to support multiple major versions of Fastify with a single version of Apollo Server.  Our solution is to leave Apollo Server 3 only supporting Fastify v3 but to change our entire approach to web framework integration with the upcoming AS4 to make the framework integration code smaller and separately versioned so that there can be separate small integration packages for each Fastify major version. See https://github.com/apollographql/apollo-server/pull/6648#issuecomment-1182558683
