### ISSUE TITLE
apollo-server-express dependencies

### ISSUE THREAD

**Issue by zaslavskyv** [apollographql/apollo-server#6761]
Is there a reason apollo-server-express depends on the following types?

- @types/accepts"
- @types/body-parser"
- @types/cors"
- @types/express"
- @types/express-serve-static-core"

Would it be possible to have them listed as dev dependencies instead?

**Comment by glasser** [comment]
In order to use an npm package with TypeScript, any types that are part of the publicly-visible API (ie, types that end up in the generated .d.ts files) need to come from packages that are installed when you install the package — ie, non-dev dependencies.

Most of these packages do in fact have their types used as part of the apollo-server-express API. For example, context functions take in express.Request and express.Response objects as arguments; and you can pass options that are passed through to cors and body-parser to a function.  (We need to pin `@types/express-serve-static-core` because the dependency versions from `@types/express` on that package have often been too loose and led to errors.)

`@types/accepts` does not appear to need to be a dependency as `accepts` is only used internally.

In Apollo Server 4 (actively under development on the `version-4` branch we no longer provide pass-through configuration for `cors` or `body-parser` so we've dropped those dependencies. We've also dropped the `@types/accept` dependency (we've switched from the `accepts` package to the `negotiator` package and have properly left its types package out of the dependencies of `@apollo/server`).  We continue to have the two express dependencies as is necessary.

Since the only part of this request that could be fixed is already fixed on `version-4`, I'm closing this.  If it would make your life much better to remove the `@types/accepts` dependency in Apollo Server 3, feel free to send in a PR.

**Comment by zaslavskyv** [comment]
Thank you very much for taking your time to explain it.
