### ISSUE TITLE
Improve documentation for `logFunction` option to server

### ISSUE THREAD

**Issue by alexturek** [apollographql/apollo-server#688]
Hi, I was trying to figure out what data I would receive, in what order, to my `logFunction`. From reading [this code](https://github.com/apollographql/apollo-server/blob/3fecfcd3218c2f7f2c5ed59a351d71022944bc35/packages/apollo-server-core/src/runQuery.ts), I see that the order is

```
action=request, step=start

action=request, step=status, key="query", data=query
action=request, step=status, key="variables", data=variables
action=request, step=status, key="operationName", data=operationName

action=parse, step=start
action=parse, step=end

action=validation, step=start
action=validation, step=end

action=execute, step=start
action=execute, step=end

action=request, step=end
```

I'd like to add this to specific API documentation (which seems to be almost entirely missing for `logFunction`). Where would the Apollo folks recommend adding this documentation and linking to it?

**Comment by martijnwalraven** [comment]
In general, the documentation for Apollo Server lives [in this repo](https://github.com/apollographql/apollo-server/tree/master/docs) and is automatically deployed to [our website](https://www.apollographql.com/docs/apollo-server/). So PRs for documentation changes and additions are welcome.

For `logFunction` specifically, I'm not actually a big fan of the current API and would prefer to find a way to change it. So I wasn't too sad it wasn't documented so not too many people would depend on it :) In particular, I would like to avoid these `status` steps and see how event logging can be unified with [Apollo Tracing](https://github.com/apollographql/apollo-tracing-js).

What is your use case for this?

**Comment by alexturek** [comment]
Gotcha, yeah the way `logFunction` works is a little surprising. We have some extra code around it to get it to behave the way we want.

Our use case is logging/tracing of response time and request/response data. I'm working on a patch from our (very old) version of `apollo-server` (0.2.4), so I'm trying to minimize the amount of code I'm changing at once.

If I wrote a quick doc for `logFunction` would you accept the PR? If it's going away soon I'm fine with leaving it undocumented and just using this ticket as my personal reminder for event sequence 😄

**Comment by martijnwalraven** [comment]
I think leaving it undocumented is probably best for now, because I'd prefer not having more people depend on it. I'd be interested in discussing what a better API would look like however, although I suspect for your use case Apollo Tracing may actually be a better fit.

**Comment by nevir** [comment]
Jumping in a bit - my understanding of apollo-tracing is that it emits the traced metrics as part of the response?  Seems like we would need to wrap apollo in middleware that would then read the tracing data, and then drop it from the response (except for cases where we do want it to forward)?  (Might also be problematic for tracing responses that ultimately lead to a server error)

Ideally, I think, we'd want the tracing hooks exposed so that we can log/trace specific metrics along the way without having to mutate the response

**Comment by martijnwalraven** [comment]
Yes, Apollo Tracing emits metrics as part of `extensions` in the response. In development, you could use [GraphQL Playground](https://github.com/graphcool/graphql-playground) to see the tracing data. And in production, Engine functions as a proxy that strips out the trace data and sends it to the Engine backend for analysis.

I agree we also want tracing hooks exposed for people to do what they want without modifying the response. Currently, Apollo Tracing depends on an undocumented [`graphql-extensions`](https://github.com/apollographql/graphql-extensions/blob/98f12f5ba1848ca1ce8199a9167b3572cd9b4056/src/index.ts#L10-L32) package, and I would like to see how we can make this into an API that people can build on even if they are not adding data to `extensions`.

**Comment by brandondoran** [comment]
@martijnwalraven I would love to see the extensions mechanism part of the API so that I could add my own. Anything I can do here to help?  Without digging too deep, it seem like it could be as easy as adding support for an `extensions` option, which would be an array of `GraphQLExtension`. I think that is the same as @nevir mentioned.

I could take a stab at it if you agree with the approach/direction?

**Comment by martijnwalraven** [comment]
@brandondoran I definitely think an extensions mechanism should be part of the API. Depending on what you want to do, the current `GraphQLExtension` approach may be a bit too heavy though, because it receives calls for events that you may not need. Maybe we should separate the ability to add data to `extensions` from receiving events. @abernix @benjamn, do you have ideas about this?

What kind of extension are you looking to add?

**Comment by brandondoran** [comment]
@martijnwalraven my use case was for adding instrumentation/tracing to resolvers.  I know that's what Engine is for but since I already have standard tools for instrumentation and tracing, I didn't want to introduce something new.

Since I'm not wanting to add data to the extensions field in the response, trying to use the extension mechanism for this this doesn't feel quite right. Now that [schema directives](https://www.apollographql.com/docs/graphql-tools/schema-directives.html) are out, that feels like a good way to accomplish it.

**Comment by JacksonKearl** [comment]
Closing this issue as it looks like we're migrating away from `logFunction` in general. Feel free to open an issue if you need any help with schema directives or extensions! (I realize this is old, but just in case 🙂)
