### ISSUE TITLE
[plugin] Expose graphQL operation query "path" for handlers other then didEncounterErrors 

### ISSUE THREAD

**Issue by liornaar** [apollographql/apollo-server#6880]
Developing a plugin and while managed to get the "path" in the error obj:

```
class MyPlugin implements ApolloServerPlugin {
    async requestDidStart(_requestContext: GraphQLRequestContext<BaseContext>): Promise<GraphQLRequestListener> {
        return {
            async didResolveOperation(requestContext) {
               myContext.operationName = requestContext.operationName;
            },
            async didEncounterErrors(requestContext) {
                requestContext.errors?.forEach((e) => {
                    logger.error(`encountered an error while trying to process request. ${e.name}: ${e.message} in ${requestContext.operationName}/${e.path} `);
                });
            }
        };
    }
}
```

it appears that this is not available in `didResolveOperation` or any of the other middleware

I do see that `GraphQLError` exposes a `path` property but could not find on any others 
can this be added? or am I missing something?

**Comment by glasser** [comment]
What kind of thing are you referring to for which you would like to have a path?

Errors that happen because a field's resolver throws have paths that tell you which field's resolver threw. That's what it means.

Can you provide an example of a different thing on which it would be helpful to have a path?
