### ISSUE TITLE
Would Apollo support Digital Ocean Functions? (code attached)

### ISSUE THREAD

**Issue by gja** [apollographql/apollo-server#6895]
Would this team be in favour of adding support for Digital Ocean Functions (via a new apollo-server-digitalocean)? DO Functions is a server less platform. 

I do have a working prototype below. If the team is in favour of supporting this platform, then I'll raise another PR with a 'apollo-server-digital-ocean-function' module added (after cleaning it up, adding tests, etc...).

```javascript
const { ApolloServerBase,  isHttpQueryError, runHttpQuery } = require('apollo-server-core');

function buildRequest({__ow_method, __ow_body, __ow_headers, __ow_path, __ow_isBase64Encoded, ...body}) {
  return {
    method: __ow_method.toUpperCase(),
    path: __ow_path,
    headers: __ow_headers,
    body: __ow_body
            ? {query: __ow_isBase64Encoded ? Buffer.from(__ow_body, 'base64').toString() : __ow_body}
            : body
  }
}

class ApolloServer extends ApolloServerBase {
  serverlessFramework() {
    return true;
  }

  createGraphQLServerOptions(req) {
    return super.graphQLServerOptions({ req });
  }

  createHandler() {
    return async (args) => {
      try {
        const request = buildRequest(args);

        if (request.method === 'POST' && !request.body) {
          return {
            body: 'POST body missing.',
            status: 400,
          };
        }

        await this.ensureStarted();
        const options = await this.createGraphQLServerOptions(request);
        const { graphqlResponse, responseInit } = await runHttpQuery(
          [request],
          {
            method: request.method,
            options: options,
            query: request.body,
            request: {
              url: request.path,
              method: request.method,
              headers: new Headers(request.headers),
            },
          },
          this.csrfPreventionRequestHeaders,
        )
        return {
          body: graphqlResponse,
          status: responseInit.status || 200,
          headers: responseInit.headers,
        }
      } catch(error) {
        if (isHttpQueryError(error)) {
          return {
            body: error.message,
            status: error.statusCode,
            headers: error.headers,
          };
        } else {
          throw error;
        }
      }
    }
  }
}

exports.main = new ApolloServer(stuffHere).createHandler();
```

**Comment by trevor-scheer** [comment]
Hey @gja, we won't be accepting any new integrations in this repo or for Apollo Server 3. You are of course welcome to write and publish them yourself, though!

Apollo Server 4 is right around the corner. We no longer wish to maintain these integrations ourselves, since we prefer time invested in this repo to be directed at solving specifically Apollo Server / GraphQL problems rather than a whole array of server frameworks. The good news is that we've made it a lot simpler to build them, with a much more favorable API. I'd really encourage you to have a look, it would be great to see community packages like what you're proposing!

Here are docs for guidance:
https://www.apollographql.com/docs/apollo-server/v4/integrations/building-integrations

Here's an example of a Lambda integration, which should be fairly similar to yours:
https://github.com/apollographql/server-v4-integration-demos/tree/main/packages/lambda

Also note we have a change to our docs in flight recommending a naming convention for serverless functions:
https://github.com/apollographql/apollo-server/pull/6922
