### ISSUE TITLE
Test suite for custom server integrations

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-server#6916]
With the upcoming changes in v4 on how server integrations are to be implemented and maintained, it would be nice to have an extensive test suite (say in form of a postman collection) that one can use to verify that the implementation is correct. This is similar to the existing diagnose-endpoint package, but should also test for common features (e.g. landing page, cors setup for apollo studio) and invoke a set of standardized graphql queries (and checks their result). Then as a developer of a sever integration one only needs to worry about setting up the test server (with the test data) in a way that is specific to the particular integration and then run the test suite (e.g. as part of ci).

**Comment by trevor-scheer** [comment]
Hey @tobiasdiez, we have a package that exports a jest test suite which we've been using to validate integrations. It only requires that you handle setup and tear down of the server.

There are at least a couple drawbacks to this approach:
* If you're familiar with jest testing and debugging, the experience of digging into test failures coming from an exported package is not great. Effectively you have to play around in the compiled code.
* This obviously imposes a requirement on integration authors to use jest.

Here's an example of how it's meant to be used. This test file runs something like ~150 integration tests that are identical to the tests running against Apollo Server Express.

https://github.com/apollographql/server-v4-integration-demos/blob/main/packages/fastify/src/__tests__/integration.test.ts

Curious to hear your thoughts!

**Comment by tobiasdiez** [comment]
This looks really nice, thanks for the pointer! One thing that I'm missing (but maybe I overlooked it) are some form of e2e tests where you only specify an url and test a deployed (or locally running) apollo-server. 

> If you're familiar with jest testing and debugging, the experience of digging into test failures coming from an exported package is not great. Effectively you have to play around in the compiled code.

I have no experience with this, but can't this be solved by shipping sourcemaps along in the jest testing package?

> This obviously imposes a requirement on integration authors to use jest.

I guess this would be okay, although alternatives such as vitest are gaining traction.

**Comment by trevor-scheer** [comment]
@tobiasdiez the source maps are shipped with the package, but I haven't had success making use of them. This is possibly a limitation of Jest (+ Typescript, maybe). It's in a usable state now and with AS4 around the corner, it's not something I've spent much time investigating. If someone who knows more about Jest, node debugging, sourcemaps, etc. than I the help would be appreciated! It's also one of those things that might not be worth perfecting - ideally integration authors do most of the work up front, get tests passing, and make very few changes beyond that, aside from major version upgrades for their framework of choice.

We don't intend to build an e2e suite like you're asking for. While I don't think it's a bad idea, I think it's mostly duplicative of the approach we've taken. We still stand up a server, send it requests, and inspect the result. We also don't require you to run the server or provide a schema, resolvers, data, runtime config, etc., since that's all handled via the testsuite. Is there something about the testing approach itself that you find insufficient?

In thinking about this more, I also realize the jest requirement is not as heavy-handed as I'd first thought. Authors would still be free to run their own tests in a different framework, but would set up jest for the sake of running the integration tests only.

**Comment by tobiasdiez** [comment]
> We don't intend to build an e2e suite like you're asking for. While I don't think it's a bad idea, I think it's mostly duplicative of the approach we've taken. We still stand up a server, send it requests, and inspect the result. We also don't require you to run the server or provide a schema, resolvers, data, runtime config, etc., since that's all handled via the testsuite. Is there something about the testing approach itself that you find insufficient?

This sounds reasonable. The only limitation that I can see is that some framework integrations might be a bit hard to find and fix. For example, if you develop an apollo-server for azure functions then you would like to make sure that it also really works if you deploy it to azure (or run it locally in the emulator). But maybe it's just my frustration speaking after spending 2 days chasing a strange bug revolving around async `res.end` calls, where the code worked perfectly fine on its own but stopped working in Azure functions.

**Comment by glasser** [comment]
The test suite is built around specific test schemas that exercise various behavior, so it's not a great fit for "just run against an existing server". Having a separate sort of "smoke test" that runs against an arbitrary running server could be nice too, I guess, but that's a bit different (and it would be hard to make it validate all the different edge cases).
