### ISSUE TITLE
Distribute integration-testsuite as esm

### ISSUE THREAD

**Issue by tobiasdiez** [apollographql/apollo-server#7042]
Importing `` in an esm context yields the error
```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/workspaces/apollo-server-integration-h3/node_modules/.pnpm/@apollo+server-integration-testsuite@4.0.0_@apollo+server@4.0.0/node_modules/@apollo/server-integration-testsuite/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
 ❯ node_modules/.pnpm/@apollo+server-integration-testsuite@4.0.0_@apollo+server@4.0.0/node_modules/@apollo/server-integration-testsuite/dist/index.js:2:23
 ❯ async /workspaces/apollo-server-integration-h3/test/index.test.ts:1:256
```
And in fact, the `package.json` specifies it as `type: module` but only commonjs files are distributed.

**Comment by olyop** [comment]
The package has a root `package.json` with `"type": "module"` so of course this will fail with CommonJS. Are you not able to run the test suite with `"type": "module"`?

@trevor-scheer I assume the fix would be to add `'integration-testsuite'` to the list of directories [here](https://github.com/apollographql/apollo-server/blob/main/scripts/postcompile.mjs#L15) and make the build script output both module types so people can import the test suite using CommonJS? :)

**Comment by glasser** [comment]
I think our intention was to distribute the test suite as a single build rather than as a dual build, but only as ESM. You're right — it looks like we have CJS files with `type: module` which is wrong. Not sure how this is working with the integrations that have already been set up, though we may have just done something strange with the `ts-jest` setup in the other integrations.

I do agree it would be better to use somebody else's tool than to try to figure out how to do dual-build by ourselves. I didn't find unbuild when looking into this a few months ago. Unclear if it supports multiple import path entry points...

**Comment by tobiasdiez** [comment]
As far as I know the esm support of jest is still pretty bad, so maybe commonjs-only would be a better option (or of course valid dual-build).

(the error also only appeared since I tried to run the test suite with vitest - which is not a good idea anyway...so nothing urgent)

**Comment by glasser** [comment]
OK, so sounds like the right fix may be to just remove the `type: module` from the integration testsuite package.json?
