### ISSUE TITLE
Type error in apollo-server-core because @types/fs-capacitor have been removed

### ISSUE THREAD

**Issue by Yogu** [apollographql/apollo-server#7060]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62785 removed the types for fs-capacitor and replaced it with a stub. apollo-server-core uses https://github.com/apollographql/graphql-upload, a fork of graphql-upload, which specifies "*" for this package. Therefore, starting yesterday, using apollo-server-core 2 causes a type error.

I created a pull request that fixes this https://github.com/apollographql/graphql-upload/pull/3. I'm opening an issue here, too, because I'm not sure how closely watched that fork is.

**Comment by glasser** [comment]
Thanks, this is fixed in v2.26.1

Note that Apollo Server has been de facto deprecated since July 2021; we will shortly be putting our deprecation/end-of-life policy in writing. We highly recommend upgrading to Apollo Server 4 as soon as possible.  (The graphql-upload package which caused this issue and which has been removed from AS3 is particularly problematic, as using it in AS2 without security features added in AS3 is likely to create a major security hole in your app.)

**Comment by Yogu** [comment]
Thank you!
