### ISSUE TITLE
Apollo Server sandbox explorer passes cookies locally when includeCookies is set to false

### ISSUE THREAD

**Issue by bigman73** [apollographql/apollo-server#7082]
## Description
Apollo Server v4's sandbox explorer landing page has a property named `includeCookies`.
The property is documented to default to `false`.
https://github.com/apollographql/apollo-server/blob/6808c3b960cac09d759ba6f3c9b3e22fcda2d286/docs/source/api/plugin/landing-pages.mdx#includecookies

However, when executing a query in the explorer against a local service the cookies are passed to the resolvers.

## Version
@apollo/server: 4.0.2

## Version of Apollo Server that didn't happen
apollo-server-core: 2 (with playground, before the sandbox landing page)
apollo-server-core: 3 (with playground landing page)

## Expected behavior
When `includeCookies` is set to false (the default) no cookies should be passed to the resolvers, in any scenario, including a local service

## Actual behavior
Cookies are passed to the resolvers in local service mode

## Reproducing
I created another ticket in 
https://github.com/apollographql/embeddable-explorer/issues/176

**Comment by glasser** [comment]
Good catch. The exact difference in question isn't AS4 vs AS3, but embedded vs non-embedded Explorer (and the default for this changed in AS4). Looks like `includeCookies: false` maps to `credentials: 'same-origin'`, so this has a different effect when embedded and when not embedded because the origin is the same when embedded.

I'm not sure if the best fix is your PR (https://github.com/apollographql/embeddable-explorer/pull/177) or to improve the docs or to provide a third option here. I do worry that other users of Embedded Explorer/Sandbox may be accidentally relying on the fact that cookies are sent to same-origin servers even without `includeCookies: true` (and I'm not quite an expert on exactly how the release process of EE goes, eg whether this could be a major-version bump on the npm packages). Gonna pass this over to the team that maintains Explorer and Sandbox.

**Comment by bigman73** [comment]
Hey @glasser 
Thanks for the details and information

I agree that exposing a 3 state credentials option instead of the 2 state `includeCookies` is a better solution, with 1:1 straightforward mapping.
But since AS4 already has breaking changes, maybe includeCookies which is a strict `omit` will be a better secure solution. Those that rely on `same-origin` could just use includeCookies: true

**Comment by glasser** [comment]
Just to be clear, as far as I know there's no difference specific to AS4 here — the exact same behavior was available in AS3 if you set `embed: true` on the default landing page plugin.

**Comment by bigman73** [comment]
Got it, thanks for the clarification.
I did use the Playground landing page in my AS3. Let me fix the description of this issue.
