### ISSUE TITLE
Can't find stored session after refresh

### ISSUE THREAD

**Issue by gimtwi** [apollographql/apollo-server#7186]
Hello, I'm trying to create a simple logging app with  express-session, connect-mongodb-session and apollo-server-express and apollo-client for UI.
![1](https://user-images.githubusercontent.com/89921028/203531574-dfa81996-ba45-48a7-afd5-4c5487702d18.png)
![2](https://user-images.githubusercontent.com/89921028/203531596-e4bc833e-1cf4-4779-bb14-6c77404787ac.png)

Here is my login function: 
![3](https://user-images.githubusercontent.com/89921028/203531763-6f0036be-21c3-466d-9073-ffe6eea6dcad.png)

Here I'm finding session from the context to use it for protected routes in UI:
![4](https://user-images.githubusercontent.com/89921028/203532084-87f45a9f-36a0-435b-9121-faa27e4791f5.png)

It works on GraphQL Playground:
![5](https://user-images.githubusercontent.com/89921028/203532533-c75a8f88-3c4c-4e7a-b7fe-d20be45fa095.png)

And I can store cookie on UI as well: 
![6](https://user-images.githubusercontent.com/89921028/203534146-ee356b4e-3dfa-466b-8d20-b2f6c97a6441.png)

Here is UI code:
![7](https://user-images.githubusercontent.com/89921028/203534340-fc20ed03-13a5-4731-b61e-5b13f3a07834.png)
![8](https://user-images.githubusercontent.com/89921028/203534524-20a2add2-7c37-47af-a386-71d7bd91b90f.png)

The problem is that after refresh, cookie does not diaper, but ItIsMe querie does not work as intended.
Meaning when I'm requesting ItIsMe querie it returns null unlike GraphQL Playground behavior
![8](https://user-images.githubusercontent.com/89921028/203535719-b6f5b43d-d633-4ea8-bd77-9c1be3c9aa96.png)

If anyone knows where the problem could be, please help me out. Thanks.

**Comment by glasser** [comment]
Hi. It seems like there's a lot of different software components in use here. The issue you're facing is likely a complex interplay between the precise versions you have set up. There's really no way we'd be able to reproduce and help fix it based on a bunch of screenshots of sample code. If you'd like us to dive in and give it a shot, the bare minimum is giving a complete reproduction where we can see what you're running without any creativity (typically a series of steps starting with `git clone` or using codesandbox.io or something).

Additionally, it looks like you're using Apollo Server 3, which is now deprecated; if it does turn out that this is related to Apollo Server then I'd recommend you try to reproduce with Apollo Server 4 (`@apollo/server`).

Finally, it does seem likely that the issue you're facing is more of an Apollo Client issue than Apollo Server, given that you're seeing a difference between Playground and Apollo Client behavior, so you may get more help filing your reproduction over in the apollo-client repository rather than here.

**Comment by gimtwi** [comment]
Hello @glasser. Thank you for the answer. It was a client problem indeed, SSR caused the issue. https://github.com/apollographql/apollo-client/issues/10311
