### ISSUE TITLE
includeCookies didn't work and cookie cannot be attached

### ISSUE THREAD

**Issue by jochenshi** [apollographql/apollo-server#7214]
when using below config for apollo/server
```
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [
    ApolloServerPluginLandingPageLocalDefault({includeCookies: true})
  ]
});
```
and add custom header for `Cookie` in Landing Page
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/25789160/205086795-ca26efeb-5bc2-4a99-9478-3f9c141ac59f.png">

and then in apollo server side，i cannot find the `Cookie` property
<img width="890" alt="image" src="https://user-images.githubusercontent.com/25789160/205087183-3af1b972-a76d-44be-ba66-ba56949c1d2d.png">

**Comment by trevor-scheer** [comment]
Hey @jochenshi, the `cookie` header can't be set manually this way, this is actually forbidden by the fetch spec:
https://fetch.spec.whatwg.org/#forbidden-request-header
This is definitely a gotcha, so we've opened a ticket to offer some helpful information when you try to set a forbidden header in the UI like this.

You need your server to respond with the [`set-cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header in order to accomplish this. You can do this yourself with an Apollo Server plugin, or there are various express middlewares that will handle cookie/session-related logic for you (you'll need to [switch to `expressMiddleware`](https://www.apollographql.com/docs/apollo-server/api/standalone#swapping-to-expressmiddleware) to do that.
