### ISSUE TITLE
Retry request on Error

### ISSUE THREAD

**Issue by HectorDavila** [apollographql/apollo-server#7318]
Is there a way to retry a request on an error on Apollo Server? I know this can be achieved on Apollo client using Links but i wonder if there is a plugin that I can use to implement it on Apollo Server (most of our clients do not use Apollo client).

**Comment by trevor-scheer** [comment]
I don't quite understand the question. Retry which request? Apollo Server sends requests to Studio (if configured to) but otherwise it doesn't send HTTP requests.

If you're asking for Apollo Server to retry graphql execution if it encounters errors, no it doesn't do that (and I don't think it's possible to do in our plugin system but it might be if you abuse a combination of `responseForOperation` and `didEncounterErrors` just right, which I wouldn't recommend).

What problem are you trying to solve?

(this isn't an issue so I'm going to close but happy to continue the conversation here)

**Comment by HectorDavila** [comment]
@trevor-scheer  yes, i was asking for Apollo Server to retry graphql execution if it encounters errors. I have an Apollo Federation arquitecture in place and would like the Graph Router retries a graphQL execution  when it fails on a subgraph.

As I told you there are some clients that are not using Apollo Client so we would like to have the retry mechanism in a central place such as the Graph Router, is it possible?

**Comment by trevor-scheer** [comment]
Ok, I just want to be clear about what you're asking for. There are potentially 2 different things going on here.

1. Router retries: It sounds like this is what you're after. Apollo Server does nothing special. If the Router sees errors in a subgraph response it retries the query. If this is what you're after, I would open an issue in the Router repo: https://github.com/apollographql/router.
2. Apollo Server retries internally. If this is what you're after, I'm imagining this scenario: client (or router) sends request to Apollo Server. AS encounters errors during execution, so it retries the request until it succeeds (or reaches a limit) and finally responds to the client (or router).

I don't think we would implement the second option. If it's the first option you want that might be up for discussion in the Router repo.
