### ISSUE TITLE
Docs: Lambda deployment docs: `requestContext`

### ISSUE THREAD

**Issue by mxmcg** [apollographql/apollo-server#7327]
### Issue Description

Today, I was following [this documentation](https://www.apollographql.com/docs/apollo-server/deployment/lambda/#running-locally). 

I kept encountering the following error when running
`serverless invoke local -f graphql -p query.json`

![Screenshot 2023-01-25 at 1 37 58 PM](https://user-images.githubusercontent.com/8016859/214697004-c5e952ab-6e75-4e5f-bccc-899790199964.png)

`query.json` before
```
{
  "version": "1",
  "httpMethod": "POST",
  "path": "/",
  "headers": {
    "content-type": "application/json"
  },
  "requestContext": {}, # This is the problematic line
  "rawQueryString": "",
  "body": "{\"operationName\": null, \"variables\": null, \"query\": \"{ hello }\"}"
}
```

`query.json` fixed
```
{
  "version": "1",
  "httpMethod": "POST",
  "path": "/",
  "headers": {
    "content-type": "application/json"
  },
  "requestContext": { "http": { "method": "POST" } }, # Adding these fields seems to resolve the issue.
  "rawQueryString": "",
  "body": "{\"operationName\": null, \"variables\": null, \"query\": \"{ hello }\"}"
}
```

In the recent update of `"@as-integrations/aws-lambda": "^2.0.0",`, I noticed [this line](https://github.com/apollo-server-integrations/apollo-server-integration-aws-lambda/blob/main/src/request-handlers/APIGatewayProxyEventV2RequestHandler.ts#L14), where there is an expected field, `http.method`

### Link to Reproduction

https://github.com/apollographql/apollo-server/blob/main/docs/source/deployment/lambda.mdx

**Comment by BlenderDude** [comment]
I think the real issue lies in that the example local query demonstrates a ProxyV1 event, while the serverless deploy would be a ProxyV2 event. All of this and other updates in the docs have been fixed in the PR above.

If you take a look at the PR, you can see that the new event is `"version": "2"` and has the `requestContext` filled properly.

I am working on an update to the integration such that local development can be done without any local event crafting. Keep an eye out for `2.1`!
