### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by alucardu** [apollographql/apollo-server#7405]
### Issue Description

I'm trying to access my WebSocket server through a browser but in Chrome I get an connection error:

![image](https://user-images.githubusercontent.com/779921/221887050-6778666c-6fea-466a-8d23-9e1b780c2562.png)

And in Edge I get:

![image](https://user-images.githubusercontent.com/779921/221887090-39cb18b1-0af0-4415-9c1e-faf448c10659.png)

### Link to Reproduction

https://github.com/alucardu/ti4-automation/tree/36-add-apollo-websockets-server

**Comment by glasser** [comment]
Hi! Subscriptions are no longer a part of Apollo Server, although we do document how to integrate third-party subscription libraries alongside your Apollo Server. I did take a look at your repository, but it wasn't exactly clear what you had done because you had no reproduction steps. I figured out how to run your server and was able to connect to it from Apollo Explorer, so it seems like your problem must be in your client. It looks like you are combining the old [WebSocketLink](https://www.apollographql.com/docs/react/api/link/apollo-link-ws/) which implements a deprecated WS protocol with the more modern graphql-ws; you probably want to be using [GraphQLWsLink](https://www.apollographql.com/docs/react/api/link/apollo-link-subscriptions) instead.
