### ISSUE TITLE
I am using apollo studio as IDE facing an issue with CORS configuration. 

### ISSUE THREAD

**Issue by saiteja9177** [apollographql/apollo-server#7491]
There are certain headers not explicitly configured in CORS but still pass through CORS(example like Proxy-Authenticate and Proxy-Authorization). In general, these headers are not safe and can potentially leak sensitive information or allow for malicious attacks, so they are not allowed by default in CORS. Is apollo studio including these headers by default?

**Comment by trevor-scheer** [comment]
I'm not sure what you mean exactly by:
>Is apollo studio including these headers by default
Can you help me understand the question?

You can set which headers Studio sends, and you can inspect the outgoing request in the network tab to verify exactly the shape of the outgoing request. I'm not exactly familiar with the `proxy-` headers, but it looks like the [fetch spec forbids them](https://fetch.spec.whatwg.org/#forbidden-request-header) (which I think you've noted).

**Comment by saiteja9177** [comment]
My CORS configuration is set up as follows:
const corsOptions = {
    origin: origin,
    allowedHeaders: ['Content-Type', 'Authorization', 'x-transaction-id', 'x-correlation-id', 'x-source-channel'], 
    maxAge: 86400, // cache preflight response for 24 hours
    preflightContinue: false // stop processing middleware chain if preflight fails
};                                                                                                                                                                                                  
I have not allowed headers such as Proxy-Authenticate and Proxy-Authorization. However, when I set these headers (Proxy-Authenticate and Proxy-Authorization) in Apollo Studio IDE, I still receive a response. I am experiencing the same issue with other default headers present in the Studio. Even though my CORS configuration is not allowing these headers, I am still able to receive a response instead of an error.
Below are some examples of Headers 
![image](https://user-images.githubusercontent.com/54308352/229978540-f242767e-b203-44bb-a5e7-99f9eae50902.png)

**Comment by trevor-scheer** [comment]
@saiteja9177 can you confirm those headers are actually being sent when you inspect the request that the browser sends? I suspect they aren't actually being included in the request.

For what it's worth, those `proxy-` headers shouldn't be there at all since they are forbidden, so I've removed them from the suggested list. I just landed that change within the last hour, so you should see those disappear from the list soon.

I'm going to close this since I think it's behaving as expected, but if you show me an outgoing network request where those headers are somehow included I'll reopen.
