### ISSUE TITLE
preventCsrf

### ISSUE THREAD

**Issue by Hellomik2002** [apollographql/apollo-server#7511]
### Issue Description

can not recognize multipart/form-data because it tries to find 
explicit string multipart/form-data
but in header it contains boundary too

### Link to Reproduction

https://gitlab.com/Hellomik/clinic-node-1

### Reproduction Steps

upload photo with Altair in checkINN query

**Comment by glasser** [comment]
I think it would help to have a more explicit description of the problem (and ideally a much more minimal reproduction with way fewer dependencies as well). For example, I can't tell if your problem is that the CSRF prevention feature incorrectly fails to block a problematic request, or that it incorrectly blocks a non-problematic request.

**Comment by simpyparveen** [comment]
@glasser @Hellomik2002 
CSRF is right protective feature. There sre work around some requests that feature blocks. For example, uploading a file on client side, server prevents it. 
This can be resolved by passing {headers: {'Apollo-Require-Preflight': 'true'}} to createUploadLink ( I use apollo-upload-client package with Apollo Client Web, to make upload work without throwing CSRF error). This means we allow our client to upload file.

**Comment by trevor-scheer** [comment]
Closing, stale and needs reproduction.
