### ISSUE TITLE
Setting header &  method GET/POST/PUT in GrapiQL

### ISSUE THREAD

**Issue by pvsong** [apollographql/apollo-server#760]
Hi, how can I custom method and header with graphiqlExpress
I want to set Authorization to header like this.

![screen shot 2018-01-14 at 1 09 00 pm](https://user-images.githubusercontent.com/9800579/34913334-696f08ec-f92c-11e7-8780-f287750344e2.png)

![screen shot 2018-01-14 at 1 17 56 pm](https://user-images.githubusercontent.com/9800579/34913375-655096da-f92d-11e7-8451-a3ab3fbae8b3.png)

**Comment by jaredtmartin** [comment]
Yes! This would be wonderful. I know the [graphiQL team has determined their project is not the right place for this feature](https://github.com/graphql/graphiql/issues/500) in part because they also work with web socket connections, but this project IMHO would be the perfect place for this feature to be implemented.
Right now I'm working to make my graphQL server work with normal Meteor authentication.  This feature would be wonderful!

**Comment by martijnwalraven** [comment]
Closing this issue because Apollo Server 2 includes GraphQL Playground.
