### ISSUE TITLE
@apollo/usage-reporting-protobuf decoder is not able to read variables correctly in some cases

### ISSUE THREAD

**Issue by josselinbuils** [apollographql/apollo-server#7663]
**Describe the bug**
Hello,

We found an issue related to the protobuf encoding behaviour being different between gateway and router so the `@apollo/usage-reporting-protobuf` is not able to decode router usage data correctly.

By default, the variables are sent with empty string as values due to this code: https://github.com/apollographql/router/blob/3be45c458c6795a0be6ab2bc4ba175c9de7758ef/apollo-router/src/plugins/telemetry/mod.rs#L765

Until there, the gateway behaviour is the same so everything is ok but the `prost` protobuf encoder used in the router does not seem to encode empty strings the same way than the gateway does so the `@apollo/usage-reporting-protobuf` decoder is not able to read them correctly and read the next property instead:

As exemple, whereas data (`trace[0].details.variablesJson`) from the gateway is decoded like this:

```
key: 'campaignsMarket'
value: ''
```

The same data from the router will be decoded like this:

```
key: 'campaignsMarket'
value: '\n\x0EcampaignsSpace'
```

where `campaignsSpace` is the next variable.

Here is the query that generated this usage data:

```gql
query campaigns(
      $platform: Platform!
      $campaignsMarket: Market!
      $campaignsSpace: Space!
    ) {
      campaigns(
        platform: $platform
        market: $campaignsMarket
        space: $campaignsSpace
      ) {
        redirectionUrl
        creativeMobile {
          url
        }
      }
    }
```

**To Reproduce**
1. Setup services '...'
2. Submit request '....'
3. See error

**Expected behavior**

The variables should be encoded the same way between gateway and router so the `@apollo/usage-reporting-protobuf` can read them wherever it is coming from or the `@apollo/usage-reporting-protobuf` decoder should be compatible with both versions.

**Output**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.0.1

**Additional context**

Let me know if you need any other information.

**Comment by trevor-scheer** [comment]
Note: I'm going to preemptively close this since it's somewhat stale and I don't know whether or not this is actually an issue. I'm happy to reopen it if there's still interest and with some more explanation of the problem.

@josselinbuils I think I don't quite understand the issue, but these are my thoughts so far.

What problem are you trying to solve? I don't quite follow why the `@apollo/usage-reporting-protobuf` package would ever need to decode reports that the router sends. i.e. What's the use case?

The protobuf that router and the `@apollo/usage-reporting-protobuf` package do appear to be in sync (at least in latest versions / on the `main` branches), so presumably any difference you'd see in encoding/decoding would lie in the implementation of the dependencies that are in use by the two projects respectively (i.e. `prost` in router and `protobuf.js` (our fork of it, anyway) in `@apollo/usage-reporting-protobuf`).

Maybe a more comprehensive reproduction would make for a more helpful jumping off point in explaining what you're after. Can you create a repository with instructions that I can clone, run some commands, and reliably see the issue?
