### ISSUE TITLE
API Mass Assignment Mitigation

### ISSUE THREAD

**Issue by zach-betz-hln** [apollographql/apollo-server#7874]
## Background

I looked through the docs and existing issues, so forgive me if this feature already exists.

Our services are scanned by an external team. This team does penetration testing, and they claim our Apollo GraphQL services are vulnerable to something they deem _API Mass Assignment_. To quote their scan report:

> - **Risk**: API Mass Assignment exploitation may lead to privilege escalation, data tampering, bypass of security mechanisms.
> - **Cause**: API endpoints are vulnerable to Mass Assignment if they automatically convert client provided data into internal object properties without considering the sensitivity and the exposure level of these properties.
> - **Fix**: Avoid using functions that automatically bind client's input to code variables or internal objects. If applicable, explicitly define and enforce schema's for the input data payloads.

We understand their concern, and we've explained to them that Apollo _does indeed_ do schema validation, but it silently ignores any invalid fields passed in the request body.

This wasn't good enough. They expected a `400 Bad Request` response when invalid fields were added to the request body.

We ended up developing a custom solution. It's a plugin that hooks into the `didResolveSource` event, parses the request body, then validates the fields against an allow-list. If invalid fields are found, it responds with the relevant error. See snippet below.

## Question/feature

- Does Apollo have this feature built-in?
- If not, what are your thoughts on adding it?
- Otherwise, would you make any improvements to this approach?

Thanks for your time, and thanks for this server 👍 

## Snippet

<details><summary>Details</summary>

```ts
export class BadRequestGraphQLError extends GraphQLError {
  constructor(message: string) {
    super(message, {
      extensions: {
        code: 'BAD_REQUEST',
        http: {
          status: 400
        }
      }
    });
  }
}

const ALLOWED_BODY_FIELDS = ['operationName', 'variables', 'query', 'extensions'];

export const massApiAssignmentValidationPlugin = <TContext extends BaseContext>(params: {
  logger: Logger;
}): ApolloServerPlugin<TContext> => {
  const { logger } = params;

  return {
    async requestDidStart() {
      return {
        async didResolveSource(requestContext) {
          const body = (requestContext.request.http?.body ?? {}) as Record<string, unknown>;

          const invalidFields = Object.keys(body).filter((field) => {
            return !ALLOWED_BODY_FIELDS.some((allowedField) => {
              return field === allowedField;
            });
          });

          if (invalidFields.length > 0) {
            const message = `Invalid fields detected: ${invalidFields.join(', ')}`;
            logger.error(message);
            throw new BadRequestGraphQLError(message);
          }
        }
      };
    },

    // We have to re-throw the error, otherwise a generic 500 error is thrown.
    // See https://github.com/apollographql/apollo-server/issues/7278
    async unexpectedErrorProcessingRequest({ error }) {
      if (error instanceof BadRequestGraphQLError) {
        throw error;
      }
    }
  };
};

export interface ApolloServerContext {
  dataSources: {
    // existing data sources...
  };
}

const apolloServer = new ApolloServer<ApolloServerContext>({
  // existing configs...
  plugins: [
    // existing plugins...
    massApiAssignmentValidationPlugin<ApolloServerContext>({ logger })
  ]
});
```

</details>

**Comment by glasser** [comment]
I'd be disinclined to make this change. The [GraphQL-over-HTTP spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md) (which to some degree we try to follow and to some degree we try to improve) doesn't prescribe behavior here, just stating

> All other property names are reserved for future expansion; if implementors need to add additional information to a request they MUST do so via other means, the RECOMMENDED approach is to add an implementor-scoped entry to the {extensions} object.

GraphQL requests didn't support `extensions` originally. When we tried to add it in our clients, we found it pretty frustrating that a few GraphQL servers had exactly the behavior you described above of rejecting POST bodies with unknown keys — it meant any feature that used request-side extensions had to carefully be opt-in so that you wouldn't accidentally use it against one of these stricter servers.  I wouldn't want Apollo Server to cause the same sort of issue for the future.

You could posit that this issue was unique to adding `extensions` since now that `extensions` exists, it is itself the right place to put new keys. But the GraphQL spec itself could add new top-level fields here, and it would be imaginable that some field could be added that would be OK if the server didn't know about it, so I'd rather not paint us into a corner and prevent those sorts of gradual-adoption new features by rejecting these requests immediately.

It looks like our plugin API more or less suits your use case. If many people have the same issue we could consider adding it to the docs but for now I'd prefer us to not make our servers stricter unless there's an actual security issue being triggered.

**Comment by zach-betz-hln** [comment]
That reasoning makes sense. Thanks for the history on the `extensions` object.
