### ISSUE TITLE
Custom error In Graphql Query Response

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/apollo-server#807]
How can I respond with custom Errors while querying:   

 app.use('/graphql', graphqlExpress((req) => {

        return new Promise((resolve,reject) => {
            

            let user;
            let loader = Loader()
            if(!req.headers['authentication-token'] || true){
                throw new ErrorResponse([{key: 'authentication', message: 'Authentication Token is not 
                provided' }]);

            }

            req.session.reload(function (err) {
                let base_context = {
                    orders: orders,
                    users: users,
                    ppsList:ppsList,
                    auth_token: req.headers['authentication-token']
                }
                if (err) {
                    loader.CurrentUserLoader(req.headers['authentication-token']).load(req.headers['authentication-token']).then(function (res) {
                        if(!res){
                            throw new ErrorResponse([{key: 'authentication', message: 'Authentication failure' }]);
                        }
                        req.session.current_user = res
                        logger.info("Session Created for user: " + res.name)
                        Object.assign(base_context, {current_user: req.session.current_user});
                        resolve({
                            schema,
                            tracing: true,
                            cacheControl: true,
                            context: base_context,
                            
                        })
                    });

                } else {
                    logger.info("Session Stored for the user: " + req.session.current_user.name);
                    Object.assign(base_context, {current_user: req.session.current_user});
                    resolve({
                        schema,
                        tracing: true,
                        cacheControl: true,
                        context: base_context,
                    })

                }

            })

        })
    }));

**Comment by BalajiJagadeesan** [comment]
You can use this repo to throw custom errors.
https://www.npmjs.com/package/apollo-errors
It works well with Apollo graphql.

I see that you are doing authentication. As far as I know, there are two methods to do authorization,
1)manually checking for authentication in each resolver.
2)using directives as middleware as explained here.
https://github.com/apollographql/graphql-tools/issues/212
which is pushed to graphql-tools but it is limiting.

Please Note:
The method 2 using directive is limiting as it DOES NOT work on QUERIES, but rather only work on FIELD_DESCRIPTIONS.

**Comment by abernix** [comment]
👋 I'll close this since it's quite old and also doesn't appear to be a bug with Apollo Server, but rather a question about how to use it or one of its components.

For more on error handling, check out the documentation for [errors](https://www.apollographql.com/docs/apollo-server/features/errors).

Rather than asking it here in GitHub Issues — where efforts are focused on fixing bugs and adding new features — I'd ask that you take this question to the _Apollo Server_ channel within [the Apollo community on Spectrum.chat](https://spectrum.chat/apollo) where there are community members who might be able to relate to a similar problem, or might be able to help you out more interactively.  Thanks for your understanding!
