### ISSUE TITLE
Hosting server on Google AppEngine

### ISSUE THREAD

**Issue by somarjun** [apollographql/apollo-server#852]
Hi,

I'm trying to host graphql server which uses apollo to be hosted on AppEngine. Currently we are using a virtual machine to host.

We want it to be hoseted in AppEngine so that we can reduce the costs, move from manual to CI/CD process.

**Comment by gavinwilliams** [comment]
I'm running on AppEngine's flex environment fine. What is the issue @somarjun?

**Comment by somarjun** [comment]
Hi @gavinwilliams, 

Can I know the process you are following? Need some guidance on it. 

We also use BitBucket.

Thanks in advance.

**Comment by gavinwilliams** [comment]
Couple of questions. How affluent are you in Google Cloud and App Engine in particular?

I.e. have you deployed a service to it yet?

Do you need to deploy to multiple environments, I.e. prod, pre-prod?

**Comment by somarjun** [comment]
I haven't deployed anything yet on Google Cloud AppEngine. I am new to it. 

We need 2 environments Dev and Prod.

Thanks.

**Comment by gavinwilliams** [comment]
This is a hard one and I don’t think that it’s one for GutHub. I would recommend reading BitBucket’s tutorials on how to deploy to GAE from pipelines.

https://confluence.atlassian.com/bitbucket/deploy-to-google-cloud-900820342.html

You should also read about how to deploy a node application to GAE https://cloud.google.com/nodejs/

As well as the differences between flex and standard environments. Main difference being that Standard doesn’t allow you to write to disk and restricts network access.

https://cloud.google.com/appengine/docs/the-appengine-environments

You should consider that although GAE might be marginally cheaper, the cost to learn it and migrate from GAE to GKE (kubernetees) both in knowledge and stack may outweigh any benefits.

Rather than migrating our existing platform to Google Cloud we built a new one that leverages it’s functionality.

**Comment by somarjun** [comment]
Thanks @gavinwilliams will look into the docs.

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!

**Comment by japonicius** [comment]
Hello I just created a post on spectrum related to this issue https://spectrum.chat/apollo/general/deploying-apollo-server-2-to-google-app-engine-heroku~8ae52798-2adb-441c-a160-6ca9f8520aeb
