### ISSUE TITLE
Deduplicate docs and README

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-server#870]
Right now, both the README and docs have a lot of content, so we have to update two places when we make a change or improvement.

I think the docs are better because we can do redirects for stable links, there's a table of contents, etc. So I'd be in favor of shortening the README significantly and pointing to the docs for most stuff: https://www.apollographql.com/docs/apollo-server/

**Comment by abernix** [comment]
/label good first review

☝️ 

This would be a great starting contribution for someone looking to help out the project!  At the very least, the README at the root of this repository could have a bullet-point list which either points to the docs or the `README`s inside the individual packages.

(i.e. links the HAPI setup instructions on the root `README.md` to `packages/apollo-server-hapi/README.md`, rather than repeating its instructions!).

**Comment by trevorblades** [comment]
Closing this since @abernix fixed it at some point
